import type { Lang } from './seo.js';

export interface Hub {
  /** Query-string fragment identifying the app state, e.g. `layers=O` or `tool=route-planner`. */
  param: string;
  /** Copy may use the `{brand}` and `{site}` placeholders — see `expandNames`. */
  title: Record<Lang, string>;
  description: Record<Lang, string>;
}

/**
 * Curated landing pages for the main layers, tools and dialogs, in every UI
 * language. Copy is distilled from `src/static/llms.txt` and the layer
 * registry; keep it in sync when those change.
 */
export const hubs: Hub[] = [
  // ---- Map layers ----
  {
    param: 'layers=O',
    title: {
      sk: 'Podkladová mapa OpenStreetMap',
      en: 'OpenStreetMap base map',
      cs: 'Podkladová mapa OpenStreetMap',
      hu: 'OpenStreetMap alaptérkép',
      it: 'Mappa base OpenStreetMap',
      de: 'OpenStreetMap-Basiskarte',
      pl: 'Mapa podkładowa OpenStreetMap',
      sl: 'Osnovni zemljevid OpenStreetMap',
      fr: 'Fond de carte OpenStreetMap',
    },
    description: {
      sk: 'Podkladová vrstva OpenStreetMap na {brand} — štandardná celosvetová mapa OpenStreetMap. Posúvajte a približujte neustále aktualizované dáta OSM, plánujte trasy a prezerajte body záujmu.',
      en: 'OpenStreetMap base layer on {brand} — the standard worldwide OpenStreetMap map. Pan, zoom and explore continuously updated OSM data, plan routes and view points of interest.',
      cs: 'Podkladová vrstva OpenStreetMap na {brand} — standardní celosvětová mapa OpenStreetMap. Posouvejte a přibližujte průběžně aktualizovaná data OSM, plánujte trasy a prohlížejte body zájmu.',
      hu: 'OpenStreetMap alapréteg a {brand} oldalon — a szabványos világméretű OpenStreetMap-térkép. Mozgassa és nagyítsa a folyamatosan frissülő OSM-adatokat, tervezzen útvonalat és nézze meg az érdekes pontokat.',
      it: 'Livello base OpenStreetMap su {brand} — la mappa OpenStreetMap standard di tutto il mondo. Sposta, ingrandisci ed esplora dati OSM aggiornati di continuo, pianifica percorsi e consulta i punti di interesse.',
      de: 'OpenStreetMap-Basisebene auf {brand} — die weltweite OpenStreetMap-Standardkarte. Verschieben, zoomen und laufend aktualisierte OSM-Daten erkunden, Routen planen und Points of Interest ansehen.',
      pl: 'Warstwa podkładowa OpenStreetMap w {brand} — standardowa ogólnoświatowa mapa OpenStreetMap. Przesuwaj i przybliżaj stale aktualizowane dane OSM, planuj trasy i przeglądaj punkty zainteresowania.',
      sl: 'Osnovni sloj OpenStreetMap na {brand} — standardni svetovni zemljevid OpenStreetMap. Premikajte in približujte nenehno posodabljane podatke OSM, načrtujte poti in si oglejte točke zanimivosti.',
      fr: 'Couche de base OpenStreetMap sur {brand} — la carte OpenStreetMap standard du monde entier. Déplacez, zoomez et explorez des données OSM mises à jour en continu, planifiez des itinéraires et consultez les points d’intérêt.',
    },
  },
  {
    param: 'layers=S',
    title: {
      sk: 'Letecká a satelitná mapa',
      en: 'Aerial and satellite map',
      cs: 'Letecká a satelitní mapa',
      hu: 'Légi és műholdas térkép',
      it: 'Mappa aerea e satellitare',
      de: 'Luftbild- und Satellitenkarte',
      pl: 'Mapa lotnicza i satelitarna',
      sl: 'Letalski in satelitski zemljevid',
      fr: 'Carte aérienne et satellite',
    },
    description: {
      sk: 'Letecká / satelitná mapa na {brand} — celosvetové ortofoto s vysokým rozlíšením od Esri, v kombinácii s prekryvmi turistických a cyklistických trás, vrstevníc a tieňovaného reliéfu.',
      en: 'Aerial / satellite imagery on {brand} — worldwide high-resolution aerial photography from Esri, combined with overlays for hiking and cycling trails, contours and shaded relief.',
      cs: 'Letecká / satelitní mapa na {brand} — celosvětové ortofoto ve vysokém rozlišení od Esri, v kombinaci s překryvy turistických a cyklistických tras, vrstevnic a stínovaného reliéfu.',
      hu: 'Légi/műholdas felvételek a {brand} oldalon — világméretű, nagy felbontású légifotó az Esritől, túra- és kerékpárútvonal-, szintvonal- és domborzatárnyékolás-rétegekkel kombinálva.',
      it: 'Immagini aeree e satellitari su {brand} — ortofoto ad alta risoluzione di tutto il mondo da Esri, combinate con i livelli di sentieri escursionistici e ciclabili, curve di livello e rilievo ombreggiato.',
      de: 'Luft- und Satellitenbilder auf {brand} — weltweite hochauflösende Luftbilder von Esri, kombiniert mit Overlays für Wander- und Radwege, Höhenlinien und Schummerung.',
      pl: 'Zdjęcia lotnicze i satelitarne w {brand} — ogólnoświatowa ortofotomapa w wysokiej rozdzielczości od Esri, w połączeniu z warstwami szlaków pieszych i rowerowych, poziomic i cieniowania rzeźby.',
      sl: 'Letalski in satelitski posnetki na {brand} — svetovni ortofoto visoke ločljivosti podjetja Esri, v kombinaciji s sloji pohodniških in kolesarskih poti, plastnic in senčenega reliefa.',
      fr: 'Imagerie aérienne et satellite sur {brand} — orthophotographie haute résolution mondiale d’Esri, combinée aux couches de sentiers de randonnée et pistes cyclables, courbes de niveau et ombrage du relief.',
    },
  },
  {
    param: 'layers=Z',
    title: {
      sk: 'Slovenské a české ortofoto',
      en: 'Slovak and Czech orthophoto',
      cs: 'Slovenské a české ortofoto',
      hu: 'Szlovák és cseh ortofotó',
      it: 'Ortofoto slovacca e ceca',
      de: 'Slowakisches und tschechisches Orthofoto',
      pl: 'Słowacka i czeska ortofotomapa',
      sl: 'Slovaški in češki ortofoto',
      fr: 'Orthophotographie slovaque et tchèque',
    },
    description: {
      sk: 'Slovenské a české ortofoto na {brand} — detailná štátna letecká mapa (© GKÚ, NLC, ČÚZK) do vysokého priblíženia, ideálna na presnú navigáciu v teréne.',
      en: 'Slovak and Czech orthophoto on {brand} — detailed national aerial imagery (© GKÚ, NLC, ČÚZK) up to high zoom levels, ideal for precise outdoor navigation.',
      cs: 'Slovenské a české ortofoto na {brand} — detailní státní letecká mapa (© GKÚ, NLC, ČÚZK) do vysokého přiblížení, ideální pro přesnou navigaci v terénu.',
      hu: 'Szlovák és cseh ortofotó a {brand} oldalon — részletes állami légifelvétel (© GKÚ, NLC, ČÚZK) nagy nagyításig, ideális pontos terepi tájékozódáshoz.',
      it: 'Ortofoto slovacca e ceca su {brand} — immagini aeree nazionali di dettaglio (© GKÚ, NLC, ČÚZK) fino a zoom elevati, ideali per una navigazione outdoor precisa.',
      de: 'Slowakisches und tschechisches Orthofoto auf {brand} — detaillierte amtliche Luftbilder (© GKÚ, NLC, ČÚZK) bis in hohe Zoomstufen, ideal für präzise Navigation im Gelände.',
      pl: 'Słowacka i czeska ortofotomapa w {brand} — szczegółowe państwowe zdjęcia lotnicze (© GKÚ, NLC, ČÚZK) do wysokich poziomów przybliżenia, idealne do precyzyjnej nawigacji w terenie.',
      sl: 'Slovaški in češki ortofoto na {brand} — podrobni državni letalski posnetki (© GKÚ, NLC, ČÚZK) do visokih ravni približevanja, idealni za natančno orientacijo v naravi.',
      fr: 'Orthophotographie slovaque et tchèque sur {brand} — imagerie aérienne nationale détaillée (© GKÚ, NLC, ČÚZK) jusqu’aux forts niveaux de zoom, idéale pour une navigation précise sur le terrain.',
    },
  },
  {
    param: 'layers=d',
    title: {
      sk: 'Mapa verejnej dopravy',
      en: 'Public transport map',
      cs: 'Mapa veřejné dopravy',
      hu: 'Tömegközlekedési térkép',
      it: 'Mappa del trasporto pubblico',
      de: 'Nahverkehrskarte',
      pl: 'Mapa transportu publicznego',
      sl: 'Zemljevid javnega prevoza',
      fr: 'Carte des transports en commun',
    },
    description: {
      sk: 'Mapa verejnej dopravy na {brand} — vrstva ÖPNV zobrazujúca autobusové, električkové a vlakové linky a zastávky na základe dát OpenStreetMap (© MeMoMaps).',
      en: 'Public transport map on {brand} — the ÖPNV layer showing bus, tram and train lines and stops based on OpenStreetMap data (© MeMoMaps).',
      cs: 'Mapa veřejné dopravy na {brand} — vrstva ÖPNV zobrazující autobusové, tramvajové a vlakové linky a zastávky na základě dat OpenStreetMap (© MeMoMaps).',
      hu: 'Tömegközlekedési térkép a {brand} oldalon — az ÖPNV réteg busz-, villamos- és vonatvonalakkal és megállókkal, OpenStreetMap-adatok alapján (© MeMoMaps).',
      it: 'Mappa del trasporto pubblico su {brand} — il livello ÖPNV con linee e fermate di autobus, tram e treni, basato sui dati OpenStreetMap (© MeMoMaps).',
      de: 'Nahverkehrskarte auf {brand} — die ÖPNV-Ebene mit Bus-, Straßenbahn- und Bahnlinien samt Haltestellen auf Basis von OpenStreetMap-Daten (© MeMoMaps).',
      pl: 'Mapa transportu publicznego w {brand} — warstwa ÖPNV pokazująca linie i przystanki autobusowe, tramwajowe i kolejowe na podstawie danych OpenStreetMap (© MeMoMaps).',
      sl: 'Zemljevid javnega prevoza na {brand} — sloj ÖPNV s progami in postajališči avtobusov, tramvajev in vlakov na podlagi podatkov OpenStreetMap (© MeMoMaps).',
      fr: 'Carte des transports en commun sur {brand} — la couche ÖPNV montrant les lignes et arrêts de bus, tram et train à partir des données OpenStreetMap (© MeMoMaps).',
    },
  },
  {
    param: 'layers=X~w',
    title: {
      sk: 'Wikipédia v mape',
      en: 'Wikipedia on the map',
      cs: 'Wikipedie v mapě',
      hu: 'Wikipédia a térképen',
      it: 'Wikipedia sulla mappa',
      de: 'Wikipedia auf der Karte',
      pl: 'Wikipedia na mapie',
      sl: 'Wikipedija na zemljevidu',
      fr: 'Wikipédia sur la carte',
    },
    description: {
      sk: 'Prekryv Wikipédia na {brand} — objavujte okolité miesta s článkami na Wikipédii zobrazené ako značky priamo v mape.',
      en: 'Wikipedia overlay on {brand} — discover nearby places that have Wikipedia articles, shown as markers directly on the map.',
      cs: 'Překryv Wikipedie na {brand} — objevujte okolní místa s články na Wikipedii zobrazená jako značky přímo v mapě.',
      hu: 'Wikipédia-réteg a {brand} oldalon — fedezze fel a közeli helyeket, amelyekről Wikipédia-szócikk szól, közvetlenül a térképen jelölve.',
      it: 'Livello Wikipedia su {brand} — scopri i luoghi vicini che hanno una voce su Wikipedia, mostrati come segnaposto direttamente sulla mappa.',
      de: 'Wikipedia-Overlay auf {brand} — Orte in der Umgebung mit Wikipedia-Artikeln entdecken, direkt als Marker auf der Karte.',
      pl: 'Warstwa Wikipedii w {brand} — odkrywaj pobliskie miejsca opisane w Wikipedii, pokazywane jako znaczniki bezpośrednio na mapie.',
      sl: 'Sloj Wikipedije na {brand} — odkrijte bližnje kraje s članki na Wikipediji, prikazane kot oznake neposredno na zemljevidu.',
      fr: 'Calque Wikipédia sur {brand} — découvrez les lieux proches disposant d’un article Wikipédia, affichés en marqueurs directement sur la carte.',
    },
  },
  {
    param: 'layers=X~I',
    title: {
      sk: 'Komunitné outdoorové fotografie',
      en: 'Community outdoor photos',
      cs: 'Komunitní outdoorové fotografie',
      hu: 'Közösségi szabadtéri fotók',
      it: 'Foto outdoor della comunità',
      de: 'Outdoor-Fotos der Community',
      pl: 'Społecznościowe zdjęcia outdoorowe',
      sl: 'Skupnostne fotografije iz narave',
      fr: 'Photos outdoor de la communauté',
    },
    description: {
      sk: 'Komunitné fotografie na {brand} — prezerajte tisíce geolokalizovaných outdoorových fotografií (CC BY-SA 4.0) zobrazené ako značky v mape; filtrujte, hodnoťte a pridávajte vlastné.',
      en: 'Community photos on {brand} — browse thousands of geotagged outdoor photos (CC BY-SA 4.0) shown as markers on the map; filter, rate and upload your own.',
      cs: 'Komunitní fotografie na {brand} — prohlížejte tisíce geolokalizovaných outdoorových fotografií (CC BY-SA 4.0) zobrazených jako značky v mapě; filtrujte, hodnoťte a přidávejte vlastní.',
      hu: 'Közösségi fotók a {brand} oldalon — böngésszen több ezer helyadattal ellátott szabadtéri fényképet (CC BY-SA 4.0) a térképen; szűrjön, értékeljen és töltsön fel sajátot.',
      it: 'Foto della comunità su {brand} — sfoglia migliaia di foto outdoor geolocalizzate (CC BY-SA 4.0) mostrate come segnaposto sulla mappa; filtra, vota e carica le tue.',
      de: 'Community-Fotos auf {brand} — Tausende georeferenzierte Outdoor-Fotos (CC BY-SA 4.0) als Marker auf der Karte durchstöbern, filtern, bewerten und eigene hochladen.',
      pl: 'Zdjęcia społeczności w {brand} — przeglądaj tysiące geolokalizowanych zdjęć outdoorowych (CC BY-SA 4.0) pokazywanych jako znaczniki na mapie; filtruj, oceniaj i dodawaj własne.',
      sl: 'Skupnostne fotografije na {brand} — prebrskajte tisoče geolociranih fotografij iz narave (CC BY-SA 4.0), prikazanih kot oznake na zemljevidu; filtrirajte, ocenjujte in dodajte svoje.',
      fr: 'Photos de la communauté sur {brand} — parcourez des milliers de photos outdoor géolocalisées (CC BY-SA 4.0) affichées en marqueurs sur la carte ; filtrez, notez et ajoutez les vôtres.',
    },
  },
  {
    param: 'layers=X~R',
    title: {
      sk: 'Meteoradar',
      en: 'Weather radar',
      cs: 'Meteoradar',
      hu: 'Időjárási radar',
      it: 'Radar meteo',
      de: 'Wetterradar',
      pl: 'Radar pogodowy',
      sl: 'Vremenski radar',
      fr: 'Radar météo',
    },
    description: {
      sk: 'Animovaný zrážkový radar na {brand} — prehrajte si nedávny dážď a sneh nad Európou snímku po snímke na časovej osi, zo siete EUMETNET OPERA (nad Talianskom © Radar-DPC). Prémium pridáva až šesť hodín histórie a hodinovú predpoveď.',
      en: 'Animated precipitation radar on {brand} — play back recent rain and snow across Europe frame by frame on a timeline, from the EUMETNET OPERA network (over Italy © Radar-DPC). Premium adds up to six hours of history and a one-hour forecast.',
      cs: 'Animovaný srážkový radar na {brand} — přehrajte si nedávný déšť a sníh nad Evropou snímek po snímku na časové ose, ze sítě EUMETNET OPERA (nad Itálií © Radar-DPC). Prémium přidává až šest hodin historie a hodinovou předpověď.',
      hu: 'Animált csapadékradar a {brand} oldalon — játssza vissza az Európa fölötti közelmúltbeli esőt és havat képkockánként az idővonalon, az EUMETNET OPERA hálózatból (Olaszország fölött © Radar-DPC). A prémium hat óra előzményt és egyórás előrejelzést ad hozzá.',
      it: 'Radar delle precipitazioni animato su {brand} — riguarda pioggia e neve recenti su tutta Europa fotogramma per fotogramma sulla linea del tempo, dalla rete EUMETNET OPERA (sull’Italia © Radar-DPC). Il premium aggiunge fino a sei ore di storico e una previsione a un’ora.',
      de: 'Animiertes Niederschlagsradar auf {brand} — Regen und Schnee der letzten Stunden über Europa Bild für Bild auf einer Zeitleiste abspielen, aus dem EUMETNET-OPERA-Netz (über Italien © Radar-DPC). Premium bringt bis zu sechs Stunden Verlauf und eine Ein-Stunden-Vorhersage.',
      pl: 'Animowany radar opadów w {brand} — odtwórz niedawny deszcz i śnieg nad Europą klatka po klatce na osi czasu, z sieci EUMETNET OPERA (nad Włochami © Radar-DPC). Premium dodaje do sześciu godzin historii i godzinną prognozę.',
      sl: 'Animiran padavinski radar na {brand} — predvajajte nedavni dež in sneg nad Evropo sliko za sliko na časovnici, iz mreže EUMETNET OPERA (nad Italijo © Radar-DPC). Premium doda do šest ur zgodovine in enourno napoved.',
      fr: 'Radar de précipitations animé sur {brand} — rejouez image par image la pluie et la neige récentes sur l’Europe grâce à une frise chronologique, depuis le réseau EUMETNET OPERA (sur l’Italie © Radar-DPC). Le premium ajoute jusqu’à six heures d’historique et une prévision à une heure.',
    },
  },
  {
    param: 'layers=X~v',
    title: {
      sk: 'Viewshed: čo je odtiaľ vidieť',
      en: 'Viewshed: what you can see',
      cs: 'Viewshed: co je odtud vidět',
      hu: 'Kilátáselemzés: mi látszik innen',
      it: 'Bacino visivo: che cosa si vede',
      de: 'Sichtbarkeitsanalyse: was man sieht',
      pl: 'Analiza widoczności: co widać',
      sl: 'Analiza vidnosti: kaj je vidno',
      fr: 'Bassin de visibilité : ce que l’on voit',
    },
    description: {
      sk: 'Prekryv viditeľnosti na {brand} — vyberte bod a server z výškového modelu vypočíta, ktorý terén je odtiaľ vidieť, a vykreslí ho cez mapu do zvoleného dosahu. Ide o holý terén, takže lesy a budovy sa nezapočítavajú.',
      en: 'Viewshed overlay on {brand} — pick a point and the server computes which ground is visible from it out of the terrain model, drawn over the map with the range you choose. Bare earth, so forests and buildings are not accounted for.',
      cs: 'Překryv viditelnosti na {brand} — vyberte bod a server z výškového modelu spočítá, který terén je odtud vidět, a vykreslí jej přes mapu do zvoleného dosahu. Jde o holý terén, takže lesy a budovy se nezapočítávají.',
      hu: 'Kilátáselemzési réteg a {brand} oldalon — jelöljön ki egy pontot, és a kiszolgáló a domborzatmodellből kiszámítja, mely terep látszik onnan, majd a választott hatótávolságig a térképre rajzolja. Csupasz felszín, tehát az erdők és épületek nem számítanak bele.',
      it: 'Livello del bacino visivo su {brand} — scegli un punto e il server calcola dal modello del terreno quale suolo è visibile da lì, disegnandolo sulla mappa fino alla distanza scelta. È terreno nudo: boschi ed edifici non sono considerati.',
      de: 'Sichtbarkeits-Overlay auf {brand} — einen Punkt wählen, und der Server berechnet aus dem Geländemodell, welcher Boden von dort sichtbar ist, gezeichnet über die Karte bis zur gewählten Reichweite. Nacktes Gelände: Wälder und Gebäude bleiben unberücksichtigt.',
      pl: 'Warstwa analizy widoczności w {brand} — wskaż punkt, a serwer obliczy z modelu terenu, który grunt jest z niego widoczny, i narysuje to na mapie do wybranego zasięgu. To goła ziemia, więc lasy i budynki nie są uwzględniane.',
      sl: 'Sloj analize vidnosti na {brand} — izberite točko in strežnik iz modela terena izračuna, katera tla so od tam vidna, ter jih izriše čez zemljevid do izbranega dosega. Gre za golo površje, zato gozdovi in stavbe niso upoštevani.',
      fr: 'Calque de bassin de visibilité sur {brand} — choisissez un point et le serveur calcule, à partir du modèle de terrain, quel sol est visible depuis là, dessiné sur la carte jusqu’à la portée choisie. Terrain nu : forêts et bâtiments ne sont pas pris en compte.',
    },
  },
  {
    param: 'layers=X~wka',
    title: {
      sk: 'Katastrálna mapa',
      en: 'Slovak cadastral map',
      cs: 'Slovenská katastrální mapa',
      hu: 'Szlovák kataszteri térkép',
      it: 'Mappa catastale slovacca',
      de: 'Slowakische Katasterkarte',
      pl: 'Słowacka mapa katastralna',
      sl: 'Slovaški katastrski zemljevid',
      fr: 'Cadastre slovaque',
    },
    description: {
      sk: 'Prekryv katastra na {brand} — hranice a čísla katastrálnych parciel na Slovensku (© GKÚ) vykreslené nad turistickou mapou alebo ortofotom, od priblíženia 15.',
      en: 'Cadastre overlay on {brand} — Slovak cadastral parcel boundaries and numbers (© GKÚ) drawn over the outdoor map or aerial imagery, from zoom 15 up.',
      cs: 'Překryv katastru na {brand} — hranice a čísla katastrálních parcel na Slovensku (© GKÚ) vykreslené nad turistickou mapou nebo ortofotem, od přiblížení 15.',
      hu: 'Kataszteri réteg a {brand} oldalon — a szlovák kataszteri telekhatárok és helyrajzi számok (© GKÚ) a turistatérkép vagy a légifelvétel fölé rajzolva, 15-ös nagyítástól.',
      it: 'Livello catastale su {brand} — confini e numeri delle particelle catastali slovacche (© GKÚ) disegnati sopra la mappa outdoor o le immagini aeree, dallo zoom 15 in su.',
      de: 'Kataster-Overlay auf {brand} — slowakische Flurstücksgrenzen und -nummern (© GKÚ) über der Outdoor-Karte oder dem Luftbild, ab Zoomstufe 15.',
      pl: 'Warstwa katastru w {brand} — granice i numery słowackich działek katastralnych (© GKÚ) rysowane na mapie outdoorowej lub zdjęciach lotniczych, od przybliżenia 15.',
      sl: 'Katastrski sloj na {brand} — meje in številke slovaških katastrskih parcel (© GKÚ), izrisane čez pohodniški zemljevid ali letalske posnetke, od približave 15 naprej.',
      fr: 'Calque cadastral sur {brand} — limites et numéros des parcelles cadastrales slovaques (© GKÚ) dessinés sur la carte outdoor ou l’imagerie aérienne, à partir du zoom 15.',
    },
  },
  // ---- Tools ----
  {
    param: 'tool=route-planner',
    title: {
      sk: 'Plánovač trás',
      en: 'Route planner',
      cs: 'Plánovač tras',
      hu: 'Útvonaltervező',
      it: 'Pianificatore di percorsi',
      de: 'Routenplaner',
      pl: 'Planer tras',
      sl: 'Načrtovalnik poti',
      fr: 'Calculateur d’itinéraire',
    },
    description: {
      sk: 'Plánovač trás na {brand} — naplánujte pešie, turistické, cyklistické, horské a automobilové trasy pomocou smerovania GraphHopper a OSRM, s viacerými prechodmi, okruhmi a izochrónami, a exportujte do GPX.',
      en: 'Route planner on {brand} — plan walking, hiking, cycling, mountain-bike and car routes with GraphHopper and OSRM routing, multiple waypoints, round trips and isochrones, then export to GPX.',
      cs: 'Plánovač tras na {brand} — naplánujte pěší, turistické, cyklistické, horské a automobilové trasy pomocí směrování GraphHopper a OSRM, s více průjezdními body, okruhy a izochronami, a exportujte do GPX.',
      hu: 'Útvonaltervező a {brand} oldalon — tervezzen gyalogos, túra-, kerékpáros, hegyikerékpáros és autós útvonalat GraphHopper és OSRM útvonalkereséssel, több köztes ponttal, körtúrákkal és izokrónokkal, majd exportálja GPX-be.',
      it: 'Pianificatore di percorsi su {brand} — progetta itinerari a piedi, escursionistici, in bici, in mountain bike e in auto con il routing GraphHopper e OSRM, con più tappe, anelli e isocrone, poi esporta in GPX.',
      de: 'Routenplaner auf {brand} — Wander-, Fuß-, Rad-, Mountainbike- und Autorouten mit GraphHopper- und OSRM-Routing planen, mit mehreren Zwischenzielen, Rundtouren und Isochronen, dann als GPX exportieren.',
      pl: 'Planer tras w {brand} — zaplanuj trasy piesze, turystyczne, rowerowe, górskie i samochodowe z routingiem GraphHopper i OSRM, z wieloma punktami pośrednimi, pętlami i izochronami, a potem wyeksportuj do GPX.',
      sl: 'Načrtovalnik poti na {brand} — načrtujte peš, pohodniške, kolesarske, gorskokolesarske in avtomobilske poti z usmerjanjem GraphHopper in OSRM, z več vmesnimi točkami, krožnimi potmi in izokronami, nato izvozite v GPX.',
      fr: 'Calculateur d’itinéraire sur {brand} — planifiez des parcours à pied, de randonnée, à vélo, en VTT et en voiture avec le routage GraphHopper et OSRM, avec plusieurs étapes, boucles et isochrones, puis exportez en GPX.',
    },
  },
  {
    param: 'tool=draw-points',
    title: {
      sk: 'Kreslenie a meranie',
      en: 'Drawing and measurement',
      cs: 'Kreslení a měření',
      hu: 'Rajzolás és mérés',
      it: 'Disegno e misurazione',
      de: 'Zeichnen und Messen',
      pl: 'Rysowanie i pomiary',
      sl: 'Risanje in merjenje',
      fr: 'Dessin et mesure',
    },
    description: {
      sk: 'Kreslenie a meranie na {brand} — kreslite body, čiary a polygóny v mape, merajte vzdialenosť, plochu, výšku a azimut, zobrazujte výškové profily a štýlujte svoje poznámky.',
      en: 'Drawing and measurement on {brand} — draw points, lines and polygons on the map, measure distance, area, elevation and azimuth, view elevation profiles and style your annotations.',
      cs: 'Kreslení a měření na {brand} — kreslete body, čáry a polygony v mapě, měřte vzdálenost, plochu, výšku a azimut, zobrazujte výškové profily a stylujte své poznámky.',
      hu: 'Rajzolás és mérés a {brand} oldalon — rajzoljon pontokat, vonalakat és sokszögeket a térképre, mérjen távolságot, területet, magasságot és azimutot, nézzen magassági profilt és formázza a jelöléseit.',
      it: 'Disegno e misurazione su {brand} — disegna punti, linee e poligoni sulla mappa, misura distanza, area, quota e azimut, visualizza i profili altimetrici e personalizza lo stile delle tue annotazioni.',
      de: 'Zeichnen und Messen auf {brand} — Punkte, Linien und Flächen auf der Karte zeichnen, Entfernung, Fläche, Höhe und Azimut messen, Höhenprofile ansehen und Anmerkungen gestalten.',
      pl: 'Rysowanie i pomiary w {brand} — rysuj punkty, linie i wielokąty na mapie, mierz odległość, powierzchnię, wysokość i azymut, oglądaj profile wysokościowe i nadawaj styl swoim adnotacjom.',
      sl: 'Risanje in merjenje na {brand} — rišite točke, črte in poligone na zemljevidu, merite razdaljo, površino, nadmorsko višino in azimut, si oglejte višinske profile in oblikujte svoje oznake.',
      fr: 'Dessin et mesure sur {brand} — tracez des points, lignes et polygones sur la carte, mesurez distance, surface, altitude et azimut, consultez les profils altimétriques et stylisez vos annotations.',
    },
  },
  {
    param: 'tool=objects',
    title: {
      sk: 'Body záujmu (POI)',
      en: 'Points of interest (POIs)',
      cs: 'Body zájmu (POI)',
      hu: 'Érdekes pontok (POI)',
      it: 'Punti di interesse (POI)',
      de: 'Points of Interest (POI)',
      pl: 'Punkty zainteresowania (POI)',
      sl: 'Točke zanimivosti (POI)',
      fr: 'Points d’intérêt (POI)',
    },
    description: {
      sk: 'Body záujmu na {brand} — vyhľadávajte a zobrazujte POI podľa kategórie (ubytovanie, jedlo, obchody, turistika, prírodné prvky a ďalšie) ako ikony v mape.',
      en: 'Points of interest on {brand} — search and display POIs by category (accommodation, food, shops, tourism, natural features and more) as icons on the map.',
      cs: 'Body zájmu na {brand} — vyhledávejte a zobrazujte POI podle kategorie (ubytování, jídlo, obchody, turistika, přírodní prvky a další) jako ikony v mapě.',
      hu: 'Érdekes pontok a {brand} oldalon — keressen és jelenítsen meg POI-kat kategória szerint (szállás, étkezés, boltok, turizmus, természeti értékek és más) ikonként a térképen.',
      it: 'Punti di interesse su {brand} — cerca e visualizza i POI per categoria (alloggi, cibo, negozi, turismo, elementi naturali e altro) come icone sulla mappa.',
      de: 'Points of Interest auf {brand} — POIs nach Kategorie suchen und anzeigen (Unterkunft, Essen, Geschäfte, Tourismus, Naturobjekte und mehr), als Symbole auf der Karte.',
      pl: 'Punkty zainteresowania w {brand} — wyszukuj i wyświetlaj POI według kategorii (noclegi, jedzenie, sklepy, turystyka, obiekty przyrodnicze i inne) jako ikony na mapie.',
      sl: 'Točke zanimivosti na {brand} — iščite in prikazujte POI po kategorijah (nastanitve, hrana, trgovine, turizem, naravne značilnosti in drugo) kot ikone na zemljevidu.',
      fr: 'Points d’intérêt sur {brand} — recherchez et affichez les POI par catégorie (hébergement, restauration, commerces, tourisme, éléments naturels et plus) sous forme d’icônes sur la carte.',
    },
  },
  {
    param: 'tool=map-details',
    title: {
      sk: 'Detaily mapy',
      en: 'Map details',
      cs: 'Detaily mapy',
      hu: 'Térképrészletek',
      it: 'Dettagli della mappa',
      de: 'Kartendetails',
      pl: 'Szczegóły mapy',
      sl: 'Podrobnosti zemljevida',
      fr: 'Détails de la carte',
    },
    description: {
      sk: 'Detaily mapy na {brand} — kliknite na ľubovoľné miesto a získajte jeho adresu, okolité prvky a administratívne a geografické oblasti, ktoré ho obsahujú, s odkazmi na OpenStreetMap.',
      en: 'Map details on {brand} — click any place to query its address, nearby features and the administrative and geographic areas that contain it, with links to OpenStreetMap.',
      cs: 'Detaily mapy na {brand} — klikněte na libovolné místo a získejte jeho adresu, okolní prvky a administrativní a geografické oblasti, které jej obsahují, s odkazy na OpenStreetMap.',
      hu: 'Térképrészletek a {brand} oldalon — kattintson bármely helyre, és kérdezze le a címét, a közeli objektumokat, valamint az őt tartalmazó közigazgatási és földrajzi területeket, OpenStreetMap-hivatkozásokkal.',
      it: 'Dettagli della mappa su {brand} — clicca un punto qualsiasi per conoscerne l’indirizzo, gli elementi vicini e le aree amministrative e geografiche che lo contengono, con collegamenti a OpenStreetMap.',
      de: 'Kartendetails auf {brand} — auf eine beliebige Stelle klicken und Adresse, umliegende Objekte sowie die enthaltenden Verwaltungs- und Naturräume abfragen, mit Links zu OpenStreetMap.',
      pl: 'Szczegóły mapy w {brand} — kliknij dowolne miejsce, aby poznać jego adres, pobliskie obiekty oraz obszary administracyjne i geograficzne, które je zawierają, z odnośnikami do OpenStreetMap.',
      sl: 'Podrobnosti zemljevida na {brand} — kliknite katero koli mesto in poizvedite po njegovem naslovu, bližnjih objektih ter upravnih in geografskih območjih, ki ga vsebujejo, s povezavami na OpenStreetMap.',
      fr: 'Détails de la carte sur {brand} — cliquez n’importe où pour obtenir l’adresse, les éléments proches et les zones administratives et géographiques qui contiennent ce point, avec des liens vers OpenStreetMap.',
    },
  },
  {
    param: 'tool=changesets',
    title: {
      sk: 'Zmeny v OpenStreetMap',
      en: 'OpenStreetMap changes',
      cs: 'Změny v OpenStreetMap',
      hu: 'OpenStreetMap-változások',
      it: 'Modifiche a OpenStreetMap',
      de: 'OpenStreetMap-Änderungen',
      pl: 'Zmiany w OpenStreetMap',
      sl: 'Spremembe v OpenStreetMap',
      fr: 'Modifications OpenStreetMap',
    },
    description: {
      sk: 'Zmeny OpenStreetMap na {brand} — prezerajte nedávne úpravy OSM v mape podľa časového obdobia a autora, s odkazmi na changesety na osm.org a Achavi.',
      en: 'OpenStreetMap changes on {brand} — browse recent OSM edits on the map by time window and author, with links to changesets on osm.org and Achavi.',
      cs: 'Změny OpenStreetMap na {brand} — prohlížejte nedávné úpravy OSM v mapě podle časového období a autora, s odkazy na changesety na osm.org a Achavi.',
      hu: 'OpenStreetMap-változások a {brand} oldalon — böngéssze a legutóbbi OSM-szerkesztéseket a térképen időszak és szerző szerint, az osm.org és az Achavi módosításcsomagjaira mutató hivatkozásokkal.',
      it: 'Modifiche a OpenStreetMap su {brand} — sfoglia sulla mappa le modifiche OSM recenti per intervallo di tempo e autore, con collegamenti ai changeset su osm.org e Achavi.',
      de: 'OpenStreetMap-Änderungen auf {brand} — aktuelle OSM-Bearbeitungen auf der Karte nach Zeitraum und Autor durchsehen, mit Links zu den Changesets auf osm.org und Achavi.',
      pl: 'Zmiany OpenStreetMap w {brand} — przeglądaj na mapie ostatnie edycje OSM według okresu i autora, z odnośnikami do zestawów zmian na osm.org i Achavi.',
      sl: 'Spremembe OpenStreetMap na {brand} — prebrskajte nedavne urejanja OSM na zemljevidu po časovnem obdobju in avtorju, s povezavami na množice sprememb na osm.org in Achavi.',
      fr: 'Modifications OpenStreetMap sur {brand} — parcourez sur la carte les éditions OSM récentes par période et par auteur, avec des liens vers les changesets sur osm.org et Achavi.',
    },
  },
  {
    param: 'tool=toposcope',
    title: {
      sk: 'Toposkop (orientačná tabuľa)',
      en: 'Toposcope (orientation table)',
      cs: 'Toposkop (orientační tabule)',
      hu: 'Toposzkóp (tájoló tábla)',
      it: 'Toposcopio (tavola di orientamento)',
      de: 'Toposkop (Orientierungstafel)',
      pl: 'Toposkop (tablica orientacyjna)',
      sl: 'Toposkop (orientacijska tabla)',
      fr: 'Toposcope (table d’orientation)',
    },
    description: {
      sk: 'Toposkop na {brand} — nakreslite v mape orientačnú tabuľu: ružicu stojacu na jednom bode s pomenovaným lúčom ku každému ďalšiemu bodu, ktorý uvádza smer, vzdialenosť a nadmorskú výšku. Exportujte ju s mapou alebo zdieľajte odkazom.',
      en: 'Toposcope on {brand} — draw an orientation table on the map: a compass rose standing on one point with a named ray to every other point, each giving its direction, distance and elevation. Export it with the map or share it as a link.',
      cs: 'Toposkop na {brand} — nakreslete v mapě orientační tabuli: růžici stojící na jednom bodě s pojmenovaným paprskem ke každému dalšímu bodu, který udává směr, vzdálenost a nadmořskou výšku. Exportujte ji s mapou nebo sdílejte odkazem.',
      hu: 'Toposzkóp a {brand} oldalon — rajzoljon tájoló táblát a térképre: egy ponton álló szélrózsát, minden további ponthoz megnevezett sugárral, amely megadja az irányt, a távolságot és a magasságot. Exportálja a térképpel vagy ossza meg hivatkozásként.',
      it: 'Toposcopio su {brand} — disegna una tavola di orientamento sulla mappa: una rosa dei venti posata su un punto con un raggio nominato verso ogni altro punto, che ne indica direzione, distanza e quota. Esportala con la mappa o condividila come link.',
      de: 'Toposkop auf {brand} — eine Orientierungstafel auf der Karte zeichnen: eine Windrose auf einem Punkt, mit benanntem Strahl zu jedem weiteren Punkt, der Richtung, Entfernung und Höhe angibt. Mit der Karte exportieren oder als Link teilen.',
      pl: 'Toposkop w {brand} — narysuj na mapie tablicę orientacyjną: różę wiatrów stojącą w jednym punkcie, z nazwanym promieniem do każdego innego punktu, podającym kierunek, odległość i wysokość. Wyeksportuj ją z mapą lub udostępnij linkiem.',
      sl: 'Toposkop na {brand} — na zemljevid narišite orientacijsko tablo: vetrovnico na eni točki z imenovanim žarkom do vsake druge točke, ki navaja smer, razdaljo in nadmorsko višino. Izvozite jo z zemljevidom ali delite kot povezavo.',
      fr: 'Toposcope sur {brand} — dessinez une table d’orientation sur la carte : une rose des vents posée sur un point, avec un rayon nommé vers chaque autre point indiquant direction, distance et altitude. Exportez-la avec la carte ou partagez-la par lien.',
    },
  },
  {
    param: 'tool=tracking',
    title: {
      sk: 'Živé sledovanie polohy',
      en: 'Live GPS tracking',
      cs: 'Živé sledování polohy',
      hu: 'Élő GPS-követés',
      it: 'Tracciamento GPS in tempo reale',
      de: 'Live-GPS-Tracking',
      pl: 'Śledzenie GPS na żywo',
      sl: 'Sledenje GPS v živo',
      fr: 'Suivi GPS en direct',
    },
    description: {
      sk: 'Živé sledovanie na {brand} — sledujte zariadenia v mape v reálnom čase a umožnite ostatným sledovať to vaše pomocou tokenu. Funguje s OsmAnd, Locus, Traccar a podobnými sledovačmi, s farebne odlíšenými trasami a výškovými profilmi.',
      en: 'Live tracking on {brand} — follow devices on the map in real time and let others follow yours through a watch token. Works with OsmAnd, Locus, Traccar and similar trackers, with colorized tracks and elevation profiles.',
      cs: 'Živé sledování na {brand} — sledujte zařízení v mapě v reálném čase a umožněte ostatním sledovat to vaše pomocí tokenu. Funguje s OsmAnd, Locus, Traccar a podobnými sledovači, s barevně odlišenými trasami a výškovými profily.',
      hu: 'Élő követés a {brand} oldalon — kövesse az eszközöket valós időben a térképen, és engedje, hogy mások kövessék az önét megfigyelési tokennel. Működik OsmAnd, Locus, Traccar és hasonló nyomkövetőkkel, színezett nyomvonalakkal és magassági profilokkal.',
      it: 'Tracciamento in tempo reale su {brand} — segui i dispositivi sulla mappa in tempo reale e lascia che altri seguano il tuo tramite un token di osservazione. Funziona con OsmAnd, Locus, Traccar e tracker simili, con tracce colorate e profili altimetrici.',
      de: 'Live-Tracking auf {brand} — Geräte in Echtzeit auf der Karte verfolgen und das eigene per Beobachtungs-Token freigeben. Funktioniert mit OsmAnd, Locus, Traccar und ähnlichen Trackern, mit eingefärbten Tracks und Höhenprofilen.',
      pl: 'Śledzenie na żywo w {brand} — obserwuj urządzenia na mapie w czasie rzeczywistym i pozwól innym śledzić twoje za pomocą tokenu. Działa z OsmAnd, Locus, Traccar i podobnymi trackerami, z kolorowanymi śladami i profilami wysokościowymi.',
      sl: 'Sledenje v živo na {brand} — spremljajte naprave na zemljevidu v realnem času in dovolite drugim, da spremljajo vašo prek žetona za opazovanje. Deluje z OsmAnd, Locus, Traccar in podobnimi sledilniki, z obarvanimi sledmi in višinskimi profili.',
      fr: 'Suivi en direct sur {brand} — suivez des appareils sur la carte en temps réel et laissez d’autres suivre le vôtre grâce à un jeton d’observation. Compatible OsmAnd, Locus, Traccar et traceurs similaires, avec traces colorées et profils altimétriques.',
    },
  },
  {
    param: 'tool=import-file',
    title: {
      sk: 'Prehliadač GPX: trasy a dáta',
      en: 'GPX viewer: tracks and data',
      cs: 'Prohlížeč GPX: trasy a data',
      hu: 'GPX-megjelenítő: nyomvonalak és adatok',
      it: 'Visualizzatore GPX: tracce e dati',
      de: 'GPX-Viewer: Tracks und Daten',
      pl: 'Przeglądarka GPX: ślady i dane',
      sl: 'Pregledovalnik GPX: sledi in podatki',
      fr: 'Visionneuse GPX : traces et données',
    },
    description: {
      sk: 'Otvorte GPX na {brand} — načítajte do mapy GPX, KML, KMZ, TCX alebo GeoJSON, pozrite si vzdialenosť, trvanie a výškový profil, zafarbite trasu podľa výšky, rýchlosti či sklonu a znova ju exportujte.',
      en: 'Open a GPX file on {brand} — load GPX, KML, KMZ, TCX or GeoJSON onto the map, see distance, duration and the elevation profile, colorize the track by elevation, speed or steepness, and export it again.',
      cs: 'Otevřete GPX na {brand} — načtěte do mapy GPX, KML, KMZ, TCX nebo GeoJSON, prohlédněte si vzdálenost, trvání a výškový profil, obarvěte trasu podle výšky, rychlosti či sklonu a znovu ji exportujte.',
      hu: 'Nyisson meg GPX-fájlt a {brand} oldalon — töltsön be GPX, KML, KMZ, TCX vagy GeoJSON adatot a térképre, nézze meg a távolságot, az időtartamot és a magassági profilt, színezze a nyomvonalat magasság, sebesség vagy meredekség szerint, majd exportálja újra.',
      it: 'Apri un file GPX su {brand} — carica GPX, KML, KMZ, TCX o GeoJSON sulla mappa, vedi distanza, durata e profilo altimetrico, colora la traccia per quota, velocità o pendenza ed esportala di nuovo.',
      de: 'GPX-Datei auf {brand} öffnen — GPX, KML, KMZ, TCX oder GeoJSON auf die Karte laden, Distanz, Dauer und Höhenprofil sehen, den Track nach Höhe, Geschwindigkeit oder Steigung einfärben und wieder exportieren.',
      pl: 'Otwórz plik GPX w {brand} — wczytaj GPX, KML, KMZ, TCX lub GeoJSON na mapę, zobacz dystans, czas i profil wysokościowy, pokoloruj ślad według wysokości, prędkości lub nachylenia i wyeksportuj go ponownie.',
      sl: 'Odprite datoteko GPX na {brand} — na zemljevid naložite GPX, KML, KMZ, TCX ali GeoJSON, si oglejte razdaljo, trajanje in višinski profil, obarvajte sled po višini, hitrosti ali strmini ter jo znova izvozite.',
      fr: 'Ouvrez un fichier GPX sur {brand} — chargez GPX, KML, KMZ, TCX ou GeoJSON sur la carte, consultez distance, durée et profil altimétrique, colorez la trace selon l’altitude, la vitesse ou la pente, puis réexportez-la.',
    },
  },
  {
    param: 'tool=panorama',
    title: {
      sk: '360° panoráma terénu',
      en: '360° terrain panorama',
      cs: '360° panorama terénu',
      hu: '360°-os domborzati panoráma',
      it: 'Panorama 360° del terreno',
      de: '360°-Geländepanorama',
      pl: 'Panorama terenu 360°',
      sl: '360-stopinjska panorama terena',
      fr: 'Panorama 360° du relief',
    },
    description: {
      sk: 'Panoráma terénu na {brand} — vykreslite 360° výhľad z ľubovoľného bodu z tých istých výškových modelov, z akých je tieňovaná turistická mapa, s automaticky pomenovanými vrcholmi a s údajom o vzdialenosti pre každý pixel. Ide o holý terén, lesy a budovy sa nekreslia.',
      en: 'Terrain panorama on {brand} — render the 360° view from any point out of the same elevation models the outdoor map is shaded from, with summits named automatically and every pixel reporting how far away it is. Bare earth, so forests and buildings are not drawn.',
      cs: 'Panorama terénu na {brand} — vykreslete 360° výhled z libovolného bodu z týchž výškových modelů, z nichž je stínována turistická mapa, s automaticky pojmenovanými vrcholy a s údajem o vzdálenosti pro každý pixel. Jde o holý terén, lesy a budovy se nekreslí.',
      hu: 'Domborzati panoráma a {brand} oldalon — jelenítse meg a 360°-os kilátást bármely pontból ugyanabból a magassági modellből, amelyből a turistatérkép árnyékolása készül, automatikusan megnevezett csúcsokkal, és minden képpont megadja a távolságát. Csupasz felszín: erdők és épületek nem jelennek meg.',
      it: 'Panorama del terreno su {brand} — genera la vista a 360° da un punto qualsiasi a partire dagli stessi modelli altimetrici che ombreggiano la mappa outdoor, con le cime nominate in automatico e ogni pixel che indica la propria distanza. Terreno nudo: boschi ed edifici non vengono disegnati.',
      de: 'Geländepanorama auf {brand} — die 360°-Sicht von einem beliebigen Punkt aus denselben Höhenmodellen rendern, aus denen die Outdoor-Karte schummeriert wird, mit automatisch benannten Gipfeln; jedes Pixel nennt seine Entfernung. Nacktes Gelände: Wälder und Gebäude werden nicht gezeichnet.',
      pl: 'Panorama terenu w {brand} — wyrenderuj widok 360° z dowolnego punktu na podstawie tych samych modeli wysokościowych, z których powstaje cieniowanie mapy outdoorowej, z automatycznie nazwanymi szczytami i odległością podawaną dla każdego piksela. To goła ziemia, więc lasy i budynki nie są rysowane.',
      sl: 'Panorama terena na {brand} — izrišite 360-stopinjski pogled s poljubne točke iz istih višinskih modelov, iz katerih je senčen pohodniški zemljevid, s samodejno poimenovanimi vrhovi in podatkom o oddaljenosti za vsak piksel. Gre za golo površje, zato gozdovi in stavbe niso izrisani.',
      fr: 'Panorama du relief sur {brand} — calculez la vue à 360° depuis n’importe quel point à partir des mêmes modèles altimétriques qui ombrent la carte outdoor, avec les sommets nommés automatiquement et chaque pixel indiquant sa distance. Terrain nu : forêts et bâtiments ne sont pas dessinés.',
    },
  },
  {
    param: 'tool=gps-recorder',
    title: {
      sk: 'Záznamník GPS trás pre Android',
      en: 'GPS track recorder for Android',
      cs: 'Záznamník GPS tras pro Android',
      hu: 'GPS-nyomvonalrögzítő Androidra',
      it: 'Registratore di tracce GPS per Android',
      de: 'GPS-Track-Recorder für Android',
      pl: 'Rejestrator śladów GPS na Androida',
      sl: 'Snemalnik sledi GPS za Android',
      fr: 'Enregistreur de traces GPS pour Android',
    },
    description: {
      sk: 'Záznamník GPS na {brand} — zaznamenávajte trasu sprievodnou aplikáciou pre Android, zatiaľ čo mapa ju ukazuje naživo, takže záznam prežije zatvorenie či ukončenie prehliadača. Po ukončení sa trasa otvorí ako bežná, pripravená na výškový profil a všetky exporty.',
      en: 'GPS recorder on {brand} — record a track with the companion Android app while the map shows it live, so the recording survives the browser being closed or killed. Finish it and the track opens as an ordinary one, ready for the elevation profile and every export.',
      cs: 'Záznamník GPS na {brand} — zaznamenávejte trasu doprovodnou aplikací pro Android, zatímco mapa ji ukazuje živě, takže záznam přežije zavření či ukončení prohlížeče. Po dokončení se trasa otevře jako běžná, připravená na výškový profil a všechny exporty.',
      hu: 'GPS-rögzítő a {brand} oldalon — rögzítsen nyomvonalat a kísérő Android-alkalmazással, miközben a térkép élőben mutatja, így a felvétel túléli a böngésző bezárását vagy leállítását. Befejezés után a nyomvonal közönségesként nyílik meg, készen a magassági profilra és minden exportra.',
      it: 'Registratore GPS su {brand} — registra una traccia con l’app Android dedicata mentre la mappa la mostra in diretta, così la registrazione sopravvive alla chiusura del browser. Al termine la traccia si apre come una qualsiasi, pronta per il profilo altimetrico e per ogni esportazione.',
      de: 'GPS-Recorder auf {brand} — einen Track mit der zugehörigen Android-App aufzeichnen, während die Karte ihn live zeigt; die Aufzeichnung übersteht das Schließen oder Beenden des Browsers. Nach dem Beenden öffnet sich der Track wie jeder andere, bereit für Höhenprofil und alle Exporte.',
      pl: 'Rejestrator GPS w {brand} — nagrywaj ślad towarzyszącą aplikacją na Androida, podczas gdy mapa pokazuje go na żywo, więc nagranie przetrwa zamknięcie lub zabicie przeglądarki. Po zakończeniu ślad otwiera się jak zwykły, gotowy na profil wysokościowy i każdy eksport.',
      sl: 'Snemalnik GPS na {brand} — posnemite sled s spremljevalno aplikacijo za Android, medtem ko jo zemljevid prikazuje v živo, zato snemanje preživi zaprtje ali ustavitev brskalnika. Po zaključku se sled odpre kot običajna, pripravljena za višinski profil in vse izvoze.',
      fr: 'Enregistreur GPS sur {brand} — enregistrez une trace avec l’application Android compagnon pendant que la carte l’affiche en direct ; l’enregistrement survit à la fermeture du navigateur. Une fois terminée, la trace s’ouvre comme n’importe quelle autre, prête pour le profil altimétrique et tous les exports.',
    },
  },
  // ---- Dialogs ----
  {
    param: 'show=map-to-document-export',
    title: {
      sk: 'Export mapy do obrázka alebo PDF',
      en: 'Map export to image or PDF',
      cs: 'Export mapy do obrázku nebo PDF',
      hu: 'Térkép exportálása képbe vagy PDF-be',
      it: 'Esportazione della mappa in immagine o PDF',
      de: 'Kartenexport als Bild oder PDF',
      pl: 'Eksport mapy do obrazu lub PDF',
      sl: 'Izvoz zemljevida v sliko ali PDF',
      fr: 'Export de la carte en image ou PDF',
    },
    description: {
      sk: 'Export mapy na {brand} — exportujte mapu ako JPEG, PNG, PDF alebo SVG vo zvolenom rozlíšení, voliteľne s vrstevnicami, tieňovaným reliéfom, trasami, kresbou a naplánovanými trasami, pripravené na tlač.',
      en: 'Map export on {brand} — export the map as JPEG, PNG, PDF or SVG at a chosen resolution, optionally with contours, shaded relief, trails, drawing and planned routes, ready for printing.',
      cs: 'Export mapy na {brand} — exportujte mapu jako JPEG, PNG, PDF nebo SVG ve zvoleném rozlišení, volitelně s vrstevnicemi, stínovaným reliéfem, trasami, kresbou a naplánovanými trasami, připravené k tisku.',
      hu: 'Térképexport a {brand} oldalon — mentse a térképet JPEG, PNG, PDF vagy SVG formátumban a választott felbontásban, igény szerint szintvonalakkal, domborzatárnyékolással, útvonalakkal, rajzzal és tervezett útvonalakkal, nyomtatásra készen.',
      it: 'Esportazione della mappa su {brand} — esporta la mappa come JPEG, PNG, PDF o SVG alla risoluzione scelta, con la possibilità di includere curve di livello, rilievo ombreggiato, sentieri, disegno e percorsi pianificati, pronta per la stampa.',
      de: 'Kartenexport auf {brand} — die Karte als JPEG, PNG, PDF oder SVG in gewählter Auflösung exportieren, wahlweise mit Höhenlinien, Schummerung, Wegen, Zeichnung und geplanten Routen, druckfertig.',
      pl: 'Eksport mapy w {brand} — wyeksportuj mapę jako JPEG, PNG, PDF lub SVG w wybranej rozdzielczości, opcjonalnie z poziomicami, cieniowaniem rzeźby, szlakami, rysunkiem i zaplanowanymi trasami, gotową do druku.',
      sl: 'Izvoz zemljevida na {brand} — izvozite zemljevid kot JPEG, PNG, PDF ali SVG v izbrani ločljivosti, po želji s plastnicami, senčenim reliefom, potmi, risbo in načrtovanimi potmi, pripravljen za tisk.',
      fr: 'Export de la carte sur {brand} — exportez la carte en JPEG, PNG, PDF ou SVG à la résolution choisie, avec en option courbes de niveau, ombrage du relief, sentiers, dessin et itinéraires planifiés, prête à imprimer.',
    },
  },
  {
    param: 'show=map-features-export',
    title: {
      sk: 'Export mapových dát (GPX, GeoJSON)',
      en: 'Map data export (GPX, GeoJSON)',
      cs: 'Export mapových dat (GPX, GeoJSON)',
      hu: 'Térképadatok exportálása (GPX, GeoJSON)',
      it: 'Esportazione dei dati della mappa (GPX, GeoJSON)',
      de: 'Kartendaten-Export (GPX, GeoJSON)',
      pl: 'Eksport danych mapy (GPX, GeoJSON)',
      sl: 'Izvoz podatkov zemljevida (GPX, GeoJSON)',
      fr: 'Export des données de la carte (GPX, GeoJSON)',
    },
    description: {
      sk: 'Export mapových dát na {brand} — exportujte svoje trasy, body záujmu, fotografie, kresby, živé záznamy a GPX dáta ako GPX alebo GeoJSON, alebo ich odošlite do Google Drive, Dropboxu či Garmin Connect.',
      en: 'Map data export on {brand} — export your routes, points of interest, photos, drawings, live tracks and GPX data as GPX or GeoJSON, or send them to Google Drive, Dropbox or Garmin Connect.',
      cs: 'Export mapových dat na {brand} — exportujte své trasy, body zájmu, fotografie, kresby, živé záznamy a GPX data jako GPX nebo GeoJSON, nebo je odešlete do Google Drive, Dropboxu či Garmin Connect.',
      hu: 'Térképadat-export a {brand} oldalon — mentse útvonalait, érdekes pontjait, fényképeit, rajzait, élő nyomvonalait és GPX-adatait GPX vagy GeoJSON formátumban, vagy küldje őket a Google Drive, a Dropbox vagy a Garmin Connect szolgáltatásba.',
      it: 'Esportazione dei dati su {brand} — esporta percorsi, punti di interesse, foto, disegni, tracce in diretta e dati GPX come GPX o GeoJSON, oppure inviali a Google Drive, Dropbox o Garmin Connect.',
      de: 'Kartendaten-Export auf {brand} — Routen, Points of Interest, Fotos, Zeichnungen, Live-Tracks und GPX-Daten als GPX oder GeoJSON exportieren oder an Google Drive, Dropbox oder Garmin Connect senden.',
      pl: 'Eksport danych mapy w {brand} — wyeksportuj swoje trasy, punkty zainteresowania, zdjęcia, rysunki, ślady na żywo i dane GPX jako GPX lub GeoJSON albo wyślij je do Google Drive, Dropboksa czy Garmin Connect.',
      sl: 'Izvoz podatkov zemljevida na {brand} — izvozite svoje poti, točke zanimivosti, fotografije, risbe, žive sledi in podatke GPX kot GPX ali GeoJSON ali jih pošljite v Google Drive, Dropbox ali Garmin Connect.',
      fr: 'Export des données sur {brand} — exportez vos itinéraires, points d’intérêt, photos, dessins, traces en direct et données GPX en GPX ou GeoJSON, ou envoyez-les vers Google Drive, Dropbox ou Garmin Connect.',
    },
  },
  {
    param: 'show=embed',
    title: {
      sk: 'Vloženie mapy do stránky',
      en: 'Embed the map',
      cs: 'Vložení mapy do stránky',
      hu: 'Térkép beágyazása',
      it: 'Incorpora la mappa',
      de: 'Karte einbetten',
      pl: 'Osadzenie mapy',
      sl: 'Vgradnja zemljevida',
      fr: 'Intégrer la carte',
    },
    description: {
      sk: 'Vloženie mapy z {brand} — vygenerujte iframe a umiestnite interaktívnu turistickú mapu na vlastnú stránku s nastaviteľnou veľkosťou a ovládacími prvkami.',
      en: 'Embed the map from {brand} — generate an iframe to put an interactive outdoor map on your own website, with configurable size and controls.',
      cs: 'Vložení mapy z {brand} — vygenerujte iframe a umístěte interaktivní turistickou mapu na vlastní stránku s nastavitelnou velikostí a ovládacími prvky.',
      hu: 'Térkép beágyazása a {brand} oldalról — hozzon létre iframe-et, hogy interaktív túratérképet tegyen a saját webhelyére, állítható mérettel és kezelőelemekkel.',
      it: 'Incorpora la mappa da {brand} — genera un iframe per mettere una mappa outdoor interattiva sul tuo sito, con dimensioni e controlli configurabili.',
      de: 'Karte von {brand} einbetten — ein iframe erzeugen und eine interaktive Outdoor-Karte auf der eigenen Website einbinden, mit einstellbarer Größe und Bedienelementen.',
      pl: 'Osadzenie mapy z {brand} — wygeneruj iframe, aby umieścić interaktywną mapę outdoorową na własnej stronie, z konfigurowalnym rozmiarem i elementami sterującymi.',
      sl: 'Vgradnja zemljevida z {brand} — ustvarite iframe in postavite interaktivni pohodniški zemljevid na svojo spletno stran, z nastavljivo velikostjo in kontrolniki.',
      fr: 'Intégrer la carte de {brand} — générez une iframe pour placer une carte outdoor interactive sur votre propre site, avec taille et contrôles configurables.',
    },
  },
  {
    param: 'show=offline-map-export',
    title: {
      sk: 'Export offline máp (MBTiles)',
      en: 'Offline map export (MBTiles)',
      cs: 'Export offline map (MBTiles)',
      hu: 'Offline térkép exportálása (MBTiles)',
      it: 'Esportazione mappe offline (MBTiles)',
      de: 'Offline-Kartenexport (MBTiles)',
      pl: 'Eksport map offline (MBTiles)',
      sl: 'Izvoz zemljevidov brez povezave (MBTiles)',
      fr: 'Export de cartes hors ligne (MBTiles)',
    },
    description: {
      sk: 'Export offline máp na {brand} — stiahnite oblasti mapy ako MBTiles alebo SQLiteDB na offline použitie v GPS aplikáciách s výberom oblasti a rozsahu priblíženia.',
      en: 'Offline map export on {brand} — download map areas as MBTiles or SQLiteDB for offline use in GPS apps, choosing the area and zoom range.',
      cs: 'Export offline map na {brand} — stáhněte oblasti mapy jako MBTiles nebo SQLiteDB pro offline použití v GPS aplikacích s výběrem oblasti a rozsahu přiblížení.',
      hu: 'Offline térképexport a {brand} oldalon — töltsön le térképterületeket MBTiles vagy SQLiteDB formátumban GPS-alkalmazásokban való offline használatra, a terület és a nagyítási tartomány megválasztásával.',
      it: 'Esportazione mappe offline su {brand} — scarica aree della mappa come MBTiles o SQLiteDB per l’uso offline nelle app GPS, scegliendo area e intervallo di zoom.',
      de: 'Offline-Kartenexport auf {brand} — Kartenausschnitte als MBTiles oder SQLiteDB für die Offline-Nutzung in GPS-Apps herunterladen, mit Wahl von Gebiet und Zoombereich.',
      pl: 'Eksport map offline w {brand} — pobierz obszary mapy jako MBTiles lub SQLiteDB do użytku offline w aplikacjach GPS, wybierając obszar i zakres przybliżenia.',
      sl: 'Izvoz zemljevidov brez povezave na {brand} — prenesite območja zemljevida kot MBTiles ali SQLiteDB za uporabo brez povezave v aplikacijah GPS, z izbiro območja in obsega približave.',
      fr: 'Export de cartes hors ligne sur {brand} — téléchargez des zones de la carte en MBTiles ou SQLiteDB pour un usage hors ligne dans les applications GPS, en choisissant la zone et la plage de zoom.',
    },
  },
  {
    param: 'show=legend',
    title: {
      sk: 'Legenda mapy',
      en: 'Map legend',
      cs: 'Legenda mapy',
      hu: 'Térképjelmagyarázat',
      it: 'Legenda della mappa',
      de: 'Kartenlegende',
      pl: 'Legenda mapy',
      sl: 'Legenda zemljevida',
      fr: 'Légende de la carte',
    },
    description: {
      sk: 'Legenda mapy na {brand} — čo znamená každá značka, čiara a farba na turistickej mape: značenie trás, povrch a náročnosť ciest, chránené územia, prvky terénu a body záujmu.',
      en: 'Map legend on {brand} — what every symbol, line and colour on the outdoor map means: trail markings, path surfaces and grades, protected areas, terrain features and points of interest.',
      cs: 'Legenda mapy na {brand} — co znamená každá značka, čára a barva na turistické mapě: značení tras, povrch a náročnost cest, chráněná území, prvky terénu a body zájmu.',
      hu: 'Térképjelmagyarázat a {brand} oldalon — mit jelent a turistatérkép minden jele, vonala és színe: útvonaljelzések, útburkolatok és nehézségi fokozatok, védett területek, domborzati elemek és érdekes pontok.',
      it: 'Legenda della mappa su {brand} — che cosa significano tutti i simboli, le linee e i colori della mappa outdoor: segnavia, fondo e difficoltà dei sentieri, aree protette, elementi del terreno e punti di interesse.',
      de: 'Kartenlegende auf {brand} — was jedes Symbol, jede Linie und jede Farbe der Outdoor-Karte bedeutet: Wegmarkierungen, Wegbeläge und Schwierigkeitsgrade, Schutzgebiete, Geländeformen und Points of Interest.',
      pl: 'Legenda mapy w {brand} — co oznacza każdy symbol, linia i kolor na mapie outdoorowej: oznakowanie szlaków, nawierzchnia i trudność dróg, obszary chronione, formy terenu i punkty zainteresowania.',
      sl: 'Legenda zemljevida na {brand} — kaj pomeni vsak znak, črta in barva na pohodniškem zemljevidu: označbe poti, podlaga in zahtevnost poti, zavarovana območja, oblike terena in točke zanimivosti.',
      fr: 'Légende de la carte sur {brand} — ce que signifient tous les symboles, traits et couleurs de la carte outdoor : balisage des sentiers, revêtement et difficulté des chemins, espaces protégés, formes du relief et points d’intérêt.',
    },
  },
  {
    param: 'show=custom-maps',
    title: {
      sk: 'Pridanie vlastnej mapovej vrstvy',
      en: 'Add your own map layer',
      cs: 'Přidání vlastní mapové vrstvy',
      hu: 'Saját térképréteg hozzáadása',
      it: 'Aggiungi un livello mappa personale',
      de: 'Eigene Kartenebene hinzufügen',
      pl: 'Dodanie własnej warstwy mapy',
      sl: 'Dodajanje lastnega sloja zemljevida',
      fr: 'Ajouter votre propre couche de carte',
    },
    description: {
      sk: 'Vlastné mapy na {brand} — pridajte si vlastnú dlaždicovú, WMS alebo vektorovú vrstvu podľa URL a používajte ju ako podklad alebo prekryv, s vlastným názvom, ikonou, rozsahom priblíženia a uvedením zdroja.',
      en: 'Custom maps on {brand} — add your own tile, WMS or vector layer by URL and use it as a base map or an overlay, with its own name, icon, zoom range and attribution.',
      cs: 'Vlastní mapy na {brand} — přidejte si vlastní dlaždicovou, WMS nebo vektorovou vrstvu podle URL a používejte ji jako podklad nebo překryv, s vlastním názvem, ikonou, rozsahem přiblížení a uvedením zdroje.',
      hu: 'Egyéni térképek a {brand} oldalon — adjon hozzá saját csempés, WMS- vagy vektoros réteget URL alapján, és használja alaptérképként vagy fedvényként, saját névvel, ikonnal, nagyítási tartománnyal és forrásmegjelöléssel.',
      it: 'Mappe personalizzate su {brand} — aggiungi un tuo livello a tasselli, WMS o vettoriale tramite URL e usalo come mappa base o come sovrapposizione, con nome, icona, intervallo di zoom e attribuzione propri.',
      de: 'Eigene Karten auf {brand} — eine eigene Kachel-, WMS- oder Vektorebene per URL hinzufügen und als Basiskarte oder Overlay nutzen, mit eigenem Namen, Symbol, Zoombereich und Quellenangabe.',
      pl: 'Mapy własne w {brand} — dodaj własną warstwę kaflową, WMS lub wektorową przez adres URL i używaj jej jako podkładu lub nakładki, z własną nazwą, ikoną, zakresem przybliżenia i informacją o źródle.',
      sl: 'Zemljevidi po meri na {brand} — dodajte svoj tlakovani, WMS ali vektorski sloj prek URL in ga uporabljajte kot podlago ali prekrivni sloj, z lastnim imenom, ikono, obsegom približave in navedbo vira.',
      fr: 'Cartes personnalisées sur {brand} — ajoutez votre propre couche tuilée, WMS ou vectorielle par URL et utilisez-la comme fond de carte ou calque, avec nom, icône, plage de zoom et attribution propres.',
    },
  },
  {
    param: 'show=offline-maps',
    title: {
      sk: 'Offline mapy v prehliadači',
      en: 'Offline maps in the browser',
      cs: 'Offline mapy v prohlížeči',
      hu: 'Offline térképek a böngészőben',
      it: 'Mappe offline nel browser',
      de: 'Offline-Karten im Browser',
      pl: 'Mapy offline w przeglądarce',
      sl: 'Zemljevidi brez povezave v brskalniku',
      fr: 'Cartes hors ligne dans le navigateur',
    },
    description: {
      sk: 'Offline mapy na {brand} — uložte si oblasti mapy do prehliadača a používajte ich aj bez pripojenia, s výberom oblasti, vrstvy a rozsahu priblíženia. Na rozdiel od exportu MBTiles nepotrebujete inú aplikáciu: offline funguje samotná mapa.',
      en: 'Offline maps on {brand} — cache map areas in the browser and keep using them without a connection, choosing the area, layer and zoom range. Unlike the MBTiles export this needs no other app: the map itself works offline.',
      cs: 'Offline mapy na {brand} — uložte si oblasti mapy do prohlížeče a používejte je i bez připojení, s výběrem oblasti, vrstvy a rozsahu přiblížení. Na rozdíl od exportu MBTiles nepotřebujete jinou aplikaci: offline funguje samotná mapa.',
      hu: 'Offline térképek a {brand} oldalon — gyorsítótárazzon térképterületeket a böngészőben, és használja őket kapcsolat nélkül is, a terület, a réteg és a nagyítási tartomány megválasztásával. Az MBTiles-exporttal ellentétben nem kell másik alkalmazás: maga a térkép működik offline.',
      it: 'Mappe offline su {brand} — memorizza aree della mappa nel browser e continua a usarle senza connessione, scegliendo area, livello e intervallo di zoom. A differenza dell’esportazione MBTiles non serve un’altra app: è la mappa stessa a funzionare offline.',
      de: 'Offline-Karten auf {brand} — Kartenausschnitte im Browser zwischenspeichern und ohne Verbindung weiter nutzen, mit Wahl von Gebiet, Ebene und Zoombereich. Anders als beim MBTiles-Export braucht es keine weitere App: die Karte selbst funktioniert offline.',
      pl: 'Mapy offline w {brand} — zapisz obszary mapy w przeglądarce i korzystaj z nich bez połączenia, wybierając obszar, warstwę i zakres przybliżenia. W przeciwieństwie do eksportu MBTiles nie potrzebujesz innej aplikacji: offline działa sama mapa.',
      sl: 'Zemljevidi brez povezave na {brand} — shranite območja zemljevida v brskalnik in jih uporabljajte tudi brez povezave, z izbiro območja, sloja in obsega približave. Za razliko od izvoza MBTiles ne potrebujete druge aplikacije: brez povezave deluje sam zemljevid.',
      fr: 'Cartes hors ligne sur {brand} — mettez en cache des zones de la carte dans le navigateur et continuez à les utiliser sans connexion, en choisissant la zone, la couche et la plage de zoom. Contrairement à l’export MBTiles, aucune autre application n’est nécessaire : la carte elle-même fonctionne hors ligne.',
    },
  },
  {
    param: 'show=premium',
    title: {
      sk: 'Prémiový prístup',
      en: 'Premium access',
      cs: 'Prémiový přístup',
      hu: 'Prémium hozzáférés',
      it: 'Accesso premium',
      de: 'Premium-Zugang',
      pl: 'Dostęp premium',
      sl: 'Dostop premium',
      fr: 'Accès premium',
    },
    description: {
      sk: 'Prémium na {brand} — ročné predplatné, ktoré odstráni reklamný pruh a odomkne vyššie priblíženie vybraných vrstiev, výškové dáta s vysokým rozlíšením, multimodálne plánovanie trás a optimalizáciu poradia bodov, všetky režimy zafarbenia, šesť hodín meteoradaru s predpoveďou a dlhšie a jemnejšie výpočty viditeľnosti.',
      en: 'Premium on {brand} — a yearly plan that removes the ad banner and unlocks higher zoom on selected layers, high-resolution elevation data, multimodal routing and waypoint optimization, every colorize mode, six hours of weather radar with the forecast, and longer, finer viewshed renders.',
      cs: 'Prémium na {brand} — roční předplatné, které odstraní reklamní pruh a odemkne vyšší přiblížení vybraných vrstev, výšková data ve vysokém rozlišení, multimodální plánování tras a optimalizaci pořadí bodů, všechny režimy obarvení, šest hodin meteoradaru s předpovědí a delší a jemnější výpočty viditelnosti.',
      hu: 'Prémium a {brand} oldalon — éves előfizetés, amely eltünteti a hirdetéssávot, és feloldja a kiválasztott rétegek nagyobb nagyítását, a nagy felbontású magassági adatokat, a multimodális útvonaltervezést és a pontsorrend optimalizálását, az összes színezési módot, hat óra időjárási radart az előrejelzéssel, valamint a hosszabb és részletesebb kilátáselemzéseket.',
      it: 'Premium su {brand} — un abbonamento annuale che elimina il banner pubblicitario e sblocca zoom più elevati su livelli selezionati, dati altimetrici ad alta risoluzione, routing multimodale e ottimizzazione delle tappe, tutte le modalità di colorazione, sei ore di radar meteo con previsione e bacini visivi più estesi e dettagliati.',
      de: 'Premium auf {brand} — ein Jahresabo, das das Werbebanner entfernt und höhere Zoomstufen ausgewählter Ebenen, hochauflösende Höhendaten, multimodales Routing und Wegpunkt-Optimierung, alle Einfärbungsmodi, sechs Stunden Wetterradar samt Vorhersage sowie weitere und feinere Sichtbarkeitsberechnungen freischaltet.',
      pl: 'Premium w {brand} — roczny abonament, który usuwa baner reklamowy i odblokowuje wyższe przybliżenie wybranych warstw, dane wysokościowe w wysokiej rozdzielczości, routing multimodalny i optymalizację kolejności punktów, wszystkie tryby kolorowania, sześć godzin radaru pogodowego z prognozą oraz dalsze i dokładniejsze analizy widoczności.',
      sl: 'Premium na {brand} — letna naročnina, ki odstrani oglasni trak in odklene višje približave izbranih slojev, višinske podatke visoke ločljivosti, večmodalno usmerjanje in optimizacijo vrstnega reda točk, vse načine obarvanja, šest ur vremenskega radarja z napovedjo ter daljše in podrobnejše analize vidnosti.',
      fr: 'Premium sur {brand} — un abonnement annuel qui supprime la bannière publicitaire et débloque des zooms plus élevés sur certaines couches, des données altimétriques haute résolution, le routage multimodal et l’optimisation des étapes, tous les modes de colorisation, six heures de radar météo avec prévision, ainsi que des bassins de visibilité plus étendus et plus fins.',
    },
  },
];
