import { DeepPartialWithRequiredObjects } from '../deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartialWithRequiredObjects<OsmTagToNameMapping> =
  {
    aeroway: {
      aerodrome: 'Repülőtér',
    },

    aerialway: 'Felvonó, drótkötélpálya',

    amenity: {
      '*': '{}',
      animal_breeding: 'Állattenyésztés',
      animal_shelter: 'Állatmenhely',
      arts_centre: 'Művészeti központ',
      atm: 'Bankautomata',
      bank: 'Bank',
      bar: 'Bár',
      bbq: 'Grill',
      bench: 'Pad',
      bicycle_parking: 'Kerékpár parkoló',
      bicycle_rental: 'Kerékpár kölcsönző',
      biergarten: 'Sörkert',
      bus_station: 'Buszpályaudvar',
      car_rental: 'Car rental',
      car_wash: 'Autómosó',
      charging_station: 'Töltőállomás',
      childcare: 'Childcare',
      cinema: 'Mozi',
      clinic: 'Klinika',
      college: 'Főiskola',
      community_centre: 'Közösségi központ',
      compressed_air: 'Compressed air',
      courthouse: 'Bíróság',
      dentist: 'Fogorvos',
      doctors: "Doctor's office",
      drinking_water: 'Ivóvíz',
      embassy: 'Nagykövetség',
      fast_food: 'Gyorsétterem',
      fire_station: 'Tűzoltóság ',
      fountain: 'Szökőkút',
      hospital: 'Kórház',
      library: 'Könyvtár',
      marketplace: 'Piac',
      nightclub: 'Éjszakai klub',
      parking: 'Parkoló',
      parking_entrance: 'Parkoló entrance',
      parking_space: 'Parkoló space',
      pharmacy: 'Gyógyszertár',
      place_of_worship: 'Vallási hely',
      police: 'Rendőrség',
      post_office: 'Postahivatal',
      prison: 'Börtön',
      pub: 'Kocsma',
      public_bookcase: 'Kocsmalic bookcase',
      ranger_station: 'Ranger station',
      recycling: 'Újrahasznosítás',
      restaurant: 'Étterem',
      school: 'Iskola',

      shelter: {
        '*': 'Menedékhely',
        shelter_type: {
          '*': 'Menedékhely {}',
          picnic_shelter: {
            fireplace: {
              yes: 'Piknik menedék tűzhellyel',
            },
            '*': 'Piknik menedék',
          },
          basic_hut: 'Egyszerű kunyhó',
          changing_rooms: 'Öltözők',
          field_shelter: 'Mezei menedék',
          lean_to: 'Falas menedék',
          public_transport: 'Tömegközlekedési menedék',
          rock_shelter: 'Szikla menedék',
          sun_shelter: 'Napernyő menedék',
          weather_shelter: 'Időjárás elleni menedék',
        },
      },

      social_facility: {
        social_facility: {
          shelter: 'Menedékhely',
          ambulatory_care: 'Járóbeteg ellátás',
          assisted_living: 'Támogatott lakhatás',
          clothing_bank: 'Ruhabank',
          day_care: 'Napközi otthon',
          food_bank: 'Élelmiszerbank',
          group_home: 'Csoportos otthon',
          hospice: 'Hospice',
          nursing_home: 'Idősek otthona',
          soup_kitchen: 'Ingyen konyha',
          workshop: 'Műhely',
        },
        '*': 'Szociális intézmény',
      },

      theatre: 'Színház',
      toilets: 'WC',
      university: 'Egyetem',

      vending_machine: {
        vending: {
          bicycle_tube: 'Kerékpárbelső automatája',
          bread: 'Kenyeres automata',
          bottle_return: 'Üvegvisszaváltó automata',
          candles: 'Gyertyás automata',
          chewing_gums: 'Rágógumi automata',
          cigarettes: 'Dohányautomata',
          coffee: 'Kávéautomata',
          condoms: 'Óvszer automata',
          drinks: 'Italautomata',
          elongated_coin: 'Hosszított érme automata',
          eggs: 'Tojásautomata',
          excrement_bags: 'Kaki zacskó automata',
          food: 'Ételautomata',
          fuel: 'Üzemanyag automata',
          gas: 'Gáz automata',
          ice_cream: 'Fagylalt automata',
          ice_cubes: 'Jégtömb automata',
          milk: 'Tej automata',
          movies: 'Film automata',
          newspapers: 'Újság automata',
          parking_tickets: 'Parkolójegy automata',
          pizza: 'Pizza automata',
          public_transport_tickets: 'Tömegközlekedési jegy automata',
          stamps: 'Bélyeg automata',
          sweets: 'Édesség automata',
          water: 'Víz automata',
        },
        '*': 'Automata',
      },

      veterinary: 'Állatorvos',

      bicycle_repair_station: 'Kerékpárjavító állomás',
      brothel: 'Kúria',
      bureau_de_change: 'Valutaváltó',
      cafe: 'Kávézó',
      casino: 'Kaszinó',
      clock: 'Óra',
      device_charging_station: 'Eszköz töltőállomás',
      dressing_room: 'Öltöző',
      driving_school: 'Vezetőiskola',
      events_venue: 'Rendezvényhelyszín',
      feeding_place: 'Etetőhely',
      ferry_terminal: 'Kompkikötő',
      food_court: 'Étkezde',
      fuel: 'Üzemanyagtöltő állomás',
      funeral_hall: 'Temetkezési terem',
      gambling: 'Szerencsejáték',
      game_feeding: 'Vadetető',
      grave_yard: 'Temető',
      grit_bin: 'Sószóró tartály',
      hunting_stand: 'Vadászles',
      ice_cream: 'Fagylaltozó',
      kindergarten: 'Óvoda',
      language_school: 'Nyelviskola',
      monastery: 'Kolostor',
      money_transfer: 'Pénzátutalás',
      motorcycle_parking: 'Motoros parkoló',
      motorcycle_rental: 'Motoros kölcsönző',
      parcel_locker: 'Csomagautomata',
      place_of_mourning: 'Gyászhely',
      planetarium: 'Planetárium',
      post_box: 'Postafiók',
      shower: 'Zuhanyzó',
      ski_rental: 'Sífelszerelés kölcsönző',
      smoking_area: 'Dohányzóhely',
      social_centre: 'Szociális központ',
      stripclub: 'Sztriptízbár',
      studio: 'Stúdió',
      taxi: 'Taxi',
      telephone: 'Telefon',
      townhall: 'Városháza',
      traffic_park: 'Közlekedési park',
      trolley_bay: 'Kocsitároló',
      vacuum_cleaner: 'Porszívó',
      vehicle_inspection: 'Járművizsgálat',
      waste_basket: 'Szemetes',
      waste_disposal: 'Hulladékkezelés',
      water_point: 'Vízvételi hely',
      watering_place: 'Itatóhely',
    },

    barrier: {
      '*': 'Akadály {}',
      block: 'Tömb',
      bollard: 'Korlátoszlop',
      border_control: 'Határátkelő',
      cable_barrier: 'Kábelkorlát',
      chain: 'Lánc',
      city_wall: 'Városfal',
      ditch: 'Árok (akadály)',
      entrance: 'Bejárat',
      fence: 'Kerítés',
      gate: 'Kapunyílás',
      guard_rail: 'Elválasztó korlát',
      handrail: 'Kézvédő korlát',
      hedge: 'Élősövény',
      kerb: 'Járdaszegély',
      lift_gate: 'Felpattintható kapu',
      rope: 'Kötél',
      sliding_gate: 'Tolókapu',
      swing_gate: 'Lengőkapu',
      turnstile: 'Forgóajtó',
      wall: 'Fal',
    },

    boundary: {
      administrative: {
        admin_level: {
          '2': 'Ország',
          '3': 'Régió',
          '4': 'Kerület',
          '5': 'Tartomány',
          '6': 'Város',
          '7': 'Régió',
          '8': 'Kerület',
          '9': 'Falu',
          '10': 'Kataszteri terület',
        },
        '*': 'Közigazgatási terület',
      },
      '*': 'Régió',
      national_park: 'Nemzeti park',
      protected_area: 'Védett terület',
    },

    building: {
      '*': 'Épület {}',
      apartments: 'Társasház (tömb)',
      barn: 'Ól',
      bungalow: 'Bungaló',
      bunker: 'Bunker',
      cabin: 'Kunyhó',
      cathedral: 'Katedrális',
      chapel: 'Kápolna',
      church: 'Templom',
      civic: 'Középület',
      collapsed: 'Rombolt épület',
      commercial: 'Kereskedelmi épület',
      construction: 'Építkezés',
      cowshed: 'Istálló',
      detached: 'Családi ház',
      dormitory: 'Kollégium',
      entrance: 'Épületbejárat',
      farm_auxiliary: 'Gazdasági melléképület',
      farm: 'Gazdaság',
      garage: 'Garázs',
      garages: 'Garázsok',
      government: 'Kormányzati épület',
      grandstand: 'Nézőtér',
      greenhouse: 'Üvegház',
      hangar: 'Hangár',
      hayloft: 'Szénapadlás',
      hospital: 'Kórházi épület',
      hotel: 'Szállodaépület',
      house: 'Magánház',
      houseboat: 'Házihajó',
      hut: 'Viskó',
      industrial: 'Ipari épület',
      kindergarten: 'Óvodaépület',
      kiosk: 'Bódé',
      manufacture: 'Gyárépület',
      mosque: 'Mecset',
      office: 'Irodaház',
      parking: 'Parkolóépület',
      public: 'Középület',
      residential: 'Lakóház',
      retail: 'Kiskereskedelmi épület',
      roof: 'Tető',
      ruins: 'Épületrom',
      school: 'Iskolaépület',
      semidetached_house: 'Ikerház',
      service: 'Szolgáltató épület',
      shed: 'Fészer',
      shrine: 'Szentély',
      stable: 'Istálló',
      static_caravan: 'Mobilház, lakókocsi',
      storage_tank: 'Tárolótartály',
      sty: 'Disznóól',
      supermarket: 'Szupermarket épület',
      synagogue: 'Zsinagóga',
      temple: 'Templom',
      terrace: 'Sorház',
      train_station: 'Vasútállomás',
      transformer_tower: 'Transzformátor torony',
      transportation: 'Szállítási épület',
      university: 'Egyetemi épület',
      warehouse: 'Raktár',
      yes: 'Ismeretlen épület',
    },

    highway: {
      service: {
        service: {
          '*': 'Szolgálati út {}',
          alley: 'Kiskapu',
          bus: 'Tömegközlekedési út',
          'drive-through': 'Átjáró autós vásárláshoz',
          driveway: 'Bejáróút',
          emergency_access: 'Tűzoltó út',
          parking_aisle: 'Parkoló sáv',
        },
        '*': 'Szolgálati, bejáróút',
      },
      track: {
        tracktype: {
          grade1: 'Tömörített erdei út',
          grade2: 'Főként tömörített erdei út',
          grade3: 'Kevésbé tömörített, murvás erdei út',
          grade4: 'Traktorral vagy hasonló járművel járható erdei út',
          grade5: 'Alig felismerhető erdei út',
        },
        '*': 'Erdei út',
      },
      '*': 'Út {}',
      bus_stop: 'Buszmegálló',
      construction: 'Út építés alatt',
      crossing: 'Gyalogos átkelőhely',
      cycleway: 'Kerékpárút',
      footway: 'Járda',
      living_street: 'Lakóövezet',
      motorway: 'Autópálya',
      motorway_link: 'Autópálya csatlakozás',
      path: 'Ösvény',
      pedestrian: 'Gyalogos zóna',
      primary: 'Elsődleges út',
      primary_link: 'Elsődleges út csatlakozás',
      residential: 'Utca',
      secondary: 'Másodrendű út',
      secondaty_link: 'Másodrendű út csatlakozás',
      steps: 'Lépcső',
      street_lamp: 'Utcai lámpa',
      tertiary: 'Harmadrendű út',
      tertiary_link: 'Harmadrendű út csatlakozás',
      trunk: 'Főút',
      trunk_link: 'Főút csatlakozás',
      unclassified: 'Osztályozatlan út',
    },

    historic: {
      ruins: {
        ruins: {
          castle: 'Várrom',
        },
        '*': 'Romok',
      },
      '*': 'Történelmi építmény',
      archaeological_site: 'Kulturális régészeti helyszín',
      castle: 'Vár',
      church: 'Történelmi templom',
      city_gate: 'Városkapu',
      manor: 'Kúria',
      memorial: 'Emlékmű',
      monastery: 'Kolostor',
      monument: 'Műemlék',
      tomb: 'Síremlék',
      wayside_cross: 'Útszéli kereszt',
      wayside_shrine: 'Útszéli kápolna',
    },

    landuse: {
      '*': '{}',
      allotments: 'Kertészet',
      basin: 'Medence',
      brownfield: 'Barnamező',
      cemetery: 'Temető',
      commercial: 'Kereskedelmi terület',
      construction: 'Építési terület',
      education: 'Oktatási terület',
      farmland: 'Mezőgazdasági terület',
      farmyard: 'Gazdasági udvar',
      forest: 'Erdő',
      garages: 'Garázsok',
      grass: 'Gyep',
      greenfield: 'Zöldmezős terület',
      industrial: 'Ipari terület',
      landfill: 'Hulladéklerakó',
      meadow: 'Rét',
      military: 'Katonai terület',
      orchard: 'Gyümölcsös',
      plant_nursery: 'Növénykertészet',
      quarry: 'Kőfejtő',
      recreation_ground: 'Rekreációs terület',
      religions: 'Egyházi terület',
      reservoir: 'Tározó',
      residential: 'Lakóterület',
      retail: 'Kiskereskedelmi terület',
      vineyard: 'Szőlőültetvény',
      winter_sports: 'Téli sportok helye',
    },

    leisure: {
      picnic_table: {
        covered: {
          yes: 'Fedett piknikasztal',
        },
        '*': 'Piknikasztal',
      },
      pitch: {
        sport: {
          badminton: 'Röplabdapálya',
          basketball: 'Kosárlabdapálya',
          beachvolleyball: 'Strandröplabdapálya',
          hockey: 'Jégkorongpálya',
          ice_hockey: 'Jégkorongpálya',
          multi: 'Többcélú pálya',
          soccer: 'Focipálya',
          tennis: 'Teniszpálya',
          volleyball: 'Röplabdapálya',
        },
        '*': 'Pálya',
      },
      '*': '{}',
      bleachers: 'Nézőtér',
      escape_game: 'Szabadulós játék',
      hackerspace: 'Hackerspace',
      ice_rink: 'Jégpálya',
      marina: 'Marina',
      miniature_golf: 'Mini golf',
      dog_park: 'Kutyapark',
      firepit: 'Tűzrakóhely',
      fishing: 'Horgászhely',
      fitness_centre: 'Fitness központ',
      fitness_station: 'Fitness állomás',
      garden: 'Kert',
      golf_course: 'Golfpálya',
      horse_riding: 'Lovaglás',
      nature_reserve: 'Természetvédelmi terület',
      park: 'Park',
      playground: 'Játszótér',
      sports_centre: 'Sportközpont',
      sports_hall: 'Sportcsarnok',
      stadium: 'Stadion',
      swimming_pool: 'Uszoda',
      track: 'Pálya',
      water_park: 'Vízi park',
    },

    man_made: {
      tower: {
        'tower:type': {
          bell_tower: 'Harangtorony',
          communication: 'Kommunikációs torony',
          cooling: 'Hűtőtorny',
          observation: 'Kilátótorony',
        },
        '*': 'Torony',
      },
      '*': '{}',
      adit: 'Bányanyílás',
      antenna: 'Antenna',
      beacon: 'Jelzőfény',
      beehive: 'Kaptár',
      bridge: 'Híd',
      bunker_silo: 'Siló',
      cairn: 'Kőhalom',
      cellar_entrance: 'Pincebejárat',
      chimney: 'Kémény',
      clearcut: 'Erdőirtás',
      communications_tower: 'Kommunikációs torony',
      cooling_tower: 'Hűtőtorny',
      crane: 'Daruszerkezet',
      cross: 'Kereszt',
      cutline: 'Favágás vonala',
      dyke: 'Gát',
      embankment: 'Töltés',
      flagpole: 'Zászlórúd',
      "forester's_lodge": 'Erdészlak',
      gasometer: 'Gázmérő',
      goods_conveyor: 'Szállítószalag',
      groyne: 'Hullámtörő',
      lighthouse: 'Világítótorony',
      manhole: 'Aknafedél',
      mast: 'Tartóoszlop',
      mineshaft: 'Bányafeljáró',
      monitoring_station: 'Megfigyelő állomás',
      nesting_site: 'Fészkelőhely',
      observatory: 'Csillagvizsgáló',
      pier: 'Móló',
      pipeline: 'Csővezeték',
      reservoir_covered: 'Fedett tározó',
      silo: 'Siló',
      snow_cannon: 'Hókápló ágyú',
      spoil_heap: 'Hányadék halom',
      spring_box: 'Forrásvédő doboz',
      storage_tank: 'Tároló tartály',
      street_cabinet: 'Utcai szekrény',
      surveillance: 'Megfigyelő kamera',
      survey_point: 'Térképezési pont',
      telescope: 'Távcső',
      utility_pole: 'Villanyoszlop',
      wastewater_plant: 'Szennyvíztisztító',
      water_tap: 'Vízcsap',
      water_tower: 'Víztorony',
      water_well: 'Kút',
      water_works: 'Vízmű',
      watermill: 'Vízi malom',
      windmill: 'Szélmalom',
      works: 'Gyár',
    },

    natural: {
      spring: {
        drinking_water: {
          yes: 'Ivóvíz forrás',
          no: 'Nem iható forrás',
        },
        refitted: {
          yes: 'Felújított forrás',
          no: 'Nem felújított forrás',
        },
        '*': 'Forrás',
      },
      tree: {
        protected: {
          yes: 'Védett fa',
        },
        denotation: {
          natural_monument: 'Természeti emlékmű fa',
          landmark: 'Jellegzetes fa',
          avenue: 'Sétányfa',
          urban: 'Városi fa',
          agricultural: 'Mezőgazdasági fa',
        },
        '*': 'Fa',
      },
      '*': '{}',
      arch: 'Sziklaív',
      bare_rock: 'Csupasz szikla',
      basin: 'Medence',
      bay: 'Öböl',
      beach: 'Strand',
      birds_nest: 'Madárfészek',
      cave_entrance: 'Barlang',
      cliff: 'Szirt',
      earth_bank: 'Földgát',
      fell: 'Mocsár',
      geyser: 'Gejzír',
      glacier: 'Hegyi jég',
      grassland: 'Gyep',
      gully: 'Völgy',
      heath: 'Puszta',
      hot_spring: 'Termálforrás',
      landslide: 'Földcsuszamlás',
      mountain_range: 'Hegység',
      mud: 'Sár',
      peak: 'Csúcs',
      plateau: 'Fennsík',
      ridge: 'Hegylánc',
      rock: 'Szikla',
      saddle: 'Hágó',
      sand: 'Homok',
      scree: 'Törmelék',
      scrub: 'Cserje, bozót',
      shingle: 'Kavicsos part',
      shrub: 'Bokor',
      sinkhole: 'Karsztkúp',
      stone: 'Kő',
      tree_row: 'Fasor',
      valley: 'Völgy',
      water: 'Víztest',
      wetland: 'Mocsár',
      wood: 'Erdő',
    },

    place: {
      '*': 'Hely {}',
      city: 'Város',
      country: 'Ország',
      farm: 'Gazdaság',
      hamlet: 'Falucska',
      island: 'Sziget',
      islet: 'Szigetecske',
      isolated_dwelling: 'Elhagyatott lakóhely',
      locality: 'Helyiség',
      ocean: 'Óceán',
      sea: 'Tenger',
      square: 'Tér',
      state: 'Állam',
      suburb: 'Külváros',
      town: 'Város',
      village: 'Falu',
    },

    power: {
      '*': '{}',
      generator: 'Generátor',
      line: 'Villamos vezeték',
      minor_line: 'Kisebb villamos vezeték',
      plant: 'Erőmű',
      pole: 'Villanyoszlop',
      substation: 'Átviteli állomás',
      tower: 'Villamos torony',
      transformer: 'Transzformátor',
    },

    public_transport: {
      platform: 'Perron',
      station: 'Állomás',
      stop_position: 'Megállóhely',
    },

    shop: {
      '*': 'Bolt {}',
      household_linen: 'Lakástextil',
      charity: 'Jótékonysági bolt',
      chocolate: 'Csokoládébolt',
      fashion_accessories: 'Divatkiegészítő bolt',
      frozen_food: 'Fagyasztott élelmiszer bolt',
      hearing_aids: 'Hallókészülék bolt',
      weapons: 'Fegyverbolt',
      alcohol: 'Italbolt',
      antiques: 'Antikvárium',
      art: 'Művészeti bolt',
      baby_goods: 'Babaruházat bolt',
      bag: 'Táska bolt',
      bakery: 'Pékség',
      bathroom_furnishing: 'Fürdőszoba berendezés bolt',
      beauty: 'Szépségszalon',
      bed: 'Ágybolt',
      beverages: 'Italbolt',
      bicycle: 'Bicikli bolt',
      bookmaker: 'Fogadóiroda',
      books: 'Könyvesbolt',
      boutique: 'Boutique',
      butcher: 'Hentes',
      camera: 'Fényképezőgép bolt',
      car: 'Autókereskedés',
      car_parts: 'Autóalkatrész bolt',
      car_repair: 'Autószerviz',
      carpet: 'Szőnyegbolt',
      cheese: 'Sajtbolt',
      chemist: 'Gyógyszertár',
      clothes: 'Ruházati bolt',
      coffee: 'Kávézó',
      collector: 'Gyűjtői bolt',
      computer: 'Számítógép bolt',
      confectionery: 'Cukrászda',
      convenience: 'Vegyesbolt',
      copyshop: 'Fénymásoló bolt',
      cosmetics: 'Kozmetikai bolt',
      craft: 'Kézműves bolt',
      curtain: 'Függönybolt',
      dairy: 'Tejtermék bolt',
      deli: 'Húsbolt',
      department_store: 'Áruház',
      doityourself: 'Barkácsbolt',
      doors: 'Ajtóbolt',
      dry_cleaning: 'Vegytisztító',
      'e-cigarette': 'E-cigaretta bolt',
      electrical: 'Elektromos anyag bolt',
      electronics: 'Elektronikai bolt',
      erotic: 'Szexshop',
      fabric: 'Textilbolt',
      farm: 'Farm bolt',
      fireplace: 'Kandalló bolt',
      fishing: 'Horgászbolt',
      flooring: 'Padlóbolt',
      florist: 'Virágbolt',
      funeral_directors: 'Temetkezési szolgáltatás',
      furniture: 'Bútorbolt',
      games: 'Játékbolt',
      garden_center: 'Kertészeti központ',
      garden_centre: 'Kertészeti központ',
      general: 'Általános bolt',
      gift: 'Ajándékbolt',
      glaziery: 'Üveges bolt',
      greengrocer: 'Zöldséges',
      hairdresser: 'Fodrász',
      hardware: 'Vasáru bolt',
      health_food: 'Egészséges élelmiszer bolt',
      hifi: 'Hifi bolt',
      houseware: 'Háztartási bolt',
      hunting: 'Vadászfelszerelés bolt',
      ice_cream: 'Fagylaltozó',
      interior_decoration: 'Belső dekorációs bolt',
      jewelry: 'Ékszerbolt',
      kiosk: 'Bódé',
      kitchen: 'Konyhai bolt',
      laundry: 'Mosoda',
      lighting: 'Világítástechnikai bolt',
      locksmith: 'Lakatos',
      lottery: 'Lottózó',
      mall: 'Bevásárlóközpont',
      massage: 'Masszázs szalon',
      medical_supply: 'Orvosi eszköz bolt',
      mobile_phone: 'Mobiltelefon bolt',
      model: 'Modellező bolt',
      motorcycle: 'Motorbolt',
      music: 'Zene bolt',
      musical_instrument: 'Hangszerek boltja',
      newsagent: 'Újságos',
      nutrition_supplements: 'Táplálékkiegészítő bolt',
      optician: 'Optika',
      outdoor: 'Kültéri felszerelés bolt',
      outpost: 'Kikötő',
      paint: 'Festékbolt',
      pastry: 'Cukrászda',
      pawnbroker: 'Zálogház',
      perfumery: 'Parfüméria',
      pet: 'Állateledel bolt',
      pet_grooming: 'Kisállat kozmetika',
      photo: 'Fényképészeti bolt',
      radiotechnics: 'Rádiótechnikai bolt',
      rental: 'Kölcsönző',
      seafood: 'Tengeri étel bolt',
      second_hand: 'Használtcikk bolt',
      sewing: 'Varróbolt',
      shoes: 'Cipőbolt',
      sports: 'Sportbolt',
      stationery: 'Papír-írószer bolt',
      supermarket: 'Szupermarket',
      tailor: 'Szabó',
      tattoo: 'Tetováló szalon',
      tea: 'Teázó',
      ticket: 'Jegyiroda',
      tobacco: 'Dohánybolt',
      toys: 'Játékbolt',
      trade: 'Építőanyag bolt',
      travel_agency: 'Utazási iroda',
      tyres: 'Gumiabroncs bolt',
      vacant: 'Üres bolt',
      variety_store: 'Vegyesbolt',
      video: 'Videóbolt',
      video_games: 'Videójáték bolt',
      watches: 'Óra bolt',
      wholesale: 'Nagykereskedés',
      window_blind: 'Reluxa bolt',
      wine: 'Borkereskedés',
    },

    sport: {
      '*': 'Sport {}',
      australian_football: 'Ausztrál futball',
      billiards: 'Biliárd',
      boxing: 'Ökölvívás',
      cliff_diving: 'Szikláról ugrás',
      cricket: 'Krikket',
      cricket_nets: 'Krikket hálók',
      croquet: 'Krokett',
      curling: 'Curling',
      gaelic_games: 'Gaeilgei játékok',
      horseshoes: 'Patkódobás',
      korfball: 'Korfball',
      long_jump: 'Távolugrás',
      orienteering: 'Tájékozódási futás',
      paddle_tennis: 'Paddle tenisz',
      pelota: 'Pelota',
      racquet: 'Ütő',
      rc_car: 'Távirányítós autók',
      rugby: 'Rögbi',
      rugby_league: 'Rögbi liga',
      rugby_union: 'Rögbi unió',
      sailing: 'Vitorlázás',
      surfing: 'Szörfözés',
      table_soccer: 'Csocsó',
      team_handball: 'Kézilabda',
      toboggan: 'Szánkó',
      '9pin': '9-tüskés bowling',
      '10pin': '10-tüskés bowling',
      aikido: 'Aikidó',
      airsoft: 'Airsoft',
      american_football: 'Amerikai futball',
      archery: 'Íjászat',
      athletics: 'Atlétika',
      badminton: 'Tollaslabda',
      baseball: 'Baseball',
      basketball: 'Kosárlabda',
      beachvolleyball: 'Strandröplabda',
      bicycle: 'Kerékpározás',
      bmx: 'BMX',
      boules: 'Bocsa',
      bowling: 'Bowling',
      bowls: 'Bocsa',
      canoe: 'Kenuzás',
      chess: 'Sakk',
      climbing: 'Mászás',
      climbing_adventure: 'Mászó kaland',
      cycling: 'Kerékpározás',
      darts: 'Darts',
      disc_golf: 'Diszk golf',
      dog_racing: 'Kutyaverseny',
      equestrian: 'Lovaglás',
      field_hockey: 'Pályahoki',
      fitness: 'Fitness',
      floorball: 'Floorball',
      free_flying: 'Szabad repülés',
      golf: 'Golf',
      gymnastics: 'Torna',
      handball: 'Kézilabda',
      hockey: 'Jégkorong',
      horse_racing: 'Lóverseny',
      ice_hockey: 'Jégkorong',
      ice_skating: 'Jégkorcsolyázás',
      judo: 'Dzsidó',
      karate: 'Karate',
      karting: 'Gokart',
      laser_tag: 'Lézerharc',
      model_aerodrome: 'Modell repülőtér',
      motocross: 'Motokrossz',
      motor: 'Motorkerékpár verseny',
      multi: 'Több sportág',
      netball: 'Netball',
      paintball: 'Paintball',
      petanque: 'Petanque',
      roller_skating: 'Görkorcsolyázás',
      rowing: 'Evezés',
      running: 'Futás',
      scuba_diving: 'Búvárkodás',
      shooting: 'Lövészet',
      shooting_range: 'Lőtéren',
      'shot-put': 'Súlylökés',
      skateboard: 'Gördeszka',
      skating: 'Korcsolyázás',
      ski_jumping: 'Síugrás',
      skiing: 'Síelés',
      soccer: 'Foci',
      squash: 'Squash',
      streetball: 'Streetball',
      swimming: 'Úszás',
      table_tennis: 'Asztalitenisz',
      tennis: 'Tenisz',
      volleyball: 'Röplabda',
      water_ski: 'Vízi sí',
      workout: 'Edzés',
      yoga: 'Jóga',
    },

    tourism: {
      artwork: {
        artwork_type: {
          architecture: 'Építészet',
          bust: 'Mellszobor',
          graffiti: 'Graffiti',
          installation: 'Installációs művészet',
          mosaic: 'Mozaik',
          mural: 'Falfestmény',
          painting: 'Festmény',
          relief: 'Dombormű',
          sculpture: 'Szobrászat',
          statue: 'Szobor',
          stone: 'Szikla művészet',
        },
        '*': 'Művészet',
      },

      information: {
        information: {
          '*': 'Információ {}',
          board: 'Információs tábla',
          guidepost: 'Útjelző',
          map: 'Térkép',
          office: 'Információs iroda',
        },
        '*': 'Információ',
      },

      '*': '{}',

      alpine_hut: 'Alpesi menedékház',
      apartment: 'Apartman',
      aquarium: 'Akvárium',
      attraction: 'Látnivaló',
      camp_site: 'Kemping',
      caravan_site: 'Lakókocsi parkoló',
      chalet: 'Hütte',
      gallery: 'Galéria',
      guest_house: 'Vendégház',
      hostel: 'Hostel',
      hotel: 'Hotel',
      motel: 'Motel',
      museum: 'Múzeum',
      picnic_site: 'Piknikező hely',
      viewpoint: 'Kilátó',
      wilderness_hut: 'Vadregényes menedékház',
      zoo: 'Állatkert',
    },

    type: {
      route: {
        route: {
          '*': 'Útvonal {}',
          bicycle: 'Kerékpárút',
          bus: 'Busz útvonal',
          foot: 'Gyalogos útvonal',
          hiking: 'Túraútvonal',
          horse: 'Lovas útvonal',
          mtb: 'Mountain bike útvonal',
          piste: 'Sípálya vagy út',
          railway: 'Vasútvonal',
          ski: 'Sífutó útvonal',
          tram: 'Villamos útvonal',
        },
        '*': 'Útvonal',
      },
    },

    waterway: {
      '*': 'Vízút {}',
      canal: 'Csatorna',
      dam: 'Gát',
      ditch: 'Árok (vízút)',
      drain: 'Lefolyó',
      river: 'Folyó',
      stream: 'Patak, vízfolyás',
      waterfall: 'Vízesés',
      weir: 'Zsilip',
    },

    railway: 'Vasút',
  };

export const colorNames: Record<string, string> = {
  red: 'Piros',
  blue: 'Kék',
  green: 'Zöld',
  yellow: 'Sárga',
  orange: 'Narancssárga',
  purple: 'Lila',
  violet: 'Ibolya',
  white: 'Fehér',
  black: 'Fekete',
  gray: 'Szürke',
  brown: 'Barna',
};
