import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: OsmTagToNameMapping = {
  aeroway: {
    aerodrome: 'Aerodrome',
    airstrip: 'Airstrip',
    apron: 'Aircraft apron',
    gate: 'Airport gate',
    hangar: 'Aircraft hangar',
    helipad: 'Helipad',
    holding_position: 'Aircraft holding position',
    jet_bridge: 'Jet bridge / aerobridge / passenger boarding bridge',
    navigationaid: 'Air navigation aid',
    parking_position: 'Aircraft parking position',
    runway: 'Runway',
    stopway: 'Runway stopway',
    taxilane: 'Taxi lane',
    taxiway: 'Taxiway',
    terminal: 'Airport terminal',
    threshold: 'Runway threshold',
    tower: 'Air traffic control tower',
    windsock: 'Windsock',
  },
  aerialway: {
    '*': 'Aerialway',
    cable_car: 'Cable car',
    chair_lift: 'Chair lift',
    goods: 'Goods lift',
    'j-bar': 'J-bar lift',
    magic_carpet: 'Magic carpet',
    mixed_lift: 'Mixed lift',
    platter: 'Platter lift',
    pylon: 'Pylon',
    rope_tow: 'Rope tow',
    station: 'Station',
    't-bar': 'T-bar lift',
    zip_line: 'Zip line',
  },
  amenity: {
    '*': '{}',
    animal_breeding: 'Animal breeding',
    animal_shelter: 'Animal shelter',
    arts_centre: 'Arts centre',
    atm: 'ATM',
    bank: 'Bank',
    bar: 'Bar',
    bbq: 'Grill',
    bench: 'Bench',
    bicycle_parking: 'Bicycle parking',
    bicycle_rental: 'Bicycle rental',
    bicycle_repair_station: 'Bicycle repair station',
    biergarten: 'Biergarten',
    brothel: 'Brothel',
    bureau_de_change: 'Currency exchange',
    bus_station: 'Bus station',
    cafe: 'Cafe',
    car_rental: 'Car rental',
    car_wash: 'Car wash',
    casino: 'Casino',
    charging_station: 'Charging station',
    childcare: 'Childcare',
    cinema: 'Cinema',
    clinic: 'Clinic',
    clock: 'Clock',
    college: 'College',
    community_centre: 'Community centre',
    compressed_air: 'Compressed air',
    courthouse: 'Courthouse',
    dentist: 'Dentist',
    device_charging_station: 'Device charging station',
    doctors: "Doctor's office",
    dressing_room: 'Dressing room',
    drinking_water: 'Drinking water',
    driving_school: 'Driving school',
    embassy: 'Embassy',
    events_venue: 'Events venue',
    fast_food: 'Fast food',
    feeding_place: 'Feeding place',
    ferry_terminal: 'Ferry terminal',
    fire_station: 'Fire station ',
    food_court: 'Food court',
    fountain: 'Fountain',
    fuel: 'Gas station',
    funeral_hall: 'Funeral hall',
    gambling: 'Gambling',
    game_feeding: 'Game feeding',
    grave_yard: 'Grave yard',
    grit_bin: 'Grit bin',
    hospital: 'Hospital',
    hunting_stand: 'Hunting stand',
    ice_cream: 'Ice cream',
    kindergarten: 'Kindergarten',
    language_school: 'Language school',
    library: 'Library',
    marketplace: 'Marketplace',
    monastery: 'Monastery',
    money_transfer: 'Money transfer',
    motorcycle_parking: 'Motorcycle parking',
    motorcycle_rental: 'Motorcycle rental',
    nightclub: 'Nightclub',
    parcel_locker: 'Parcel locker',
    parking: 'Parking',
    parking_entrance: 'Parking entrance',
    parking_space: 'Parking space',
    pharmacy: 'Pharmacy',
    place_of_mourning: 'Place of mourning',
    place_of_worship: 'Place of worship',
    planetarium: 'Planetarium',
    police: 'Police',
    post_box: 'Post box',
    post_office: 'Post office',
    prison: 'Prison',
    pub: 'Pub',
    public_bookcase: 'Public bookcase',
    ranger_station: 'Ranger station',
    recycling: 'Recycling',
    restaurant: 'Restaurant',
    school: 'School',
    shelter: {
      '*': 'Shelter',
      shelter_type: {
        '*': 'Shelter {}',
        basic_hut: 'Basic hut',
        changing_rooms: 'Changing rooms',
        field_shelter: 'Field shelter',
        lean_to: 'Lean to',
        picnic_shelter: {
          '*': 'Picnic shelter',
          fireplace: { yes: 'Picnic shelter with fireplace' },
        },
        public_transport: 'Public transport shelter',
        rock_shelter: 'Rock shelter',
        sun_shelter: 'Sun shelter',
        weather_shelter: 'Weather shelter',
      },
    },
    shower: 'Shower',
    ski_rental: 'Ski rental',
    smoking_area: 'Smoking area',
    social_centre: 'Social centre',
    social_facility: {
      '*': 'Social facility',
      social_facility: {
        // dairy_kitchen: 'Dairy kitchen',
        // outreach: 'Outreach',
        ambulatory_care: 'Ambulatory care',
        assisted_living: 'Assisted_living',
        clothing_bank: 'Clothing bank',
        day_care: 'Day care',
        food_bank: 'Food bank',
        group_home: 'Group home',
        hospice: 'Hospice',
        nursing_home: 'Nursing home',
        shelter: 'Shelter',
        soup_kitchen: 'Soup kitchen',
        workshop: 'Workshop',
      },
    },
    stripclub: 'Stripclub',
    studio: 'Studio',
    taxi: 'Taxi',
    telephone: 'Telephone',
    theatre: 'Theatre',
    toilets: 'WC',
    townhall: 'Town hall',
    traffic_park: 'Traffic park',
    trolley_bay: 'Trolley bay',
    university: 'University',
    vacuum_cleaner: 'Vacuum cleaner',
    vehicle_inspection: 'Vehicle inspection',
    vending_machine: {
      '*': 'Vending machine',
      vending: {
        bicycle_tube: 'Bicycle tube vending machine',
        bread: 'Bread vending machine',
        bottle_return: 'Deposit bottle return machine',
        candles: 'Candle vending machine',
        chewing_gums: 'Chewing gum vending machine',
        cigarettes: 'Cigarette vending machine',
        coffee: 'Coffee vending machine',
        condoms: 'Condom vending machine',
        drinks: 'Drink vending machine',
        elongated_coin: 'Elongated coin machine',
        eggs: 'Egg vending machine',
        excrement_bags: 'Excrement bag vending machine',
        food: 'Food vending machine',
        fuel: 'Fuel vending machine',
        gas: 'Gas vending machine',
        ice_cream: 'Ice cream vending machine',
        ice_cubes: 'Ice cube vending machine',
        milk: 'Milk vending machine',
        movies: 'Movie vending machine',
        newspapers: 'Newspaper vending machine',
        parking_tickets: 'Parking ticket machine',
        pizza: 'Pizza vending machine',
        public_transport_tickets: 'Public transport ticket machine',
        stamps: 'Stamp vending machine',
        sweets: 'Sweets vending machine',
        water: 'Water vending machine',
      },
    },
    veterinary: 'Veterinary',
    waste_basket: 'Trash bin',
    waste_disposal: 'Waste disposal',
    water_point: 'Water point',
    watering_place: 'Watering place',
  },
  attraction: {
    animal: 'Animal attraction',
    amusement_ride: 'Amusement ride',
    big_wheel: 'Ferris wheel',
    carousel: 'Carousel',
    historic: 'Historic attraction',
    maze: 'Maze attraction',
    roller_coaster: 'Roller coaster',
    summer_toboggan: 'Summer toboggan run',
    train: 'Attraction train',
    water_slide: 'Water slide',
  },
  barrier: {
    '*': 'Barrier {}',
    block: 'Block',
    bollard: 'Bollard',
    border_control: 'Border control',
    cable_barrier: 'Cable barrier',
    chain: 'Chain',
    city_wall: 'City wall',
    ditch: 'Ditch (barrier)',
    entrance: 'Entrance',
    fence: 'Fence',
    gate: 'Gate',
    guard_rail: 'Guard rail',
    handrail: 'Handrail',
    hedge: 'Hedge',
    kerb: 'Kerb',
    lift_gate: 'Lift gate',
    retaining_wall: 'Retaining wall',
    rope: 'Rope',
    sliding_gate: 'Sliding gate',
    swing_gate: 'Swing gate',
    turnstile: 'Turnstile',
    wall: 'Wall',
  },
  boundary: {
    '*': 'Region',
    administrative: {
      '*': 'Administrative region',
      admin_level: {
        '2': 'Country',
        '3': 'Region',
        '4': 'District',
        '5': 'Province',
        '6': 'City',
        '7': 'Region',
        '8': 'District',
        '9': 'Village',
        '10': 'Cadastre region',
      },
    },
    marker: 'Boundary stone',
    national_park: 'National park',
    protected_area: 'Protected area',
  },
  'abandoned:building': { '*': 'Abandoned building' },
  'disused:building': { '*': 'Disused building' },
  'ruins:building': { '*': 'Ruins of a building' },
  building: {
    '*': {
      '*': 'Building',
      abandoned: {
        yes: 'Abandoned building',
      },
      disused: {
        yes: 'Disused building',
      },
      ruins: {
        yes: 'Ruins of a building',
      },
    },
    abandoned: 'Abandoned building',
    disused: 'Disused building',
    apartments: 'Apartments (block)',
    barn: 'Barn',
    bungalow: 'Bungalow',
    bunker: 'Bunker',
    cabin: 'Cabin',
    cathedral: 'Cathedral',
    chapel: 'Chapel',
    church: 'Church',
    civic: 'Civic building',
    collapsed: 'Collapsed building',
    commercial: 'Commercial building',
    construction: 'Building construction',
    cowshed: 'Cowshed',
    detached: 'Free standing house',
    dormitory: 'Dormitory',
    entrance: 'Building entrance',
    farm_auxiliary: 'Auxiliary farm building',
    farm: 'Farm',
    garage: 'Garage',
    garages: 'Garages',
    government: 'Government building',
    grandstand: 'Grandstand',
    greenhouse: 'Greenhouse',
    hangar: 'Hangar',
    hayloft: 'Hayloft',
    hospital: 'Hospital building',
    hotel: 'Hotel building',
    house: 'Private house',
    houseboat: 'Houseboat',
    hut: 'Hut',
    industrial: 'Industrial building',
    kindergarten: 'Kindergarten building',
    kiosk: 'Stánok',
    manufacture: 'Budova fabriky',
    mosque: 'Mosque',
    office: 'Office building',
    parking: 'Parking building',
    public: 'Public building',
    residential: 'Residential house',
    retail: 'Retail building',
    roof: 'Roof',
    ruins: 'Building ruins',
    school: 'School building',
    semidetached_house: 'Duplex house',
    service: 'Service building',
    shed: 'Shed',
    shrine: 'Shrine',
    stable: 'Stable',
    stadium: 'Stadium building',
    static_caravan: 'Mobile house, caravan',
    storage_tank: 'Storage tank',
    sty: 'Sty',
    supermarket: 'Budova supermarketu',
    synagogue: 'Synagogue',
    temple: 'Temple',
    terrace: 'Row house',
    train_station: 'Train station',
    transformer_tower: 'Transformačná veža',
    transportation: 'Transportation building',
    university: 'University building',
    warehouse: 'Warehouse',
    yes: 'Indeterminate building',
  },
  fixme: {
    '*': 'Incorrectly or partially mapped feature',
  },
  ford: {
    yes: 'Ford',
  },
  bridge: {
    '*': {
      '*': 'Bridge',
      highway: {
        '*': 'Road bridge',
      },
      railway: {
        '*': 'Railway bridge',
      },
    },
    no: '',
  },
  tunnel: {
    '*': {
      '*': 'Tunnel',
      highway: {
        '*': 'Road tunnel',
      },
      railway: {
        '*': 'Railway tunnel',
      },
    },
    culvert: 'Culvert',
    no: '',
  },
  oneway: {
    yes: 'One-way',
  },
  foot: {
    no: 'Pedestrian access prohibited',
    yes: 'Pedestrian access permitted',
    private: 'Pedestrian access for owners only',
    designated: 'Designated for pedestrians',
  },
  bicycle: {
    no: 'Bicycle access prohibited',
    yes: 'Bicycle access permitted',
    private: 'Bicycle access for owners only',
    designated: 'Designated for bicycles',
  },
  vehicle: {
    no: 'Vehicle access prohibited',
    yes: 'Vehicle access permitted',
    private: 'Vehicle access for owners only',
    designated: 'Designated for vehicles',
  },
  motor_vehicle: {
    no: 'Motor vehicle access prohibited',
    yes: 'Motor vehicle access permitted',
    private: 'Motor vehicle access for owners only',
    designated: 'Designated for motor vehicles',
  },
  highway: {
    '*': 'Road {}',
    bridleway: 'Bridleway',
    bus_stop: 'Bus stop',
    construction: 'Road under construction',
    crossing: 'Pedestrian crossing',
    cycleway: 'Cycleway',
    footway: 'Sidewalk',
    living_street: 'Residential',
    motorway: 'Highway',
    motorway_link: 'Motorway link',
    path: {
      '*': 'Path',
      foot: {
        designated: {
          bicycle: {
            designated: 'Shared pedestrian and cycle path',
          },
        },
      },
    },
    pedestrian: 'Pedestrian zone',
    piste: 'Piste',
    platform: 'Platform',
    primary: 'Primary highway',
    primary_link: 'Primary road link',
    raceway: 'Raceway',
    residential: 'Street',
    road: 'Road of unknown kind',
    secondary: 'Secondary highway',
    secondaty_link: 'Secondary road link',
    service: {
      '*': 'Service driveway road',
      service: {
        '*': 'Service road {}',
        alley: 'Alley',
        bus: 'Mass transit road',
        'drive-through': 'Drive through',
        driveway: 'Driveway',
        emergency_access: 'Emergency access road',
        parking_aisle: 'Parking aisle',
      },
    },
    steps: 'Stairs',
    street_lamp: 'Street lamp',
    tertiary: 'Tertiary highway',
    tertiary_link: 'Tertiary road link',
    track: {
      '*': 'Forest road of unknown quality',
      tracktype: {
        grade1: 'Compacted forest road',
        grade2: 'Mostly compacted forest road',
        grade3: 'Less firm, unpaved forest road',
        grade4: 'Forest road navigable by tractor or similar vehicles',
        grade5: 'Barely discernible forest road',
      },
    },
    trunk: 'Trunk road',
    trunk_link: 'Trunk link',
    unclassified: 'Unclassified road',
    via_ferrata: 'Via ferrata',
  },
  historic: {
    '*': 'Historic structure {}',
    yes: 'Historic structure',
    aircraft: 'Historic aircraft',
    archaeological_site: 'Archaeological site',
    boundary_stone: 'Historic boundary stone',
    building: 'Historic building',
    cannon: 'Historic cannon',
    castle: 'Castle',
    charcoal_pile: 'Charcoal pile site',
    church: 'Historic church',
    city_gate: 'City gate',
    citywalls: 'City walls',
    fort: 'Fort',
    heritage: 'Heritage site',
    hollow_way: 'Hollow way',
    house: 'Historic house',
    manor: 'Manor',
    memorial: 'Memorial',
    milestone: 'Historic milestone',
    mine_shaft: 'Historic mine shaft',
    mine: 'Historic mine',
    monastery: 'Historic monastery',
    monument: 'Monument',
    ruins: {
      '*': 'Ruins',
      ruins: {
        castle: 'Castle ruins',
      },
    },
    shieling: 'Shieling (seasonal mountain hut)',
    stone: 'Historic stone',
    tomb: 'Tomb',
    tree_shrine: 'Tree shrine',
    wayside_cross: 'Wayside cross',
    wayside_shrine: 'Wayside shrine',
    wreck: 'Shipwreck',
  },
  landuse: {
    '*': '{}',
    allotments: 'Allotments',
    basin: 'Basin',
    brownfield: 'Brownfield',
    cemetery: 'Cemetery',
    commercial: 'Commercial',
    construction: 'Construction',
    education: 'Educational zone',
    farmland: 'Farmland',
    farmyard: 'Farmyard',
    forest: 'Forest',
    garages: 'Garages',
    grass: 'Grass',
    greenfield: 'Greenfield',
    industrial: 'Industrial',
    landfill: 'Landfill',
    meadow: 'Meadow',
    military: 'Military area',
    orchard: 'Orchard',
    pedestrian: 'Area for pedestrians',
    plant_nursery: 'Plant nursery',
    quarry: 'Quarry',
    railway: 'Railway area',
    recreation_ground: 'Recreation ground',
    religions: 'Religious land',
    // TODO
    reservoir: 'Reservoir',
    residential: 'Residential',
    retail: 'Retail',
    vineyard: 'Vineyard',
    village_green: 'Village green',
    winter_sports: 'Winter sports',
  },
  leisure: {
    '*': '{}',
    adult_gaming_centre: 'Adult gaming centre',
    amusement_arcade: 'Amusement arcade',
    bandstand: 'Bandstand',
    bathing_place: 'Bathing place',
    beach_resort: 'Beach resort',
    bird_hide: 'Bird hide',
    bleachers: 'Bleachers',
    bowling_alley: 'Bowling alley',
    dance: 'Dance venue',
    disc_golf_course: 'Disc golf course',
    dog_park: 'Dog park',
    escape_game: 'Escape game',
    firepit: 'Fireplace',
    fishing: 'Fishing',
    fitness_centre: 'Fintess centre',
    fitness_station: 'Fintess station',
    garden: 'Garden',
    golf_course: 'Golf course',
    hackerspace: 'Hackerspace',
    high_ropes_course: 'High ropes course',
    horse_riding: 'Horse riding',
    ice_rink: 'Ice rink',
    marina: 'Marina',
    miniature_golf: 'Miniature golf',
    nature_reserve: 'Nature reserve',
    outdoor_seating: 'Outdoor seating',
    park: 'Park',
    picnic_table: {
      '*': 'Picnic table',
      covered: {
        yes: 'Covered picnic table',
        no: 'Uncovered picnic table',
      },
    },
    pitch: 'Pitch',
    playground: 'Playground',
    resort: 'Recreation resort',
    slipway: 'Boat slipway',
    sauna: {
      '*': 'Sauna',
      sauna: {
        hot: 'Finnish sauna',
        steam: 'Steam sauna (Turkish bath)',
        smoke: 'Smoke sauna (Finnish)',
        dry: 'Dry sauna',
        hanjeungmak: 'Hanjeungmak (Korean sauna)',
        aroma: 'Aroma sauna',
        infrared: 'Infrared sauna',
      },
    },
    sports_centre: 'Sports centre',
    sports_hall: 'Sports hall',
    stadium: 'Stadium',
    summer_camp: 'Summer camp',
    sunbathing: 'Sunbathing area',
    swimming_area: 'Swimming area',
    swimming_pool: 'Swimming pool',
    tanning_salon: 'Tanning salon',
    track: 'Track',
    trampoline_park: 'Trampoline park',
    water_park: 'Water park',
    wildlife_hide: 'Wildlife hide',
  },
  man_made: {
    '*': '{}',
    adit: {
      '*': 'Adit',
      disused: {
        yes: 'Disused adit',
      },
    },
    antenna: 'Antenna',
    apiary: 'Apiary',
    beacon: 'Beacon',
    beehive: 'Beehive',
    bridge: 'Bridge',
    bunker_silo: 'Bunker silo',
    cairn: 'Cairn',
    cellar_entrance: 'Cellar entrance',
    chimney: 'Chimney',
    clearcut: 'Forest clearing',
    communications_tower: 'Big telecommunication tower',
    cooling_tower: 'Cooling tower',
    crane: 'Crane',
    cross: 'Cross',
    cutline: 'Cutline',
    dyke: 'Dyke',
    embankment: 'Embankment',
    flagpole: 'Flagpole',
    "forester's_lodge": "Forester's lodge",
    gasometer: 'Gasometer',
    goods_conveyor: 'Goods conveyor',
    groyne: 'Groyne',
    lighthouse: 'Lighthouse',
    manhole: 'Manhole',
    mast: {
      '*': 'Mast',
      'tower:type': {
        clock: 'Clock tower mast',
        communication: 'Communication mast',
        lighting: 'Lighting mast',
        monitoring: 'Monitoring mast',
        radar: 'Radar mast',
        siren: 'Siren mast',
      },
    },
    mineshaft: {
      '*': 'Mineshaft',
      disused: {
        yes: 'Disused mineshaft',
      },
    },
    monitoring_station: 'Monitoring station',
    nesting_site: 'Nesting site',
    observatory: 'Observatory',
    pier: 'Pier',
    pipeline: {
      '*': 'Pipeline',
      location: {
        underground: 'Underground pipeline',
        underwater: 'Underwater pipeline',
      },
    },
    pumping_station: 'Pumping station',
    reservoir_covered: 'Covered reservoir',
    silo: 'Silo',
    snow_cannon: 'Snow cannon',
    spoil_heap: 'Spoil heap',
    spring_box: 'Spring box',
    storage_tank: 'Storage tank',
    street_cabinet: 'Street cabinet',
    surveillance: 'Surveillance',
    survey_point: 'Survey point',
    telescope: 'Telescope',
    tower: {
      '*': 'Tower',
      'tower:type': {
        bell_tower: 'Bell tower',
        climbing: 'Climbing tower',
        clock: 'Clock tower',
        communication: 'Communication tower',
        cooling: 'Cooling tower',
        defensive: 'Defensive tower',
        diving: 'Diving tower',
        hose: 'Hose-drying tower',
        lighting: 'Lighting tower',
        minaret: 'Minaret',
        monitoring: 'Monitoring tower',
        observation: 'Observation tower',
        pagoda: 'Pagoda tower',
        radar: 'Radar tower',
        siren: 'Siren tower',
        watchtower: 'Watchtower',
      },
    },
    utility_pole: 'Utility pole',
    wastewater_plant: 'Wastewater plant',
    water_tap: 'Water tap',
    water_tower: 'Water Tower',
    water_well: 'Water well',
    water_works: 'Water works',
    watermill: 'Watermill',
    windmill: 'Windmill',
    works: 'Works',
  },
  military: {
    '*': 'Military facility {}',
    academy: 'Military academy',
    airfield: 'Military airfield',
    ammunition: 'Ammunition depot',
    barracks: 'Barracks',
    base: 'Military base',
    bunker: 'Bunker',
    checkpoint: 'Military Checkpoint',
    danger_area: 'Military danger area',
    depot: 'Military depot',
    launchpad: 'Launch pad',
    naval_base: 'Naval base',
    nuclear_explosion_site: 'Nuclear test site',
    obstacle_course: 'Military obstacle course',
    office: 'Military office',
    range: 'Firing range',
    school: 'Military school',
    training_area: 'Military training area',
    trench: 'Trench',
  },
  mountain_pass: {
    yes: 'Mountain pass',
  },
  natural: {
    '*': '{}',
    arch: 'Rock arch',
    bare_rock: 'Bare rock',
    basin: 'Basin',
    bay: 'Bay',
    beach: 'Beach',
    birds_nest: 'Birds_nest',
    cave_entrance: 'Cave',
    cliff: 'Cliff',
    earth_bank: 'Earth bank',
    fell: 'Fell',
    geyser: 'Geyser',
    glacier: 'Glacier',
    grassland: 'Grassland',
    gully: 'Gully',
    heath: 'Heathland',
    hot_spring: 'Hot spring',
    landslide: 'Landslide',
    mountain_range: 'Mountain range',
    mud: 'Mud',
    peak: 'Peak',
    plateau: 'Plateau',
    ridge: 'Ridge',
    rock: 'Rock',
    saddle: 'Saddle',
    sand: 'Sand',
    scree: 'Scree',
    scrub: 'Scrub, bushes',
    shingle: 'Shingle',
    shrub: 'Shrub',
    sinkhole: 'Sinkhole',
    spring: {
      '*': 'Spring',
      drinking_water: {
        yes: 'Drinkable spring',
        no: 'Non-drinking spring',
      },
      refitted: {
        yes: 'Refitted spring',
        no: 'Non-refitted spring',
      },
      intermittent: {
        yes: 'Intermittent spring',
      },
      seasonal: {
        yes: 'Seasonal spring',
      },
      water_characteristic: {
        '*': 'Mineral spring',
      },
    },
    stone: 'Stone',
    tree: {
      '*': 'Tree',
      protected: { yes: 'Protected tree' },
      denotation: {
        natural_monument: 'Natural monument tree',
        landmark: 'Landmark tree',
        avenue: 'Avenue tree',
        urban: 'Urban tree',
        agricultural: 'Agricultural tree',
      },
    },
    tree_row: 'Tree row',
    valley: 'Valley',
    water: 'Water body',
    wetland: {
      '*': 'Wetland',
      wetland: {
        bog: 'Bog',
        reedbed: 'Reedbed',
        marsh: 'Marsh',
        swamp: 'Swamp',
        wet_meadow: 'Wet_meadow',
        mangrove: 'Mangrove',
        fen: 'Fen',
      },
    },
    wood: 'Forest',
  },
  place: {
    '*': 'Place {}',
    city: 'City',
    country: 'Country',
    farm: 'Farm',
    hamlet: 'Hamlet',
    island: 'Island',
    islet: 'Islet',
    isolated_dwelling: 'Isolated dwelling',
    locality: 'Locality',
    ocean: 'Ocean',
    sea: 'Sea',
    square: 'Square',
    state: 'State',
    suburb: 'Suburb',
    town: 'Town',
    village: 'Village',
  },
  power: {
    '*': '{}',
    generator: {
      '*': 'Electric power generator',
      'generator:source': {
        nuclear: {
          '*': 'Nuclear power generator',
          'generator:method': {
            fission: 'Nuclear fission power generator',
            fusion: 'Nuclear fusion power generator',
          },
        },
        wind: {
          '*': 'Wind power generator',
        },
        hydro: {
          '*': 'Hydroelectric power generator',
          'generator:method': {
            'water-storage': 'Reservoir hydroelectric power generator',
            'water-pumped-storage':
              'Pumped-storage hydroelectric power generator',
            'run-of-the-river':
              'Run-of-the-river hydroelectric power generator',
          },
        },
        tidal: {
          '*': 'Tidal power generator',
          'generator:method': {
            barrage: 'Tidal barrage power generator',
            stream: 'Tidal stream power generator',
          },
        },
        wave: {
          '*': 'Wave power generator',
        },
        geothermal: {
          '*': 'Geothermal power generator',
        },
        solar: {
          '*': 'Solar power generator',
          'generator:method': {
            thermal: 'Solar thermal power generator',
            photovoltaic: 'Solar photovoltaic power generator',
          },
        },
        coal: {
          '*': 'Coal-fired power generator',
        },
        gas: {
          '*': 'Gas-fired power generator',
        },
        biomass: {
          '*': 'Biomass power generator',
          'generator:method': {
            combustion: 'Biomass combustion power generator',
            gasification: 'Biomass gasification power generator',
            anaerobic_digestion: 'Anaerobic digestion biomass power generator',
          },
        },
        biofuel: {
          '*': 'Biofuel power generator',
        },
        biogas: {
          '*': 'Biogas power generator',
        },
        oil: {
          '*': 'Oil-fired power generator',
        },
        diesel: {
          '*': 'Diesel power generator',
        },
        gasoline: {
          '*': 'Gasoline power generator',
        },
        waste: {
          '*': 'Waste-to-energy power generator',
          'generator:method': {
            combustion: 'Waste combustion power generator',
            gasification: 'Waste gasification power generator',
          },
        },
      },
    },
    line: 'Power line',
    minor_line: 'Minor power line',
    plant: {
      '*': 'Plant',
      'plant:source': {
        nuclear: {
          '*': 'Nuclear power plant',
          'plant:method': {
            fission: 'Nuclear fission power plant',
            fusion: 'Nuclear fusion power plant',
          },
        },
        wind: {
          '*': 'Wind power plant',
        },
        hydro: {
          '*': 'Hydroelectric power plant',
          'plant:method': {
            'water-storage': 'Reservoir hydroelectric power plant',
            'water-pumped-storage': 'Pumped-storage hydroelectric power plant',
            'run-of-the-river': 'Run-of-the-river hydroelectric power plant',
          },
        },
        tidal: {
          '*': 'Tidal power plant',
          'plant:method': {
            barrage: 'Tidal barrage power plant',
            stream: 'Tidal stream power plant',
          },
        },
        wave: {
          '*': 'Wave power plant',
        },
        geothermal: {
          '*': 'Geothermal power plant',
        },
        solar: {
          '*': 'Solar power plant',
          'plant:method': {
            thermal: 'Solar thermal power plant',
            photovoltaic: 'Solar photovoltaic power plant',
          },
        },
        coal: {
          '*': 'Coal-fired power plant',
        },
        gas: {
          '*': 'Gas-fired power plant',
        },
        biomass: {
          '*': 'Biomass power plant',
          'plant:method': {
            combustion: 'Biomass combustion power plant',
            gasification: 'Biomass gasification power plant',
            anaerobic_digestion: 'Anaerobic digestion biomass power plant',
          },
        },
        biofuel: {
          '*': 'Biofuel power plant',
        },
        biogas: {
          '*': 'Biogas power plant',
        },
        oil: {
          '*': 'Oil-fired power plant',
        },
        diesel: {
          '*': 'Diesel power plant',
        },
        gasoline: {
          '*': 'Gasoline power plant',
        },
        waste: {
          '*': 'Waste-to-energy power plant',
          'plant:method': {
            combustion: 'Waste combustion power plant',
            gasification: 'Waste gasification power plant',
          },
        },
      },
    },
    pole: 'Power pole',
    substation: 'Substation',
    tower: 'Power tower',
    transformer: 'Transformer',
  },
  public_transport: {
    platform: 'Platform of public transportation',
    station: 'Station',
    stop_position: 'Stop position',
  },
  railway: {
    '*': 'Railway',
    abandoned: 'Abandoned railway',
    construction: 'Railway under construction',
    proposed: 'Proposed railway',
    disused: 'Disused railway',
    funicular: 'Funicular railway',
    light_rail: 'Light rail',
    miniature: 'Miniature railway',
    monorail: 'Monorail',
    narrow_gauge: 'Narrow gauge railway',
    rail: 'Railway line',
    subway: 'Subway line',
    tram: 'Tramway',
    halt: 'Railway halt',
    platform: 'Railway platform',
    preserved: 'Preserved railway',
    station: 'Railway station',
    stop: 'Railway stop',
    subway_entrance: 'Subway entrance',
    tram_stop: 'Tram stop',
    buffer_stop: 'Railway buffer stop',
    crossing: 'Railway crossing (tracks crossing)',
    derail: 'Derail device',
    railway_crossing: 'Railway crossing',
    roundhouse: 'Railway roundhouse',
    signal: 'Railway signal',
    switch: 'Railway switch',
    level_crossing: 'Level crossing',
    traverser: 'Railway traverser',
    turntable: 'Railway turntable',
    ventilation_shaft: 'Railway ventilation shaft',
    wash: 'Train wash',
    water_crane: 'Railway water crane',
    workshop: 'Railway workshop',
  },
  shop: {
    '*': 'Shop {}',
    household_linen: 'Household linen',
    charity: 'Charity Shop',
    chocolate: 'Chocolate Shop',
    fashion_accessories: 'Fashion Accessories Shop',
    frozen_food: 'Frozen Food Shop',
    hearing_aids: 'Hearing Aids Shop',
    weapons: 'Weapons Shop',
    alcohol: 'Alcohol shop',
    antiques: 'Antiques',
    art: 'Art shop',
    baby_goods: 'Baby goods',
    bag: 'Bag shop',
    bakery: 'Bakery',
    bathroom_furnishing: 'Bathroom furnishing',
    beauty: 'Beauty shop',
    bed: 'Bed store',
    beverages: 'Beverages',
    bicycle: 'Bicycle shop',
    bookmaker: 'Bookmaker',
    books: 'Book store',
    boutique: 'Boutique',
    butcher: 'Butcher',
    camera: 'Camera shop',
    car: 'Car dealership',
    car_parts: 'Car parts',
    car_repair: 'Car repair',
    carpet: 'Carpet store',
    cheese: 'Cheese shop',
    chemist: 'Drug-store, chemist',
    clothes: 'Apparel store',
    coffee: 'Coffee shop',
    collector: 'Collector',
    computer: 'Computer store',
    confectionery: 'Confectionery',
    convenience: 'Convenience store',
    copyshop: 'Copy shop',
    cosmetics: 'Cosmetics shop',
    craft: 'Craft',
    curtain: 'Curtain',
    dairy: 'Dairy',
    deli: 'Delicatessen',
    department_store: 'Department store',
    doityourself: 'Doityourself',
    doors: 'Doors shop',
    dry_cleaning: 'Dry_cleaning',
    'e-cigarette': 'E-cigarette',
    electrical: 'Electrical',
    electronics: 'Electronics',
    erotic: 'Sex shop',
    fabric: 'Textile store',
    farm: 'Shop at a farm',
    fireplace: 'Fireplace',
    fishing: 'Fishing shop',
    flooring: 'Flooring shop',
    florist: 'Florist',
    funeral_directors: 'Funeral Services',
    furniture: 'Furniture store',
    games: 'Game shop',
    garden_center: 'Gardening center',
    garden_centre: 'Garden centre',
    general: 'General shop',
    gift: 'Gift shop',
    glaziery: 'Glaziery',
    greengrocer: 'Fruit and vegetables store',
    hairdresser: 'Hairdresser',
    hardware: 'Hardware',
    health_food: 'Health food',
    hifi: 'Hifi shop',
    houseware: 'Houseware shop',
    hunting: 'Hunting shop',
    ice_cream: 'Ice cream',
    interior_decoration: 'Interior decoration shop',
    jewelry: 'Jewerly',
    kiosk: 'Kiosk',
    kitchen: 'Kitchen shop',
    laundry: 'Lanudry',
    lighting: 'Lighting shop',
    locksmith: 'Locksmith',
    lottery: 'Lottery shop',
    mall: 'Shopping center / mall',
    massage: 'Massages',
    medical_supply: 'Medical supply',
    mobile_phone: 'Mobile phone store',
    model: 'Model',
    motorcycle: 'Motorcycle',
    music: 'Music shop',
    musical_instrument: 'Musical instruments shop',
    newsagent: 'Newsagent',
    nutrition_supplements: 'Nutrition supplements shop',
    optician: 'Optics',
    outdoor: 'Outdoor',
    outpost: 'Outpost',
    paint: 'Paint shop',
    pastry: 'Pastry shop',
    pawnbroker: 'Pawnbroker',
    perfumery: 'Perfumery',
    pet: 'Pet shop',
    pet_grooming: 'Pet grooming',
    photo: 'Photo shop',
    radiotechnics: 'Radiotechnics',
    rental: 'Rental',
    seafood: 'Seafood',
    second_hand: 'Secondhand',
    sewing: 'Sewing',
    shoes: 'Shoes',
    sports: 'Sports',
    stationery: 'Stationery store',
    supermarket: 'Supermarket',
    tailor: 'Tailor',
    tattoo: 'Tattoo',
    tea: 'Tea shop',
    ticket: 'Ticket shop',
    tobacco: 'Tobacco shop',
    toys: 'Toy store',
    trade: 'Building materials store',
    travel_agency: 'Travel agency',
    tyres: 'Tyres shop',
    vacant: 'Vacant shop',
    variety_store: 'Variety store',
    video: 'Video shop',
    video_games: 'Video games shop',
    watches: 'Watches',
    wholesale: 'Wholesale',
    window_blind: 'Window blind',
    wine: 'Wine shop',
  },
  sport: {
    '*': 'Sport {}',
    '10pin': 'Ten-pin Bowling',
    '8pin': 'Eight-pin bowling',
    '9pin': '9-pin Bowling',
    'five-a-side': 'Five-a-side football',
    'in-line_hockey': 'Inline hockey',
    'shot-put': 'Shot-put',
    aerobics: 'Aerobics',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'American football',
    american_handball: 'American handball',
    archery: 'Archery',
    association_football: 'Association football (soccer)',
    athletics: 'Athletics',
    australian_football: 'Australian football',
    axe_throwing: 'Axe throwing sport',
    badminton: 'Badminton',
    balle_pelote: 'Balle pelote sport',
    ballooning: 'Hot air ballooning',
    bandy: 'Bandy',
    barre: 'Barre fitness',
    base: 'BASE jumping',
    baseball: 'Baseball',
    basketball: 'Basketball',
    batting_cage: 'Batting cage (baseball/softball)',
    beach_soccer: 'Beach soccer',
    beach_tennis: 'Beach tennis',
    beachhandball: 'Beach handball',
    beachtennis: 'Beach tennis',
    beachvolleyball: 'Beachvolleyball',
    biathlon: 'Biathlon',
    bicycle: 'Bicycle',
    billards: 'Billiards',
    billiards: 'Billiards',
    bmx: 'BMX',
    bobsleigh: 'Bobsleigh',
    bodybuilding: 'Bodybuilding',
    boules: 'Boules',
    bowling: 'Bowling',
    bowls: 'Bowls',
    boxing: 'Boxing',
    bullfighting: 'Bullfighting',
    calisthenics: 'Calisthenics',
    canadian_football: 'Canadian football',
    candlepin: 'Candlepin bowling',
    canoe_polo: 'Canoe polo',
    canoe: 'Canoe',
    chess: 'Chess',
    chinlone: 'Chinlone sport',
    cliff_diving: 'Cliff diving',
    climbing_adventure: 'Climbing adventure',
    climbing: 'Climbing',
    cockfighting: 'Cockfighting',
    cricket_nets: 'Cricket nets',
    cricket: 'Cricket',
    croquet: 'Croquet',
    crossfit: 'CrossFit training',
    curling: 'Curling',
    cycle_ball: 'Cycle ball',
    cycle_polo: 'Cycle polo',
    cycling: 'Cycling',
    dance: 'Dance sport',
    dancing: 'Dance sport',
    darts: 'Darts',
    disc_golf: 'Disc golf',
    diving: 'Diving sport',
    dodgeball: 'Dodgeball',
    dog_agility: 'Dog agility sport',
    dog_racing: 'Dog racing',
    dragon_boat: 'Dragon boat racing',
    equestrian: 'Equestrian',
    fencing: 'Fencing',
    field_hockey: 'Field hockey',
    fistball: 'Fistball',
    fitness: 'Fitness',
    fives: 'Fives sport',
    floorball: 'Floorball',
    football: 'Football',
    footballgolf: 'Football golf',
    four_square: 'Four square game',
    free_flying: 'Free flying',
    freediving: 'Freediving',
    funnel_ball: 'Funnel ball game',
    futsal: 'Futsal',
    gaelic_football: 'Gaelic football',
    gaelic_games: 'Gaelic games',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Gliding sport',
    golf: 'Golf',
    gymnastics: 'Gymnastics',
    handball: 'Handball',
    hanggliding: 'Hang gliding',
    hapkido: 'Hapkido',
    high_rope_course: 'High ropes course',
    hiking: 'Hiking',
    hockey: 'Hockey',
    hopscotch: 'Hopscotch game',
    horse_racing: 'Horse racing',
    horse_riding: 'Horse riding',
    horseshoes: 'Horseshoes',
    ice_hockey: 'Ice hockey',
    ice_skating: 'Ice skating',
    ice_stock: 'Ice stock sport',
    jetsprint: 'Jet sprint boat racing',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Karting',
    kick_scooter: 'Kick scooter sport',
    kickball: 'Kickball',
    kickboxing: 'Kickboxing',
    kitesurfing: 'Kitesurfing',
    korfball: 'Krofball',
    krachtbal: 'Krachtbal sport',
    krolf: 'Krolf sport',
    lacrosse: 'Lacrosse',
    laser_tag: 'Laser tag',
    long_jump: 'Long jump',
    martial_arts: 'Martial arts',
    mind_body_interventions: 'Mind-body exercise (e.g. yoga)',
    miniature_golf: 'Miniature golf',
    model_aerodrome: 'Model aerodrome',
    motocross: 'Motocross',
    motor: 'Motor',
    mtb: 'Mountain biking',
    multi: 'Multi',
    netball: 'Netball',
    nine_mens_morris: "Nine men's morris game",
    obstacle_course: 'Obstacle course racing',
    orienteering: 'Orienteering',
    paddle_tennis: 'Paddle tennis',
    paddleball: 'Paddleball',
    paddleboard: 'Stand-up paddleboarding',
    padel: 'Padel tennis',
    paintball: 'Paintball',
    parachuting: 'Parachuting',
    paragliding: 'Paragliding',
    parkour: 'Parkour',
    pedal_car_racing: 'Pedal car racing',
    pelota: 'Pelota',
    pesäpallo: 'Pesäpallo (Finnish baseball)',
    petanque: 'Petanque',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole dance sport',
    polo: 'Polo',
    powerlifting: 'Powerlifting',
    racquet: 'Racquet',
    rc_car: 'RC Cars',
    rodeo: 'Rodeo sport',
    roller_hockey: 'Roller hockey',
    roller_skating: 'Roller skating',
    rowing: 'Rowing',
    rugby_league: 'Rugby league',
    rugby_union: 'Rugby union',
    rugby: 'Rugby',
    running: 'Running',
    russian_skittles: 'Russian skittles',
    safety_training: 'Safety training sport',
    sailing: 'Sailing',
    scuba_diving: 'Scuba_diving',
    shooting_range: 'Shooting range',
    shooting: 'Shooting',
    shuffleboard: 'Shuffleboard',
    skateboard: 'Skateboard',
    skating: 'Skating',
    ski_jumping: 'Ski jumping',
    skiing: 'Skiing',
    snooker: 'Snooker',
    snorkeling: 'Snorkeling',
    soccer: 'Football / soccer',
    softball: 'Softball',
    speedway: 'Speedway motorcycle racing',
    squash: 'Squash',
    streetball: 'Streetball',
    summer_toboggan: 'Summer toboggan run',
    sumo: 'Sumo wrestling',
    surfing: 'Surfing',
    swimming: 'Swimming',
    table_soccer: 'Table soccer',
    table_tennis: 'Table tennis',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello sport',
    team_handball: 'Team handball',
    tennis: 'Tennis',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    toboggan: 'Toboggan',
    touch_football: 'Touch football',
    trampoline: 'Trampolining',
    trugo: 'Trugo sport',
    tug_of_war: 'Tug of war',
    ultimate: 'Ultimate frisbee',
    ultralight_aviation: 'Ultralight aviation sport',
    volleyball: 'Volleyball',
    wakeboarding: 'Wakeboarding',
    walking: 'Walking sport',
    water_polo: 'Water polo',
    water_ski: 'Water skiing',
    water_sports: 'Water sports',
    weightlifting: 'Weightlifting',
    windsurfing: 'Windsurfing',
    workout: 'Workout',
    wrestling: 'Wrestling',
    yoga: 'Yoga',
    zurkhaneh_sport: 'Zurkhaneh sport',
  },
  tourism: {
    '*': '{}',
    alpine_hut: 'Alpine hut',
    apartment: 'Apartment',
    aquarium: 'Aquarium',
    artwork: {
      '*': 'Art',
      artwork_type: {
        architecture: 'Architecture',
        bust: 'Bust',
        graffiti: 'Graffiti',
        installation: 'Installation art',
        mosaic: 'Tilework',
        mural: 'Mural',
        painting: 'Painting',
        relief: 'Relief (artwork)',
        sculpture: 'Sculpture',
        statue: 'Statue',
        stone: 'Boulder (artwork)',
      },
    },
    attraction: 'Attraction',
    camp_site: 'Campsite',
    caravan_site: 'Caravan site',
    chalet: 'Chalet',
    gallery: 'Gallery',
    guest_house: 'Guest house',
    hostel: 'Hostel',
    hotel: 'Hotel',
    information: {
      '*': 'Information',
      information: {
        '*': 'Information {}',
        board: 'Information board',
        guidepost: 'Guidepost',
        map: 'Map',
        office: 'Information office',
        route_marker: 'Route marker',
      },
    },
    motel: 'Motel',
    museum: 'Museum',
    picnic_site: 'Picnic site',
    viewpoint: 'Viewpoint',
    wilderness_hut: 'Wilderness hut',
    zoo: 'ZOO',
  },
  type: {
    route: {
      '*': 'Trail',
      route: {
        '*': 'Trail {}',
        bicycle: 'Bicycle trail',
        bus: 'Bus way',
        foot: 'Pedestrian trail',
        hiking: {
          '*': 'Hiking trail',
          network: {
            lwn: 'Local hiking trail',
            rwn: 'Regional hiking trail',
            nwn: 'National hiking trail',
            iwn: 'International hiking trail',
          },
        },
        horse: 'Equestrian path',
        mtb: 'Mountain biking trail',
        piste: 'Ski slope or path',
        railway: 'Railway',
        ski: 'Ski trail',
        tram: 'Tramway',
      },
    },
  },
  seasonal: {
    yes: {
      waterway: 'Seasonal waterway',
      natural: {
        water: 'Seasonal water area',
      },
    },
  },
  intermittent: {
    yes: {
      waterway: 'Intermittent waterway',
      natural: {
        water: 'Intermittent water area',
      },
    },
  },
  waterway: {
    '*': 'Waterway {}',
    canal: 'Canal',
    canoe_pass: 'Canoe pass',
    dam: 'Dam',
    ditch: 'Ditch (waterway)',
    drain: 'Drain',
    fairway: 'Fairway',
    fish_pass: 'Fish pass',
    flowline: 'Flow line',
    link: 'Waterway link',
    pressurised: 'Pressurised water conduit',
    rapids: 'Pereje',
    river: 'River',
    stream: 'Creek, stream',
    tidal_channel: 'Tidal channel',
    waterfall: 'Waterfall',
    weir: 'Weir',
  },
  trail_visibility: {
    excellent: 'Excellent trail visibility',
    good: 'Good trail visibility',
    intermediate: 'Intermediate trail visibility',
    bad: 'Bad trail visibility',
    horrible: 'Horrible trail visibility',
    no: 'No trail visibility',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Red',
  blue: 'Blue',
  green: 'Green',
  yellow: 'Yellow',
  orange: 'Orange',
  purple: 'Purple',
  violet: 'Violet',
  white: 'White',
  black: 'Black',
  gray: 'Gray',
  brown: 'Brown',
};
