import { DeepPartial } from '@shared/types/deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  aeroway: {
    aerodrome: 'Repülőtér',
    airstrip: 'Repülőpálya',
    apron: 'Forgalmi előtér',
    gate: 'Beszállókapu',
    hangar: 'Repülőgéphangár',
    helipad: 'Helikopter-leszálló',
    holding_position: 'Várakozási pont',
    jet_bridge: 'Utashíd',
    navigationaid: 'Légi navigációs berendezés',
    parking_position: 'Repülőgép-parkolóállás',
    runway: 'Kifutópálya',
    stopway: 'Megállási biztonsági sáv',
    taxilane: 'Gurulóút-sáv',
    taxiway: 'Gurulóút',
    terminal: 'Repülőtéri terminál',
    threshold: 'Kifutópálya küszöb',
    tower: 'Irányítótorony',
    windsock: 'Szélzsák',
  },

  aerialway: {
    '*': 'Felvonó, drótkötélpálya',
    cable_car: 'Kabinos felvonó',
    chair_lift: 'Ülőlift',
    goods: 'Teherfelvonó',
    'j-bar': 'J-rudas lift',
    magic_carpet: 'Varázsszőnyeg',
    mixed_lift: 'Vegyes felvonó',
    platter: 'Tányéros felvonó',
    pylon: 'Tartóoszlop',
    rope_tow: 'Köteles felvonó',
    station: 'Felvonóállomás',
    't-bar': 'T-rudas felvonó',
    zip_line: 'Zipline',
  },

  amenity: {
    '*': '{}',
    animal_breeding: 'Állattenyésztés',
    animal_shelter: 'Állatmenhely',
    arts_centre: 'Művészeti központ',
    atm: 'Bankautomata',
    bank: 'Bank',
    bar: 'Bár',
    bbq: 'Grillezőhely',
    bench: 'Pad',
    bicycle_parking: 'Kerékpártároló',
    bicycle_rental: 'Kerékpárkölcsönző',
    biergarten: 'Sörkert',
    bus_station: 'Buszpályaudvar',
    car_rental: 'Autókölcsönző',
    car_wash: 'Autómosó',
    charging_station: 'Elektromos töltőállomás',
    childcare: 'Bölcsőde',
    cinema: 'Mozi',
    clinic: 'Rendelőintézet',
    college: 'Főiskola',
    community_centre: 'Közösségi ház',
    compressed_air: 'Sűrített levegő',
    courthouse: 'Bíróság',
    dentist: 'Fogorvos',
    doctors: 'Orvosi rendelő',
    drinking_water: 'Ivóvíz',
    embassy: 'Nagykövetség',
    fast_food: 'Büfé, gyorsétterem',
    fire_station: 'Tűzoltóság ',
    fountain: 'Szökőkút',
    hospital: 'Kórház',
    library: 'Könyvtár',
    marketplace: 'Piac',
    nightclub: 'Diszkó, night club',
    parking: 'Parkoló',
    parking_entrance: 'Parkolóház-bejárat',
    parking_space: 'Parkolóhely',
    pharmacy: 'Gyógyszertár',
    place_of_worship: 'Vallási hely',
    police: 'Rendőrség',
    post_office: 'Posta',
    prison: 'Börtön',
    pub: 'Kocsma',
    public_bookcase: 'Közösségi könyvespolc',
    ranger_station: 'Ranger station',
    recycling: 'Újrahasznosítás',
    restaurant: 'Étterem',
    school: 'Iskola',

    shelter: {
      '*': 'Esőbeálló',
      shelter_type: {
        '*': 'Esőbeálló {}',
        picnic_shelter: {
          fireplace: {
            yes: 'Fedett piknikezőhely tűzhellyel',
          },
          '*': 'Fedett piknikezőhely',
        },
        basic_hut: 'Bivakkunyhó',
        changing_rooms: 'Öltözőhelyiség',
        field_shelter: 'Mezei menedékhely (állatoknak)',
        lean_to: 'Háromfalú fészer',
        public_transport: 'Tömegközlekedési esőbeálló',
        rock_shelter: 'Sziklába vájt menedékhely',
        sun_shelter: 'Árnyékoló',
        weather_shelter: 'Esőház',
      },
    },

    social_facility: {
      social_facility: {
        shelter: 'Menedékhely',
        ambulatory_care: 'Ambuláns ellátás',
        assisted_living: 'Bentlakásos otthon',
        clothing_bank: 'Ruhabank',
        day_care: 'Szociális napközi otthon',
        food_bank: 'Élelmiszerbank',
        group_home: 'Lakóotthon',
        hospice: 'Hospice',
        nursing_home: 'Ápolóotthon',
        soup_kitchen: 'Ingyen konyha',
        workshop: 'Műhely',
      },
      '*': 'Szociális intézmény',
    },

    theatre: 'Színház',
    toilets: 'WC',
    university: 'Egyetem',

    vending_machine: {
      vending: {
        bicycle_tube: 'Kerékpárbelső-árusító automata',
        bread: 'Kenyérárudító automata',
        bottle_return: 'Üvegvisszaváltó automata',
        candles: 'Gyertyaárusító automata',
        chewing_gums: 'Rágógumi-automata',
        cigarettes: 'Cigarettaautomata',
        coffee: 'Kávéautomata',
        condoms: 'Óvszerautomata',
        drinks: 'Italautomata',
        elongated_coin: 'Kinyújtott érmét árusító automata',
        eggs: 'Tojásautomata',
        excrement_bags: 'Állatürülékes tasakot árusító automata',
        food: 'Ételautomata',
        fuel: 'Üzemanyag-automata',
        gas: 'Gázpalack-automata',
        ice_cream: 'Fagylaltautomata',
        ice_cubes: 'Jégkocka-automata',
        milk: 'Tejautomata',
        movies: 'Filmautomata',
        newspapers: 'Újságautomata',
        parking_tickets: 'Parkolójegy-automata',
        pizza: 'Pizzaautomata',
        public_transport_tickets: 'Tömegközlekedésijegy-automata',
        stamps: 'Bélyegautomata',
        sweets: 'Édességautomata',
        water: 'Vízautomata',
      },
      '*': 'Automata',
    },

    veterinary: 'Állatorvos',

    bicycle_repair_station: 'Kerékpárszerelő pont',
    brothel: 'Bordély',
    bureau_de_change: 'Valutaváltó',
    cafe: 'Kávézó',
    casino: 'Kaszinó',
    clock: 'Óra',
    device_charging_station: 'Mobileszköztöltő pont',
    dressing_room: 'Öltöző',
    driving_school: 'Autósiskola',
    events_venue: 'Rendezvényhelyszín',
    feeding_place: 'Állatetető hely',
    ferry_terminal: 'Kompkikötő',
    food_court: 'Étkezőtér',
    fuel: 'Üzemanyagtöltő állomás',
    funeral_hall: 'Ravatalozó',
    gambling: 'Szerencsejáték',
    game_feeding: 'Vadetető',
    grave_yard: 'Templom körüli temető',
    grit_bin: 'Útszóróanyagos láda',
    hunting_stand: 'Magasles',
    ice_cream: 'Fagylaltozó',
    kindergarten: 'Óvoda',
    language_school: 'Nyelviskola',
    monastery: 'Kolostor',
    money_transfer: 'Pénzküldő szolgáltatás',
    motorcycle_parking: 'Motorkerékpár-parkoló',
    motorcycle_rental: 'Motorkölcsönző',
    parcel_locker: 'Csomagautomata',
    place_of_mourning: 'Ravatal helye',
    planetarium: 'Planetárium',
    post_box: 'Postaláda',
    shower: 'Zuhany',
    ski_rental: 'Sífelszerelés-kölcsönző',
    smoking_area: 'Dohányzóhely',
    social_centre: 'Szociális létesítmény',
    stripclub: 'Sztriptízbár',
    studio: 'Stúdió',
    taxi: 'Taxiállomás',
    telephone: 'Telefon',
    townhall: 'Városháza',
    traffic_park: 'Közlekedési park',
    trolley_bay: 'Bevásárolókocsi-tároló',
    vacuum_cleaner: 'Porszívó',
    vehicle_inspection: 'Műszaki vizsgálat',
    waste_basket: 'Szemeteskosár',
    waste_disposal: 'Hulladékkonténer',
    water_point: 'Vízvételi hely',
    watering_place: 'Állatitató hely',
  },

  barrier: {
    '*': 'Akadály {}',
    block: 'Tömb',
    bollard: 'Terelőoszlop',
    border_control: 'Határátkelő',
    cable_barrier: 'Kábelkorlát',
    chain: 'Lánc',
    city_wall: 'Városfal',
    ditch: 'Árok (akadály)',
    entrance: 'Átjárás falon',
    fence: 'Kerítés',
    gate: 'Kapu',
    guard_rail: 'Szalagkorlát',
    handrail: 'Kapaszkodó korlát',
    hedge: 'Sövény (akadály)',
    kerb: 'Járdaszegély',
    lift_gate: 'Emelkedő sorompó',
    rope: 'Kötél',
    sliding_gate: 'Tolókapu',
    swing_gate: 'Elforduló soromó',
    turnstile: 'Forgóajtó',
    wall: 'Fal',
    retaining_wall: 'Támfal',
  },

  boundary: {
    administrative: {
      admin_level: {
        '2': 'Ország',
        '3': 'Régió (SK)',
        '4': 'Tartomány, kerület (SK)',
        '5': 'Régió (HU)',
        '6': 'Megye (HU)',
        '7': 'Járás (HU)',
        '8': 'Település (HU), járás (SK)',
        '9': 'Kerület (HU), település (SK)',
        '10': 'Településrész',
      },
      '*': 'Közigazgatási terület',
    },
    '*': 'Régió',
    marker: 'Határkő',
    national_park: 'Nemzeti park',
    protected_area: 'Védett terület',
  },

  building: {
    '*': {
      '*': 'Épület',

      abandoned: {
        yes: 'Elhagyott épület',
      },

      disused: {
        yes: 'Használaton kívüli épület',
      },

      ruins: {
        yes: 'Épület romjai',
      },
    },

    apartments: 'Társasház',
    barn: 'Pajta',
    bungalow: 'Bungaló',
    bunker: 'Bunker',
    cabin: 'Kis faház',
    cathedral: 'Székesegyház (katedrális)',
    chapel: 'Kápolna',
    church: 'Templom',
    civic: 'Közösségi épület',
    collapsed: 'Összedőlt épület',
    commercial: 'Kereskedelmi épület',
    construction: 'Építkezés',
    cowshed: 'Szarvasmarha-istálló',
    detached: 'Családi ház (UK)',
    dormitory: 'Kollégium',
    entrance: 'Épületbejárat',
    farm_auxiliary: 'Tanya melléképülete',
    farm: 'Tanya',
    garage: 'Garázs',
    garages: 'Garázsok',
    government: 'Kormányzati épület',
    grandstand: 'Lelátó',
    greenhouse: 'Üvegház',
    hangar: 'Hangár',
    hayloft: 'Szénapadlás',
    hospital: 'Kórházépület',
    hotel: 'Szállodaépület',
    house: 'Családi ház',
    houseboat: 'Lakóhajó',
    hut: 'Kunyhó',
    industrial: 'Ipari épület',
    kindergarten: 'Óvodaépület',
    kiosk: 'Trafik',
    manufacture: 'Gyárépület',
    mosque: 'Mecset',
    office: 'Irodaház',
    parking: 'Parkolóház',
    public: 'Középület',
    residential: 'Lakóépület',
    retail: 'Kiskereskedelmi épület',
    roof: 'Tető',
    ruins: 'Rom',
    school: 'Iskolaépület',
    semidetached_house: 'Ikerház',
    service: 'Gépészeti épület',
    shed: 'Fészer',
    shrine: 'Szentély',
    stable: 'Lóistálló',
    static_caravan: 'Mobilház, lakókocsi',
    storage_tank: 'Tárolótartály',
    sty: 'Disznóól',
    supermarket: 'Szupermarket-épület',
    synagogue: 'Zsinagóga',
    temple: 'Nem keresztény templom',
    terrace: 'Sorház',
    train_station: 'Vasútállomás',
    transformer_tower: 'Transzformátortorony',
    transportation: 'Közlekedési épület',
    university: 'Egyetemi épület',
    warehouse: 'Raktár',
    yes: 'Ismeretlen épület',
    abandoned: 'Elhagyott épület',
    disused: 'Használaton kívüli épület',
    stadium: 'Stadionépület',
  },

  highway: {
    service: {
      service: {
        '*': 'Szervizút {}',
        alley: 'Hátsó „szolgalmi” út',
        bus: 'Tömegközlekedési út',
        'drive-through': 'Autós szolgáltatáshoz vezető út',
        driveway: 'Kocsibehajtó',
        emergency_access: 'Tűzoltási felvonulási út',
        parking_aisle: 'Parkolón belüli út',
      },
      '*': 'Szolgálati, bejáróút',
    },

    track: {
      tracktype: {
        grade1: 'Tömör mzg. vagy erdészeti út',
        grade2: 'Többnyire tömör mzg. vagy erdészeti út',
        grade3: 'Vegyesen tömör és laza mzg. vagy erdészeti út',
        grade4: 'Többnyire laza mzg. vagy erdészeti út',
        grade5: 'Laza mzg. vagy erdészeti út',
      },
      '*': 'Mezőgazdasági vagy erdészeti út',
    },

    '*': 'Út {}',
    bus_stop: 'Buszmegálló',
    construction: 'Épülő út',
    crossing: 'Gyalogosátkelő (zebra)',
    cycleway: 'Kerékpárút',
    footway: 'Gyalogút',
    living_street: 'Lakó-pihenő övezet',
    motorway: 'Autópálya',
    motorway_link: 'Autópálya fel- vagy lehajtó',

    path: {
      '*': 'Ösvény',

      foot: {
        designated: {
          bicycle: {
            designated: 'Közös gyalog- és kerékpárút',
          },
        },
      },
    },

    pedestrian: 'Sétálóutca',
    primary: 'Főút',
    primary_link: 'Főút fel- vagy lehajtó',
    residential: 'Lakóút',
    secondary: 'Összekötő út',
    secondaty_link: 'Összekötő út fel- vagy lehajtó',
    steps: 'Lépcső',
    street_lamp: 'Utcai lámpa',
    tertiary: 'Bekötőút',
    tertiary_link: 'Bekötőút fel- vagy lehajtó',
    trunk: 'Autóút',
    trunk_link: 'Autóút fel- vagy lehajtó',
    unclassified: 'Egyéb közút',
    bridleway: 'Lovas út',
    piste: 'Sípálya',
    platform: 'Peron',
    raceway: 'Versenypálya',
    road: 'Ismeretlen típusú út',
    via_ferrata: 'Via ferrata',
  },

  historic: {
    ruins: {
      ruins: {
        castle: 'Várrom',
      },
      '*': 'Romok',
    },

    '*': 'Történelmi építmény',
    archaeological_site: 'Régészeti lelőhely',
    castle: 'Vár',
    church: 'Történelmi templom',
    city_gate: 'Városkapu',
    manor: 'Kúria, udvarház',
    memorial: 'Emlékmű',
    monastery: 'Kolostor',
    monument: 'Monumentális, épületszerű emlékmű',
    tomb: 'Síremlék',
    wayside_cross: 'Út menti kereszt',
    wayside_shrine: 'Út menti kegyhely',
    aircraft: 'Történelmi repülőgép',
    boundary_stone: 'Történelmi határkő',
    building: 'Történelmi épület',
    cannon: 'Történelmi ágyú',
    charcoal_pile: 'Szénégetőhely',
    citywalls: 'Városfalak',
    fort: 'Erőd',
    heritage: 'Örökségi helyszín',
    hollow_way: 'Mélyút',
    house: 'Történelmi ház',
    milestone: 'Történelmi mérföldkő',
    mine: 'Történelmi bánya',
    mine_shaft: 'Történelmi akna',
    shieling: 'Pásztorszállás',
    stone: 'Történelmi kő',
    tree_shrine: 'Fán lévő kegyhely',
    wreck: 'Hajóroncs',
    yes: 'Történelmi objektum',
  },

  landuse: {
    '*': '{}',
    allotments: 'Kiskertek',
    basin: 'Vízgyűjtő medence',
    brownfield: 'Barnamezős terület',
    cemetery: 'Temető',
    commercial: 'Kereskedelmi terület',
    construction: 'Építési terület',
    education: 'Oktatási terület',
    farmland: 'Mezőgazdasági terület',
    farmyard: 'Tanyaudvar',
    forest: 'Telepített erdő',
    garages: 'Garázsok',
    grass: 'Gyep',
    greenfield: 'Zöldmezős terület',
    industrial: 'Ipari terület',
    landfill: 'Hulladéklerakó',
    meadow: 'Rét',
    military: 'Katonai terület',
    orchard: 'Gyümölcsös',
    plant_nursery: 'Faiskola',
    quarry: 'Külszíni fejtés, kőfejtő',
    recreation_ground: 'Szabadidőpark',
    religions: 'Egyházi terület',
    reservoir: 'Víztározó, mesterséges tó',
    residential: 'Lakóterület',
    retail: 'Kiskereskedelmi terület',
    vineyard: 'Szőlőültetvény',
    winter_sports: 'Sípálya, télisport-terület',
    pedestrian: 'Gyalogos terület',
    railway: 'Vasúti terület',
    village_green: 'Falu zöldterülete',
  },

  leisure: {
    '*': '{}',

    picnic_table: {
      covered: {
        yes: 'Fedett piknikezőasztal',
        no: 'Fedetlen piknikasztal',
      },
      '*': 'Piknikezőasztal',
    },

    pitch: 'Sportpálya',
    bleachers: 'Lelátó',
    escape_game: 'Szabadulószoba',
    hackerspace: 'Hackerspace',
    ice_rink: 'Jégpálya',
    marina: 'Kishajókikötő, marina',
    miniature_golf: 'Minigolf',
    dog_park: 'Kutyafuttató',
    firepit: 'Tűzrakóhely',
    fishing: 'Horgászhely',
    fitness_centre: 'Edzőterem',
    fitness_station: 'Fitneszpark',
    garden: 'Kert',
    golf_course: 'Golfpálya',
    horse_riding: 'Lovaglás',
    nature_reserve: 'Természetvédelmi terület',
    park: 'Park',
    playground: 'Játszótér',
    sports_centre: 'Sportközpont',
    sports_hall: 'Sportcsarnok',
    stadium: 'Stadion',
    swimming_pool: 'Úszómedence',
    track: 'Versenypálya',
    water_park: 'Strand, élményfürdő',
    adult_gaming_centre: 'Felnőtt játékközpont',
    amusement_arcade: 'Játékterem',
    bandstand: 'Zenepavilon',
    bathing_place: 'Fürdőhely',
    beach_resort: 'Strandüdülő',
    bird_hide: 'Madármegfigyelő les',
    bowling_alley: 'Bowlingpálya',
    dance: 'Tánchelyszín',
    disc_golf_course: 'Discgolfpálya',
    high_ropes_course: 'Kötélpálya',
    outdoor_seating: 'Kültéri ülőhely',
    resort: 'Üdülőhely',

    sauna: {
      '*': 'Szauna',

      sauna: {
        aroma: 'Aromaszauna',
        dry: 'Száraz szauna',
        hanjeungmak: 'Hanjeungmak (koreai szauna)',
        hot: 'Finn szauna',
        infrared: 'Infraszauna',
        smoke: 'Füstös szauna (finn)',
        steam: 'Gőzszauna (törökfürdő)',
      },
    },

    slipway: 'Csónakrámpa',
    summer_camp: 'Nyári tábor',
    sunbathing: 'Napozóterület',
    swimming_area: 'Fürdőterület',
    tanning_salon: 'Szolárium',
    trampoline_park: 'Trambulinpark',
    wildlife_hide: 'Vadmegfigyelő les',
  },

  man_made: {
    tower: {
      'tower:type': {
        bell_tower: 'Harangtorony',
        communication: 'Távközlési torony',
        cooling: 'Hűtőtorny',
        observation: 'Kilátótorony',
        climbing: 'Mászótorony',
        clock: 'Óratorony',
        defensive: 'Védelmi torony',
        diving: 'Ugrótorony',
        hose: 'Tömlőszárító torony',
        lighting: 'Világítótorony',
        minaret: 'Minaret',
        monitoring: 'Megfigyelőtorony',
        pagoda: 'Pagodatorony',
        radar: 'Radartorony',
        siren: 'Szirénatorony',
        watchtower: 'Őrtorony',
      },
      '*': 'Torony',
    },

    '*': '{}',

    adit: {
      '*': 'Bányatárna',

      disused: {
        yes: 'Használaton kívüli táró',
      },
    },

    antenna: 'Antenna',
    beacon: 'Jelzőfény',
    beehive: 'Kaptár',
    bridge: 'Híd',
    bunker_silo: 'Falközi siló',
    cairn: 'Kőhalom (mesterséges)',
    cellar_entrance: 'Pincebejárat',
    chimney: 'Kémény',
    clearcut: 'Tarvágás',
    communications_tower: 'TV-torony',
    cooling_tower: 'Hűtőtorny',
    crane: 'Daruszerkezet',
    cross: 'Kereszt',
    cutline: 'Nyiladék',
    dyke: 'Árvízvédelmi töltés',
    embankment: 'Töltés',
    flagpole: 'Zászlórúd',
    "forester's_lodge": 'Erdészlak',
    gasometer: 'Gazométer',
    goods_conveyor: 'Szállítószalag',
    groyne: 'Sarkantyú',
    lighthouse: 'Világítótorony',
    manhole: 'Aknafedél',

    mast: {
      '*': 'Pózna',

      'tower:type': {
        clock: 'Órás árboc',
        communication: 'Távközlési árboc',
        lighting: 'Világítási árboc',
        monitoring: 'Megfigyelő árboc',
        radar: 'Radarárboc',
        siren: 'Szirénás árboc',
      },
    },

    mineshaft: {
      '*': 'Bányaakna',

      disused: {
        yes: 'Használaton kívüli bányakürtő',
      },
    },

    monitoring_station: 'Megfigyelőállomás',
    nesting_site: 'Fészkelőhely',
    observatory: 'Obszervatórium',
    pier: 'Móló',

    pipeline: {
      '*': 'Csővezeték',

      location: {
        underground: 'Föld alatti csővezeték',
        underwater: 'Víz alatti csővezeték',
      },
    },

    reservoir_covered: 'Fedett víztározó',
    silo: 'Siló',
    snow_cannon: 'Hóágyú',
    spoil_heap: 'Meddőhányó',
    spring_box: 'Forrásfoglalás',
    storage_tank: 'Tároló tartály',
    street_cabinet: 'Utcai közműszekrény',
    surveillance: 'Térfigyelő berendezés',
    survey_point: 'Földmérési alappont',
    telescope: 'Teleszkóp',
    utility_pole: 'Közműoszlop',
    wastewater_plant: 'Szennyvíztisztító',
    water_tap: 'Vízcsap',
    water_tower: 'Víztorony',
    water_well: 'Kút',
    water_works: 'Vízmű',
    watermill: 'Vízimalom',
    windmill: 'Szélmalom',
    works: 'Gyár',
    apiary: 'Méhészet',
    pumping_station: 'Szivattyúállomás',
  },

  natural: {
    spring: {
      drinking_water: {
        yes: 'Forrás (ivóvíz)',
        no: 'Forrás (nem ivóvíz)',
      },

      refitted: {
        yes: 'Foglalt forrás',
        no: 'Természetes állapotú, nem foglalt forrás',
      },

      '*': 'Forrás',

      intermittent: {
        yes: 'Időszakos forrás',
      },

      seasonal: {
        yes: 'Szezonális forrás',
      },

      water_characteristic: {
        '*': 'Ásványforrás',
      },
    },
    tree: {
      protected: {
        yes: 'Védett fa',
      },
      denotation: {
        natural_monument: 'Fa – természeti emlék',
        landmark: 'Fa – tájékozódási pont',
        avenue: 'Fa – fasor',
        urban: 'Városi fa',
        agricultural: 'Mezőgazdasági fa',
      },
      '*': 'Fa',
    },
    '*': '{}',
    arch: 'Sziklaív',
    bare_rock: 'Csupasz szikla',
    basin: 'Medence',
    bay: 'Öböl',
    beach: 'Természetes strand',
    birds_nest: 'Madárfészek',
    cave_entrance: 'Barlangbejárat',
    cliff: 'Szirt',
    earth_bank: 'Partfal, természetes rézsű',
    fell: 'Fjell',
    geyser: 'Gejzír',
    glacier: 'Gleccser',
    grassland: 'Füves puszta',
    gully: 'Vízmosta árok',
    heath: 'Fenyér',
    hot_spring: 'Hőforrás',
    landslide: 'Földcsuszamlás',
    mountain_range: 'Magas hegylánc',
    mud: 'Sár',
    peak: 'Hegycsúcs',
    plateau: 'Fennsík',
    ridge: 'Hegygerinc',
    rock: 'Szikla',
    saddle: 'Nyereg',
    sand: 'Homok',
    scree: 'Törmeléklejtő',
    scrub: 'Bozót',
    shingle: 'Kavicshordalék',
    shrub: 'Cserje',
    sinkhole: 'Víznyelő',
    stone: 'Kő',
    tree_row: 'Fasor',
    valley: 'Völgy',
    water: 'Víztest',
    wetland: {
      '*': 'Vizenyős terület',
      wetland: {
        bog: 'Láp',
        fen: 'Mocsárrét',
        mangrove: 'Mangrove',
        marsh: 'Mocsár',
        reedbed: 'Nádas',
        swamp: 'Ingovány',
        wet_meadow: 'Nedves rét',
      },
    },
    wood: 'Természetes erdő',
  },

  place: {
    '*': 'Hely {}',
    city: 'Nagyváros',
    country: 'Ország',
    farm: 'Tanya, gazdaság',
    hamlet: 'Falucska',
    island: 'Sziget',
    islet: 'Kis sziget',
    isolated_dwelling: 'Magányos lakóhely',
    locality: 'Dűlő, lakatlan hely',
    ocean: 'Óceán',
    sea: 'Tenger',
    square: 'Tér',
    state: 'Állam',
    suburb: 'Városrész',
    town: 'Kisváros',
    village: 'Falu',
  },

  power: {
    '*': '{}',
    generator: {
      '*': 'Generátor',

      'generator:source': {
        biofuel: {
          '*': 'Biotüzelőanyaggal működő áramfejlesztő',
        },

        biogas: {
          '*': 'Biogázzal működő áramfejlesztő',
        },

        biomass: {
          '*': 'Biomasszával működő áramfejlesztő',

          'generator:method': {
            anaerobic_digestion:
              'Anaerob biomassza-bontással működő áramfejlesztő',
            combustion: 'Biomassza-égetéses áramfejlesztő',
            gasification: 'Biomassza-elgázosításos áramfejlesztő',
          },
        },

        coal: {
          '*': 'Széntüzelésű áramfejlesztő',
        },

        diesel: {
          '*': 'Dízel áramfejlesztő',
        },

        gas: {
          '*': 'Gáztüzelésű áramfejlesztő',
        },

        gasoline: {
          '*': 'Benzines áramfejlesztő',
        },

        geothermal: {
          '*': 'Geotermikus áramfejlesztő',
        },

        hydro: {
          '*': 'Vízenergiás áramfejlesztő',

          'generator:method': {
            'run-of-the-river': 'Folyóvizes vízenergiás áramfejlesztő',
            'water-pumped-storage':
              'Szivattyús-tározós vízenergiás áramfejlesztő',
            'water-storage': 'Tározós vízenergiás áramfejlesztő',
          },
        },

        nuclear: {
          '*': 'Nukleáris áramfejlesztő',

          'generator:method': {
            fission: 'Maghasadásos nukleáris áramfejlesztő',
            fusion: 'Magfúziós nukleáris áramfejlesztő',
          },
        },

        oil: {
          '*': 'Olajtüzelésű áramfejlesztő',
        },

        solar: {
          '*': 'Napelemes áramfejlesztő',

          'generator:method': {
            photovoltaic: 'Fotovoltaikus napelemes áramfejlesztő',
            thermal: 'Nap-hőenergiás áramfejlesztő',
          },
        },

        tidal: {
          '*': 'Árapály-energiás áramfejlesztő',

          'generator:method': {
            barrage: 'Árapálygátas áramfejlesztő',
            stream: 'Árapályáramlatos áramfejlesztő',
          },
        },

        waste: {
          '*': 'Hulladékból energiát termelő áramfejlesztő',

          'generator:method': {
            combustion: 'Hulladékégetéses áramfejlesztő',
            gasification: 'Hulladék-elgázosításos áramfejlesztő',
          },
        },

        wave: {
          '*': 'Hullámenergiás áramfejlesztő',
        },

        wind: {
          '*': 'Szélerőművi áramfejlesztő',
        },
      },
    },
    line: 'Távvezeték',
    minor_line: 'Kisebb villanyvezeték',
    plant: {
      '*': 'Erőmű',

      'plant:source': {
        biofuel: {
          '*': 'Biotüzelőanyag-erőmű',
        },

        biogas: {
          '*': 'Biogáz-erőmű',
        },

        biomass: {
          '*': 'Biomassza-erőmű',

          'plant:method': {
            anaerobic_digestion: 'Anaerob biomassza-bontású erőmű',
            combustion: 'Biomassza-égetéses erőmű',
            gasification: 'Biomassza-elgázosításos erőmű',
          },
        },

        coal: {
          '*': 'Széntüzelésű erőmű',
        },

        diesel: {
          '*': 'Dízel-erőmű',
        },

        gas: {
          '*': 'Gáztüzelésű erőmű',
        },

        gasoline: {
          '*': 'Benzines erőmű',
        },

        geothermal: {
          '*': 'Geotermikus erőmű',
        },

        hydro: {
          '*': 'Vízerőmű',

          'plant:method': {
            'run-of-the-river': 'Folyóvizes vízerőmű',
            'water-pumped-storage': 'Szivattyús-tározós vízerőmű',
            'water-storage': 'Tározós vízerőmű',
          },
        },

        nuclear: {
          '*': 'Atomerőmű',

          'plant:method': {
            fission: 'Maghasadásos atomerőmű',
            fusion: 'Magfúziós erőmű',
          },
        },

        oil: {
          '*': 'Olajtüzelésű erőmű',
        },

        solar: {
          '*': 'Naperőmű',

          'plant:method': {
            photovoltaic: 'Fotovoltaikus naperőmű',
            thermal: 'Nap-hőerőmű',
          },
        },

        tidal: {
          '*': 'Árapály-erőmű',

          'plant:method': {
            barrage: 'Árapálygátas erőmű',
            stream: 'Árapályáramlatos erőmű',
          },
        },

        waste: {
          '*': 'Hulladékhasznosító erőmű',

          'plant:method': {
            combustion: 'Hulladékégető erőmű',
            gasification: 'Hulladék-elgázosító erőmű',
          },
        },

        wave: {
          '*': 'Hullámenergia-erőmű',
        },

        wind: {
          '*': 'Szélerőmű',
        },
      },
    },
    pole: 'Villanyoszlop',
    substation: 'Alállomás',
    tower: 'Távvezetékoszlop',
    transformer: 'Transzformátor',
  },

  public_transport: {
    platform: 'Peron',
    station: 'Állomás',
    stop_position: 'Megállási pont',
  },

  shop: {
    '*': 'Bolt {}',
    household_linen: 'Lakástextil',
    charity: 'Jótékonysági bolt',
    chocolate: 'Csokoládébolt',
    fashion_accessories: 'Divatkiegészítő bolt',
    frozen_food: 'Fagyasztottélelmiszer-bolt',
    hearing_aids: 'Hallókészülék-bolt',
    weapons: 'Fegyverbolt',
    alcohol: 'Szeszesitalbolt',
    antiques: 'Antikvitás',
    art: 'Műalkotásbolt',
    baby_goods: 'Bababolt',
    bag: 'Táskabolt',
    bakery: 'Pékség',
    bathroom_furnishing: 'Fürdőszoba berendezés',
    beauty: 'Szépségszalon',
    bed: 'Hálószoba-felszerelés',
    beverages: 'Italbolt',
    bicycle: 'Kerékpár-szaküzlet',
    bookmaker: 'Fogadóiroda',
    books: 'Könyvesbolt',
    boutique: 'Butik',
    butcher: 'Hentes',
    camera: 'Fényképezőgép-bolt',
    car: 'Autókereskedés',
    car_parts: 'Autóalkatrész',
    car_repair: 'Autószerelő',
    carpet: 'Szőnyeg-szaküzlet',
    cheese: 'Sajtbolt',
    chemist: 'Drogéria',
    clothes: 'Ruházati bolt',
    coffee: 'Kávé-szaküzlet',
    collector: 'Gyűjtői bolt',
    computer: 'Számítógép-szaküzlet',
    confectionery: 'Édességbolt',
    convenience: 'Kis élelmiszerbolt',
    copyshop: 'Fénymásoló',
    cosmetics: 'Kozmetikai üzlet',
    craft: 'Kézműveskellék-szaküzlet',
    curtain: 'Függönybolt',
    dairy: 'Tejtermékbolt',
    deli: 'Csemegeüzlet',
    department_store: 'Nagyáruház',
    doityourself: 'Barkácsbolt',
    doors: 'Ajtóbolt',
    dry_cleaning: 'Vegytisztító',
    'e-cigarette': 'E-cigaretta bolt',
    electrical: 'Villamossági cikkek',
    electronics: 'Elektronikai bolt',
    erotic: 'Szexshop',
    fabric: 'Méteráru',
    farm: 'Termelői stand',
    fireplace: 'Kandalló bolt',
    fishing: 'Horgászbolt',
    flooring: 'Padlóbolt',
    florist: 'Virágbolt',
    funeral_directors: 'Temetkezési iroda',
    furniture: 'Bútorbolt',
    games: 'Játékbolt',
    garden_center: 'Kertészet',
    garden_centre: 'Kertészet',
    general: 'Vegyesbolt',
    gift: 'Ajándékbolt, souvenir',
    glaziery: 'Üveges bolt',
    greengrocer: 'Zöldséges',
    hairdresser: 'Fodrász',
    hardware: 'Vas-műszaki bolt',
    health_food: 'Egészségesélelmiszer-bolt',
    hifi: 'Hifi szaküzlet',
    houseware: 'Háztartási bolt',
    hunting: 'Vadászfelszerelés bolt',
    ice_cream: 'Fagylaltozó',
    interior_decoration: 'Lakberendezési szaküzlet',
    jewelry: 'Ékszerbolt',
    kiosk: 'Trafik',
    kitchen: 'Konyhafelszerelés-bolt',
    laundry: 'Mosoda',
    lighting: 'Világítástechnikai szaküzlet',
    locksmith: 'Lakatos',
    lottery: 'Lottózó',
    mall: 'Bevásárlóközpont',
    massage: 'Masszázsszalon',
    medical_supply: 'Gyógyászati segédeszközök boltja',
    mobile_phone: 'Mobiltelefon-szaküzlet',
    model: 'Modellező-szaküzlet',
    motorcycle: 'Motorkerékpár-szaküzlet',
    music: 'Zenebolt',
    musical_instrument: 'Hangszerbolt',
    newsagent: 'Újságos',
    nutrition_supplements: 'Étrend-kiegészítők boltja',
    optician: 'Látszerész',
    outdoor: 'Túrafelszerelés-bolt',
    outpost: 'Megrendelt áru átvevőhelye',
    paint: 'Festékbolt',
    pastry: 'Cukrászda',
    pawnbroker: 'Zálogház',
    perfumery: 'Illatszer-szaküzlet',
    pet: 'Állateledel-bolt',
    pet_grooming: 'Kisállat-kozmetika',
    photo: 'Fényképészeti bolt',
    radiotechnics: 'Rádiótechnikai bolt',
    rental: 'Kölcsönző',
    seafood: 'Tengeriélelmiszer-bolt',
    second_hand: 'Használtcikk-kereskedés',
    sewing: 'Varróbolt',
    shoes: 'Cipőbolt',
    sports: 'Sportbolt',
    stationery: 'Papír-írószer bolt',
    supermarket: 'Szupermarket',
    tailor: 'Szabó',
    tattoo: 'Tetováló szalon',
    tea: 'Tea-szaküzlet',
    ticket: 'Jegyiroda',
    tobacco: 'Dohánybolt',
    toys: 'Játékbolt',
    trade: 'Szakáruház',
    travel_agency: 'Utazási iroda',
    tyres: 'Gumiabroncs-bolt',
    vacant: 'Üres üzlethelyiség',
    variety_store: '100 forintos bolt',
    video: 'Videóbolt',
    video_games: 'Videójáték-bolt',
    watches: 'Óra-szaküzlet',
    wholesale: 'Nagykereskedés',
    window_blind: 'Redőnybolt',
    wine: 'Borkereskedés',
  },

  sport: {
    '*': 'Sport {}',
    australian_football: 'Ausztrál futball',
    billiards: 'Biliárd',
    boxing: 'Ökölvívás',
    cliff_diving: 'Szikláról ugrás',
    cricket: 'Krikket',
    cricket_nets: 'Krikkethálók',
    croquet: 'Krokett',
    curling: 'Curling',
    gaelic_games: 'Kelta játékok',
    horseshoes: 'Patkódobás',
    korfball: 'Korfball',
    long_jump: 'Távolugrás',
    orienteering: 'Tájékozódási futás',
    paddle_tennis: 'Paddle tenisz',
    pelota: 'Pelota',
    racquet: 'Racquetball',
    rc_car: 'Távirányítós autók',
    rugby: 'Rögbi',
    rugby_league: 'Rögbi (league)',
    rugby_union: 'Rögbi (union)',
    sailing: 'Vitorlázás',
    surfing: 'Szörfözés',
    table_soccer: 'Csocsó',
    team_handball: 'Kézilabda',
    toboggan: 'Szánkó',
    '9pin': 'Teke',
    '10pin': 'Bowling',
    aikido: 'Aikidó',
    airsoft: 'Airsoft',
    american_football: 'Amerikai futball',
    archery: 'Íjászat',
    athletics: 'Atlétika',
    badminton: 'Tollaslabda',
    baseball: 'Baseball',
    basketball: 'Kosárlabda',
    beachvolleyball: 'Strandröplabda',
    bicycle: 'Kerékpározás',
    bmx: 'BMX',
    boules: 'Bocsa',
    bowling: 'Bowling',
    bowls: 'Bocsa',
    canoe: 'Kenuzás',
    chess: 'Sakk',
    climbing: 'Sziklamászás',
    climbing_adventure: 'Kalandpark',
    cycling: 'Kerékpározás',
    darts: 'Darts',
    disc_golf: 'Frizbigolf',
    dog_racing: 'Kutyaverseny',
    equestrian: 'Lovaglás',
    field_hockey: 'Gyeplabda',
    fitness: 'Fitnesz',
    floorball: 'Floorball',
    free_flying: 'Siklóernyőzés, sárkányrepülés',
    golf: 'Golf',
    gymnastics: 'Torna',
    handball: 'Kézilabda',
    hockey: 'Jégkorong',
    horse_racing: 'Lóverseny',
    ice_hockey: 'Jégkorong',
    ice_skating: 'Jégkorcsolya',
    judo: 'Cselgáncs',
    karate: 'Karate',
    karting: 'Gokart',
    laser_tag: 'Lézerharc',
    model_aerodrome: 'Modellrepülőtér',
    motocross: 'Motokrossz',
    motor: 'Motorkerékpár verseny',
    multi: 'Több sportág',
    netball: 'Netball',
    paintball: 'Paintball',
    petanque: 'Petanque',
    roller_skating: 'Görkorcsolyázás',
    rowing: 'Evezés',
    running: 'Futás',
    scuba_diving: 'Palackos búvárkodás',
    shooting: 'Lövészet',
    shooting_range: 'Lőtér',
    'shot-put': 'Súlylökés',
    skateboard: 'Gördeszka',
    skating: 'Korcsolyázás',
    ski_jumping: 'Síugrás',
    skiing: 'Síelés',
    soccer: 'Labdarúgás',
    squash: 'Fallabda',
    streetball: 'Streetball',
    swimming: 'Úszás',
    table_tennis: 'Asztalitenisz',
    tennis: 'Tenisz',
    volleyball: 'Röplabda',
    water_ski: 'Vízisí',
    workout: 'Edzés',
    yoga: 'Jóga',
    '8pin': 'Nyolcbábus bowling',
    aerobics: 'Aerobik',
    american_handball: 'Amerikai kézilabda',
    association_football: 'Labdarúgás (soccer)',
    axe_throwing: 'Fejszedobás',
    balle_pelote: 'Balle pelote',
    ballooning: 'Hőlégballonozás',
    bandy: 'Bandy',
    barre: 'Barre edzés',
    base: 'BASE ugrás',
    batting_cage: 'Baseball/softball ütőketrec',
    beach_soccer: 'Strandfoci',
    beach_tennis: 'Strandtenisz',
    beachhandball: 'Strandkézilabda',
    beachtennis: 'Strandtenisz',
    biathlon: 'Biatlon',
    billards: 'Biliárd',
    bobsleigh: 'Bob',
    bodybuilding: 'Testépítés',
    bullfighting: 'Bikaviadal',
    calisthenics: 'Kalisztenika',
    canadian_football: 'Kanadai futball',
    candlepin: 'Candlepin bowling',
    canoe_polo: 'Kenupóló',
    chinlone: 'Chinlone',
    cockfighting: 'Kakasviadal',
    crossfit: 'CrossFit',
    cycle_ball: 'Kerékpárlabda',
    cycle_polo: 'Kerékpárpóló',
    dance: 'Táncsport',
    dancing: 'Táncsport',
    diving: 'Műugrás',
    dodgeball: 'Kidobós',
    dog_agility: 'Kutyás agility',
    dragon_boat: 'Sárkányhajózás',
    fencing: 'Vívás',
    fistball: 'Ököllabda',
    'five-a-side': 'Kispályás foci (5 az 5 ellen)',
    fives: 'Fives',
    football: 'Labdarúgás',
    footballgolf: 'Futballgolf',
    four_square: 'Four square',
    freediving: 'Szabadtüdős merülés',
    funnel_ball: 'Funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Gael futball',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Vitorlázórepülés',
    hanggliding: 'Sárkányrepülés',
    hapkido: 'Hapkido',
    high_rope_course: 'Magaskötélpálya',
    hiking: 'Túrázás',
    hopscotch: 'Ugróiskola',
    horse_riding: 'Lovaglás',
    ice_stock: 'Jégstock',
    'in-line_hockey': 'Inline hoki',
    jetsprint: 'Jet sprint hajóverseny',
    kick_scooter: 'Rolleres sport',
    kickball: 'Kickball',
    kickboxing: 'Kick-box',
    kitesurfing: 'Kiteszörf',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Lacrosse',
    martial_arts: 'Harcművészetek',
    mind_body_interventions: 'Test-lélek gyakorlatok (pl. jóga)',
    miniature_golf: 'Minigolf',
    mtb: 'Hegyikerékpározás',
    nine_mens_morris: 'Malomjáték',
    obstacle_course: 'Akadályfutás',
    paddleball: 'Paddleball',
    paddleboard: 'Állva evezés (SUP)',
    padel: 'Padel',
    parachuting: 'Ejtőernyőzés',
    paragliding: 'Siklóernyőzés',
    parkour: 'Parkour',
    pedal_car_racing: 'Pedálos autóverseny',
    pesäpallo: 'Pesäpallo (finn baseball)',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Rúdtánc',
    polo: 'Póló',
    powerlifting: 'Erőemelés',
    rodeo: 'Rodeó',
    roller_hockey: 'Görhoki',
    russian_skittles: 'Orosz teke',
    safety_training: 'Biztonsági sportképzés',
    shuffleboard: 'Shuffleboard',
    snooker: 'Snooker',
    snorkeling: 'Sznorkelezés',
    softball: 'Softball',
    speedway: 'Salakmotor',
    summer_toboggan: 'Nyári bobpálya',
    sumo: 'Szumó',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    touch_football: 'Érintéses futball',
    trampoline: 'Trambulin',
    trugo: 'Trugo',
    tug_of_war: 'Kötélhúzás',
    ultimate: 'Ultimate frizbi',
    ultralight_aviation: 'Ultrakönnyű repülés',
    wakeboarding: 'Wakeboard',
    walking: 'Sportgyaloglás',
    water_polo: 'Vízilabda',
    water_sports: 'Vízisportok',
    weightlifting: 'Súlyemelés',
    windsurfing: 'Windszörf',
    wrestling: 'Birkózás',
    zurkhaneh_sport: 'Zurkhaneh (iráni hagyományos sport)',
  },

  tourism: {
    artwork: {
      artwork_type: {
        architecture: 'Építészet',
        bust: 'Mellszobor',
        graffiti: 'Graffiti',
        installation: 'Installáció',
        mosaic: 'Mozaik',
        mural: 'Falfestmény',
        painting: 'Festmény',
        relief: 'Dombormű',
        sculpture: 'Absztrakt szobor',
        statue: 'Szobor',
        stone: 'Megmunkált kő',
      },
      '*': 'Művészet',
    },

    information: {
      information: {
        '*': 'Információ {}',
        board: 'Tájékoztató tábla',
        guidepost: 'Útirányjelző tábla',
        map: 'Térkép',
        office: 'Tourinform iroda',
        route_marker: 'Útvonaljelzés',
      },
      '*': 'Információ',
    },

    '*': '{}',
    alpine_hut: 'Menedékház (személyzettel)',
    apartment: 'Apartman',
    aquarium: 'Akvárium',
    attraction: 'Látnivaló',
    camp_site: 'Kemping',
    caravan_site: 'Lakóautós pihenőhely',
    chalet: 'Nyaralóház',
    gallery: 'Galéria',
    guest_house: 'Vendégház',
    hostel: 'Turistaszálló',
    hotel: 'Szálloda',
    motel: 'Motel',
    museum: 'Múzeum',
    picnic_site: 'Piknikezőhely',
    viewpoint: 'Kilátóhely',
    wilderness_hut: 'Menedékház (személyzet nélkül)',
    zoo: 'Állatkert',
    theme_park: 'Tematikus park',
  },

  type: {
    route: {
      route: {
        '*': 'Útvonal {}',
        bicycle: 'Kerékpáros útvonal',
        bus: 'Buszútvonal',
        foot: 'Gyalogos útvonal',
        hiking: {
          '*': 'Turistaút',

          network: {
            iwn: 'Nemzetközi turistaút',
            lwn: 'Helyi turistaút',
            nwn: 'Országos turistaút',
            rwn: 'Regionális turistaút',
          },
        },
        horse: 'Lovas útvonal',
        mtb: 'Mountain bike útvonal',
        piste: 'Sípálya',
        railway: 'Vasútvonal',
        ski: 'Sífutó útvonal',
        tram: 'Villamosútvonal',
      },
      '*': 'Útvonal',
    },
  },

  waterway: {
    '*': 'Vízfolyás {}',
    canal: 'Csatorna',
    dam: 'Duzzasztógát',
    ditch: 'Árok (vízfolyás)',
    drain: 'Vízelvezető árok',
    river: 'Folyó',
    stream: 'Patak',
    waterfall: 'Vízesés',
    weir: 'Bukógát',
    canoe_pass: 'Kenuátemelő',
    fairway: 'Hajózóút',
    fish_pass: 'Hallépcső',
    flowline: 'Áramlási vonal',
    link: 'Vízfolyás-kapcsolat',
    pressurised: 'Nyomás alatti vízvezeték',
    rapids: 'Zuhatag',
    tidal_channel: 'Árapálycsatorna',
  },

  railway: {
    '*': 'Vasút',
    abandoned: 'Elhagyott vasút',
    buffer_stop: 'Vasúti ütközőbak',
    construction: 'Épülő vasút',
    crossing: 'Vasúti pályakeresztezés',
    derail: 'Kisiklásgátló',
    disused: 'Használaton kívüli vasút',
    funicular: 'Siklóvasút',
    halt: 'Vasúti megállóhely',
    level_crossing: 'Szintbeni vasúti átjáró',
    light_rail: 'Könnyűvasút',
    miniature: 'Minivasút',
    monorail: 'Egysínű vasút',
    narrow_gauge: 'Keskenynyomközű vasút',
    platform: 'Vasúti peron',
    preserved: 'Műemlékvasút',
    proposed: 'Tervezett vasút',
    rail: 'Vasútvonal',
    railway_crossing: 'Vasúti átjáró',
    roundhouse: 'Mozdonyfűtőház',
    signal: 'Vasúti jelző',
    station: 'Vasútállomás',
    stop: 'Vasúti megálló',
    subway: 'Metróvonal',
    subway_entrance: 'Metróbejárat',
    switch: 'Vasúti váltó',
    tram: 'Villamosvonal',
    tram_stop: 'Villamosmegálló',
    traverser: 'Vasúti áthelyező berendezés',
    turntable: 'Mozdonyfordító korong',
    ventilation_shaft: 'Vasúti szellőzőakna',
    wash: 'Vonatmosó',
    water_crane: 'Vasúti vízdaru',
    workshop: 'Vasúti műhely',
  },

  'abandoned:building': {
    '*': 'Elhagyott épület',
  },

  'disused:building': {
    '*': 'Használaton kívüli épület',
  },

  'ruins:building': {
    '*': 'Épületrom',
  },

  attraction: {
    amusement_ride: 'Vidámparki játék',
    animal: 'Állatos látványosság',
    big_wheel: 'Óriáskerék',
    carousel: 'Körhinta',
    historic: 'Történelmi látványosság',
    maze: 'Labirintus',
    roller_coaster: 'Hullámvasút',
    summer_toboggan: 'Nyári bobpálya',
    train: 'Látványvonat',
    water_slide: 'Vízicsúszda',
  },

  bicycle: {
    designated: 'Kerékpárral kijelölt',
    no: 'Kerékpárral tilos',
    private: 'Kerékpárral csak tulajdonosnak',
    yes: 'Kerékpárral megengedett',
  },

  bridge: {
    '*': {
      '*': 'Híd',

      highway: {
        '*': 'Közúti híd',
      },

      railway: {
        '*': 'Vasúti híd',
      },
    },

    no: '',
  },

  fixme: {
    '*': 'Hibásan vagy részben feltérképezett objektum',
  },

  foot: {
    designated: 'Gyalogosok számára kijelölt',
    no: 'Gyalogos forgalom tilos',
    private: 'Gyalogos forgalom csak tulajdonosnak',
    yes: 'Gyalogos forgalom megengedett',
  },

  ford: {
    yes: 'Gázló',
  },

  intermittent: {
    yes: {
      natural: {
        water: 'Időszakos vízfelület',
      },

      waterway: 'Időszakos vízfolyás',
    },
  },

  mountain_pass: {
    yes: 'Hágó',
  },

  oneway: {
    yes: 'Egyirányú',
  },

  motor_vehicle: {
    designated: 'Gépjárművek számára kijelölt',
    no: 'Gépjárművel tilos',
    private: 'Gépjárművel csak tulajdonosnak',
    yes: 'Gépjárművel megengedett',
  },

  military: {
    '*': 'Katonai létesítmény {}',
    academy: 'Katonai akadémia',
    airfield: 'Katonai repülőtér',
    ammunition: 'Lőszerraktár',
    barracks: 'Laktanya',
    base: 'Katonai bázis',
    bunker: 'Bunker',
    checkpoint: 'Katonai ellenőrzőpont',
    danger_area: 'Katonai veszélyzóna',
    depot: 'Katonai raktár',
    launchpad: 'Indítóállás',
    naval_base: 'Haditengerészeti bázis',
    nuclear_explosion_site: 'Nukleáris kísérleti helyszín',
    obstacle_course: 'Katonai akadálypálya',
    office: 'Katonai hivatal',
    range: 'Lőtér',
    school: 'Katonai iskola',
    training_area: 'Katonai gyakorlótér',
    trench: 'Lövészárok',
  },

  seasonal: {
    yes: {
      natural: {
        water: 'Szezonális vízfelület',
      },

      waterway: 'Szezonális vízfolyás',
    },
  },

  trail_visibility: {
    bad: 'Rossz ösvényláthatóság',
    excellent: 'Kiváló ösvényláthatóság',
    good: 'Jó ösvényláthatóság',
    horrible: 'Nagyon rossz ösvényláthatóság',
    intermediate: 'Közepes ösvényláthatóság',
    no: 'Nincs ösvényláthatóság',
  },

  tunnel: {
    '*': {
      '*': 'Alagút',

      highway: {
        '*': 'Közúti alagút',
      },

      railway: {
        '*': 'Vasúti alagút',
      },
    },

    culvert: 'Áteresz',
    no: '',
  },

  vehicle: {
    designated: 'Járművek számára kijelölt',
    no: 'Járműforgalom tilos',
    private: 'Járműforgalom csak tulajdonosnak',
    yes: 'Járműforgalom megengedett',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Piros',
  blue: 'Kék',
  green: 'Zöld',
  yellow: 'Sárga',
  orange: 'Narancssárga',
  purple: 'Bíbor',
  violet: 'Ibolya',
  white: 'Fehér',
  black: 'Fekete',
  gray: 'Szürke',
  brown: 'Barna',
};
