import type { DeepPartial } from '@shared/types/deepPartial.js';
import type { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  aeroway: {
    aerodrome: 'Lotnisko',
    airstrip: 'Pas startowy',
    apron: 'Płyta postojowa',
    gate: 'Bramka lotniskowa',
    hangar: 'Hangar lotniczy',
    helipad: 'Lądowisko dla śmigłowców',
    holding_position: 'Miejsce oczekiwania samolotu',
    jet_bridge: 'Rękaw pasażerski',
    navigationaid: 'Pomoc nawigacji lotniczej',
    parking_position: 'Stanowisko postojowe samolotu',
    runway: 'Droga startowa',
    stopway: 'Stopway drogi startowej',
    taxilane: 'Pas kołowania',
    taxiway: 'Droga kołowania',
    terminal: 'Terminal lotniczy',
    threshold: 'Próg pasa startowego',
    tower: 'Wieża kontroli lotów',
    windsock: 'Rękaw wiatrowy',
  },

  amenity: {
    exhibition_centre: 'Centrum wystawiennicze',
    letter_box: 'Skrzynka na listy',
    loading_dock: 'Rampa załadunkowa',
    lounger: 'Leżak',
    public_bath: 'Łaźnia publiczna',
    public_building: 'Budynek użyteczności publicznej',
    shelter: {
      shelter_type: {
        picnic_shelter: {
          fireplace: {
            yes: 'Altana piknikowa z kominkiem',
          },
          '*': 'Altana piknikowa',
        },
        '*': 'Schronienie {}',
        basic_hut: 'Prosta chata',
        changing_rooms: 'Przebieralnia',
        field_shelter: 'Polowe schronienie',
        lean_to: 'Schronienie z otwartą ścianą',
        public_transport: 'Wiata przystankowa',
        rock_shelter: 'Schronisko skalne',
        sun_shelter: 'Zadaszenie przeciwsłoneczne',
        weather_shelter: 'Schronienie przed pogodą',
      },
      '*': 'Schronienie',
    },

    social_facility: {
      social_facility: {
        ambulatory_care: 'Opieka ambulatoryjna',
        assisted_living: 'Mieszkanie wspomagane',
        clothing_bank: 'Bank odzieży',
        day_care: 'Opieka dzienna',
        food_bank: 'Bank żywności',
        group_home: 'Dom grupowy',
        hospice: 'Hospicjum',
        nursing_home: 'Dom opieki',
        shelter: 'Schronisko',
        soup_kitchen: 'Jadłodajnia',
        workshop: 'Warsztat',
      },
      '*': 'Placówka socjalna',
    },

    vending_machine: {
      vending: {
        bicycle_tube: 'Automat z dętkami rowerowymi',
        bread: 'Automat z chlebem',
        bottle_return: 'Automat do zwrotu butelek',
        candles: 'Automat ze świecami',
        chewing_gums: 'Automat z gumami do żucia',
        cigarettes: 'Automat z papierosami',
        coffee: 'Automat z kawą',
        condoms: 'Automat z prezerwatywami',
        drinks: 'Automat z napojami',
        elongated_coin: 'Automat z monetami pamiątkowymi',
        eggs: 'Automat z jajkami',
        excrement_bags: 'Automat z woreczkami na odchody',
        food: 'Automat z jedzeniem',
        fuel: 'Automat z paliwem',
        gas: 'Automat z gazem',
        ice_cream: 'Automat z lodami',
        ice_cubes: 'Automat z kostkami lodu',
        milk: 'Automat z mlekiem',
        movies: 'Automat z filmami',
        newspapers: 'Automat z gazetami',
        parking_tickets: 'Automat biletów parkingowych',
        pizza: 'Automat z pizzą',
        public_transport_tickets: 'Automat biletów komunikacji miejskiej',
        stamps: 'Automat ze znaczkami',
        sweets: 'Automat ze słodyczami',
        water: 'Automat z wodą',
      },
      '*': 'Automat',
    },

    '*': '{}',

    animal_breeding: 'Hodowla zwierząt',
    animal_shelter: 'Schronisko dla zwierząt',
    arts_centre: 'Centrum sztuki',
    atm: 'Bankomat',
    bank: 'Bank',
    bar: 'Bar',
    bbq: 'Grill',
    bench: 'Ławka',
    bicycle_parking: 'Parking rowerowy',
    bicycle_rental: 'Wypożyczalnia rowerów',
    bicycle_repair_station: 'Stacja naprawy rowerów',
    biergarten: 'Ogródek piwny',
    brothel: 'Dom publiczny',
    bureau_de_change: 'Kantor',
    bus_station: 'Dworzec autobusowy',
    cafe: 'Kawiarnia',
    car_rental: 'Wypożyczalnia samochodów',
    car_wash: 'Myjnia samochodowa',
    casino: 'Kasyno',
    charging_station: 'Stacja ładowania',
    childcare: 'Opieka nad dziećmi',
    cinema: 'Kino',
    clinic: 'Przychodnia',
    clock: 'Zegar',
    college: 'Kolegium',
    community_centre: 'Centrum społecznościowe',
    compressed_air: 'Sprężone powietrze',
    courthouse: 'Sąd',
    dentist: 'Dentysta',
    device_charging_station: 'Stacja ładowania urządzeń',
    doctors: 'Gabinet lekarski',
    dressing_room: 'Przebieralnia',
    drinking_water: 'Woda pitna',
    driving_school: 'Szkoła jazdy',
    embassy: 'Ambasada',
    events_venue: 'Miejsce wydarzeń',
    fast_food: 'Fast food',
    feeding_place: 'Miejsce karmienia',
    ferry_terminal: 'Terminal promowy',
    fire_station: 'Straż pożarna',
    food_court: 'Strefa gastronomiczna',
    fountain: 'Fontanna',
    fuel: 'Stacja paliw',
    funeral_hall: 'Dom pogrzebowy',
    gambling: 'Hazard',
    game_feeding: 'Karmisko',
    grave_yard: 'Cmentarz',
    grit_bin: 'Pojemnik na piasek',
    hospital: 'Szpital',
    hunting_stand: 'Ambona myśliwska',
    ice_cream: 'Lody',
    kindergarten: 'Przedszkole',
    language_school: 'Szkoła językowa',
    library: 'Biblioteka',
    marketplace: 'Targowisko',
    monastery: 'Klasztor',
    money_transfer: 'Przelew pieniędzy',
    motorcycle_parking: 'Parking dla motocykli',
    motorcycle_rental: 'Wypożyczalnia motocykli',
    nightclub: 'Klub nocny',
    parcel_locker: 'Paczkomat',
    parking: 'Parking',
    parking_entrance: 'Wjazd na parking',
    parking_space: 'Miejsce parkingowe',
    pharmacy: 'Apteka',
    place_of_mourning: 'Miejsce żałoby',
    place_of_worship: 'Miejsce kultu',
    planetarium: 'Planetarium',
    police: 'Policja',
    post_box: 'Skrzynka pocztowa',
    post_office: 'Poczta',
    prison: 'Więzienie',
    pub: 'Pub',
    public_bookcase: 'Publiczna biblioteczka',
    ranger_station: 'Posterunek strażników',
    recycling: 'Recykling',
    restaurant: 'Restauracja',
    school: 'Szkoła',
    shower: 'Prysznic',
    ski_rental: 'Wypożyczalnia nart',
    smoking_area: 'Strefa dla palących',
    social_centre: 'Centrum socjalne',
    stripclub: 'Klub ze striptizem',
    studio: 'Studio',
    taxi: 'Taksówka',
    telephone: 'Telefon',
    theatre: 'Teatr',
    toilets: 'Toaleta',
    townhall: 'Ratusz',
    traffic_park: 'Miasteczko ruchu drogowego',
    trolley_bay: 'Stanowisko na wózki',
    university: 'Uniwersytet',
    vacuum_cleaner: 'Odkurzacz',
    vehicle_inspection: 'Kontrola pojazdów',
    veterinary: 'Weterynarz',
    waste_basket: 'Kosz na śmieci',
    waste_disposal: 'Utylizacja odpadów',
    water_point: 'Punkt poboru wody',
    watering_place: 'Wodopój',
  },

  barrier: {
    '*': 'Bariera {}',
    block: 'Blok',
    bollard: 'Słupek',
    border_control: 'Kontrola graniczna',
    cable_barrier: 'Bariera kablowa',
    chain: 'Łańcuch',
    city_wall: 'Mur miejski',
    ditch: 'Rów (bariera)',
    entrance: 'Wejście',
    fence: 'Ogrodzenie',
    gate: 'Brama',
    guard_rail: 'Bariera ochronna',
    handrail: 'Poręcz',
    hedge: 'Żywopłot',
    kerb: 'Krawężnik',
    lift_gate: 'Szlaban',
    rope: 'Lina',
    sliding_gate: 'Brama przesuwna',
    swing_gate: 'Brama uchylna',
    turnstile: 'Kołowrót',
    wall: 'Mur',
    retaining_wall: 'Mur oporowy',
  },

  boundary: {
    aboriginal_lands: 'Terytorium rdzennych mieszkańców',
    administrative: {
      admin_level: {
        '2': 'Państwo',
        '3': 'Region',
        '4': 'Okręg',
        '5': 'Prowincja',
        '6': 'Miasto',
        '7': 'Region',
        '8': 'Powiat',
        '9': 'Wieś',
        '10': 'Obszar katastralny',
      },
      '*': 'Region administracyjny',
    },
    '*': 'Region',
    cadastral: 'Granica katastralna',
    census: 'Obwód spisowy',
    forest_compartment: 'Oddział leśny',
    forest_planning: 'Jednostka urządzania lasu',
    'geomorphological-unit': 'Jednostka geomorfologiczna',
    health: 'Okręg zdrowotny',
    local_authority: 'Obszar samorządu lokalnego',
    maritime: 'Granica morska',
    marker: 'Kamień graniczny',
    national_park: 'Park narodowy',
    political: 'Okręg wyborczy',
    postal_code: 'Obszar kodu pocztowego',
    protected_area: 'Obszar chroniony',
    religious_administration: 'Okręg administracji kościelnej',
    statistical: 'Obszar statystyczny',
    water_protection_area: 'Strefa ochronna ujęcia wody',
  },

  building: {
    '*': {
      '*': 'Budynek',

      abandoned: {
        yes: 'Opuszczony budynek',
      },

      disused: {
        yes: 'Nieużywany budynek',
      },

      ruins: {
        yes: 'Ruiny budynku',
      },
    },

    agricultural: 'Budynek rolniczy',
    allotment_house: 'Altana działkowa',
    apartments: 'Apartamenty (blok)',
    barn: 'Stodoła',
    boathouse: 'Hangar dla łodzi',
    bungalow: 'Bungalow',
    bunker: 'Bunkier',
    cabin: 'Domek',
    carport: 'Wiata garażowa',
    cathedral: 'Katedra',
    chapel: 'Kaplica',
    church: 'Kościół',
    civic: 'Budynek publiczny',
    collapsed: 'Zawalony budynek',
    college: 'Budynek szkoły policealnej',
    commercial: 'Budynek komercyjny',
    construction: 'Budowa budynku',
    container: 'Budynek kontenerowy',
    cowshed: 'Obora',
    detached: 'Dom wolnostojący',
    dormitory: 'Akademik',
    entrance: 'Wejście do budynku',
    farm_auxiliary: 'Pomocniczy budynek gospodarstwa',
    farm: 'Gospodarstwo',
    fire_station: 'Budynek straży pożarnej',
    garage: 'Garaż',
    garages: 'Garaże',
    government: 'Budynek rządowy',
    grandstand: 'Trybuna',
    greenhouse: 'Szklarnia',
    hangar: 'Hangar',
    hayloft: 'Stodoła na siano',
    historic: 'Budynek zabytkowy',
    hospital: 'Budynek szpitalny',
    hotel: 'Budynek hotelowy',
    house: 'Dom prywatny',
    houseboat: 'Dom na wodzie',
    hut: 'Chatka',
    industrial: 'Budynek przemysłowy',
    kindergarten: 'Budynek przedszkola',
    kiosk: 'Kiosk',
    manufacture: 'Budynek fabryczny',
    mosque: 'Meczet',
    office: 'Budynek biurowy',
    outbuilding: 'Budynek gospodarczy',
    parking: 'Budynek parkingowy',
    pavilion: 'Pawilon',
    public: 'Budynek publiczny',
    residential: 'Budynek mieszkalny',
    retail: 'Budynek handlowy',
    roof: 'Dach',
    ruins: 'Ruiny budynku',
    school: 'Budynek szkoły',
    semidetached_house: 'Bliźniak',
    service: 'Budynek usługowy',
    shed: 'Szopa',
    shrine: 'Kapliczka',
    silo: 'Silos',
    sports_centre: 'Budynek centrum sportowego',
    sports_hall: 'Hala sportowa',
    stable: 'Stajnia',
    static_caravan: 'Dom mobilny, przyczepa kempingowa',
    storage_tank: 'Zbiornik magazynowy',
    sty: 'Chlew',
    supermarket: 'Budynek supermarketu',
    synagogue: 'Synagoga',
    temple: 'Świątynia',
    tent: 'Stały namiot',
    terrace: 'Szeregowiec',
    toilets: 'Budynek toalet',
    train_station: 'Stacja kolejowa',
    transformer_tower: 'Wieża transformatorowa',
    transportation: 'Budynek transportu',
    university: 'Budynek uniwersytetu',
    warehouse: 'Magazyn',
    yes: 'Niezidentyfikowany budynek',
    abandoned: 'Opuszczony budynek',
    disused: 'Nieużywany budynek',
    stadium: 'Budynek stadionu',
  },

  club: {
    '*': 'Klub',
    automobile: 'Automobilklub',
    charity: 'Klub charytatywny',
    culture: 'Klub kulturalny',
    fishing: 'Klub wędkarski',
    hunting: 'Klub myśliwski',
    music: 'Klub muzyczny',
    nature: 'Klub przyrodniczy',
    scout: 'Drużyna harcerska',
    social: 'Klub towarzyski',
    sport: 'Klub sportowy',
    veterans: 'Klub weteranów',
  },
  healthcare: {
    '*': 'Placówka zdrowia',
    alternative: 'Medycyna alternatywna',
    audiologist: 'Audiolog',
    blood_donation: 'Punkt krwiodawstwa',
    centre: 'Ośrodek zdrowia',
    clinic: 'Przychodnia',
    counselling: 'Poradnia',
    dentist: 'Dentysta',
    dialysis: 'Stacja dializ',
    doctor: 'Gabinet lekarski',
    hospital: 'Szpital',
    laboratory: 'Laboratorium medyczne',
    midwife: 'Położna',
    nurse: 'Opieka pielęgniarska',
    optometrist: 'Optometrysta',
    pharmacy: 'Apteka',
    physiotherapist: 'Fizjoterapeuta',
    podiatrist: 'Podolog',
    psychotherapist: 'Psychoterapeuta',
    rehabilitation: 'Ośrodek rehabilitacji',
    speech_therapist: 'Logopeda',
  },
  fitness_station: {
    air_walker: 'Air walker',
    balance_beam: 'Równoważnia (siłownia)',
    box: 'Skrzynia do wyskoków',
    elliptical_trainer: 'Orbitrek',
    exercise_bike: 'Rower stacjonarny',
    horizontal_bar: 'Drążek (siłownia)',
    horizontal_ladder: 'Drabinka pozioma',
    hyperextension: 'Ławka do wyprostów',
    parallel_bars: 'Poręcze',
    'push-up': 'Poręcze do pompek',
    rings: 'Kółka gimnastyczne',
    rower: 'Wioślarz',
    sign: 'Tablica siłowni plenerowej',
    'sit-up': 'Ławka do brzuszków',
    stairs: 'Schody treningowe',
    wall_bars: 'Drabinka gimnastyczna',
    yes: 'Urządzenie siłowni plenerowej',
  },
  highway: {
    '*': 'Droga {}',
    bridleway: 'Droga jeździecka',
    bus_stop: 'Przystanek autobusowy',
    busway: 'Buspas',
    construction: 'Droga w budowie',
    corridor: 'Korytarz w budynku',
    crossing: 'Przejście dla pieszych',
    cycleway: 'Droga rowerowa',
    elevator: 'Winda',
    emergency_access_point: 'Punkt ratunkowy',
    emergency_bay: 'Zatoka awaryjna',
    escape: 'Awaryjny pas ucieczkowy',
    footway: 'Chodnik',
    give_way: 'Ustąp pierwszeństwa',
    hitchhiking: 'Miejsce na autostop',
    ladder: 'Drabina',
    living_street: 'Strefa zamieszkania',
    milestone: 'Kilometrowskaz',
    mini_roundabout: 'Mini rondo',
    motorway: 'Autostrada',
    motorway_junction: 'Węzeł autostradowy',
    motorway_link: 'Zjazd na autostradę',
    passing_place: 'Mijanka',
    path: {
      '*': 'Ścieżka',
      foot: {
        designated: {
          bicycle: {
            designated: 'Wspólna droga pieszo-rowerowa',
          },
        },
      },
    },
    pedestrian: 'Strefa piesza',
    piste: 'Trasa narciarska',
    platform: 'Peron',
    primary: 'Droga główna',
    primary_link: 'Zjazd z drogi głównej',
    priority: 'Znak pierwszeństwa',
    proposed: 'Planowana droga',
    raceway: 'Tor wyścigowy',
    residential: 'Ulica mieszkalna',
    rest_area: 'Miejsce odpoczynku',
    road: 'Droga nieokreślonego typu',
    secondary: 'Droga drugorzędna',
    secondary_link: 'Zjazd z drogi drugorzędnej',
    service: {
      service: {
        '*': 'Droga serwisowa {}',
        alley: 'Zaułek',
        bus: 'Droga dla komunikacji publicznej',
        'drive-through': 'Przejazd dla samochodów',
        driveway: 'Podjazd',
        emergency_access: 'Droga pożarowa',
        parking_aisle: 'Droga na parkingu',
      },
      '*': 'Droga serwisowa / dojazdowa',
    },
    services: 'Miejsce obsługi podróżnych',
    speed_camera: 'Fotoradar',
    speed_display: 'Wyświetlacz prędkości',
    steps: 'Schody',
    stop: 'Znak stop',
    street_lamp: 'Latarnia uliczna',
    tertiary: 'Droga trzeciorzędna',
    tertiary_link: 'Zjazd z drogi trzeciorzędnej',
    toll_gantry: 'Brama poboru opłat',
    track: {
      tracktype: {
        grade1: 'Utwardzona droga leśna',
        grade2: 'Przeważnie utwardzona droga leśna',
        grade3: 'Słabiej utwardzona droga leśna',
        grade4: 'Droga leśna dla traktorów lub podobnych pojazdów',
        grade5: 'Słabo widoczna droga leśna',
      },
      '*': 'Droga leśna / polna',
    },
    traffic_calming: 'Element uspokojenia ruchu',
    traffic_island: 'Wysepka drogowa',
    traffic_mirror: 'Lustro drogowe',
    traffic_sign: 'Znak drogowy',
    traffic_signals: 'Sygnalizacja świetlna',
    trailhead: 'Początek szlaku',
    trunk: 'Droga ekspresowa',
    trunk_link: 'Zjazd z drogi ekspresowej',
    turning_circle: 'Plac do zawracania',
    turning_loop: 'Pętla do zawracania',
    unclassified: 'Droga nieklasyfikowana',
    via_ferrata: 'Via ferrata',
  },

  historic: {
    battlefield: 'Pole bitwy',
    bomb_crater: 'Lej po bombie',
    bunker: 'Historyczny bunkier',
    dome: 'Historyczna kopuła',
    quarry: 'Historyczny kamieniołom',
    railway: 'Historyczna kolej',
    railway_station: 'Historyczny dworzec kolejowy',
    roman_road: 'Droga rzymska',
    ruins: {
      ruins: {
        castle: 'Ruiny zamku',
      },
      '*': 'Ruiny',
    },

    '*': 'Obiekt historyczny',
    archaeological_site: 'Stanowisko archeologiczne',
    castle: 'Zamek',
    church: 'Zabytkowy kościół',
    city_gate: 'Brama miejska',
    manor: 'Dwór',
    memorial: 'Pomnik',
    monastery: 'Klasztor',
    monument: 'Monument',
    tomb: 'Grobowiec',
    tower: 'Historyczna wieża',
    wayside_cross: 'Przydrożny krzyż',
    wayside_shrine: 'Przydrożna kapliczka',
    aircraft: 'Historyczny samolot',
    boundary_stone: 'Historyczny kamień graniczny',
    building: 'Historyczny budynek',
    cannon: 'Historyczna armata',
    charcoal_pile: 'Miejsce po mielerzu',
    citywalls: 'Mury miejskie',
    fort: 'Fort',
    heritage: 'Obiekt dziedzictwa',
    hollow_way: 'Droga wąwozowa',
    house: 'Historyczny dom',
    milestone: 'Historyczny kamień milowy',
    mine: 'Historyczna kopalnia',
    mine_shaft: 'Historyczny szyb kopalniany',
    shieling: 'Sezonowa chata pasterska',
    stone: 'Historyczny kamień',
    tree_shrine: 'Kapliczka na drzewie',
    wreck: 'Wrak',
    yes: 'Obiekt historyczny',
  },

  junction: {
    '*': 'Węzeł drogowy',
    circular: 'Skrzyżowanie okrężne',
    intersection: 'Skrzyżowanie',
    jughandle: 'Jughandle',
    roundabout: 'Rondo',
  },
  landuse: {
    '*': '{}',
    allotments: 'Ogródki działkowe',
    animal_keeping: 'Hodowla zwierząt',
    apiary: 'Teren pasieki',
    aquaculture: 'Akwakultura',
    basin: 'Zbiornik',
    brownfield: 'Teren poprzemysłowy',
    cemetery: 'Cmentarz',
    churchyard: 'Teren przykościelny',
    civic: 'Teren publiczny',
    civic_admin: 'Teren administracyjny',
    commercial: 'Strefa handlowa',
    conservation: 'Obszar chroniony',
    construction: 'Plac budowy',
    culture: 'Teren kultury',
    depot: 'Zajezdnia',
    education: 'Strefa edukacyjna',
    emergency: 'Teren służb ratunkowych',
    fairground: 'Teren targowy',
    farm: 'Grunt rolny',
    farmland: 'Ziemia uprawna',
    farmyard: 'Podwórze',
    flowerbed: 'Klomb',
    forest: 'Las',
    forestry: 'Teren leśny',
    garages: 'Garaże',
    garden: 'Teren ogrodu',
    grass: 'Trawa',
    greenery: 'Zieleń',
    greenfield: 'Teren pod zabudowę',
    greenhouse_horticulture: 'Uprawa szklarniowa',
    harbour: 'Teren portowy',
    healthcare: 'Teren opieki zdrowotnej',
    highway: 'Teren drogi',
    houseboat: 'Przystań domów na wodzie',
    industrial: 'Strefa przemysłowa',
    institutional: 'Teren instytucji',
    landfill: 'Wysypisko',
    logging: 'Wyręby',
    meadow: 'Łąka',
    military: 'Obszar wojskowy',
    mine_spoils: 'Hałda',
    orchard: 'Sad',
    paddock: 'Wybieg dla zwierząt',
    peat_cutting: 'Wydobycie torfu',
    pedestrian: 'Obszar pieszy',
    piste: 'Teren stoku narciarskiego',
    plant_nursery: 'Szkółka roślin',
    plantation: 'Plantacja',
    quarry: 'Kamieniołom',
    railway: 'Obszar kolejowy',
    recreation_ground: 'Teren rekreacyjny',
    religious: 'Teren sakralny',
    reservoir: 'Zbiornik wodny',
    residential: 'Teren mieszkalny',
    retail: 'Strefa handlowa',
    salt_pond: 'Warzelnia soli',
    school: 'Teren szkoły',
    shrubs: 'Krzewy',
    static_caravan: 'Osiedle domków mobilnych',
    storage: 'Teren składowy',
    tourism: 'Teren turystyczny',
    traffic_island: 'Teren wysepki drogowej',
    tree_pit: 'Misa drzewa',
    village_green: 'Zieleń wiejska',
    vineyard: 'Winnica',
    wasteland: 'Nieużytki',
    winter_sports: 'Sporty zimowe',
  },

  leisure: {
    '*': '{}',

    common: 'Teren wspólny',
    hot_tub: 'Jacuzzi',
    indoor_play: 'Sala zabaw',
    picnic_table: {
      covered: {
        yes: 'Zadaszony stół piknikowy',
        no: 'Niezadaszony stół piknikowy',
      },
      '*': 'Stół piknikowy',
    },

    recreation_ground: 'Teren rekreacyjny',
    sauna: {
      sauna: {
        aroma: 'Sauna aromatyczna',
        dry: 'Sauna sucha',
        hanjeungmak: 'Hanjeungmak (sauna koreańska)',
        hot: 'Sauna fińska',
        infrared: 'Sauna na podczerwień',
        smoke: 'Sauna dymna (fińska)',
        steam: 'Sauna parowa (łaźnia turecka)',
      },

      '*': 'Sauna',
    },

    pitch: 'Boisko',
    bleachers: 'Trybuny',
    escape_game: 'Escape game',
    hackerspace: 'Hackerspace',
    ice_rink: 'Lodowisko',
    marina: 'Marina',
    miniature_golf: 'Minigolf',
    dog_park: 'Park dla psów',
    firepit: 'Miejsce na ognisko',
    fishing: 'Miejsce do wędkowania',
    fitness_centre: 'Centrum fitness',
    fitness_station: 'Stacja fitness',
    garden: 'Ogród',
    golf_course: 'Pole golfowe',
    horse_riding: 'Jazda konna',
    nature_reserve: 'Rezerwat przyrody',
    park: 'Park',
    playground: 'Plac zabaw',
    schoolyard: 'Boisko szkolne',
    sports_centre: 'Centrum sportowe',
    sports_hall: 'Hala sportowa',
    stadium: 'Stadion',
    swimming_pool: 'Basen',
    track: {
      '*': 'Tor',
      sport: {
        cycling: 'Tor kolarski',
        equestrian: 'Tor jeździecki',
        horse_racing: 'Tor wyścigów konnych',
      },
    },
    water_park: 'Park wodny',
    adult_gaming_centre: 'Salon gier dla dorosłych',
    amusement_arcade: 'Salon gier',
    bandstand: 'Estrada',
    bathing_place: 'Miejsce kąpieli',
    beach_resort: 'Ośrodek plażowy',
    bird_hide: 'Czatownia ornitologiczna',
    bowling_alley: 'Tor bowlingowy',
    dance: 'Miejsce tańca',
    disc_golf_course: 'Pole do disc golfa',
    high_ropes_course: 'Park linowy',
    outdoor_seating: 'Miejsca siedzące na zewnątrz',
    resort: 'Ośrodek wypoczynkowy',
    slipway: 'Pochylnia dla łodzi',
    summer_camp: 'Obóz letni',
    sunbathing: 'Strefa opalania',
    swimming_area: 'Strefa pływania',
    tanning_salon: 'Solarium',
    trampoline_park: 'Park trampolin',
    wildlife_hide: 'Czatownia przyrodnicza',
  },

  lock: {
    '*': 'Śluza',
  },
  man_made: {
    breakwater: 'Falochron',
    quay: 'Nabrzeże',
    tower: {
      'tower:type': {
        bell_tower: 'Dzwonnica',
        communication: 'Wieża telekomunikacyjna',
        cooling: 'Wieża chłodnicza',
        observation: 'Wieża widokowa',
        climbing: 'Wieża wspinaczkowa',
        clock: 'Wieża zegarowa',
        defensive: 'Wieża obronna',
        diving: 'Wieża do skoków',
        hose: 'Wieża suszenia węży',
        lighting: 'Wieża oświetleniowa',
        minaret: 'Minaret',
        monitoring: 'Wieża monitoringu',
        pagoda: 'Wieża pagoda',
        radar: 'Wieża radarowa',
        siren: 'Wieża z syreną',
        watchtower: 'Wieża strażnicza',
      },
      '*': 'Wieża',
    },

    '*': '{}',

    adit: {
      '*': 'Sztolnia',

      disused: {
        yes: 'Nieużywana sztolnia',
      },
    },

    antenna: 'Antena',
    beacon: 'Latarnia',
    beehive: 'Ul',
    bridge: 'Most',
    bunker_silo: 'Silos bunkrowy',
    cairn: 'Stos kamieni',
    cellar_entrance: 'Wejście do piwnicy',
    chimney: 'Komin',
    clearcut: 'Wycinka',
    communications_tower: 'Wieża telekomunikacyjna',
    cooling_tower: 'Wieża chłodnicza',
    crane: 'Dźwig',
    cross: 'Krzyż',
    cutline: 'Linia wycinki',
    dyke: 'Wał przeciwpowodziowy',
    embankment: 'Nasyp',
    flagpole: 'Maszt flagowy',
    "forester's_lodge": 'Leśniczówka',
    gasometer: 'Gazomierz',
    goods_conveyor: 'Przenośnik towarów',
    groyne: 'Falochron',
    lighthouse: 'Latarnia morska',
    manhole: 'Wpust kanalizacyjny',

    mast: {
      '*': 'Maszt',

      'tower:type': {
        clock: 'Maszt zegarowy',
        communication: 'Maszt telekomunikacyjny',
        lighting: 'Maszt oświetleniowy',
        monitoring: 'Maszt monitoringu',
        radar: 'Maszt radarowy',
        siren: 'Maszt z syreną',
      },
    },

    mineshaft: {
      '*': 'Szyb kopalniany',

      disused: {
        yes: 'Nieużywany szyb kopalniany',
      },
    },

    monitoring_station: 'Stacja monitoringu',
    nesting_site: 'Miejsce gniazdowania',
    observatory: 'Obserwatorium',
    pier: 'Pirs',

    pipeline: {
      '*': 'Rurociąg',

      location: {
        underground: 'Rurociąg podziemny',
        underwater: 'Rurociąg podwodny',
      },
    },

    reservoir_covered: 'Zbiornik kryty',
    silo: 'Silos',
    snow_cannon: 'Armatka śnieżna',
    spoil_heap: 'Hałda odpadów',
    spring_box: 'Skrzynka źródlana',
    storage_tank: 'Zbiornik magazynowy',
    street_cabinet: 'Szafka uliczna',
    surveillance: 'Monitoring',
    survey_point: 'Punkt pomiarowy',
    telescope: 'Teleskop',
    tunnel: 'Tunel techniczny',
    utility_pole: 'Słup użyteczności publicznej',
    wastewater_plant: 'Oczyszczalnia ścieków',
    water_tap: 'Kran wodny',
    water_tower: 'Wieża ciśnień',
    water_well: 'Studnia',
    water_works: 'Ujęcie wody',
    watermill: 'Młyn wodny',
    windmill: 'Młyn wiatrowy',
    works: 'Zakład',
    apiary: 'Pasieka',
    pumping_station: 'Stacja pomp',
  },

  natural: {
    arete: 'Grań',
    cape: 'Przylądek',
    crevasse: 'Szczelina lodowcowa',
    dune: 'Wydma',
    grass: 'Trawnik',
    hill: 'Wzgórze',
    isthmus: 'Przesmyk',
    land: 'Ląd',
    landform: 'Forma terenu',
    peninsula: 'Półwysep',
    plain: 'Równina',
    reef: 'Rafa',
    shoal: 'Mielizna',
    shrubbery: 'Zarośla ozdobne',
    spring: {
      drinking_water: {
        yes: 'Źródło pitnej wody',
        no: 'Źródło nie do picia',
      },

      refitted: {
        yes: 'Przerobione źródło',
        no: 'Nieprzerobione źródło',
      },

      '*': 'Źródło',

      intermittent: {
        yes: 'Źródło okresowe',
      },

      seasonal: {
        yes: 'Źródło sezonowe',
      },

      water_characteristic: {
        '*': 'Źródło mineralne',
      },
    },
    strait: 'Cieśnina',
    tree: {
      protected: {
        yes: 'Drzewo chronione',
      },
      denotation: {
        natural_monument: 'Drzewo pomnikowe',
        landmark: 'Drzewo charakterystyczne',
        avenue: 'Drzewo alei',
        urban: 'Drzewo miejskie',
        agricultural: 'Drzewo gospodarcze',
      },
      '*': 'Drzewo',
    },
    '*': '{}',
    arch: 'Łuk skalny',
    bare_rock: 'Goła skała',
    basin: 'Kotlina',
    bay: 'Zatoka',
    beach: 'Plaża',
    birds_nest: 'Gniazdo ptaków',
    cave_entrance: 'Jaskinia',
    cliff: 'Skała',
    earth_bank: 'Nasyp ziemny',
    fell: 'Błotnisty teren',
    geyser: 'Gejzer',
    glacier: 'Lodowiec',
    grassland: 'Teren trawiasty',
    gully: 'Wąwóz',
    heath: 'Wrzosowisko',
    hot_spring: 'Gorące źródło',
    landslide: 'Osuwisko',
    mountain_range: 'Pasmo górskie',
    mud: 'Błoto',
    peak: 'Szczyt',
    plateau: 'Płaskowyż',
    ridge: 'Grzbiet',
    rock: 'Skała',
    saddle: 'Przełęcz',
    sand: 'Piasek',
    scree: 'Osuwisko skalne',
    scrub: 'Zarośla',
    shingle: 'Żwir',
    shrub: 'Krzew',
    sinkhole: 'Lej krasowy',
    stone: 'Kamień',
    tree_group: 'Grupa drzew',
    tree_row: 'Szpaler drzew',
    tree_stump: 'Pniak',
    valley: 'Dolina',
    water: {
      '*': 'Zbiornik wodny',

      water: {
        basin: 'Zbiornik',
        canal: 'Kanał',
        ditch: 'Rów',
        drain: 'Rów odwadniający',
        fish_pass: 'Przepławka',
        lagoon: 'Laguna',
        lake: 'Jezioro',
        moat: 'Fosa',
        oxbow: 'Starorzecze',
        pond: 'Staw',
        reflecting_pool: 'Basen lustrzany',
        reservoir: 'Zbiornik retencyjny',
        river: 'Rzeka',
        salt_pond: 'Staw solny',
        stream: 'Potok',
        stream_pool: 'Rozlewisko potoku',
        wastewater: 'Zbiornik ścieków',
      },
    },
    wetland: {
      '*': 'Torfowisko',
      wetland: {
        bog: 'Torfowisko wysokie',
        fen: 'Torfowisko niskie',
        mangrove: 'Namorzyny',
        marsh: 'Mokradło',
        reedbed: 'Trzcinowisko',
        swamp: 'Bagno',
        wet_meadow: 'Podmokła łąka',
      },
    },
    wood: 'Las',
    volcano: 'Wulkan',
  },
  obstacle: {
    '*': 'Przeszkoda {}',
    vegetation: 'Gęsta roślinność',
    fallen_tree: 'Powalone drzewo / drzewa',
    unevenness: 'Nierówność',
    precipice: 'Urwisko',
    heap: 'Sterta',
    hole: 'Dziura',
    mud: 'Błoto',
  },
  office: {
    '*': 'Biuro',
    accountant: 'Biuro rachunkowe',
    advertising_agency: 'Agencja reklamowa',
    architect: 'Biuro architektoniczne',
    association: 'Stowarzyszenie',
    company: 'Biuro firmy',
    consulting: 'Firma doradcza',
    coworking: 'Przestrzeń coworkingowa',
    diplomatic: 'Przedstawicielstwo dyplomatyczne',
    educational_institution: 'Instytucja edukacyjna',
    employment_agency: 'Agencja pracy',
    energy_supplier: 'Dostawca energii',
    estate_agent: 'Biuro nieruchomości',
    financial: 'Usługi finansowe',
    financial_advisor: 'Doradca finansowy',
    forestry: 'Nadleśnictwo',
    government: 'Urząd',
    insurance: 'Ubezpieczenia',
    it: 'Firma informatyczna',
    lawyer: 'Kancelaria adwokacka',
    logistics: 'Firma logistyczna',
    newspaper: 'Redakcja gazety',
    ngo: 'Organizacja pozarządowa',
    notary: 'Notariusz',
    political_party: 'Partia polityczna',
    property_management: 'Zarządzanie nieruchomościami',
    religion: 'Urząd kościelny',
    research: 'Placówka badawcza',
    security: 'Firma ochroniarska',
    tax_advisor: 'Doradca podatkowy',
    telecommunication: 'Firma telekomunikacyjna',
    travel_agent: 'Biuro podróży',
    union: 'Biuro związku zawodowego',
    water_utility: 'Wodociągi',
  },
  place: {
    '*': 'Miejsce {}',
    allotments: 'Osiedle działkowe',
    archipelago: 'Archipelag',
    borough: 'Dzielnica miasta',
    cadastral_community: 'Obręb ewidencyjny',
    city: 'Miasto',
    city_block: 'Kwartał zabudowy',
    civil_parish: 'Parafia cywilna',
    country: 'Kraj',
    county: 'Hrabstwo',
    croft: 'Zagroda',
    district: 'Powiat',
    farm: 'Gospodarstwo',
    hamlet: 'Przysiółek',
    island: 'Wyspa',
    islet: 'Wysepka',
    isolated_dwelling: 'Samotne gospodarstwo',
    locality: 'Miejscowość',
    municipality: 'Gmina',
    neighbourhood: 'Osiedle',
    ocean: 'Ocean',
    plot: 'Działka',
    province: 'Prowincja',
    quarter: 'Kwartał',
    region: 'Region',
    sea: 'Morze',
    square: 'Plac',
    state: 'Stan',
    subdivision: 'Część miejscowości',
    suburb: 'Przedmieście',
    town: 'Miasteczko',
    township: 'Gmina (township)',
    village: 'Wieś',
    // Not real OSM tags: Nominatim classifies address objects, address
    // interpolations and computed postcode areas this way, and Photon falls back
    // to `yes` for a class it cannot use. See doc/photon-geocoder.md.
    house: 'Adres',
    house_number: 'Adres',
    postcode: 'Kod pocztowy',
    yes: 'Miejsce',
  },

  playground: {
    '*': 'Urządzenie zabawowe {}',
    activitypanel: 'Panel zabawowy',
    aerialrotator: 'Karuzela podwieszana',
    agility_trail: 'Tor sprawnościowy',
    baby_swing: 'Huśtawka dla maluchów',
    balancebeam: 'Równoważnia',
    basketrotator: 'Obrotowy kosz',
    basketswing: 'Huśtawka bocianie gniazdo',
    bridge: 'Mostek zabawowy',
    climbing: 'Urządzenie wspinaczkowe',
    climbing_pole: 'Słup do wspinania',
    climbing_slope: 'Skarpa wspinaczkowa',
    climbingframe: 'Drabinka do wspinania',
    climbingwall: 'Ścianka wspinaczkowa',
    cushion: 'Poduszka do skakania',
    exercise: 'Urządzenie do ćwiczeń',
    hammock: 'Hamak',
    hopscotch: 'Klasy na placu zabaw',
    horizontal_bar: 'Drążek',
    ladder: 'Drabinka zabawowa',
    platform: 'Platforma zabawowa',
    playhouse: 'Domek zabawowy',
    pump: 'Pompa zabawowa',
    rope_traverse: 'Przeprawa linowa',
    roundabout: 'Karuzela zabawowa',
    sandpit: 'Piaskownica',
    seesaw: 'Huśtawka ważka',
    sledding: 'Górka saneczkowa',
    slide: 'Zjeżdżalnia',
    spinner: 'Kręciołek',
    splash_pad: 'Wodny plac zabaw',
    spring_board: 'Deska sprężynowa',
    springy: 'Bujak sprężynowy',
    stepping_stone: 'Kamienie do przeskakiwania',
    steps: 'Schodki zabawowe',
    structure: 'Zestaw zabawowy',
    swing: 'Huśtawka',
    teenshelter: 'Wiata dla młodzieży',
    trampoline: 'Trampolina',
    tunnel_tube: 'Tunel zabawowy',
    water: 'Wodny element zabawowy',
    water_channel: 'Zabawowy kanał wodny',
    wobble_bridge: 'Mostek chwiejny',
    youth_bench: 'Ławka dla młodzieży',
    zipwire: 'Tyrolka zabawowa',
  },
  power: {
    '*': '{}',
    cable: 'Kabel elektroenergetyczny',
    cable_distribution: 'Rozdzielnia kablowa',
    cable_distribution_cabinet: 'Szafka rozdzielcza',
    catenary_mast: 'Słup trakcyjny',
    catenary_portal: 'Brama trakcyjna',
    circuit: 'Obwód elektryczny',
    compensator: 'Kompensator mocy biernej',
    connection: 'Połączenie linii elektroenergetycznej',
    converter: 'Przekształtnik',
    generator: {
      '*': 'Generator',
      'generator:source': {
        biofuel: {
          '*': 'Generator energii elektrycznej na biopaliwo',
        },
        biogas: {
          '*': 'Generator energii elektrycznej na biogaz',
        },
        biomass: {
          '*': 'Generator energii elektrycznej na biomasę',
          'generator:method': {
            anaerobic_digestion:
              'Generator energii z beztlenowej fermentacji biomasy',
            combustion: 'Generator energii ze spalania biomasy',
            gasification: 'Generator energii ze zgazowania biomasy',
          },
        },
        coal: {
          '*': 'Generator energii elektrycznej na węgiel',
        },
        diesel: {
          '*': 'Generator energii elektrycznej na olej napędowy',
        },
        gas: {
          '*': 'Generator energii elektrycznej na gaz',
        },
        gasoline: {
          '*': 'Generator energii elektrycznej na benzynę',
        },
        geothermal: {
          '*': 'Generator energii geotermalnej',
        },
        hydro: {
          '*': 'Generator hydroelektryczny',
          'generator:method': {
            'run-of-the-river': 'Przepływowy generator hydroelektryczny',
            'water-pumped-storage':
              'Generator hydroelektryczny szczytowo-pompowy',
            'water-storage': 'Zbiornikowy generator hydroelektryczny',
          },
        },
        nuclear: {
          '*': 'Generator energii jądrowej',
          'generator:method': {
            fission: 'Generator energii jądrowej z rozszczepienia',
            fusion: 'Generator energii jądrowej z syntezy',
          },
        },
        oil: {
          '*': 'Generator energii elektrycznej na olej',
        },
        solar: {
          '*': 'Generator energii słonecznej',
          'generator:method': {
            photovoltaic: 'Generator energii słonecznej fotowoltaiczny',
            thermal: 'Generator energii słonecznej termiczny',
          },
        },
        tidal: {
          '*': 'Generator energii pływowej',
          'generator:method': {
            barrage: 'Generator energii pływowej zaporowy',
            stream: 'Generator energii pływowej prądowy',
          },
        },
        waste: {
          '*': 'Generator energii z odpadów',
          'generator:method': {
            combustion: 'Generator energii ze spalania odpadów',
            gasification: 'Generator energii ze zgazowania odpadów',
          },
        },
        wave: {
          '*': 'Generator energii falowej',
        },
        wind: {
          '*': 'Generator energii wiatrowej',
        },
      },
    },
    heliostat: 'Heliostat',
    insulator: 'Izolator',
    inverter: 'Falownik',
    line: 'Linia energetyczna',
    line_section: 'Odcinek linii elektroenergetycznej',
    minor_cable: 'Mniejszy kabel elektroenergetyczny',
    minor_line: 'Mała linia energetyczna',
    minor_underground_cable: 'Mniejszy kabel podziemny',
    plant: {
      '*': 'Elektrownia',
      'plant:source': {
        biofuel: {
          '*': 'Elektrownia na biopaliwo',
        },
        biogas: {
          '*': 'Elektrownia biogazowa',
        },
        biomass: {
          '*': 'Elektrownia na biomasę',
          'plant:method': {
            anaerobic_digestion:
              'Elektrownia na biomasę z fermentacją beztlenową',
            combustion: 'Elektrownia na biomasę ze spalaniem',
            gasification: 'Elektrownia na biomasę ze zgazowaniem',
          },
        },
        coal: {
          '*': 'Elektrownia węglowa',
        },
        diesel: {
          '*': 'Elektrownia dieslowska',
        },
        gas: {
          '*': 'Elektrownia gazowa',
        },
        gasoline: {
          '*': 'Elektrownia benzynowa',
        },
        geothermal: {
          '*': 'Elektrownia geotermalna',
        },
        hydro: {
          '*': 'Elektrownia wodna',
          'plant:method': {
            'run-of-the-river': 'Przepływowa elektrownia wodna',
            'water-pumped-storage': 'Szczytowo-pompowa elektrownia wodna',
            'water-storage': 'Zbiornikowa elektrownia wodna',
          },
        },
        nuclear: {
          '*': 'Elektrownia jądrowa',
          'plant:method': {
            fission: 'Elektrownia jądrowa rozszczepieniowa',
            fusion: 'Elektrownia jądrowa fuzyjna',
          },
        },
        oil: {
          '*': 'Elektrownia olejowa',
        },
        solar: {
          '*': 'Elektrownia słoneczna',
          'plant:method': {
            photovoltaic: 'Elektrownia fotowoltaiczna',
            thermal: 'Elektrownia słoneczna termiczna',
          },
        },
        tidal: {
          '*': 'Elektrownia pływowa',
          'plant:method': {
            barrage: 'Elektrownia pływowa zaporowa',
            stream: 'Elektrownia pływowa prądowa',
          },
        },
        waste: {
          '*': 'Elektrownia z odpadów',
          'plant:method': {
            combustion: 'Elektrownia ze spalania odpadów',
            gasification: 'Elektrownia ze zgazowania odpadów',
          },
        },
        wave: {
          '*': 'Elektrownia falowa',
        },
        wind: {
          '*': 'Elektrownia wiatrowa',
        },
      },
    },
    pole: 'Słup energetyczny',
    portal: 'Portal linii elektroenergetycznej',
    roof_pole: 'Słup dachowy',
    substation: 'Stacja transformatorowa',
    switch: 'Odłącznik',
    switchgear: 'Rozdzielnica',
    terminal: 'Zakończenie linii elektroenergetycznej',
    tower: 'Wieża energetyczna',
    transformer: 'Transformator',
    transition: 'Przejście linii w kabel',
  },

  public_transport: {
    platform: 'Peron',
    station: 'Stacja',
    stop_position: 'Miejsce zatrzymania',
  },

  shop: {
    '*': 'Sklep {}',
    agrarian: 'Sklep rolniczy',
    household_linen: 'Pościel domowa',
    charity: 'Sklep charytatywny',
    chocolate: 'Sklep z czekoladą',
    fashion_accessories: 'Sklep z akcesoriami modowymi',
    frozen_food: 'Sklep z mrożonkami',
    hearing_aids: 'Sklep z aparatami słuchowymi',
    storage_rental: 'Wynajem magazynów',
    telecommunication: 'Sklep telekomunikacyjny',
    weapons: 'Sklep z bronią',
    alcohol: 'Sklep z alkoholem',
    antiques: 'Antyki',
    art: 'Sklep z dziełami sztuki',
    baby_goods: 'Sklep dla niemowląt',
    bag: 'Sklep z torebkami',
    bakery: 'Piekarnia',
    bathroom_furnishing: 'Sklep z wyposażeniem łazienkowym',
    beauty: 'Sklep kosmetyczny',
    bed: 'Sklep z łóżkami',
    beverages: 'Sklep z napojami',
    bicycle: 'Sklep rowerowy',
    bookmaker: 'Zakłady bukmacherskie',
    books: 'Księgarnia',
    boutique: 'Butik',
    butcher: 'Rzeźnik',
    camera: 'Sklep fotograficzny',
    car: 'Salon samochodowy',
    car_parts: 'Części samochodowe',
    car_repair: 'Warsztat samochodowy',
    carpet: 'Sklep z dywanami',
    cheese: 'Sklep z serami',
    chemist: 'Drogeria',
    clothes: 'Sklep odzieżowy',
    coffee: 'Kawiarnia',
    collector: 'Sklep dla kolekcjonerów',
    computer: 'Sklep komputerowy',
    confectionery: 'Cukiernia',
    convenience: 'Sklep spożywczy',
    copyshop: 'Ksero',
    cosmetics: 'Drogeria kosmetyczna',
    craft: 'Sklep z artykułami rękodzielniczymi',
    curtain: 'Sklep z zasłonami',
    dairy: 'Sklep z nabiałem',
    deli: 'Delikatesy',
    department_store: 'Dom handlowy',
    doityourself: 'Sklep z narzędziami',
    doors: 'Sklep z drzwiami',
    dry_cleaning: 'Pralnia chemiczna',
    'e-cigarette': 'Sklep z e-papierosami',
    electrical: 'Sklep elektryczny',
    electronics: 'Sklep elektroniczny',
    erotic: 'Sklep erotyczny',
    fabric: 'Sklep z tkaninami',
    farm: 'Sklep na farmie',
    fireplace: 'Sklep z kominkami',
    fishing: 'Sklep wędkarski',
    flooring: 'Sklep z podłogami',
    florist: 'Kwiaciarnia',
    funeral_directors: 'Zakład pogrzebowy',
    furniture: 'Sklep meblowy',
    games: 'Sklep z grami',
    garden_center: 'Centrum ogrodnicze',
    garden_centre: 'Centrum ogrodnicze',
    general: 'Sklep ogólnospożywczy',
    gift: 'Sklep z upominkami',
    glaziery: 'Witrynarstwo',
    greengrocer: 'Sklep z owocami i warzywami',
    hairdresser: 'Fryzjer',
    hardware: 'Sklep z narzędziami',
    health_food: 'Sklep ze zdrową żywnością',
    hifi: 'Sklep Hi-Fi',
    houseware: 'Sklep z artykułami gospodarstwa domowego',
    hunting: 'Sklep myśliwski',
    ice_cream: 'Lodziarnia',
    interior_decoration: 'Sklep z dekoracjami wnętrz',
    jewelry: 'Jubiler',
    kiosk: 'Kiosk',
    kitchen: 'Sklep kuchenny',
    laundry: 'Pralnia',
    lighting: 'Sklep oświetleniowy',
    locksmith: 'Ślusarz',
    lottery: 'Salon gier losowych',
    mall: 'Centrum handlowe',
    massage: 'Salon masażu',
    medical_supply: 'Sklep medyczny',
    mobile_phone: 'Sklep z telefonami komórkowymi',
    model: 'Sklep modelarski',
    motorcycle: 'Sklep motocyklowy',
    music: 'Sklep muzyczny',
    musical_instrument: 'Sklep z instrumentami muzycznymi',
    newsagent: 'Kiosk z prasą',
    nutrition_supplements: 'Sklep z suplementami diety',
    optician: 'Optyk',
    outdoor: 'Sklep outdoorowy',
    outpost: 'Placówka',
    paint: 'Sklep z farbami',
    pastry: 'Cukiernia',
    pawnbroker: 'Lombard',
    perfumery: 'Perfumy',
    pet: 'Sklep zoologiczny',
    pet_grooming: 'Salon pielęgnacji zwierząt',
    photo: 'Sklep fotograficzny',
    radiotechnics: 'Sklep radiotechniczny',
    rental: 'Wypożyczalnia',
    seafood: 'Sklep z owocami morza',
    second_hand: 'Secondhand',
    sewing: 'Sklep krawiecki',
    shoes: 'Sklep obuwniczy',
    sports: 'Sklep sportowy',
    stationery: 'Papierniczy',
    supermarket: 'Supermarket',
    tailor: 'Krawiec',
    tattoo: 'Salon tatuażu',
    tea: 'Herbaciarnia',
    ticket: 'Sprzedaż biletów',
    tobacco: 'Sklep tytoniowy',
    toys: 'Sklep z zabawkami',
    trade: 'Sklep budowlany',
    travel_agency: 'Biuro podróży',
    tyres: 'Sklep z oponami',
    vacant: 'Wolny lokal',
    variety_store: 'Sklep wielobranżowy',
    video: 'Sklep wideo',
    video_games: 'Sklep z grami wideo',
    watches: 'Sklep z zegarkami',
    wholesale: 'Hurtownia',
    window_blind: 'Sklep z roletami',
    wine: 'Sklep z winem',
  },

  sport: {
    '*': 'Sport {}',
    australian_football: 'Football australijski',
    billiards: 'Bilard',
    boxing: 'Boks',
    cliff_diving: 'Skoki do wody z klifu',
    cricket: 'Krykiet',
    cricket_nets: 'Siatki do krykieta',
    croquet: 'Kroket',
    curling: 'Curling',
    gaelic_games: 'Gry gaelickie',
    horseshoes: 'Rzut podkową',
    korfball: 'Korfball',
    long_jump: 'Skok w dal',
    orienteering: 'Orientacja sportowa',
    paddle_tennis: 'Tenis paddle',
    pelota: 'Pelota',
    racquet: 'Rakieta',
    rc_car: 'Samochody RC',
    rugby: 'Rugby',
    rugby_league: 'Liga rugby',
    rugby_union: 'Unia rugby',
    sailing: 'Żeglarstwo',
    surfing: 'Surfing',
    table_soccer: 'Piłkarzyki',
    team_handball: 'Piłka ręczna',
    toboggan: 'Tobogan',
    '9pin': 'Kręgle 9-kołowe',
    '10pin': 'Kręgle 10-kołowe',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'Football amerykański',
    archery: 'Łucznictwo',
    athletics: 'Lekkoatletyka',
    badminton: 'Badminton',
    baseball: 'Baseball',
    basketball: 'Koszykówka',
    beachvolleyball: 'Siatkówka plażowa',
    bicycle: 'Kolarstwo',
    bmx: 'BMX',
    boules: 'Bulet',
    bowling: 'Kręgle',
    bowls: 'Bowls',
    canoe: 'Kajakarstwo',
    chess: 'Szachy',
    climbing: 'Wspinaczka',
    climbing_adventure: 'Przygoda wspinaczkowa',
    cycling: 'Kolarstwo',
    darts: 'Rzutki',
    disc_golf: 'Disc golf',
    dog_racing: 'Wyścigi psów',
    equestrian: 'Jeździectwo',
    field_hockey: 'Hokej na trawie',
    fitness: 'Fitness',
    floorball: 'Unihokej',
    free_flying: 'Lot swobodny',
    golf: 'Golf',
    gymnastics: 'Gimnastyka',
    handball: 'Piłka ręczna',
    hockey: 'Hokej',
    horse_racing: 'Wyścigi konne',
    ice_hockey: 'Hokej na lodzie',
    ice_skating: 'Łyżwiarstwo',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Karting',
    laser_tag: 'Laser tag',
    model_aerodrome: 'Modelarski aerodrom',
    motocross: 'Motocross',
    motor: 'Motorsport',
    multi: 'Wiele sportów',
    netball: 'Netball',
    paintball: 'Paintball',
    petanque: 'Petanque',
    roller_skating: 'Jazda na rolkach',
    rowing: 'Wioślarstwo',
    running: 'Bieganie',
    scuba_diving: 'Nurkowanie',
    shooting: 'Strzelectwo',
    shooting_range: 'Strzelnica',
    'shot-put': 'Pchnięcie kulą',
    skateboard: 'Skateboard',
    skating: 'Łyżwiarstwo',
    ski_jumping: 'Skoki narciarskie',
    skiing: 'Narciarstwo',
    soccer: 'Piłka nożna',
    squash: 'Squash',
    streetball: 'Streetball',
    swimming: 'Pływanie',
    table_tennis: 'Tenis stołowy',
    tennis: 'Tenis',
    volleyball: 'Siatkówka',
    water_ski: 'Narty wodne',
    workout: 'Trening',
    yoga: 'Joga',
    '8pin': 'Kręgle ośmiokreglowe',
    aerobics: 'Aerobik',
    american_handball: 'Amerykańska piłka ręczna',
    association_football: 'Piłka nożna (soccer)',
    axe_throwing: 'Rzut siekierą',
    balle_pelote: 'Balle pelote',
    ballooning: 'Loty balonem',
    bandy: 'Bandy',
    barre: 'Barre fitness',
    base: 'BASE jumping',
    batting_cage: 'Klatka do odbijania (baseball/softball)',
    beach_soccer: 'Piłka nożna plażowa',
    beach_tennis: 'Tenis plażowy',
    beachhandball: 'Piłka ręczna plażowa',
    beachtennis: 'Tenis plażowy',
    biathlon: 'Biatlon',
    billards: 'Bilard',
    bobsleigh: 'Bobsleje',
    bodybuilding: 'Kulturystyka',
    bullfighting: 'Walka byków',
    calisthenics: 'Kalistenika',
    canadian_football: 'Futbol kanadyjski',
    candlepin: 'Kręgle candlepin',
    canoe_polo: 'Kajak polo',
    chinlone: 'Chinlone',
    cockfighting: 'Walki kogutów',
    crossfit: 'CrossFit',
    cycle_ball: 'Cyklobal',
    cycle_polo: 'Cyklopolo',
    dance: 'Sport taneczny',
    dancing: 'Sport taneczny',
    diving: 'Skoki do wody',
    dodgeball: 'Dodgeball',
    dog_agility: 'Agility z psami',
    dragon_boat: 'Wyścigi smoczych łodzi',
    fencing: 'Szermierka',
    fistball: 'Fistball',
    'five-a-side': 'Piłka nożna 5-osobowa',
    fives: 'Fives',
    football: 'Football',
    footballgolf: 'Football golf',
    four_square: 'Four square',
    freediving: 'Nurkowanie swobodne',
    funnel_ball: 'Funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Futbol gaelicki',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Szybownictwo',
    hanggliding: 'Lotniarstwo',
    hapkido: 'Hapkido',
    high_rope_course: 'Wysoki park linowy',
    hiking: 'Turystyka piesza',
    hopscotch: 'Gra w klasy',
    horse_riding: 'Jazda konna',
    ice_stock: 'Eisstock',
    'in-line_hockey': 'Hokej na rolkach',
    jetsprint: 'Wyścigi jet sprint',
    kick_scooter: 'Hulajnoga sportowa',
    kickball: 'Kickball',
    kickboxing: 'Kickboxing',
    kitesurfing: 'Kitesurfing',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Lacrosse',
    martial_arts: 'Sztuki walki',
    mind_body_interventions: 'Ćwiczenia ciało-umysł (np. joga)',
    miniature_golf: 'Minigolf',
    mtb: 'Kolarstwo górskie',
    nine_mens_morris: 'Młynek (gra)',
    obstacle_course: 'Bieg z przeszkodami',
    paddleball: 'Paddleball',
    paddleboard: 'SUP (stand-up paddle)',
    padel: 'Padel',
    parachuting: 'Spadochroniarstwo',
    paragliding: 'Paralotniarstwo',
    parkour: 'Parkour',
    pedal_car_racing: 'Wyścigi samochodów na pedały',
    pesäpallo: 'Pesäpallo (fiński baseball)',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole dance',
    polo: 'Polo',
    powerlifting: 'Trójbój siłowy',
    rodeo: 'Rodeo',
    roller_hockey: 'Hokej na wrotkach',
    russian_skittles: 'Rosyjskie kręgle',
    safety_training: 'Trening bezpieczeństwa',
    shuffleboard: 'Shuffleboard',
    snooker: 'Snooker',
    snorkeling: 'Snorkeling',
    softball: 'Softball',
    speedway: 'Żużel',
    summer_toboggan: 'Letni tor saneczkowy',
    sumo: 'Sumo',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    touch_football: 'Touch football',
    trampoline: 'Skoki na trampolinie',
    trugo: 'Trugo',
    tug_of_war: 'Przeciąganie liny',
    ultimate: 'Ultimate frisbee',
    ultralight_aviation: 'Lotnictwo ultralekkie',
    wakeboarding: 'Wakeboarding',
    walking: 'Chód sportowy',
    water_polo: 'Piłka wodna',
    water_sports: 'Sporty wodne',
    weightlifting: 'Podnoszenie ciężarów',
    windsurfing: 'Windsurfing',
    wrestling: 'Zapasy',
    zurkhaneh_sport: 'Zurkhaneh',
  },

  tourism: {
    artwork: {
      artwork_type: {
        architecture: 'Architektura',
        bust: 'Popiersie',
        graffiti: 'Graffiti',
        installation: 'Instalacja artystyczna',
        mosaic: 'Mozaika',
        mural: 'Mural',
        painting: 'Obraz',
        relief: 'Płaskorzeźba',
        sculpture: 'Rzeźba',
        statue: 'Figura',
        stone: 'Głaz (dzieło sztuki)',
      },
      '*': 'Sztuka',
    },

    cabin: 'Domek turystyczny',
    camp_pitch: 'Stanowisko biwakowe',
    hunting_lodge: 'Domek myśliwski',
    information: {
      information: {
        '*': 'Informacja {}',
        board: 'Tablica informacyjna',
        guidepost: 'Drogowskaz',
        map: 'Mapa',
        office: 'Biuro informacji',
        route_marker: 'Oznakowanie trasy',
      },
      '*': 'Informacja',
    },

    '*': '{}',
    alpine_hut: 'Schronisko górskie',
    apartment: 'Apartament',
    aquarium: 'Akwarium',
    attraction: 'Atrakcja',
    camp_site: 'Pole namiotowe',
    caravan_site: 'Miejsce dla przyczep kempingowych',
    chalet: 'Szałas',
    gallery: 'Galeria',
    guest_house: 'Pensjonat',
    hostel: 'Hostel',
    hotel: 'Hotel',
    motel: 'Motel',
    museum: 'Muzeum',
    picnic_site: 'Miejsce na piknik',
    viewpoint: 'Punkt widokowy',
    wilderness_hut: 'Szałas na odludziu',
    zoo: 'Zoo',
    theme_park: 'Park tematyczny',
  },

  type: {
    route: {
      '*': 'Szlak',
      route: {
        '*': 'Szlak {}',
        aerialway: 'Trasa kolei linowej',
        bicycle: {
          '*': 'Szlak rowerowy',
          network: {
            icn: 'Międzynarodowy szlak rowerowy',
            lcn: 'Lokalny szlak rowerowy',
            ncn: 'Krajowy szlak rowerowy',
            rcn: 'Regionalny szlak rowerowy',
          },
        },
        bus: 'Trasa autobusu',
        canoe: 'Szlak kajakowy',
        canyoning: 'Trasa kanioningowa',
        detour: 'Trasa objazdu',
        emergency_access: 'Trasa dojazdu ratunkowego',
        ferry: 'Trasa promu',
        fitness_trail: 'Ścieżka zdrowia',
        foot: {
          '*': 'Szlak pieszy',
          network: {
            iwn: 'Międzynarodowa trasa piesza',
            lwn: 'Lokalna trasa piesza',
            nwn: 'Krajowa trasa piesza',
            rwn: 'Regionalna trasa piesza',
          },
          pilgrimage: {
            '*': 'Szlak pielgrzymkowy',
            no: '',
          },
        },
        funicular: 'Trasa kolei linowo-terenowej',
        hiking: {
          '*': 'Szlak turystyczny',
          network: {
            iwn: 'Międzynarodowy szlak pieszy',
            lwn: 'Lokalny szlak pieszy',
            nwn: 'Krajowy szlak pieszy',
            rwn: 'Regionalny szlak pieszy',
          },
          pilgrimage: {
            '*': 'Szlak pielgrzymkowy',
            no: '',
          },
        },
        historic: 'Trasa historyczna',
        historic_railway: 'Historyczna linia kolejowa',
        horse: {
          '*': 'Szlak jeździecki',
          network: {
            lhn: 'Lokalny szlak jeździecki',
            rhn: 'Regionalny szlak jeździecki',
          },
        },
        inline_skates: 'Trasa rolkowa',
        junction: 'Węzeł drogowy',
        light_rail: 'Trasa kolei miejskiej',
        motorboat: 'Trasa motorówki',
        mtb: 'Szlak rowerów górskich',
        nordic_walking: 'Trasa nordic walking',
        pipeline: 'Trasa rurociągu',
        piste: 'Stok narciarski lub ścieżka',
        portage: 'Trasa przenoski',
        power: 'Trasa linii energetycznej',
        railway: 'Linia kolejowa',
        road: 'Trasa drogowa',
        running: 'Trasa biegowa',
        share_taxi: 'Trasa taksówki zbiorowej',
        ski: 'Trasa narciarska',
        subway: 'Trasa metra',
        tracks: 'Przebieg torów',
        train: 'Trasa pociągu',
        tram: 'Trasa tramwajowa',
        trolleybus: 'Trasa trolejbusu',
        via_ferrata: 'Via ferrata',
        waterway: 'Szlak wodny',
        worship: {
          '*': 'Szlak pielgrzymkowy',
          worship: {
            stations_of_the_cross: 'Droga krzyżowa',
          },
        },
      },
    },
  },

  waterway: {
    '*': 'Droga wodna {}',
    boatyard: 'Stocznia',
    canal: 'Kanał',
    dam: 'Zapora',
    ditch: 'Rów (droga wodna)',
    dock: 'Dok',
    drain: 'Odpływ',
    drystream: 'Ciek okresowy',
    lock_gate: 'Wrota śluzy',
    milestone: 'Kilometrowskaz rzeczny',
    river: 'Rzeka',
    sluice_gate: 'Zastawka',
    stream: 'Strumień, potok',
    wadi: 'Wadi',
    waterfall: 'Wodospad',
    weir: 'Próg wodny',
    canoe_pass: 'Przenoska dla kajaków',
    fairway: 'Tor wodny',
    fish_pass: 'Przepławka dla ryb',
    flowline: 'Linia przepływu',
    link: 'Łącznik cieku wodnego',
    pressurised: 'Ciśnieniowy przewód wodny',
    rapids: 'Bystrza',
    tidal_channel: 'Kanał pływowy',
  },

  aerialway: {
    '*': 'Wyciąg linowy, kolejka',
    cable_car: 'Kolej linowa kabinowa',
    chair_lift: 'Wyciąg krzesełkowy',
    goods: 'Kolej towarowa',
    'j-bar': 'Wyciąg J',
    magic_carpet: 'Taśma transportowa',
    mixed_lift: 'Wyciąg mieszany',
    platter: 'Wyciąg talerzykowy',
    pylon: 'Pylon',
    rope_tow: 'Wyciąg linowy',
    station: 'Stacja kolejki',
    't-bar': 'Wyciąg orczykowy',
    zip_line: 'Tyrolka',
  },

  railway: {
    '*': 'Kolej',
    abandoned: 'Opuszczona linia kolejowa',
    buffer_stop: 'Kozioł oporowy',
    construction: 'Linia kolejowa w budowie',
    crossing: 'Skrzyżowanie torów',
    derail: 'Wykolejnica',
    disused: 'Nieużywana linia kolejowa',
    facility: 'Obiekt kolejowy',
    funicular: 'Kolej linowo-terenowa',
    halt: 'Przystanek kolejowy',
    junction: 'Rozjazd kolejowy',
    level_crossing: 'Przejazd kolejowy',
    light_rail: 'Lekka kolej',
    milestone: 'Kilometrowskaz kolejowy',
    miniature: 'Kolejka miniaturowa',
    monorail: 'Kolej jednoszynowa',
    narrow_gauge: 'Kolej wąskotorowa',
    platform: 'Peron kolejowy',
    preserved: 'Kolej zabytkowa',
    proposed: 'Planowana linia kolejowa',
    rail: 'Linia kolejowa',
    railway_crossing: 'Przejście kolejowe',
    razed: 'Rozebrana linia kolejowa',
    roundhouse: 'Parowozownia wachlarzowa',
    signal: 'Sygnał kolejowy',
    signal_box: 'Nastawnia',
    site: 'Teren kolejowy',
    station: 'Stacja kolejowa',
    stop: 'Przystanek kolejowy',
    subway: 'Linia metra',
    subway_entrance: 'Wejście do metra',
    switch: 'Zwrotnica kolejowa',
    train_station_entrance: 'Wejście na dworzec',
    tram: 'Linia tramwajowa',
    tram_crossing: 'Przejście przez torowisko tramwajowe',
    tram_level_crossing: 'Przejazd tramwajowy',
    tram_stop: 'Przystanek tramwajowy',
    traverser: 'Przesuwnica kolejowa',
    turntable: 'Obrotnica kolejowa',
    ventilation_shaft: 'Szyb wentylacyjny kolei',
    wash: 'Myjnia pociągów',
    water_crane: 'Żuraw wodny kolejowy',
    workshop: 'Warsztat kolejowy',
    yard: 'Stacja rozrządowa',
  },

  'abandoned:building': {
    '*': 'Opuszczony budynek',
  },

  'disused:building': {
    '*': 'Nieużywany budynek',
  },

  'ruins:building': {
    '*': 'Ruiny budynku',
  },

  attraction: {
    amusement_ride: 'Atrakcja rozrywkowa',
    animal: 'Atrakcja zwierzęca',
    big_wheel: 'Diabelski młyn',
    carousel: 'Karuzela',
    historic: 'Atrakcja historyczna',
    maze: 'Labirynt',
    roller_coaster: 'Kolejka górska',
    summer_toboggan: 'Letni tor saneczkowy',
    train: 'Kolejka turystyczna',
    water_slide: 'Zjeżdżalnia wodna',
  },

  bicycle: {
    designated: 'Wyznaczone dla rowerów',
    no: 'Zakaz ruchu rowerów',
    private: 'Ruch rowerów tylko dla właścicieli',
    yes: 'Ruch rowerów dozwolony',
  },

  bridge: {
    '*': {
      '*': 'Most',

      highway: {
        '*': 'Most drogowy',
      },

      railway: {
        '*': 'Most kolejowy',
      },
    },

    no: '',
  },

  fixme: {
    '*': 'Obiekt zmapowany niepoprawnie lub niekompletnie',
  },

  foot: {
    designated: 'Wyznaczone dla pieszych',
    no: 'Zakaz ruchu pieszego',
    private: 'Ruch pieszy tylko dla właścicieli',
    yes: 'Ruch pieszy dozwolony',
  },

  ford: {
    yes: 'Bród',
  },

  intermittent: {
    yes: {
      '*': 'Okresowy',

      natural: {
        water: 'Okresowy obszar wodny',
      },

      waterway: {
        stream: 'Okresowy strumień',
        ditch: 'Okresowy rów',
        drain: 'Okresowy odpływ',
        waterfall: 'Okresowy wodospad',
      },
    },
  },

  military: {
    '*': 'Obiekt wojskowy {}',
    academy: 'Akademia wojskowa',
    airfield: 'Lotnisko wojskowe',
    ammunition: 'Skład amunicji',
    barracks: 'Koszary',
    base: 'Baza wojskowa',
    bunker: 'Bunkier',
    checkpoint: 'Wojskowy punkt kontrolny',
    danger_area: 'Wojskowa strefa zagrożenia',
    depot: 'Magazyn wojskowy',
    launchpad: 'Platforma startowa',
    naval_base: 'Baza morska',
    nuclear_explosion_site: 'Miejsce prób jądrowych',
    obstacle_course: 'Wojskowy tor przeszkód',
    office: 'Biuro wojskowe',
    range: 'Poligon strzelecki',
    school: 'Szkoła wojskowa',
    training_area: 'Wojskowy teren szkoleniowy',
    trench: 'Okop',
  },

  motor_vehicle: {
    designated: 'Wyznaczone dla pojazdów silnikowych',
    no: 'Zakaz ruchu pojazdów silnikowych',
    private: 'Ruch pojazdów silnikowych tylko dla właścicieli',
    yes: 'Ruch pojazdów silnikowych dozwolony',
  },

  mountain_pass: {
    yes: 'Przełęcz górska',
  },

  oneway: {
    yes: 'Ruch jednokierunkowy',
  },

  seasonal: {
    yes: {
      '*': 'Sezonowy',

      natural: {
        water: 'Sezonowy obszar wodny',
      },

      waterway: {
        stream: 'Sezonowy strumień',
        ditch: 'Sezonowy rów',
        drain: 'Sezonowy odpływ',
        waterfall: 'Sezonowy wodospad',
      },
    },
  },

  trail_visibility: {
    bad: 'Zła widoczność szlaku',
    excellent: 'Doskonała widoczność szlaku',
    good: 'Dobra widoczność szlaku',
    horrible: 'Bardzo zła widoczność szlaku',
    intermediate: 'Średnia widoczność szlaku',
    no: 'Brak widoczności szlaku',
  },

  tunnel: {
    '*': {
      '*': 'Tunel',

      highway: {
        '*': 'Tunel drogowy',
      },

      railway: {
        '*': 'Tunel kolejowy',
      },
    },

    culvert: 'Przepust',
    no: '',
  },

  vehicle: {
    designated: 'Wyznaczone dla pojazdów',
    no: 'Zakaz ruchu pojazdów',
    private: 'Ruch pojazdów tylko dla właścicieli',
    yes: 'Ruch pojazdów dozwolony',
  },

  access: {
    customers: 'Tylko dla klientów',
    private: 'Obiekt prywatny',
    no: 'Obiekt z zakazem wstępu',
  },

  craft: {
    '*': 'Rzemiosło {}',
    yes: 'Zakład rzemieślniczy',
    bakery: 'Piekarnia',
    beekeeper: 'Pszczelarz',
    blacksmith: 'Kowal',
    brewery: 'Browar',
    builder: 'Firma budowlana',
    carpenter: 'Cieśla',
    caterer: 'Firma cateringowa',
    cleaning: 'Firma sprzątająca',
    confectionery: 'Cukiernik',
    distillery: 'Gorzelnia',
    dressmaker: 'Krawcowa',
    electrician: 'Elektryk',
    electronics_repair: 'Naprawa elektroniki',
    gardener: 'Ogrodnik',
    glaziery: 'Zakład szklarski',
    grinding_mill: 'Młyn',
    handicraft: 'Rękodzieło',
    hvac: 'Ogrzewanie i klimatyzacja',
    jeweller: 'Jubiler',
    joiner: 'Stolarz',
    key_cutter: 'Dorabianie kluczy',
    locksmith: 'Ślusarz',
    metal_construction: 'Konstrukcje metalowe',
    painter: 'Malarz',
    photographer: 'Fotograf',
    plumber: 'Hydraulik',
    pottery: 'Garncarstwo',
    roofer: 'Dekarz',
    sawmill: 'Tartak',
    shoemaker: 'Szewc',
    signmaker: 'Wytwórnia szyldów',
    stonemason: 'Kamieniarz',
    tailor: 'Krawiec',
    tiler: 'Glazurnik',
    upholsterer: 'Tapicer',
    watchmaker: 'Zegarmistrz',
    window_construction: 'Produkcja okien',
    winery: 'Winiarnia',
  },
  emergency: {
    access_point: 'Punkt ratunkowy',
    ambulance_station: 'Stacja pogotowia ratunkowego',
    assembly_point: 'Miejsce zbiórki',
    defibrillator: 'Defibrylator',
    fire_extinguisher: 'Gaśnica',
    fire_hose: 'Wąż pożarniczy',
    fire_hydrant: 'Hydrant',
    fire_water_pond: 'Zbiornik przeciwpożarowy',
    landing_site: 'Awaryjne lądowisko',
    life_ring: 'Koło ratunkowe',
    lifeguard: 'Stanowisko ratownika',
    phone: 'Telefon alarmowy',
    siren: 'Syrena alarmowa',
    suction_point: 'Punkt czerpania wody',
    water_tank: 'Zbiornik wody gaśniczej',
  },

  entrance: {
    '*': 'Wejście',
    main: 'Wejście główne',
    secondary: 'Wejście boczne',
    service: 'Wejście służbowe',
    exit: 'Wyjście',
    entrance: 'Wejście (tylko)',
    emergency: 'Wyjście awaryjne',
    staircase: 'Wejście na klatkę schodową',
    home: 'Wejście do prywatnego domu/ogrodu/mieszkania',
    garage: 'Wejście do garażu',
    shop: 'Wejście do sklepu',
    no: 'Brak wejścia',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Czerwona',
  blue: 'Niebieska',
  green: 'Zielona',
  yellow: 'Żółta',
  orange: 'Pomarańczowa',
  purple: 'Purpurowa',
  violet: 'Fioletowa',
  white: 'Biała',
  black: 'Czarna',
  gray: 'Szara',
  brown: 'Brązowa',
};
