import { OsmTagToNameMapping } from './osmTagToNameMappingType';

export const osmTagToNameMapping: OsmTagToNameMapping = {
  aeroway: {
    aerodrome: 'Aereoporto',
  },
  aerialway: 'Via aerea, ascensore',
  amenity: {
    '*': '{}',
    animal_breeding: 'Allevamento',
    animal_shelter: 'Rifugio per animali',
    arts_centre: 'Centro artistico',
    atm: 'Bancomat',
    bank: 'Banca',
    bar: 'Bar',
    bbq: 'Griglia',
    bench: 'Panchina',
    bicycle_parking: 'Parcheggio bici',
    bicycle_rental: 'Noleggio bici',
    bicycle_repair_station: 'Meccanico bici',
    biergarten: 'Birreria',
    brothel: 'Bordello',
    bureau_de_change: 'Cambio valuta',
    bus_station: 'Stazione autobus',
    cafe: 'Caffè',
    car_rental: 'Noleggio auto',
    car_wash: 'Lavaggio auto',
    casino: 'Casinò',
    charging_station: 'Stazione di ricarica',
    childcare: 'Assistenza infantile',
    cinema: 'Cinema',
    clinic: 'Clinica',
    clock: 'Orologio',
    college: 'College',
    community_centre: 'Centro comunitario',
    compressed_air: 'Aria compressa',
    courthouse: 'Tribunale',
    dentist: 'Dentista',
    device_charging_station: 'Stazione ricarica dispositivi',
    doctors: "Ambulatorio medico",
    dressing_room: 'Spogliatoio',
    drinking_water: 'Acqua potabile',
    driving_school: 'Scuola guida',
    embassy: 'Ambasciata',
    events_venue: 'Luogo per eventi',
    fast_food: 'Fast food',
    feeding_place: 'Mangiatoia',
    ferry_terminal: 'Terminal traghetti',
    fire_station: 'Caserma Pompieri',
    food_court: 'Ristoro',
    fountain: 'Fontana',
    fuel: 'Stazione Gas',
    funeral_hall: 'Casa del commiato',
    gambling: 'Gioco azzardo',
    game_feeding: 'Gioco alimentazione',
    grave_yard: 'Cimitero',
    grit_bin: 'Pattumiera',
    hospital: 'Ospedale',
    hunting_stand: 'Supporto da caccia',
    ice_cream: 'Gelati',
    kindergarten: 'Scuola materna',
    language_school: 'Scuola di lingue',
    library: 'Biblioteca',
    marketplace: 'Mercato',
    monastery: 'Monastero',
    money_transfer: 'Transazioni denaro',
    motorcycle_parking: 'Parcheggio motocicli',
    motorcycle_rental: 'Noleggio motocicli',
    nightclub: 'Nightclub',
    parking: 'Parcheggio',
    parking_entrance: 'Entrata parcheggio',
    parking_space: 'Area di parcheggio',
    pharmacy: 'Farmacia',
    place_of_mourning: 'Luogo di lutto',
    place_of_worship: 'Luogo di culto',
    planetarium: 'Planetario',
    police: 'Polizia',
    post_box: 'Casella postale',
    post_office: 'Ufficio postale',
    prison: 'Prigione',
    pub: 'Pub',
    public_bookcase: 'Libreria pubblica',
    ranger_station: 'Stazione Ranger',
    recycling: 'Raccolta differenziata',
    restaurant: 'Ristorante',
    school: 'Scuola',
    shelter: {
      '*': 'Riparo',
      shelter_type: {
        '*': 'Shelter {}',
        basic_hut: 'Tettoia',
        changing_rooms: 'Spogliatoi',
        field_shelter: 'Rifugio da campo',
        lean_to: 'Appoggiato a',
        picnic_shelter: 'Tettoia per picnic',
        public_transport: 'Ricovero mezzi pubblici',
        rock_shelter: 'Riparo roccioso',
        sun_shelter: 'Riparo dal sole',
        weather_shelter: 'Rifugio meteorologico',
      },
    },
    shower: 'Doccia',
    ski_rental: 'Noleggio sci',
    smoking_area: 'Area fumatori',
    social_centre: 'Centro sociale',
    social_facility: {
      '*': 'Struttura sociale',
      social_facility: {
        // dairy_kitchen: 'Cucina casearia',
        // outreach: 'Sensibilizzazione',
        ambulatory_care: 'Ambulatorio di cura',
        assisted_living: 'Assistenza vita',
        clothing_bank: 'Banca abbigliamento',
        day_care: 'Asilo nido',
        food_bank: 'Banca del cibo',
        group_home: 'Casa di accoglienza',
        hospice: 'Ospizio',
        nursing_home: 'Casa di riposo',
        shelter: 'Riparo',
        soup_kitchen: 'Mensa per i poveri',
        workshop: 'Officina',
      },
    },
    stripclub: 'Spogliarello',
    studio: 'Studio',
    taxi: 'Taxi',
    telephone: 'Telefono',
    theatre: 'Teatro',
    toilets: 'WC',
    townhall: 'Municipio',
    traffic_park: 'Parco del traffico',
    trolley_bay: 'Trolley',
    university: 'Università',
    vacuum_cleaner: 'Aspirapolvere',
    vehicle_inspection: 'Controllo veicolo',
    vending_machine: 'Distributore automatico',
    veterinary: 'Veterinario',
    waste_basket: 'Cassonetto',
    waste_disposal: 'Smaltimento rifiuti',
    water_point: 'Punto Acqua',
    watering_place: 'Abbeveratoio',
  },
  barrier: {
    '*': 'Barrier {}',
    block: 'Blocco',
    bollard: 'Dissuasore',
    border_control: 'Controllo di frontiera',
    cable_barrier: 'Barriera cavi',
    chain: 'Catena',
    city_wall: 'Mura cittadine',
    ditch: 'Fossato',
    entrance: 'Entrata',
    fence: 'Recinzione',
    gate: 'Cancello',
    guard_rail: 'Guardrail',
    handrail: 'Corrimano',
    hedge: 'Siepe',
    kerb: 'Cordolo',
    lift_gate: 'Ascensore',
    rope: 'Corda',
    sliding_gate: 'Cancello scorrevole',
    swing_gate: 'Cancello a battente',
    turnstile: 'Tornello',
    wall: 'Muro',
  },
  boundary: {
    '*': 'Regione',
    administrative: {
      '*': 'Regione Amministrativa',
      admin_level: {
        '2': 'Stato',
        '3': 'Regione',
        '4': 'Distretto',
        '5': 'Provincia',
        '6': 'Città',
        '7': 'Regione',
        '8': 'Distretto',
        '9': 'Villaggio',
        '10': 'Regione catastale',
      },
    },
    national_park: 'Parco Nazionale',
    protected_area: 'Area Protetta',
  },
  building: {
    '*': 'Edificio {}',
    apartments: 'Condominio',
    barn: 'Fienile',
    bungalow: 'Bungalow',
    bunker: 'Bunker',
    cabin: 'Cabina',
    cathedral: 'Cattedrale',
    chapel: 'Cappella',
    church: 'Chiesa',
    civic: 'Palazzo civico',
    collapsed: 'Edificio crollato',
    commercial: 'Edificio commerciale',
    construction: 'Edificio in costruzione',
    cowshed: 'Stalla',
    detached: 'Casa indipendente',
    dormitory: 'Dormitorio',
    entrance: 'Ingresso edificio',
    farm_auxiliary: 'Fabbricato agricolo ausiliario',
    farm: 'Azienda agricola',
    garage: 'Garage',
    garages: 'Garage',
    government: 'Edificio governativo',
    grandstand: 'Tribuna',
    greenhouse: 'Serra',
    hangar: 'Hangar',
    hayloft: 'Fienile',
    hospital: 'Edificio ospedaliero',
    hotel: 'Edificio alberghiero',
    house: 'Casa privata',
    houseboat: 'Casa galleggiante',
    hut: 'Capanna',
    industrial: 'Edificio industriale',
    kindergarten: 'Edificio dell''asilo',
    kiosk: 'Chiosco',
    manufacture: 'Manifattura',
    mosque: 'Moschea',
    office: 'Ufficio',
    parking: 'Parcheggio',
    public: 'Edificio pubblico',
    residential: 'Casa residenziale',
    retail: 'Rivendita',
    roof: 'Tetto',
    ruins: 'Rovine di edifici',
    school: 'Scuola',
    semidetached_house: 'Casa bifamiliare',
    service: 'Edificio di servizio',
    shed: 'Capannone',
    shrine: 'Altare',
    stable: 'Stalla',
    static_caravan: 'Casa mobile',
    storage_tank: 'Serbatoio di stoccaggio',
    sty: 'Porcile',
    supermarket: 'Supermercato',
    synagogue: 'Sinagoga',
    temple: 'Tempio',
    terrace: 'Terrazza',
    train_station: 'Stazione dei treni',
    transformer_tower: 'Torre di trasformazione',
    transportation: 'Trasporti',
    university: 'Università',
    warehouse: 'Magazzino',
    yes: 'Indeterminato',
  },
  highway: {
    '*': 'Strada {}',
    bus_stop: 'Fermata autobus',
    construction: 'Strada in costruzione',
    crossing: 'Attraversamento pedonale',
    cycleway: 'Pista ciclabile',
    footway: 'Marciapiedi',
    living_street: 'Strada residenziale',
    motorway: 'Autostrada',
    motorway_link: 'Collegamento autostradale',
    path: 'Sentiero',
    pedestrian: 'Zona pedonale',
    primary: 'Strada primaria',
    primary_link: 'Collegamento strada primaria',
    residential: 'Strada',
    secondary: 'Strada secondaria',
    secondaty_link: 'Collegamento strada secondaria',
    service: {
      '*': 'Servizio stradale',
      service: {
        '*': 'Strada di servizio {}',
        alley: 'Vicolo',
        bus: 'Strada autobus',
        'drive-through': 'percorribile in auto',
        driveway: 'Viale',
        emergency_access: 'Accesso di emergenza',
        parking_aisle: 'Corridoio di parcheggio',
      },
    },
    steps: 'Scale',
    street_lamp: 'Lampione',
    tertiary: 'Strada terziaria',
    tertiary_link: 'Collegamento strada terziaria',
    track: {
      '*': 'Strada forestale',
      tracktype: {
        grade1: 'Strada forestale compattata',
        grade2: 'Strada forestale prevalentemente compattata',
        grade3: 'Strada forestale sterrata',
        grade4: 'Strada forestale percorribile con trattore o similari',
        grade5: 'Strada forestale poco distinguibile',
      },
    },
    trunk: 'Strada principale',
    trunk_link: 'Collegamento strada principale',
    unclassified: 'Strada minore/non classificata',
  },
  historic: {
    '*': 'Struttura storica',
    archaeological_site: 'Sito archeologico',
    castle: 'Castello',
    church: 'Chiesa storica',
    city_gate: 'Porta della città',
    manor: 'Maniero',
    memorial: 'Memoriale',
    monastery: 'Monastero',
    monument: 'Monumento',
    ruins: {
      '*': 'Rovine',
      ruins: {
        castle: 'Rovine Castello',
      },
    },
    tomb: 'Tomba',
    wayside_cross: 'Croce lungo la strada',
    wayside_shrine: 'Altare lungo la strada',
  },
  landuse: {
    '*': '{}',
    allotments: 'Lottizzazioni',
    brownfield: 'Terreno dismesso',
    cemetery: 'Cimitero',
    commercial: 'Commerciale',
    construction: 'Costruzione',
    farmland: 'Terreno agricolo',
    farmyard: 'Aia',
    forest: 'Foresta',
    garages: 'Garage',
    grass: 'Erba',
    greenfield: 'Terreno edificabile',
    industrial: 'Industriale',
    landfill: 'Discarica',
    meadow: 'Prateria',
    military: 'Area militare',
    orchard: 'Frutteto',
    plant_nursery: 'Vivaio',
    quarry: 'Cava',
    recreation_ground: 'Terreno ricreativo',
    religions: 'Area religiosa',
    // TODO
    reservoir: 'Serbatoio',
    residential: 'Residenziale',
    
    retail: 'Retail',
    vineyard: 'Vineyard',
    winter_sports: 'Winter sports',
  },
  leisure: {
    '*': '{}',
    dog_park: 'Dog park',
    firepit: 'Fireplace',
    fishing: 'Fishing',
    fitness_centre: 'Fintess centre',
    fitness_station: 'Fintess station',
    garden: 'Garden',
    golf_course: 'Golf course',
    horse_riding: 'Horse riding',
    nature_reserve: 'Nature reserve',
    park: 'Park',
    picnic_table: 'Picnic table',
    pitch: {
      '*': 'Pitch',
      sport: {
        badminton: 'Badminton pitch',
        basketball: 'Basketball pitch',
        beachvolleyball: 'Beach volleyball pitch',
        hockey: 'Hockey pitch',
        ice_hockey: 'Ice hockey pitch',
        multi: 'Multi pitch',
        soccer: 'Soccer pitch',
        tennis: 'Tennis pitch',
        volleyball: 'Volleyball pitch',
      },
    },
    playground: 'Playground',
    sports_centre: 'Sports centre',
    sports_hall: 'Sports hall',
    stadium: 'Stadium',
    swimming_pool: 'Swimming pool',
    track: 'Track',
    water_park: 'Water park',
  },
  man_made: {
    '*': '{}',
    adit: 'Adit',
    antenna: 'Antenna',
    beacon: 'Beacon',
    beehive: 'Beehive',
    bridge: 'Bridge',
    bunker_silo: 'Bunker silo',
    cairn: 'Cairn',
    cellar_entrance: 'Cellar entrance',
    chimney: 'Chimney',
    clearcut: 'Forest clearing',
    communications_tower: 'Communication tower',
    cooling_tower: 'Cooling tower',
    crane: 'Crane',
    cross: 'Cross',
    cutline: 'Cutline',
    dyke: 'Dyke',
    embankment: 'Embankment',
    flagpole: 'Flagpole',
    "forester's_lodge": "Forester's lodge",
    gasometer: 'Gasometer',
    goods_conveyor: 'Goods conveyor',
    groyne: 'Groyne',
    lighthouse: 'Lighthouse',
    manhole: 'Manhole',
    mast: 'Mast',
    mineshaft: 'Mineshaft',
    monitoring_station: 'Monitoring station',
    nesting_site: 'Nesting site',
    observatory: 'Observatory',
    pier: 'Pier',
    pipeline: 'Pipeline',
    reservoir_covered: 'Covered reservoir',
    silo: 'Silo',
    snow_cannon: 'Snow cannon',
    spoil_heap: 'Spoil heap',
    spring_box: 'Spring box',
    storage_tank: 'Storage tank',
    street_cabinet: 'Street cabinet',
    surveillance: 'Surveillance',
    survey_point: 'Survey point',
    telescope: 'Telescope',
    tower: {
      '*': 'Tower',
      'tower:type': {
        bell_tower: 'Bell tower',
        communication: 'Communication tower',
        cooling: 'Cooling tower',
        observation: 'Observation tower',
      },
    },
    utility_pole: 'Utility pole',
    wastewater_plant: 'Wastewater plant',
    water_tap: 'Water tap',
    water_tower: 'Water Tower',
    water_well: 'Water well',
    water_works: 'Water works',
    watermill: 'Watermill',
    windmill: 'Windmill',
    works: 'Works',
  },
  natural: {
    '*': '{}',
    arch: 'Rock arch',
    bare_rock: 'Bare rock',
    basin: 'Basin',
    bay: 'Bay',
    beach: 'Beach',
    birds_nest: 'Birds_nest',
    cave_entrance: 'Cave',
    cliff: 'Cliff',
    earth_bank: 'Earth bank',
    fell: 'Fell',
    geyser: 'Geyser',
    glacier: 'Glacier',
    grassland: 'Grassland',
    gully: 'Gully',
    heath: 'Heathland',
    hot_spring: 'Hot spring',
    landslide: 'Landslide',
    mountain_range: 'Mountain range',
    mud: 'Mud',
    peak: 'Peak',
    plateau: 'Plateau',
    ridge: 'Ridge',
    rock: 'Rock',
    saddle: 'Saddle',
    sand: 'Sand',
    scree: 'Scree',
    scrub: 'Scrub, bushes',
    shingle: 'Shingle',
    shrub: 'Shrub',
    sinkhole: 'Sinkhole',
    spring: {
      '*': 'Spring',
      drinking_water: {
        yes: 'Drinkable spring',
        no: 'Non-drinking spring',
      },
      refitted: {
        yes: 'Refitted spring',
        no: 'Non-refitted spring',
      },
    },
    stone: 'Stone',
    tree: 'Tree',
    tree_row: 'Tree row',
    valley: 'Valley',
    water: 'Water body',
    wetland: 'Wetland',
    wood: 'Forest',
  },
  place: {
    '*': 'Place {}',
    city: 'City',
    country: 'Country',
    farm: 'Farm',
    hamlet: 'Hamlet',
    island: 'Island',
    islet: 'Islet',
    isolated_dwelling: 'Isolated dwelling',
    locality: 'Locality',
    ocean: 'Ocean',
    sea: 'Sea',
    square: 'Square',
    state: 'State',
    suburb: 'Suburb',
    town: 'Town',
    village: 'Village',
  },
  power: {
    '*': '{}',
    generator: 'Generator',
    line: 'Power line',
    minor_line: 'Minor power line',
    plant: 'Plant',
    pole: 'Power pole',
    substation: 'Substation',
    tower: 'Power tower',
    transformer: 'Transformer',
  },
  public_transport: {
    platform: 'Platform',
    station: 'Station',
    stop_position: 'Stop position',
  },
  railway: 'Railroad',
  shop: {
    '*': 'Shop {}',
    alcohol: 'Alcohol shop',
    antiques: 'Antiques',
    art: 'Art shop',
    baby_goods: 'Baby goods',
    bag: 'Bag shop',
    bakery: 'Bakery',
    bathroom_furnishing: 'Bathroom furnishing',
    beauty: 'Beauty shop',
    bed: 'Bed store',
    beverages: 'Beverages',
    bicycle: 'Bicycle shop',
    bookmaker: 'Bookmaker',
    books: 'Book store',
    boutique: 'Boutique',
    butcher: 'Butcher',
    camera: 'Camera shop',
    car: 'Car dealership',
    car_parts: 'Car parts',
    car_repair: 'Car repair',
    carpet: 'Carpet store',
    cheese: 'Cheese shop',
    chemist: 'Drug-store, chemist',
    clothes: 'Apparel store',
    coffee: 'Coffee shop',
    collector: 'Collector',
    computer: 'Computer store',
    confectionery: 'Confectionery',
    convenience: 'Convenience store',
    copyshop: 'Copy shop',
    cosmetics: 'Cosmetics shop',
    craft: 'Craft',
    curtain: 'Curtain',
    dairy: 'Dairy',
    deli: 'Delicatessen',
    department_store: 'Department store',
    doityourself: 'Doityourself',
    doors: 'Doors shop',
    dry_cleaning: 'Dry_cleaning',
    'e-cigarette': 'E-cigarette',
    electrical: 'Electrical',
    electronics: 'Electronics',
    erotic: 'Sex shop',
    fabric: 'Textile store',
    farm: 'Shop at a farm',
    fireplace: 'Fireplace',
    fishing: 'Fishing shop',
    flooring: 'Flooring shop',
    florist: 'Florist',
    funeral_directors: 'Funeral Services',
    furniture: 'Furniture store',
    games: 'Game shop',
    garden_center: 'Gardening center',
    garden_centre: 'Garden centre',
    general: 'General shop',
    gift: 'Gift shop',
    glaziery: 'Glaziery',
    greengrocer: 'Fruit and vegetables store',
    hairdresser: 'Hairdresser',
    hardware: 'Hardware',
    health_food: 'Health food',
    hifi: 'Hifi shop',
    houseware: 'Houseware shop',
    hunting: 'Hunting shop',
    ice_cream: 'Ice cream',
    interior_decoration: 'Interior decoration shop',
    jewelry: 'Jewerly',
    kiosk: 'Kiosk',
    kitchen: 'Kitchen shop',
    laundry: 'Lanudry',
    lighting: 'Lighting shop',
    locksmith: 'Locksmith',
    lottery: 'Lottery shop',
    mall: 'Shopping center / mall',
    massage: 'Massages',
    medical_supply: 'Medical supply',
    mobile_phone: 'Mobile phone store',
    model: 'Model',
    motorcycle: 'Motorcycle',
    music: 'Music shop',
    musical_instrument: 'Musical instruments shop',
    newsagent: 'Newsagent',
    nutrition_supplements: 'Nutrition supplements shop',
    optician: 'Optics',
    outdoor: 'Outdoor',
    outpost: 'Outpost',
    paint: 'Paint shop',
    pastry: 'Pastry shop',
    pawnbroker: 'Pawnbroker',
    perfumery: 'Perfumery',
    pet: 'Pet shop',
    pet_grooming: 'Pet grooming',
    photo: 'Photo shop',
    radiotechnics: 'Radiotechnics',
    rental: 'Rental',
    seafood: 'Seafood',
    second_hand: 'Secondhand',
    sewing: 'Sewing',
    shoes: 'Shoes',
    sports: 'Sports',
    stationery: 'Stationery store',
    supermarket: 'Supermarket',
    tailor: 'Tailor',
    tattoo: 'Tattoo',
    tea: 'Tea shop',
    ticket: 'Ticket shop',
    tobacco: 'Tobacco shop',
    toys: 'Toy store',
    trade: 'Building materials store',
    travel_agency: 'Travel agency',
    tyres: 'Tyres shop',
    vacant: 'Vacant shop',
    variety_store: 'Variety store',
    video: 'Video shop',
    video_games: 'Video games shop',
    watches: 'Watches',
    wholesale: 'Wholesale',
    window_blind: 'Window blind',
    wine: 'Wine shop',
  },
  sport: {
    '*': 'Sport {}',
    '9pin': '9-pin Bowling',
    '10pin': 'Ten-pin Bowling',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'American football',
    archery: 'Archery',
    athletics: 'Athletics',
    badminton: 'Badminton',
    baseball: 'Baseball',
    basketball: 'Basketball',
    beachvolleyball: 'Beachvolleyball',
    bicycle: 'Bicycle',
    bmx: 'BMX',
    boules: 'Boules',
    bowling: 'Bowling',
    bowls: 'Bowls',
    canoe: 'Canoe',
    chess: 'Chess',
    climbing: 'Climbing',
    climbing_adventure: 'Climbing adventure',
    cycling: 'Cycling',
    darts: 'Darts',
    disc_golf: 'Disc golf',
    dog_racing: 'Dog racing',
    equestrian: 'Equestrian',
    field_hockey: 'Field hockey',
    fitness: 'Fitness',
    floorball: 'Floorball',
    free_flying: 'Free flying',
    golf: 'Golf',
    gymnastics: 'Gymnastics',
    handball: 'Handball',
    hockey: 'Hockey',
    horse_racing: 'Horse racing',
    ice_hockey: 'Ice hockey',
    ice_skating: 'Ice skating',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Karting',
    laser_tag: 'Laser tag',
    model_aerodrome: 'Model aerodrome',
    motocross: 'Motocross',
    motor: 'Motor',
    multi: 'Multi',
    netball: 'Netball',
    paintball: 'Paintball',
    petanque: 'Petanque',
    roller_skating: 'Roller skating',
    rowing: 'Rowing',
    running: 'Running',
    scuba_diving: 'Scuba_diving',
    shooting: 'Shooting',
    shooting_range: 'Shooting range',
    'shot-put': 'Shot-put',
    skateboard: 'Skateboard',
    skating: 'Skating',
    ski_jumping: 'Ski jumping',
    skiing: 'Skiing',
    soccer: 'Football / soccer',
    squash: 'Squash',
    streetball: 'Streetball',
    swimming: 'Swimming',
    table_tennis: 'Table tennis',
    tennis: 'Tennis',
    volleyball: 'Volleyball',
    water_ski: 'Water skiing',
    workout: 'Workout',
    yoga: 'Yoga',
  },
  tourism: {
    '*': '{}',
    alpine_hut: 'Alpine hut',
    apartment: 'Apartment',
    artwork: {
      '*': 'Art',
      artwork_type: {
        architecture: 'Architecture',
        bust: 'Bust',
        graffiti: 'Graffiti',
        installation: 'Installation art',
        mosaic: 'Tilework',
        mural: 'Mural',
        painting: 'Painting',
        relief: 'Relief (artwork)',
        sculpture: 'Sculpture',
        statue: 'Statue',
        stone: 'Boulder (artwork)',
      },
    },
    attraction: 'Attraction',
    camp_site: 'Campsite',
    caravan_site: 'Caravan site',
    chalet: 'Chalet',
    guest_house: 'Guest house',
    hostel: 'Hostel',
    hotel: 'Hotel',
    information: {
      '*': 'Information',
      information: {
        '*': 'Information {}',
        board: 'Information board',
        guidepost: 'Guidepost',
        map: 'Map',
        office: 'Information office',
      },
    },
    motel: 'Motel',
    museum: 'Museum',
    picnic_site: 'Picnic site',
    viewpoint: 'Viewpoint',
    wilderness_hut: 'Wilderness hut',
    zoo: 'ZOO',
  },
  type: {
    route: {
      '*': 'Trail',
      route: {
        '*': 'Trail {}',
        bicycle: 'Bicycle trail',
        bus: 'Bus way',
        foot: 'Pedestrian trail',
        hiking: 'Hiking trail',
        horse: 'Equestrian path',
        mtb: 'Mountain biking trail',
        piste: 'Ski slope or path',
        railway: 'Railway',
        ski: 'Ski trail',
        tram: 'Tramway',
      },
    },
  },
  waterway: {
    '*': 'Waterway {}',
    canal: 'Canal',
    dam: 'Dam',
    ditch: 'Ditch (waterway)',
    drain: 'Drain',
    river: 'River',
    stream: 'Creek, stream',
    waterfall: 'Waterfall',
    weir: 'Weir',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Rosso',
  blue: 'Blu',
  green: 'Verde',
  yellow: 'Giallo',
  orange: 'Arancio',
  purple: 'Porpora',
  violet: 'Viola',
  white: 'Bianco',
  black: 'Nero',
  gray: 'Grigio',
  brown: 'Marrone',
};
