import type { DeepPartial } from '@shared/types/deepPartial.js';
import type { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  aeroway: {
    aerodrome: 'Flughafen',
    airstrip: 'Flugpiste',
    apron: 'Vorfeld',
    gate: 'Fluggastbrücke/Gate',
    hangar: 'Flugzeughangar',
    helipad: 'Hubschrauberlandeplatz',
    holding_position: 'Warteposition',
    jet_bridge: 'Fluggastbrücke',
    navigationaid: 'Flugnavigationshilfe',
    parking_position: 'Flugzeugstandplatz',
    runway: 'Start- und Landebahn',
    stopway: 'Pistenstopfläche',
    taxilane: 'Rollspur',
    taxiway: 'Rollweg',
    terminal: 'Flughafenterminal',
    threshold: 'Pistenschwelle',
    tower: 'Flugkontrollturm',
    windsock: 'Windsack',
  },

  amenity: {
    exhibition_centre: 'Ausstellungszentrum',
    letter_box: 'Hausbriefkasten',
    loading_dock: 'Laderampe',
    lounger: 'Liege',
    public_bath: 'Öffentliches Bad',
    public_building: 'Öffentliches Gebäude',
    shelter: {
      shelter_type: {
        picnic_shelter: {
          fireplace: {
            yes: 'Picknickunterstand mit Kamin',
          },
          '*': 'Picknickunterstand',
        },
        '*': 'Unterstand {}',
        basic_hut: 'Einfache Hütte',
        changing_rooms: 'Umkleideraum',
        field_shelter: 'Feldunterstand',
        lean_to: 'Anlehnunterstand',
        public_transport: 'Haltestellenunterstand',
        rock_shelter: 'Felsunterstand',
        sun_shelter: 'Sonnenschutz',
        weather_shelter: 'Wetterschutz',
      },
      '*': 'Unterstand',
    },
    social_facility: {
      social_facility: {
        ambulatory_care: 'Ambulante Pflege',
        assisted_living: 'Betreutes Wohnen',
        clothing_bank: 'Kleiderkammer',
        day_care: 'Tagesstätte',
        food_bank: 'Tafel',
        group_home: 'Gemeinschaftswohnheim',
        hospice: 'Hospiz',
        nursing_home: 'Pflegeheim',
        shelter: 'Obdach',
        soup_kitchen: 'Suppenküche',
        workshop: 'Werkstatt',
      },
      '*': 'Soziale Einrichtung',
    },
    vending_machine: {
      vending: {
        bicycle_tube: 'Fahrradschlauch-Automat',
        bread: 'Brotautomat',
        bottle_return: 'Pfandflaschenrückgabeautomat',
        candles: 'Kerzenautomat',
        chewing_gums: 'Kaugummi-Automat',
        cigarettes: 'Zigarettenautomat',
        coffee: 'Kaffeeautomat',
        condoms: 'Kondomautomat',
        drinks: 'Getränkeautomat',
        elongated_coin: 'Souvenir-Münzautomat',
        eggs: 'Eierautomat',
        excrement_bags: 'Hundekotbeutelautomat',
        food: 'Lebensmittelautomat',
        fuel: 'Kraftstoffautomat',
        gas: 'Gasautomat',
        ice_cream: 'Eisautomat',
        ice_cubes: 'Eiswürfelautomat',
        milk: 'Milchautomat',
        movies: 'Filmautomat',
        newspapers: 'Zeitungsautomat',
        parking_tickets: 'Parkscheinautomat',
        pizza: 'Pizzaautomat',
        public_transport_tickets: 'Fahrkartenautomat',
        stamps: 'Briefmarkenautomat',
        sweets: 'Süßigkeitenautomat',
        water: 'Wasserspender',
      },
      '*': 'Automat',
    },
    '*': '{}',
    animal_breeding: 'Tierhaltung',
    animal_shelter: 'Tierheim',
    arts_centre: 'Kunstzentrum',
    atm: 'Geldautomat',
    bank: 'Bank',
    bar: 'Bar',
    bbq: 'Grill',
    bench: 'Bank',
    bicycle_parking: 'Fahrradparkplatz',
    bicycle_rental: 'Fahrradverleih',
    bicycle_repair_station: 'Fahrradreparaturstation',
    biergarten: 'Biergarten',
    brothel: 'Bordell',
    bureau_de_change: 'Wechselstube',
    bus_station: 'Busbahnhof',
    cafe: 'Café',
    car_rental: 'Autovermietung',
    car_wash: 'Autowäsche',
    casino: 'Casino',
    charging_station: 'Ladestation',
    childcare: 'Kinderbetreuung',
    cinema: 'Kino',
    clinic: 'Klinik',
    clock: 'Uhr',
    college: 'Hochschule',
    community_centre: 'Gemeinschaftszentrum',
    compressed_air: 'Druckluft',
    courthouse: 'Gericht',
    dentist: 'Zahnarzt',
    device_charging_station: 'Ladestation für Geräte',
    doctors: 'Arztpraxis',
    dressing_room: 'Umkleide',
    drinking_water: 'Trinkwasser',
    driving_school: 'Fahrschule',
    embassy: 'Botschaft',
    events_venue: 'Veranstaltungsort',
    fast_food: 'Fast Food',
    feeding_place: 'Futterstelle',
    ferry_terminal: 'Fährterminal',
    fire_station: 'Feuerwache',
    food_court: 'Foodcourt',
    fountain: 'Brunnen',
    fuel: 'Tankstelle',
    funeral_hall: 'Trauerhalle',
    gambling: 'Glücksspiel',
    game_feeding: 'Wildfütterung',
    grave_yard: 'Friedhof',
    grit_bin: 'Streugutbehälter',
    hospital: 'Krankenhaus',
    hunting_stand: 'Jagdstand',
    ice_cream: 'Eis',
    kindergarten: 'Kindergarten',
    language_school: 'Sprachschule',
    library: 'Bibliothek',
    marketplace: 'Marktplatz',
    monastery: 'Kloster',
    money_transfer: 'Geldtransfer',
    motorcycle_parking: 'Motorradparkplatz',
    motorcycle_rental: 'Motorradverleih',
    nightclub: 'Nachtclub',
    parcel_locker: 'Paketfach',
    parking: 'Parkplatz',
    parking_entrance: 'Parkplatzeingang',
    parking_space: 'Parkplatz',
    pharmacy: 'Apotheke',
    place_of_mourning: 'Trauerstätte',
    place_of_worship: 'Andachtsstätte',
    planetarium: 'Planetarium',
    police: 'Polizei',
    post_box: 'Briefkasten',
    post_office: 'Postamt',
    prison: 'Gefängnis',
    pub: 'Kneipe',
    public_bookcase: 'Öffentlicher Bücherschrank',
    ranger_station: 'Rangerstation',
    recycling: 'Recycling',
    restaurant: 'Restaurant',
    school: 'Schule',
    shower: 'Dusche',
    ski_rental: 'Skiverleih',
    smoking_area: 'Raucherbereich',
    social_centre: 'Soziales Zentrum',
    stripclub: 'Stripclub',
    studio: 'Studio',
    taxi: 'Taxi',
    telephone: 'Telefon',
    theatre: 'Theater',
    toilets: 'WC',
    townhall: 'Rathaus',
    traffic_park: 'Verkehrsübungsplatz',
    trolley_bay: 'Einkaufswagenstellplatz',
    university: 'Universität',
    vacuum_cleaner: 'Staubsauger',
    vehicle_inspection: 'Fahrzeugprüfung',
    veterinary: 'Tierarzt',
    waste_basket: 'Mülleimer',
    waste_disposal: 'Abfallentsorgung',
    water_point: 'Wasserstelle',
    watering_place: 'Tränkestelle',
  },

  barrier: {
    '*': 'Barriere {}',
    block: 'Blockade',
    bollard: 'Poller',
    border_control: 'Grenzkontrolle',
    cable_barrier: 'Kabelschutzplanke',
    chain: 'Kette',
    city_wall: 'Stadtmauer',
    ditch: 'Graben (Barriere)',
    entrance: 'Eingang',
    fence: 'Zaun',
    gate: 'Tor',
    guard_rail: 'Leitplanke',
    handrail: 'Handlauf',
    hedge: 'Hecke',
    kerb: 'Bordstein',
    lift_gate: 'Schranke',
    rope: 'Seil',
    sliding_gate: 'Schiebetor',
    swing_gate: 'Drehtor',
    turnstile: 'Drehkreuz',
    wall: 'Mauer',
    retaining_wall: 'Stützmauer',
  },

  boundary: {
    aboriginal_lands: 'Gebiet indigener Völker',
    administrative: {
      admin_level: {
        '2': 'Land',
        '3': 'Region',
        '4': 'Bezirk',
        '5': 'Provinz',
        '6': 'Stadt',
        '7': 'Region',
        '8': 'Bezirk',
        '9': 'Dorf',
        '10': 'Katastergebiet',
      },
      '*': 'Verwaltungsregion',
    },
    '*': 'Region',
    cadastral: 'Katastergrenze',
    census: 'Zensusgebiet',
    forest_compartment: 'Waldabteilung',
    forest_planning: 'Forstplanungseinheit',
    'geomorphological-unit': 'Geomorphologische Einheit',
    health: 'Gesundheitsbezirk',
    local_authority: 'Kommunalverwaltungsgebiet',
    maritime: 'Seegrenze',
    marker: 'Grenzstein',
    national_park: 'Nationalpark',
    political: 'Wahlkreis',
    postal_code: 'Postleitzahlgebiet',
    protected_area: 'Schutzgebiet',
    religious_administration: 'Kirchlicher Verwaltungsbezirk',
    statistical: 'Statistikgebiet',
    water_protection_area: 'Wasserschutzgebiet',
  },

  building: {
    '*': {
      '*': 'Gebäude',

      abandoned: {
        yes: 'Aufgegebenes Gebäude',
      },

      disused: {
        yes: 'Stillgelegtes Gebäude',
      },

      ruins: {
        yes: 'Gebäuderuine',
      },
    },

    agricultural: 'Landwirtschaftsgebäude',
    allotment_house: 'Gartenlaube',
    apartments: 'Wohnungen (Block)',
    barn: 'Scheune',
    boathouse: 'Bootshaus',
    bungalow: 'Bungalow',
    bunker: 'Bunker',
    cabin: 'Hütte',
    carport: 'Carport',
    cathedral: 'Kathedrale',
    chapel: 'Kapelle',
    church: 'Kirche',
    civic: 'Öffentliches Gebäude',
    collapsed: 'Eingestürztes Gebäude',
    college: 'Collegegebäude',
    commercial: 'Gewerbegebäude',
    construction: 'Gebäude im Bau',
    container: 'Containergebäude',
    cowshed: 'Kuhstall',
    detached: 'Freistehendes Haus',
    dormitory: 'Schlafsaal',
    entrance: 'Gebäudeeingang',
    farm_auxiliary: 'Nebengebäude eines Bauernhofs',
    farm: 'Bauernhof',
    fire_station: 'Feuerwehrgebäude',
    garage: 'Garage',
    garages: 'Garagen',
    government: 'Regierungsgebäude',
    grandstand: 'Tribüne',
    greenhouse: 'Gewächshaus',
    hangar: 'Hangar',
    hayloft: 'Heuboden',
    historic: 'Historisches Gebäude',
    hospital: 'Krankenhausgebäude',
    hotel: 'Hotelgebäude',
    house: 'Privathaus',
    houseboat: 'Hausboot',
    hut: 'Hütte',
    industrial: 'Industriegebäude',
    kindergarten: 'Kindergartengebäude',
    kiosk: 'Kiosk',
    manufacture: 'Fabrikgebäude',
    mosque: 'Moschee',
    office: 'Bürogebäude',
    outbuilding: 'Nebengebäude',
    parking: 'Parkhaus',
    pavilion: 'Pavillon',
    public: 'Öffentliches Gebäude',
    residential: 'Wohnhaus',
    retail: 'Geschäftsgebäude',
    roof: 'Dach',
    ruins: 'Gebäuderuine',
    school: 'Schulgebäude',
    semidetached_house: 'Doppelhaushälfte',
    service: 'Servicegebäude',
    shed: 'Schuppen',
    shrine: 'Schrein',
    silo: 'Silo',
    sports_centre: 'Sportzentrumsgebäude',
    sports_hall: 'Sporthalle',
    stable: 'Stall',
    static_caravan: 'Mobilheim, Wohnwagen',
    storage_tank: 'Lagerbehälter',
    sty: 'Schweinestall',
    supermarket: 'Supermarktgebäude',
    synagogue: 'Synagoge',
    temple: 'Tempel',
    tent: 'Dauerzelt',
    terrace: 'Reihenhaus',
    toilets: 'Toilettengebäude',
    train_station: 'Bahnhof',
    transformer_tower: 'Umspannwerk',
    transportation: 'Verkehrsgebäude',
    university: 'Universitätsgebäude',
    warehouse: 'Lagerhaus',
    yes: 'Unbestimmtes Gebäude',
    abandoned: 'Aufgegebenes Gebäude',
    disused: 'Stillgelegtes Gebäude',
    stadium: 'Stadiongebäude',
  },

  club: {
    '*': 'Verein',
    automobile: 'Automobilclub',
    charity: 'Wohltätigkeitsverein',
    culture: 'Kulturverein',
    fishing: 'Angelverein',
    hunting: 'Jagdverein',
    music: 'Musikverein',
    nature: 'Naturschutzverein',
    scout: 'Pfadfindergruppe',
    social: 'Geselligkeitsverein',
    sport: 'Sportverein',
    veterans: 'Veteranenverein',
  },
  healthcare: {
    '*': 'Gesundheitseinrichtung',
    alternative: 'Alternativmedizin',
    audiologist: 'Hörgeräteakustiker',
    blood_donation: 'Blutspendezentrum',
    centre: 'Gesundheitszentrum',
    clinic: 'Klinik',
    counselling: 'Beratungsstelle',
    dentist: 'Zahnarzt',
    dialysis: 'Dialysezentrum',
    doctor: 'Arztpraxis',
    hospital: 'Krankenhaus',
    laboratory: 'Medizinisches Labor',
    midwife: 'Hebamme',
    nurse: 'Pflegedienst',
    optometrist: 'Optometrist',
    pharmacy: 'Apotheke',
    physiotherapist: 'Physiotherapeut',
    podiatrist: 'Podologe',
    psychotherapist: 'Psychotherapeut',
    rehabilitation: 'Rehabilitationszentrum',
    speech_therapist: 'Logopäde',
  },
  highway: {
    '*': 'Straße {}',
    bridleway: 'Reitweg',
    bus_stop: 'Bushaltestelle',
    busway: 'Busspur',
    construction: 'Straße im Bau',
    corridor: 'Gebäudekorridor',
    crossing: 'Fußgängerüberweg',
    cycleway: 'Radweg',
    elevator: 'Aufzug',
    emergency_access_point: 'Rettungspunkt',
    emergency_bay: 'Nothaltebucht',
    escape: 'Notbremsspur',
    footway: 'Gehweg',
    give_way: 'Vorfahrt gewähren',
    hitchhiking: 'Trampplatz',
    ladder: 'Leiter',
    living_street: 'Wohnstraße',
    milestone: 'Kilometerstein',
    mini_roundabout: 'Minikreisverkehr',
    motorway: 'Autobahn',
    motorway_junction: 'Autobahnausfahrt',
    motorway_link: 'Autobahnanschluss',
    passing_place: 'Ausweichstelle',
    path: {
      '*': 'Pfad',
      foot: {
        designated: {
          bicycle: {
            designated: 'Gemeinsamer Geh- und Radweg',
          },
        },
      },
    },
    pedestrian: 'Fußgängerzone',
    piste: 'Ski-/Pistenweg',
    platform: 'Bahnsteig',
    primary: 'Hauptstraße',
    primary_link: 'Anschluss Hauptstraße',
    priority: 'Vorfahrtschild',
    proposed: 'Geplante Straße',
    raceway: 'Rennstrecke',
    residential: 'Straße',
    rest_area: 'Rastplatz',
    road: 'Straße unbekannter Art',
    secondary: 'Nebenstraße',
    secondary_link: 'Anschluss Nebenstraße',
    service: {
      service: {
        '*': 'Servicestraße {}',
        alley: 'Gasse',
        bus: 'Busstraße',
        'drive-through': 'Drive-through',
        driveway: 'Zufahrt',
        emergency_access: 'Feuerwehrzufahrt',
        parking_aisle: 'Parkgasse',
      },
      '*': 'Servicezufahrt',
    },
    services: 'Autobahnraststätte',
    speed_camera: 'Blitzer',
    speed_display: 'Geschwindigkeitsanzeige',
    steps: 'Treppen',
    stop: 'Stoppschild',
    street_lamp: 'Straßenlaterne',
    tertiary: 'Tertiärstraße',
    tertiary_link: 'Anschluss Tertiärstraße',
    toll_gantry: 'Mautbrücke',
    track: {
      tracktype: {
        grade1: 'Verdichteter Waldweg',
        grade2: 'Überwiegend verdichteter Waldweg',
        grade3: 'Weniger fester, unbefestigter Waldweg',
        grade4: 'Waldweg befahrbar mit Traktor oder ähnlichen Fahrzeugen',
        grade5: 'Kaum erkennbarer Waldweg',
      },
      '*': 'Waldweg',
    },
    traffic_calming: 'Verkehrsberuhigung',
    traffic_island: 'Verkehrsinsel',
    traffic_mirror: 'Verkehrsspiegel',
    traffic_sign: 'Verkehrszeichen',
    traffic_signals: 'Ampel',
    trailhead: 'Wanderwegeinstieg',
    trunk: 'Fernstraße',
    trunk_link: 'Fernstraßenanschluss',
    turning_circle: 'Wendehammer',
    turning_loop: 'Wendeschleife',
    unclassified: 'unklassifizierte Straße',
    via_ferrata: 'Klettersteig',
  },

  historic: {
    battlefield: 'Schlachtfeld',
    bomb_crater: 'Bombenkrater',
    bunker: 'Historischer Bunker',
    dome: 'Historische Kuppel',
    quarry: 'Historischer Steinbruch',
    railway: 'Historische Eisenbahn',
    railway_station: 'Historischer Bahnhof',
    roman_road: 'Römerstraße',
    ruins: {
      ruins: {
        castle: 'Burgruine',
      },
      '*': 'Ruinen',
    },

    '*': 'Historische Struktur',
    archaeological_site: 'Archäologische Fundstätte',
    castle: 'Burg',
    church: 'Historische Kirche',
    city_gate: 'Stadttor',
    manor: 'Herrenhaus',
    memorial: 'Gedenkstätte',
    monastery: 'Kloster',
    monument: 'Denkmal',
    tomb: 'Grab',
    tower: 'Historischer Turm',
    wayside_cross: 'Bildstock',
    wayside_shrine: 'Feldkapelle',
    yes: 'Historisches Bauwerk',
    aircraft: 'Historisches Flugzeug',
    boundary_stone: 'Historischer Grenzstein',
    building: 'Historisches Gebäude',
    cannon: 'Historische Kanone',
    charcoal_pile: 'Kohlenmeilerplatz',
    citywalls: 'Stadtmauer',
    fort: 'Fort',
    heritage: 'Kulturerbestätte',
    hollow_way: 'Hohlweg',
    house: 'Historisches Haus',
    milestone: 'Historischer Meilenstein',
    mine_shaft: 'Historischer Schacht',
    mine: 'Historisches Bergwerk',
    shieling: 'Almhütte (saisonal)',
    stone: 'Historischer Stein',
    tree_shrine: 'Baumheiligtum',
    wreck: 'Schiffswrack',
  },

  junction: {
    '*': 'Knotenpunkt',
    circular: 'Kreisverkehr',
    intersection: 'Straßenkreuzung',
    jughandle: 'Jughandle',
    roundabout: 'Kreisverkehr',
  },
  landuse: {
    '*': '{}',
    allotments: 'Kleingärten',
    animal_keeping: 'Tierhaltung',
    apiary: 'Bienenstandfläche',
    aquaculture: 'Aquakultur',
    basin: 'Becken',
    brownfield: 'Brachfläche',
    cemetery: 'Friedhof',
    churchyard: 'Kirchhof',
    civic: 'Öffentliches Grundstück',
    civic_admin: 'Verwaltungsgrundstück',
    commercial: 'Gewerbegebiet',
    conservation: 'Schutzgebiet',
    construction: 'Baustelle',
    culture: 'Kulturgelände',
    depot: 'Betriebshof',
    education: 'Bildungszone',
    emergency: 'Gelände der Rettungsdienste',
    fairground: 'Festplatz',
    farm: 'Landwirtschaftsfläche',
    farmland: 'Ackerland',
    farmyard: 'Hof',
    flowerbed: 'Blumenbeet',
    forest: 'Wald',
    forestry: 'Forstfläche',
    garages: 'Garagen',
    garden: 'Gartenfläche',
    grass: 'Gras',
    greenery: 'Grünanlage',
    greenfield: 'Grünfläche',
    greenhouse_horticulture: 'Gewächshausanbau',
    harbour: 'Hafengelände',
    healthcare: 'Gesundheitsgelände',
    highway: 'Straßenfläche',
    houseboat: 'Hausbootliegeplatz',
    industrial: 'Industriegebiet',
    institutional: 'Institutionelles Grundstück',
    landfill: 'Mülldeponie',
    logging: 'Holzeinschlag',
    meadow: 'Wiese',
    military: 'Militärgebiet',
    mine_spoils: 'Abraumfläche',
    orchard: 'Obstgarten',
    paddock: 'Koppel',
    peat_cutting: 'Torfstich',
    pedestrian: 'Fußgängerbereich',
    piste: 'Pistenfläche',
    plant_nursery: 'Pflanzschule',
    plantation: 'Plantage',
    quarry: 'Steinbruch',
    railway: 'Eisenbahnfläche',
    recreation_ground: 'Erholungsgebiet',
    religious: 'Kirchliches Grundstück',
    reservoir: 'Stausee',
    residential: 'Wohngebiet',
    retail: 'Einzelhandel',
    salt_pond: 'Salzbecken',
    school: 'Schulgelände',
    shrubs: 'Sträucher',
    static_caravan: 'Dauercampingplatz',
    storage: 'Lagerfläche',
    tourism: 'Tourismusgelände',
    traffic_island: 'Verkehrsinselfläche',
    tree_pit: 'Baumscheibe',
    village_green: 'Dorfanger',
    vineyard: 'Weinberg',
    wasteland: 'Ödland',
    winter_sports: 'Wintersportgebiet',
  },

  leisure: {
    '*': '{}',

    common: 'Allmende',
    hot_tub: 'Whirlpool',
    indoor_play: 'Indoorspielplatz',
    picnic_table: {
      covered: {
        yes: 'Überdachter Picknicktisch',
        no: 'Unüberdachter Picknicktisch',
      },
      '*': 'Picknicktisch',
    },

    pitch: 'Spielfeld',
    bleachers: 'Tribüne',
    escape_game: 'Escape Room',
    hackerspace: 'Hackerspace',
    ice_rink: 'Eisbahn',
    marina: 'Marina',
    miniature_golf: 'Minigolf',
    dog_park: 'Hundespielplatz',
    firepit: 'Feuerstelle',
    fishing: 'Angelplatz',
    fitness_centre: 'Fitnesscenter',
    fitness_station: 'Fitnessstation',
    garden: 'Garten',
    golf_course: 'Golfplatz',
    horse_riding: 'Reiten',
    nature_reserve: 'Naturschutzgebiet',
    park: 'Park',
    playground: 'Spielplatz',
    recreation_ground: 'Freizeitgelände',
    schoolyard: 'Schulhof',
    sports_centre: 'Sportzentrum',
    sports_hall: 'Sporthalle',
    stadium: 'Stadion',
    swimming_pool: 'Schwimmbad',
    track: {
      '*': 'Bahn',
      sport: {
        cycling: 'Radrennbahn',
        equestrian: 'Reitbahn',
        horse_racing: 'Pferderennbahn',
      },
    },
    water_park: 'Wasserpark',
    adult_gaming_centre: 'Spielhalle für Erwachsene',
    amusement_arcade: 'Spielhalle',
    bandstand: 'Musikpavillon',
    bathing_place: 'Badestelle',
    beach_resort: 'Strandbad',
    bird_hide: 'Vogelbeobachtungshütte',
    bowling_alley: 'Bowlingbahn',
    dance: 'Tanzfläche',
    disc_golf_course: 'Discgolf-Anlage',
    high_ropes_course: 'Hochseilgarten',
    outdoor_seating: 'Außensitzbereich',
    resort: 'Freizeitanlage',
    slipway: 'Bootsrampe',

    sauna: {
      '*': 'Sauna',

      sauna: {
        hot: 'Finnische Sauna',
        steam: 'Dampfsauna (Türkisches Bad)',
        smoke: 'Rauchsauna (finnisch)',
        dry: 'Trockensauna',
        hanjeungmak: 'Hanjeungmak (koreanische Sauna)',
        aroma: 'Aromasauna',
        infrared: 'Infrarotsauna',
      },
    },

    summer_camp: 'Sommercamp',
    sunbathing: 'Sonnenbadbereich',
    swimming_area: 'Schwimmbereich',
    tanning_salon: 'Solarium',
    trampoline_park: 'Trampolinpark',
    wildlife_hide: 'Wildbeobachtungshütte',
  },

  lock: {
    '*': 'Schleuse',
  },
  man_made: {
    breakwater: 'Wellenbrecher',
    quay: 'Kai',
    tower: {
      'tower:type': {
        bell_tower: 'Glockenturm',
        communication: 'Kommunikationsturm',
        cooling: 'Kühlturm',
        observation: 'Aussichtsturm',
        climbing: 'Kletterturm',
        clock: 'Uhrturm',
        defensive: 'Wehrturm',
        diving: 'Sprungturm',
        hose: 'Schlauchtrockenturm',
        lighting: 'Beleuchtungsturm',
        minaret: 'Minaret',
        monitoring: 'Überwachungsturm',
        pagoda: 'Pagodenturm',
        radar: 'Radarturm',
        siren: 'Sirenenturm',
        watchtower: 'Wachturm',
      },
      '*': 'Turm',
    },

    '*': '{}',

    adit: {
      '*': 'Stollen',

      disused: {
        yes: 'Stillgelegter Stollen',
      },
    },

    antenna: 'Antenne',
    beacon: 'Leuchtturm',
    beehive: 'Bienenstock',
    bridge: 'Brücke',
    bunker_silo: 'Bunkersilo',
    cairn: 'Steinmarkierung',
    cellar_entrance: 'Kellerzugang',
    chimney: 'Schornstein',
    clearcut: 'Rodung',
    communications_tower: 'Kommunikationsturm',
    cooling_tower: 'Kühlturm',
    crane: 'Kran',
    cross: 'Kreuz',
    cutline: 'Schneise',
    dyke: 'Deich',
    embankment: 'Damm',
    flagpole: 'Fahnenmast',
    "forester's_lodge": 'Forsthaus',
    gasometer: 'Gasometer',
    goods_conveyor: 'Förderband',
    groyne: 'Wellenbrecher',
    lighthouse: 'Leuchtturm',
    manhole: 'Schacht',

    mast: {
      '*': 'Mast',

      'tower:type': {
        clock: 'Uhrmast',
        communication: 'Kommunikationsmast',
        lighting: 'Beleuchtungsmast',
        monitoring: 'Überwachungsmast',
        radar: 'Radarmast',
        siren: 'Sirenenmast',
      },
    },

    mineshaft: {
      '*': 'Bergwerkschacht',

      disused: {
        yes: 'Stillgelegter Bergwerkschacht',
      },
    },

    monitoring_station: 'Überwachungsstation',
    nesting_site: 'Nistplatz',
    observatory: 'Observatorium',
    pier: 'Pier',

    pipeline: {
      '*': 'Pipeline',

      location: {
        underground: 'Unterirdische Pipeline',
        underwater: 'Unterwasserpipeline',
      },
    },

    reservoir_covered: 'Überdachtes Reservoir',
    silo: 'Silo',
    snow_cannon: 'Schneekanone',
    spoil_heap: 'Abraumhalde',
    spring_box: 'Quellschutz',
    storage_tank: 'Lagertank',
    street_cabinet: 'Straßenschrank',
    surveillance: 'Überwachungskamera',
    survey_point: 'Vermessungspunkt',
    telescope: 'Teleskop',
    tunnel: 'Versorgungstunnel',
    utility_pole: 'Strommast',
    wastewater_plant: 'Kläranlage',
    water_tap: 'Wasserhahn',
    water_tower: 'Wasserturm',
    water_well: 'Brunnen',
    water_works: 'Wasserwerk',
    watermill: 'Wassermühle',
    windmill: 'Windmühle',
    works: 'Fabrik',
    apiary: 'Bienenstand',
    pumping_station: 'Pumpstation',
  },

  natural: {
    arete: 'Grat',
    cape: 'Kap',
    crevasse: 'Gletscherspalte',
    dune: 'Düne',
    grass: 'Grasfläche',
    hill: 'Hügel',
    isthmus: 'Landenge',
    land: 'Landfläche',
    landform: 'Landform',
    peninsula: 'Halbinsel',
    plain: 'Ebene',
    reef: 'Riff',
    shoal: 'Untiefe',
    shrubbery: 'Ziersträucher',
    spring: {
      drinking_water: {
        yes: 'Trinkquelle',
        no: 'Nicht trinkbare Quelle',
      },

      refitted: {
        yes: 'Ausgebaute Quelle',
        no: 'Unausgebaute Quelle',
      },

      '*': 'Quelle',

      intermittent: {
        yes: 'Zeitweise Quelle',
      },

      seasonal: {
        yes: 'Saisonale Quelle',
      },

      water_characteristic: {
        '*': 'Mineralquelle',
      },
    },
    strait: 'Meerenge',
    tree: {
      protected: {
        yes: 'Geschützter Baum',
      },
      denotation: {
        natural_monument: 'Naturdenkmalbaum',
        landmark: 'Markanter Baum',
        avenue: 'Allee-Baum',
        urban: 'Stadtbaum',
        agricultural: 'Nutzbaum',
      },
      '*': 'Baum',
    },
    '*': '{}',
    arch: 'Felsbogen',
    bare_rock: 'Fels',
    basin: 'Becken',
    bay: 'Bucht',
    beach: 'Strand',
    birds_nest: 'Vogelnest',
    cave_entrance: 'Höhle',
    cliff: 'Klippe',
    earth_bank: 'Erdwall',
    fell: 'Hochmoor',
    geyser: 'Geysir',
    glacier: 'Gletscher',
    grassland: 'Grasland',
    gully: 'Rinne',
    heath: 'Heide',
    hot_spring: 'Heißquelle',
    landslide: 'Erdrutsch',
    mountain_range: 'Gebirgskette',
    mud: 'Schlamm',
    peak: 'Gipfel',
    plateau: 'Hochebene',
    ridge: 'Grat',
    rock: 'Fels',
    saddle: 'Sattel',
    sand: 'Sand',
    scree: 'Schutt',
    scrub: 'Buschwerk',
    shingle: 'Kiesstrand',
    shrub: 'Strauch',
    sinkhole: 'Dolinen',
    stone: 'Felsblock',
    tree_group: 'Baumgruppe',
    tree_row: 'Baumreihe',
    tree_stump: 'Baumstumpf',
    valley: 'Tal',
    water: {
      '*': 'Gewässer',

      water: {
        basin: 'Becken',
        canal: 'Kanal',
        ditch: 'Graben',
        drain: 'Entwässerungsgraben',
        fish_pass: 'Fischtreppe',
        lagoon: 'Lagune',
        lake: 'See',
        moat: 'Wassergraben',
        oxbow: 'Altarm',
        pond: 'Teich',
        reflecting_pool: 'Wasserspiegelbecken',
        reservoir: 'Stausee',
        river: 'Fluss',
        salt_pond: 'Salzteich',
        stream: 'Bach',
        stream_pool: 'Kolk',
        wastewater: 'Abwasserbecken',
      },
    },
    wetland: {
      '*': 'Feuchtgebiet',
      wetland: {
        bog: 'Hochmoor',
        reedbed: 'Schilfgebiet',
        marsh: 'Sumpf',
        swamp: 'Moor',
        wet_meadow: 'Feuchtwiese',
        mangrove: 'Mangrove',
        fen: 'Niedermoor',
      },
    },
    wood: 'Wald',
    volcano: 'Vulkan',
  },
  obstacle: {
    '*': 'Hindernis {}',
    vegetation: 'Dichter Bewuchs',
    fallen_tree: 'Umgestürzter Baum / Bäume',
    unevenness: 'Unebenheit',
    precipice: 'Steilabfall',
    heap: 'Haufen',
    hole: 'Loch',
    mud: 'Schlamm',
  },
  office: {
    '*': 'Büro',
    accountant: 'Steuerbüro',
    advertising_agency: 'Werbeagentur',
    architect: 'Architekturbüro',
    association: 'Verein',
    company: 'Firmenbüro',
    consulting: 'Unternehmensberatung',
    coworking: 'Coworking-Space',
    diplomatic: 'Diplomatische Vertretung',
    educational_institution: 'Bildungseinrichtung',
    employment_agency: 'Arbeitsvermittlung',
    energy_supplier: 'Energieversorger',
    estate_agent: 'Immobilienbüro',
    financial: 'Finanzdienstleister',
    financial_advisor: 'Finanzberatung',
    forestry: 'Forstamt',
    government: 'Behörde',
    insurance: 'Versicherungsbüro',
    it: 'IT-Unternehmen',
    lawyer: 'Rechtsanwalt',
    logistics: 'Logistikunternehmen',
    newspaper: 'Zeitungsredaktion',
    ngo: 'Nichtregierungsorganisation',
    notary: 'Notar',
    political_party: 'Parteibüro',
    property_management: 'Hausverwaltung',
    religion: 'Kirchenverwaltung',
    research: 'Forschungseinrichtung',
    security: 'Sicherheitsdienst',
    tax_advisor: 'Steuerberater',
    telecommunication: 'Telekommunikationsbüro',
    travel_agent: 'Reisebüro',
    union: 'Gewerkschaftsbüro',
    water_utility: 'Wasserwerk-Verwaltung',
  },
  place: {
    '*': 'Ort {}',
    allotments: 'Kleingartensiedlung',
    archipelago: 'Archipel',
    borough: 'Stadtbezirk',
    cadastral_community: 'Katastralgemeinde',
    city: 'Stadt',
    city_block: 'Häuserblock',
    civil_parish: 'Zivilgemeinde',
    country: 'Land',
    county: 'Landkreis',
    croft: 'Kleinbauernhof',
    district: 'Bezirk',
    farm: 'Bauernhof',
    hamlet: 'Weiler',
    island: 'Insel',
    islet: 'Inselchen',
    isolated_dwelling: 'Einzelhof',
    locality: 'Ortslage',
    municipality: 'Gemeinde',
    neighbourhood: 'Nachbarschaft',
    ocean: 'Ozean',
    plot: 'Grundstück',
    province: 'Provinz',
    quarter: 'Stadtviertel',
    region: 'Region',
    sea: 'Meer',
    square: 'Platz',
    state: 'Bundesland',
    subdivision: 'Ortsteil',
    suburb: 'Vorort',
    town: 'Städtchen',
    township: 'Township',
    village: 'Dorf',
    // Not real OSM tags: Nominatim classifies address objects, address
    // interpolations and computed postcode areas this way, and Photon falls back
    // to `yes` for a class it cannot use. See doc/photon-geocoder.md.
    house: 'Adresse',
    house_number: 'Adresse',
    postcode: 'Postleitzahl',
    yes: 'Ort',
  },

  power: {
    '*': '{}',
    generator: {
      '*': 'Generator',

      'generator:source': {
        nuclear: {
          '*': 'Kernenergie-Stromgenerator',

          'generator:method': {
            fission: 'Kernspaltungs-Stromgenerator',
            fusion: 'Kernfusions-Stromgenerator',
          },
        },

        wind: {
          '*': 'Windkraft-Stromgenerator',
        },

        hydro: {
          '*': 'Wasserkraft-Stromgenerator',

          'generator:method': {
            'water-storage': 'Speicherwasser-Stromgenerator',
            'water-pumped-storage': 'Pumpspeicher-Stromgenerator',
            'run-of-the-river': 'Laufwasser-Stromgenerator',
          },
        },

        tidal: {
          '*': 'Gezeiten-Stromgenerator',

          'generator:method': {
            barrage: 'Gezeitenkraftwerks-Stromgenerator (Staudamm)',
            stream: 'Gezeitenströmungs-Stromgenerator',
          },
        },

        wave: {
          '*': 'Wellenenergie-Stromgenerator',
        },

        geothermal: {
          '*': 'Geothermie-Stromgenerator',
        },

        solar: {
          '*': 'Solarstrom-Generator',

          'generator:method': {
            thermal: 'Solarthermie-Stromgenerator',
            photovoltaic: 'Photovoltaik-Stromgenerator',
          },
        },

        coal: {
          '*': 'Kohle-Stromgenerator',
        },

        gas: {
          '*': 'Gas-Stromgenerator',
        },

        biomass: {
          '*': 'Biomasse-Stromgenerator',

          'generator:method': {
            combustion: 'Biomasse-Stromgenerator mit Verbrennung',
            gasification: 'Biomasse-Stromgenerator mit Vergasung',
            anaerobic_digestion:
              'Biomasse-Stromgenerator mit anaerober Vergärung',
          },
        },

        biofuel: {
          '*': 'Biokraftstoff-Stromgenerator',
        },

        biogas: {
          '*': 'Biogas-Stromgenerator',
        },

        oil: {
          '*': 'Öl-Stromgenerator',
        },

        diesel: {
          '*': 'Diesel-Stromgenerator',
        },

        gasoline: {
          '*': 'Benzin-Stromgenerator',
        },

        waste: {
          '*': 'Abfall-zu-Energie-Stromgenerator',

          'generator:method': {
            combustion: 'Abfallverbrennungs-Stromgenerator',
            gasification: 'Abfallvergasungs-Stromgenerator',
          },
        },
      },
    },
    line: 'Stromleitung',
    minor_line: 'Nebenstromleitung',
    plant: {
      '*': 'Kraftwerk',

      'plant:source': {
        nuclear: {
          '*': 'Kernkraftwerk',

          'plant:method': {
            fission: 'Kernspaltungskraftwerk',
            fusion: 'Kernfusionskraftwerk',
          },
        },

        wind: {
          '*': 'Windkraftwerk',
        },

        hydro: {
          '*': 'Wasserkraftwerk',

          'plant:method': {
            'water-storage': 'Speicherkraftwerk',
            'water-pumped-storage': 'Pumpspeicherkraftwerk',
            'run-of-the-river': 'Laufwasserkraftwerk',
          },
        },

        tidal: {
          '*': 'Gezeitenkraftwerk',

          'plant:method': {
            barrage: 'Gezeitenkraftwerk mit Staudamm',
            stream: 'Gezeitenströmungskraftwerk',
          },
        },

        wave: {
          '*': 'Wellenkraftwerk',
        },

        geothermal: {
          '*': 'Geothermiekraftwerk',
        },

        solar: {
          '*': 'Solarkraftwerk',

          'plant:method': {
            thermal: 'Solarthermie-Kraftwerk',
            photovoltaic: 'Photovoltaik-Kraftwerk',
          },
        },

        coal: {
          '*': 'Kohlekraftwerk',
        },

        gas: {
          '*': 'Gaskraftwerk',
        },

        biomass: {
          '*': 'Biomassekraftwerk',

          'plant:method': {
            combustion: 'Biomassekraftwerk mit Verbrennung',
            gasification: 'Biomassekraftwerk mit Vergasung',
            anaerobic_digestion: 'Biomassekraftwerk mit anaerober Vergärung',
          },
        },

        biofuel: {
          '*': 'Biokraftstoff-Kraftwerk',
        },

        biogas: {
          '*': 'Biogaskraftwerk',
        },

        oil: {
          '*': 'Ölkraftwerk',
        },

        diesel: {
          '*': 'Dieselkraftwerk',
        },

        gasoline: {
          '*': 'Benzinkraftwerk',
        },

        waste: {
          '*': 'Müllheizkraftwerk',

          'plant:method': {
            combustion: 'Abfallverbrennungskraftwerk',
            gasification: 'Abfallvergasungskraftwerk',
          },
        },
      },
    },
    pole: 'Strommast',
    substation: 'Umspannwerk',
    tower: 'Stromturm',
    transformer: 'Transformator',
  },

  public_transport: {
    platform: 'Bahnsteig',
    station: 'Station',
    stop_position: 'Haltestelle',
  },

  shop: {
    '*': 'Geschäft {}',
    agrarian: 'Landhandel',
    household_linen: 'Haushaltswäsche',
    charity: 'Wohltätigkeitsladen',
    chocolate: 'Schokoladengeschäft',
    fashion_accessories: 'Modezubehörgeschäft',
    frozen_food: 'Tiefkühlkostladen',
    hearing_aids: 'Hörgerätegeschäft',
    storage_rental: 'Lagerraumvermietung',
    telecommunication: 'Telekommunikationsgeschäft',
    weapons: 'Waffenladen',
    alcohol: 'Alkoholgeschäft',
    antiques: 'Antiquitäten',
    art: 'Kunstladen',
    baby_goods: 'Babybedarf',
    bag: 'Taschengeschäft',
    bakery: 'Bäckerei',
    bathroom_furnishing: 'Badausstattung',
    beauty: 'Kosmetikgeschäft',
    bed: 'Bettengeschäft',
    beverages: 'Getränkeladen',
    bicycle: 'Fahrradladen',
    bookmaker: 'Wettbüro',
    books: 'Buchhandlung',
    boutique: 'Boutique',
    butcher: 'Metzgerei',
    camera: 'Kamera Geschäft',
    car: 'Autohändler',
    car_parts: 'Autoteile',
    car_repair: 'Autowerkstatt',
    carpet: 'Teppichgeschäft',
    cheese: 'Käseladen',
    chemist: 'Drogerie',
    clothes: 'Bekleidungsgeschäft',
    coffee: 'Coffeeshop',
    collector: 'Sammlergeschäft',
    computer: 'Computerladen',
    confectionery: 'Süßwarenladen',
    convenience: 'Spätkauf',
    copyshop: 'Copyshop',
    cosmetics: 'Kosmetikladen',
    craft: 'Handwerksladen',
    curtain: 'Gardinenladen',
    dairy: 'Milchprodukte',
    deli: 'Feinkostladen',
    department_store: 'Kaufhaus',
    doityourself: 'Baumarkt',
    doors: 'Türenladen',
    dry_cleaning: 'Reinigung',
    'e-cigarette': 'E-Zigarettenladen',
    electrical: 'Elektrogeschäft',
    electronics: 'Elektronikladen',
    erotic: 'Sexshop',
    fabric: 'Stoffladen',
    farm: 'Hofladen',
    fireplace: 'Kaminladen',
    fishing: 'Angelgeschäft',
    flooring: 'Bodenbelagsladen',
    florist: 'Blumenladen',
    funeral_directors: 'Bestattungsinstitut',
    furniture: 'Möbelgeschäft',
    games: 'Spieleladen',
    garden_center: 'Gartencenter',
    garden_centre: 'Gartencenter',
    general: 'Gemischtwarenladen',
    gift: 'Geschenkeladen',
    glaziery: 'Glaser',
    greengrocer: 'Obst- und Gemüseladen',
    hairdresser: 'Friseursalon',
    hardware: 'Eisenwarenladen',
    health_food: 'Naturkostladen',
    hifi: 'HiFi-Laden',
    houseware: 'Haushaltswarenladen',
    hunting: 'Jagdausrüstung',
    ice_cream: 'Eisdiele',
    interior_decoration: 'Einrichtungsdekoration',
    jewelry: 'Juwelier',
    kiosk: 'Kiosk',
    kitchen: 'Küchenstudio',
    laundry: 'Waschsalon',
    lighting: 'Beleuchtungsgeschäft',
    locksmith: 'Schlüsseldienst',
    lottery: 'Lottoannahmestelle',
    mall: 'Einkaufszentrum',
    massage: 'Massagesalon',
    medical_supply: 'Sanitätsfachgeschäft',
    mobile_phone: 'Handyladen',
    model: 'Modellbau',
    motorcycle: 'Motorradgeschäft',
    music: 'Musikladen',
    musical_instrument: 'Musikinstrumentengeschäft',
    newsagent: 'Zeitschriftenladen',
    nutrition_supplements: 'Nahrungsergänzungsmittel',
    optician: 'Optiker',
    outdoor: 'Outdoorladen',
    outpost: 'Außenstelle',
    paint: 'Farbengeschäft',
    pastry: 'Konditorei',
    pawnbroker: 'Pfandleihhaus',
    perfumery: 'Parfümerie',
    pet: 'Tierbedarf',
    pet_grooming: 'Tierpflegesalon',
    photo: 'Fotogeschäft',
    radiotechnics: 'Radiotechnikladen',
    rental: 'Verleih',
    seafood: 'Meeresfrüchtegeschäft',
    second_hand: 'Secondhandladen',
    sewing: 'Nähbedarf',
    shoes: 'Schuhladen',
    sports: 'Sportgeschäft',
    stationery: 'Papierwarenladen',
    supermarket: 'Supermarkt',
    tailor: 'Schneider',
    tattoo: 'Tattoo-Studio',
    tea: 'Teeladen',
    ticket: 'Ticketverkauf',
    tobacco: 'Tabakladen',
    toys: 'Spielwarengeschäft',
    trade: 'Baumaterialgeschäft',
    travel_agency: 'Reisebüro',
    tyres: 'Reifenhandel',
    vacant: 'Leerstehendes Geschäft',
    variety_store: 'Vielzweckladen',
    video: 'Videoverleih',
    video_games: 'Videospieleladen',
    watches: 'Uhrengeschäft',
    wholesale: 'Großhandel',
    window_blind: 'Jalousienladen',
    wine: 'Weinladen',
  },

  sport: {
    '*': 'Sport {}',
    australian_football: 'Australischer Fußball',
    billiards: 'Billard',
    boxing: 'Boxen',
    cliff_diving: 'Klipptauchen',
    cricket: 'Cricket',
    cricket_nets: 'Cricket-Netze',
    croquet: 'Krocket',
    curling: 'Curling',
    gaelic_games: 'Gaelic Games',
    horseshoes: 'Hufeisenwerfen',
    korfball: 'Korfball',
    long_jump: 'Weitsprung',
    orienteering: 'Orientierungslauf',
    paddle_tennis: 'Paddle Tennis',
    pelota: 'Pelota',
    racquet: 'Schläger',
    rc_car: 'RC-Autos',
    rugby: 'Rugby',
    rugby_league: 'Rugby League',
    rugby_union: 'Rugby Union',
    sailing: 'Segeln',
    surfing: 'Surfen',
    table_soccer: 'Tischfußball',
    team_handball: 'Handball',
    toboggan: 'Rodeln',
    '9pin': '9-Pin Bowling',
    '10pin': '10-Pin Bowling',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'American Football',
    archery: 'Bogenschießen',
    athletics: 'Leichtathletik',
    badminton: 'Badminton',
    baseball: 'Baseball',
    basketball: 'Basketball',
    beachvolleyball: 'Beachvolleyball',
    bicycle: 'Fahrrad',
    bmx: 'BMX',
    boules: 'Boule',
    bowling: 'Bowling',
    bowls: 'Bowls',
    canoe: 'Kanu',
    chess: 'Schach',
    climbing: 'Klettern',
    climbing_adventure: 'Kletterabenteuer',
    cycling: 'Radfahren',
    darts: 'Darts',
    disc_golf: 'Disc Golf',
    dog_racing: 'Hunderennen',
    equestrian: 'Reiten',
    field_hockey: 'Feldhockey',
    fitness: 'Fitness',
    floorball: 'Floorball',
    free_flying: 'Freiflug',
    golf: 'Golf',
    gymnastics: 'Gymnastik',
    handball: 'Handball',
    hockey: 'Hockey',
    horse_racing: 'Pferderennen',
    ice_hockey: 'Eishockey',
    ice_skating: 'Eislaufen',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Kartfahren',
    laser_tag: 'Lasertag',
    model_aerodrome: 'Modellflugplatz',
    motocross: 'Motocross',
    motor: 'Motorsport',
    multi: 'Mehrere Sportarten',
    netball: 'Netball',
    paintball: 'Paintball',
    petanque: 'Pétanque',
    roller_skating: 'Rollschuhlaufen',
    rowing: 'Rudern',
    running: 'Laufen',
    scuba_diving: 'Tauchen',
    shooting: 'Schießen',
    shooting_range: 'Schießstand',
    'shot-put': 'Kugelstoßen',
    skateboard: 'Skateboard',
    skating: 'Schlittschuhlaufen',
    ski_jumping: 'Skispringen',
    skiing: 'Skifahren',
    soccer: 'Fußball',
    squash: 'Squash',
    streetball: 'Streetball',
    swimming: 'Schwimmen',
    table_tennis: 'Tischtennis',
    tennis: 'Tennis',
    volleyball: 'Volleyball',
    water_ski: 'Wasserski',
    workout: 'Workout',
    yoga: 'Yoga',
    '8pin': 'Acht-Kegel-Bowling',
    'five-a-side': 'Fünf-gegen-fünf-Fußball',
    'in-line_hockey': 'Inlinehockey',
    aerobics: 'Aerobic',
    american_handball: 'Amerikanischer Handball',
    association_football: 'Fußball (Soccer)',
    axe_throwing: 'Axtwerfen',
    balle_pelote: 'Balle Pelote',
    ballooning: 'Heißluftballonfahren',
    bandy: 'Bandy',
    barre: 'Barre-Fitness',
    base: 'BASE-Jumping',
    batting_cage: 'Schlagkäfig (Baseball/Softball)',
    beach_soccer: 'Beachsoccer',
    beach_tennis: 'Beachtennis',
    beachhandball: 'Beachhandball',
    beachtennis: 'Beachtennis',
    biathlon: 'Biathlon',
    billards: 'Billard',
    bobsleigh: 'Bobsport',
    bodybuilding: 'Bodybuilding',
    bullfighting: 'Stierkampf',
    calisthenics: 'Calisthenics',
    canadian_football: 'Kanadischer Football',
    candlepin: 'Candlepin-Bowling',
    canoe_polo: 'Kanupolo',
    chinlone: 'Chinlone',
    cockfighting: 'Hahnenkampf',
    crossfit: 'CrossFit',
    cycle_ball: 'Radball',
    cycle_polo: 'Radpolo',
    dance: 'Tanzsport',
    dancing: 'Tanzsport',
    diving: 'Wasserspringen',
    dodgeball: 'Völkerball',
    dog_agility: 'Hundesport Agility',
    dragon_boat: 'Drachenbootrennen',
    fencing: 'Fechten',
    fistball: 'Faustball',
    fives: 'Fives',
    football: 'Football',
    footballgolf: 'Fußballgolf',
    four_square: 'Four Square',
    freediving: 'Apnoetauchen',
    funnel_ball: 'Funnel Ball',
    futsal: 'Futsal',
    gaelic_football: 'Gälischer Fußball',
    gaga: 'Gaga-Ball',
    gateball: 'Gateball',
    gliding: 'Segelflug',
    hanggliding: 'Drachenfliegen',
    hapkido: 'Hapkido',
    high_rope_course: 'Hochseilgarten',
    hiking: 'Wandern',
    hopscotch: 'Himmel und Hölle',
    horse_riding: 'Reiten',
    ice_stock: 'Eisstockschießen',
    jetsprint: 'Jetsprint-Bootsrennen',
    kick_scooter: 'Tretroller-Sport',
    kickball: 'Kickball',
    kickboxing: 'Kickboxen',
    kitesurfing: 'Kitesurfen',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Lacrosse',
    martial_arts: 'Kampfsport',
    mind_body_interventions: 'Körper-Geist-Übungen (z. B. Yoga)',
    miniature_golf: 'Minigolf',
    mtb: 'Mountainbiken',
    nine_mens_morris: "Nine men's morris game",
    obstacle_course: 'Hindernislauf',
    paddleball: 'Paddleball',
    paddleboard: 'Stand-up-Paddling',
    padel: 'Padel-Tennis',
    parachuting: 'Fallschirmspringen',
    paragliding: 'Paragliding',
    parkour: 'Parkour',
    pedal_car_racing: 'Tretauto-Rennen',
    pesäpallo: 'Pesäpallo (finnisches Baseball)',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole Dance',
    polo: 'Polo',
    powerlifting: 'Kraftdreikampf',
    rodeo: 'Rodeo',
    roller_hockey: 'Rollhockey',
    russian_skittles: 'Russisches Kegeln',
    safety_training: 'Sicherheitstraining',
    shuffleboard: 'Shuffleboard',
    snooker: 'Snooker',
    snorkeling: 'Schnorcheln',
    softball: 'Softball',
    speedway: 'Speedway',
    summer_toboggan: 'Sommerrodeln',
    sumo: 'Sumo',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    touch_football: 'Touch Football',
    trampoline: 'Trampolinspringen',
    trugo: 'Trugo',
    tug_of_war: 'Tauziehen',
    ultimate: 'Ultimate Frisbee',
    ultralight_aviation: 'Ultraleichtflugsport',
    wakeboarding: 'Wakeboarding',
    walking: 'Gehen (Sport)',
    water_polo: 'Wasserball',
    water_sports: 'Wassersport',
    weightlifting: 'Gewichtheben',
    windsurfing: 'Windsurfen',
    wrestling: 'Ringen',
    zurkhaneh_sport: 'Zurkhaneh-Sport',
  },

  tourism: {
    artwork: {
      artwork_type: {
        architecture: 'Architektur',
        bust: 'Büste',
        graffiti: 'Graffiti',
        installation: 'Kunstinstallation',
        mosaic: 'Mosaik',
        mural: 'Wandmalerei',
        painting: 'Gemälde',
        relief: 'Relief (Kunstwerk)',
        sculpture: 'Skulptur',
        statue: 'Statue',
        stone: 'Felskunst',
      },
      '*': 'Kunst',
    },

    cabin: 'Touristenhütte',
    camp_pitch: 'Stellplatz',
    hunting_lodge: 'Jagdhütte',
    information: {
      information: {
        '*': 'Information {}',
        board: 'Informationsschild',
        guidepost: 'Wegweiser',
        map: 'Karte',
        office: 'Informationsbüro',
        route_marker: 'Routenmarkierung',
      },
      '*': 'Information',
    },

    '*': '{}',
    alpine_hut: 'Alpenhütte',
    apartment: 'Apartment',
    aquarium: 'Aquarium',
    attraction: 'Attraktion',
    camp_site: 'Campingplatz',
    caravan_site: 'Wohnwagenstellplatz',
    chalet: 'Chalet',
    gallery: 'Galerie',
    guest_house: 'Gästehaus',
    hostel: 'Hostel',
    hotel: 'Hotel',
    motel: 'Motel',
    museum: 'Museum',
    picnic_site: 'Picknickplatz',
    viewpoint: 'Aussichtspunkt',
    wilderness_hut: 'Schutzhütte',
    zoo: 'Zoo',
    theme_park: 'Themenpark',
  },

  type: {
    route: {
      '*': 'Weg',
      route: {
        '*': 'Weg {}',
        aerialway: 'Seilbahnlinie',
        bicycle: {
          '*': 'Fahrradweg',
          network: {
            lcn: 'Lokale Radroute',
            rcn: 'Regionale Radroute',
            ncn: 'Nationale Radroute',
            icn: 'Internationale Radroute',
          },
        },
        bus: 'Buslinie',
        canoe: 'Kanuroute',
        canyoning: 'Canyoning-Route',
        detour: 'Umleitungsroute',
        emergency_access: 'Rettungszufahrt',
        ferry: 'Fährverbindung',
        fitness_trail: 'Trimm-dich-Pfad',
        foot: {
          '*': 'Fußweg',
          network: {
            lwn: 'Lokaler Fußweg',
            rwn: 'Regionaler Fußweg',
            nwn: 'Nationaler Fußweg',
            iwn: 'Internationaler Fußweg',
          },
          pilgrimage: {
            '*': 'Pilgerweg',
            no: '',
          },
        },
        funicular: 'Standseilbahnlinie',
        hiking: {
          '*': 'Wanderweg',
          network: {
            lwn: 'Lokaler Wanderweg',
            rwn: 'Regionaler Wanderweg',
            nwn: 'Nationaler Wanderweg',
            iwn: 'Internationaler Wanderweg',
          },
          pilgrimage: {
            '*': 'Pilgerweg',
            no: '',
          },
        },
        historic: 'Historische Route',
        historic_railway: 'Historische Bahnstrecke',
        horse: {
          '*': 'Reitweg',
          network: {
            lhn: 'Lokaler Reitweg',
            rhn: 'Regionaler Reitweg',
          },
        },
        inline_skates: 'Inline-Skating-Route',
        junction: 'Knotenpunkt',
        light_rail: 'Stadtbahnlinie',
        motorboat: 'Motorbootroute',
        mtb: 'Mountainbike-Strecke',
        nordic_walking: 'Nordic-Walking-Strecke',
        pipeline: 'Pipelineroute',
        piste: 'Skipiste',
        portage: 'Umtrageroute',
        power: 'Stromleitungsroute',
        railway: 'Bahnstrecke',
        road: 'Straßenroute',
        running: 'Laufstrecke',
        share_taxi: 'Sammeltaxilinie',
        ski: 'Langlaufloipe',
        subway: 'U-Bahn-Linie',
        tracks: 'Gleisverlauf',
        train: 'Zuglinie',
        tram: 'Straßenbahnlinie',
        trolleybus: 'Obuslinie',
        via_ferrata: 'Klettersteig',
        waterway: 'Wasserstraßenroute',
        worship: {
          '*': 'Pilgerweg',
          worship: {
            stations_of_the_cross: 'Kreuzweg',
          },
        },
      },
    },
  },

  waterway: {
    '*': 'Wasserstraße {}',
    boatyard: 'Bootswerft',
    canal: 'Kanal',
    dam: 'Staudamm',
    ditch: 'Graben (Wasserstraße)',
    dock: 'Dock',
    drain: 'Entwässerung',
    drystream: 'Trockenbach',
    lock_gate: 'Schleusentor',
    milestone: 'Wasserstraßen-Kilometerstein',
    river: 'Fluss',
    sluice_gate: 'Schütz',
    stream: 'Bach, Fließ',
    wadi: 'Wadi',
    waterfall: 'Wasserfall',
    weir: 'Wehr',
    canoe_pass: 'Kanuumtrage',
    fairway: 'Fahrrinne',
    fish_pass: 'Fischpass',
    flowline: 'Fließlinie',
    link: 'Gewässerverbindung',
    pressurised: 'Druckwasserleitung',
    rapids: 'Pereje',
    tidal_channel: 'Gezeitenkanal',
  },

  aerialway: {
    '*': 'Seilbahn, Aufzug',
    cable_car: 'Kabinenbahn',
    chair_lift: 'Sessellift',
    goods: 'Materialseilbahn',
    'j-bar': 'J-Lift',
    magic_carpet: 'Zauberteppich',
    mixed_lift: 'Kombilift',
    platter: 'Schlepplift',
    pylon: 'Seilbahnstütze',
    rope_tow: 'Seillift',
    station: 'Seilbahnstation',
    't-bar': 'T-Bügellift',
    zip_line: 'Zipline',
  },

  railway: {
    '*': 'Eisenbahn',
    abandoned: 'Aufgegebene Bahnstrecke',
    construction: 'Bahnstrecke im Bau',
    facility: 'Bahnanlage',
    junction: 'Bahnabzweig',
    milestone: 'Bahnkilometerstein',
    proposed: 'Geplante Bahnstrecke',
    disused: 'Stillgelegte Bahnstrecke',
    funicular: 'Standseilbahn',
    light_rail: 'Stadtbahn',
    miniature: 'Miniaturbahn',
    monorail: 'Einschienenbahn',
    narrow_gauge: 'Schmalspurbahn',
    rail: 'Bahnstrecke',
    razed: 'Abgetragene Bahnstrecke',
    signal_box: 'Stellwerk',
    site: 'Bahngelände',
    subway: 'U-Bahn-Linie',
    train_station_entrance: 'Bahnhofszugang',
    tram: 'Straßenbahnlinie',
    halt: 'Haltepunkt',
    platform: 'Bahnsteig',
    preserved: 'Museumsbahn',
    station: 'Bahnhof',
    stop: 'Bahnhalt',
    subway_entrance: 'U-Bahneingang',
    tram_crossing: 'Straßenbahnübergang',
    tram_level_crossing: 'Straßenbahnkreuzung',
    tram_stop: 'Straßenbahnhaltestelle',
    buffer_stop: 'Prellbock',
    crossing: 'Gleisquerung',
    derail: 'Entgleisungsvorrichtung',
    railway_crossing: 'Bahnquerung',
    roundhouse: 'Ringlokschuppen',
    signal: 'Eisenbahnsignal',
    switch: 'Weiche',
    level_crossing: 'Bahnübergang',
    traverser: 'Verschiebebühne',
    turntable: 'Drehscheibe',
    ventilation_shaft: 'Eisenbahnlüftungsschacht',
    wash: 'Zugwaschanlage',
    water_crane: 'Wasserkran',
    workshop: 'Bahnwerkstatt',
    yard: 'Rangierbahnhof',
  },

  attraction: {
    animal: 'Tierattraktion',
    amusement_ride: 'Fahrgeschäft',
    big_wheel: 'Riesenrad',
    carousel: 'Karussell',
    historic: 'Historische Attraktion',
    maze: 'Labyrinthattraktion',
    roller_coaster: 'Achterbahn',
    summer_toboggan: 'Sommerrodelbahn',
    train: 'Attraktionszug',
    water_slide: 'Wasserrutsche',
  },

  'abandoned:building': {
    '*': 'Aufgegebenes Gebäude',
  },

  'disused:building': {
    '*': 'Stillgelegtes Gebäude',
  },

  'ruins:building': {
    '*': 'Ruins of a building',
  },

  fixme: {
    '*': 'Fehlerhaft oder unvollständig kartiertes Objekt',
  },

  ford: {
    yes: 'Furt',
  },

  bridge: {
    '*': {
      '*': 'Brücke',

      highway: {
        '*': 'Straßenbrücke',
      },

      railway: {
        '*': 'Eisenbahnbrücke',
      },
    },

    no: '',
  },

  tunnel: {
    '*': {
      '*': 'Tunnel',

      highway: {
        '*': 'Straßentunnel',
      },

      railway: {
        '*': 'Eisenbahntunnel',
      },
    },

    culvert: 'Durchlass',
    no: '',
  },

  oneway: {
    yes: 'Einbahnstraße',
  },

  foot: {
    no: 'Zugang für Fußgänger verboten',
    yes: 'Zugang für Fußgänger erlaubt',
    private: 'Zugang für Fußgänger nur für Berechtigte',
    designated: 'Für Fußgänger ausgewiesen',
  },

  bicycle: {
    no: 'Fahrradfahren verboten',
    yes: 'Fahrradfahren erlaubt',
    private: 'Fahrradfahren nur für Berechtigte',
    designated: 'Für Fahrräder ausgewiesen',
  },

  vehicle: {
    no: 'Fahrzeugverkehr verboten',
    yes: 'Fahrzeugverkehr erlaubt',
    private: 'Fahrzeugverkehr nur für Berechtigte',
    designated: 'Für Fahrzeuge ausgewiesen',
  },

  motor_vehicle: {
    no: 'Zugang für Kraftfahrzeuge verboten',
    yes: 'Zugang für Kraftfahrzeuge erlaubt',
    private: 'Zugang für Kraftfahrzeuge nur für Berechtigte',
    designated: 'Für Kraftfahrzeuge ausgewiesen',
  },

  military: {
    '*': 'Militäranlage {}',
    academy: 'Militärakademie',
    airfield: 'Militärflugplatz',
    ammunition: 'Munitionsdepot',
    barracks: 'Kaserne',
    base: 'Militärbasis',
    bunker: 'Bunker',
    checkpoint: 'Militärkontrollpunkt',
    danger_area: 'Militärisches Gefahrengebiet',
    depot: 'Militärdepot',
    launchpad: 'Startplattform',
    naval_base: 'Marinebasis',
    nuclear_explosion_site: 'Atomtestgelände',
    obstacle_course: 'Militärischer Hindernisparcours',
    office: 'Militärisches Amt',
    range: 'Schießplatz',
    school: 'Militärschule',
    training_area: 'Militärisches Übungsgelände',
    trench: 'Schützengraben',
  },

  mountain_pass: {
    yes: 'Gebirgspass',
  },

  seasonal: {
    yes: {
      '*': 'Saisonal',

      waterway: {
        stream: 'Saisonaler Bach',
        ditch: 'Saisonaler Graben',
        drain: 'Saisonale Entwässerung',
        waterfall: 'Saisonaler Wasserfall',
      },

      natural: {
        water: 'Saisonale Wasserfläche',
      },
    },
  },

  intermittent: {
    yes: {
      '*': 'Periodisch',

      waterway: {
        stream: 'Periodischer Bach',
        ditch: 'Periodischer Graben',
        drain: 'Periodische Entwässerung',
        waterfall: 'Periodischer Wasserfall',
      },

      natural: {
        water: 'Periodische Wasserfläche',
      },
    },
  },

  trail_visibility: {
    excellent: 'Ausgezeichnete Wegsichtbarkeit',
    good: 'Gute Wegsichtbarkeit',
    intermediate: 'Mittlere Wegsichtbarkeit',
    bad: 'Schlechte Wegsichtbarkeit',
    horrible: 'Sehr schlechte Wegsichtbarkeit',
    no: 'Keine Wegsichtbarkeit',
  },

  access: {
    customers: 'Nur für Kunden',
    private: 'Privates Objekt',
    no: 'Objekt mit Zutrittsverbot',
  },

  craft: {
    '*': 'Handwerk {}',
    yes: 'Handwerksbetrieb',
    bakery: 'Bäckerei',
    beekeeper: 'Imker',
    blacksmith: 'Schmied',
    brewery: 'Brauerei',
    builder: 'Bauunternehmen',
    carpenter: 'Zimmerer',
    caterer: 'Catering-Service',
    cleaning: 'Reinigungsdienst',
    confectionery: 'Konditorei',
    distillery: 'Brennerei',
    dressmaker: 'Schneiderin',
    electrician: 'Elektriker',
    electronics_repair: 'Elektronikreparatur',
    gardener: 'Gärtner',
    glaziery: 'Glaserei',
    grinding_mill: 'Mühle',
    handicraft: 'Kunsthandwerk',
    hvac: 'Heizung und Klimatechnik',
    jeweller: 'Juwelier',
    joiner: 'Tischler',
    key_cutter: 'Schlüsseldienst',
    locksmith: 'Schlosser',
    metal_construction: 'Metallbau',
    painter: 'Maler',
    photographer: 'Fotograf',
    plumber: 'Klempner',
    pottery: 'Töpferei',
    roofer: 'Dachdecker',
    sawmill: 'Sägewerk',
    shoemaker: 'Schuhmacher',
    signmaker: 'Schilderhersteller',
    stonemason: 'Steinmetz',
    tailor: 'Schneider',
    tiler: 'Fliesenleger',
    upholsterer: 'Polsterer',
    watchmaker: 'Uhrmacher',
    window_construction: 'Fensterbau',
    winery: 'Weingut',
  },
  emergency: {
    access_point: 'Rettungspunkt',
    ambulance_station: 'Rettungswache',
    assembly_point: 'Sammelplatz',
    defibrillator: 'Defibrillator',
    fire_extinguisher: 'Feuerlöscher',
    fire_hose: 'Feuerwehrschlauch',
    fire_hydrant: 'Hydrant',
    fire_water_pond: 'Löschteich',
    landing_site: 'Notlandeplatz',
    life_ring: 'Rettungsring',
    lifeguard: 'Rettungsschwimmerstation',
    phone: 'Notruftelefon',
    siren: 'Sirene',
    suction_point: 'Löschwasserentnahmestelle',
    water_tank: 'Löschwasserbehälter',
  },

  entrance: {
    '*': 'Eingang',
    main: 'Haupteingang',
    secondary: 'Nebeneingang',
    service: 'Diensteingang',
    exit: 'Ausgang',
    entrance: 'Eingang (nur)',
    emergency: 'Notausgang',
    staircase: 'Eingang zum Treppenhaus',
    home: 'Eingang zu Privathaus/Garten/Wohnung',
    garage: 'Garageneingang',
    shop: 'Ladeneingang',
    no: 'Kein Eingang',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Rot',
  blue: 'Blau',
  green: 'Grün',
  yellow: 'Gelb',
  orange: 'Orange',
  purple: 'Lila',
  violet: 'Violett',
  white: 'Weiß',
  black: 'Schwarz',
  gray: 'Grau',
  brown: 'Braun',
};
