import type { DeepPartial } from '@shared/types/deepPartial.js';
import type { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  access: {
    customers: 'Samo za stranke',
    private: 'Zasebni objekt',
    no: 'Objekt s prepovedanim dostopom',
  },
  aeroway: {
    aerodrome: 'Letališče',
    airstrip: 'Vzletno-pristajalna steza (manjše letališče)',
    apron: 'Ploščad za letala',
    gate: 'Letališki izhod',
    hangar: 'Hangar za letala',
    helipad: 'Heliport',
    holding_position: 'Čakalno mesto za letala',
    jet_bridge: 'Potniški most do letala',
    navigationaid: 'Letalska navigacijska naprava',
    parking_position: 'Parkirno mesto za letala',
    runway: 'Vzletno-pristajalna steza',
    stopway: 'Varnostna ustavna steza',
    taxilane: 'Vozna steza na ploščadi',
    taxiway: 'Vozna steza',
    terminal: 'Letališki terminal',
    threshold: 'Prag vzletno-pristajalne steze',
    tower: 'Kontrolni stolp letalskega prometa',
    windsock: 'Vetrna vreča',
  },
  aerialway: {
    '*': 'Žičnica',
    cable_car: 'Kabinska žičnica',
    chair_lift: 'Sedežnica',
    goods: 'Tovorna žičnica',
    'j-bar': 'Sidro tipa J',
    magic_carpet: 'Tekoči trak',
    mixed_lift: 'Kombinirana žičnica',
    platter: 'Krožnikasta vlečnica',
    pylon: 'Steber žičnice',
    rope_tow: 'Vrvna vlečnica',
    station: 'Postaja žičnice',
    't-bar': 'Sidro tipa T',
    zip_line: 'Vrvna drča',
  },
  amenity: {
    '*': '{}',
    animal_breeding: 'Vzreja živali',
    animal_shelter: 'Zavetišče za živali',
    arts_centre: 'Umetnostni center',
    atm: 'Bankomat',
    bank: 'Banka',
    bar: 'Bar',
    bbq: 'Žar',
    bench: 'Klop',
    bicycle_parking: 'Parkirišče za kolesa',
    bicycle_rental: 'Izposoja koles',
    bicycle_repair_station: 'Postaja za popravilo koles',
    biergarten: 'Pivski vrt',
    brothel: 'Bordel',
    bureau_de_change: 'Menjalnica',
    bus_station: 'Avtobusna postaja',
    cafe: 'Kavarna',
    car_rental: 'Izposoja avtomobilov',
    car_wash: 'Avtopralnica',
    casino: 'Igralnica',
    charging_station: 'Polnilna postaja',
    childcare: 'Varstvo otrok',
    cinema: 'Kino',
    clinic: 'Klinika',
    clock: 'Ura',
    college: 'Višja šola',
    community_centre: 'Skupnostni center',
    compressed_air: 'Stisnjen zrak',
    courthouse: 'Sodišče',
    dentist: 'Zobozdravnik',
    device_charging_station: 'Polnilna postaja za naprave',
    doctors: 'Zdravniška ordinacija',
    dressing_room: 'Garderoba',
    drinking_water: 'Pitna voda',
    driving_school: 'Avtošola',
    embassy: 'Veleposlaništvo',
    events_venue: 'Prizorišče dogodkov',
    fast_food: 'Hitra prehrana',
    feeding_place: 'Krmišče',
    ferry_terminal: 'Trajektni terminal',
    fire_station: 'Gasilska postaja',
    food_court: 'Prehrambni kotiček',
    fountain: 'Vodnjak',
    fuel: 'Bencinska črpalka',
    funeral_hall: 'Pogrebna dvorana',
    gambling: 'Igralnica',
    game_feeding: 'Krmišče za divjad',
    grave_yard: 'Pokopališče',
    grit_bin: 'Zabojnik s posipom',
    hospital: 'Bolnišnica',
    hunting_stand: 'Lovska preža',
    ice_cream: 'Sladoled',
    kindergarten: 'Vrtec',
    language_school: 'Jezikovna šola',
    library: 'Knjižnica',
    marketplace: 'Tržnica',
    monastery: 'Samostan',
    money_transfer: 'Prenos denarja',
    motorcycle_parking: 'Parkirišče za motorna kolesa',
    motorcycle_rental: 'Izposoja motornih koles',
    nightclub: 'Nočni klub',
    parcel_locker: 'Paketnik',
    parking: 'Parkirišče',
    parking_entrance: 'Uvoz na parkirišče',
    parking_space: 'Parkirno mesto',
    pharmacy: 'Lekarna',
    place_of_mourning: 'Mrliška vežica',
    place_of_worship: 'Verski objekt',
    planetarium: 'Planetarij',
    police: 'Policija',
    post_box: 'Poštni nabiralnik',
    post_office: 'Pošta',
    prison: 'Zapor',
    pub: 'Gostilna',
    public_bookcase: 'Javna knjižna omara',
    ranger_station: 'Postaja gozdnih čuvajev',
    recycling: 'Recikliranje',
    restaurant: 'Restavracija',
    school: 'Šola',
    shelter: {
      '*': 'Zavetišče',
      shelter_type: {
        '*': 'Zavetišče {}',
        basic_hut: 'Preprosta koča',
        changing_rooms: 'Preoblačilnice',
        field_shelter: 'Poljsko zavetišče',
        lean_to: 'Nadstrešek ob steni',
        picnic_shelter: {
          '*': 'Piknik zavetišče',
          fireplace: { yes: 'Piknik zavetišče z ognjiščem' },
        },
        public_transport: 'Zavetišče javnega prevoza',
        rock_shelter: 'Skalno zavetišče',
        sun_shelter: 'Zavetišče pred soncem',
        weather_shelter: 'Zavetišče pred vremenom',
      },
    },
    shower: 'Prha',
    ski_rental: 'Izposoja smuči',
    smoking_area: 'Kadilnica',
    social_centre: 'Socialni center',
    social_facility: {
      '*': 'Socialna ustanova',
      social_facility: {
        // dairy_kitchen: 'Mlečna kuhinja',
        // outreach: 'Terensko delo',
        ambulatory_care: 'Ambulantna oskrba',
        assisted_living: 'Oskrbovana bivalna enota',
        clothing_bank: 'Banka oblačil',
        day_care: 'Dnevno varstvo',
        food_bank: 'Banka hrane',
        group_home: 'Skupinski dom',
        hospice: 'Hospic',
        nursing_home: 'Dom za ostarele',
        shelter: 'Zavetišče',
        soup_kitchen: 'Ljudska kuhinja',
        workshop: 'Delavnica',
      },
    },
    stripclub: 'Striptiz klub',
    studio: 'Studio',
    taxi: 'Taksi',
    telephone: 'Telefon',
    theatre: 'Gledališče',
    toilets: 'WC, stranišča',
    townhall: 'Mestna hiša',
    traffic_park: 'Prometni park',
    trolley_bay: 'Prostor za vozičke',
    university: 'Univerza',
    vacuum_cleaner: 'Sesalnik',
    vehicle_inspection: 'Tehnični pregled vozil',
    vending_machine: {
      '*': 'Prodajni avtomat',
      vending: {
        bicycle_tube: 'Avtomat za kolesarske zračnice',
        bread: 'Avtomat za kruh',
        bottle_return: 'Avtomat za vračanje kavcijskih steklenic',
        candles: 'Avtomat za sveče',
        chewing_gums: 'Avtomat za žvečilne gumije',
        cigarettes: 'Avtomat za cigarete',
        coffee: 'Avtomat za kavo',
        condoms: 'Avtomat za kondome',
        drinks: 'Avtomat za pijačo',
        elongated_coin: 'Avtomat za spominske kovance',
        eggs: 'Avtomat za jajca',
        excrement_bags: 'Avtomat za vrečke za iztrebke',
        food: 'Avtomat za hrano',
        fuel: 'Avtomat za gorivo',
        gas: 'Avtomat za plin',
        ice_cream: 'Avtomat za sladoled',
        ice_cubes: 'Avtomat za ledene kocke',
        milk: 'Avtomat za mleko',
        movies: 'Avtomat za filme',
        newspapers: 'Avtomat za časopise',
        parking_tickets: 'Parkirni avtomat',
        pizza: 'Avtomat za pico',
        public_transport_tickets: 'Avtomat za vozovnice javnega prevoza',
        stamps: 'Avtomat za znamke',
        sweets: 'Avtomat za sladkarije',
        water: 'Avtomat za vodo',
      },
    },
    veterinary: 'Veterinar',
    waste_basket: 'Koš za smeti',
    waste_disposal: 'Odlaganje odpadkov',
    water_point: 'Odjemno mesto za vodo',
    watering_place: 'Napajališče',
  },
  attraction: {
    animal: 'Živalska atrakcija',
    amusement_ride: 'Zabaviščna vožnja',
    big_wheel: 'Panoramsko kolo',
    carousel: 'Vrtiljak',
    historic: 'Zgodovinska atrakcija',
    maze: 'Labirint',
    roller_coaster: 'Vlak smrti',
    summer_toboggan: 'Poletno sankališče',
    train: 'Turistični vlakec',
    water_slide: 'Vodni tobogan',
  },
  barrier: {
    '*': 'Ovira {}',
    block: 'Blok',
    bollard: 'Stebriček',
    border_control: 'Mejna kontrola',
    cable_barrier: 'Kabelska ograja',
    chain: 'Veriga',
    city_wall: 'Mestno obzidje',
    ditch: 'Jarek (ovira)',
    entrance: 'Vhod',
    fence: 'Ograja',
    gate: 'Vrata',
    guard_rail: 'Varnostna ograja',
    handrail: 'Držalo',
    hedge: 'Živa meja',
    kerb: 'Robnik',
    lift_gate: 'Zapornica',
    retaining_wall: 'Podporni zid',
    rope: 'Vrv',
    sliding_gate: 'Drsna vrata',
    swing_gate: 'Vrtljiva zapornica',
    turnstile: 'Vrtljivi križ',
    wall: 'Zid',
  },
  boundary: {
    '*': 'Območje',
    administrative: {
      '*': 'Upravno območje',
      admin_level: {
        '2': 'Država',
        '3': 'Regija',
        '4': 'Pokrajina',
        '5': 'Provinca',
        '6': 'Mesto',
        '7': 'Območje',
        '8': 'Občina',
        '9': 'Naselje',
        '10': 'Katastrska občina',
      },
    },
    marker: 'Mejni kamen',
    national_park: 'Narodni park',
    protected_area: 'Zavarovano območje',
  },
  'abandoned:building': { '*': 'Opuščena stavba' },
  'disused:building': { '*': 'Neuporabljana stavba' },
  'ruins:building': { '*': 'Ruševina stavbe' },
  building: {
    '*': {
      '*': 'Stavba',
      abandoned: {
        yes: 'Opuščena stavba',
      },
      disused: {
        yes: 'Neuporabljana stavba',
      },
      ruins: {
        yes: 'Ruševina stavbe',
      },
    },
    abandoned: 'Opuščena stavba',
    disused: 'Neuporabljana stavba',
    apartments: 'Stanovanjski blok',
    barn: 'Skedenj',
    bungalow: 'Bungalov',
    bunker: 'Bunker',
    cabin: 'Koča',
    cathedral: 'Katedrala',
    chapel: 'Kapela',
    church: 'Cerkev',
    civic: 'Javna stavba',
    collapsed: 'Podrta stavba',
    commercial: 'Poslovna stavba',
    construction: 'Stavba v gradnji',
    cowshed: 'Hlev za govedo',
    detached: 'Samostojna hiša',
    dormitory: 'Dijaški dom',
    entrance: 'Vhod v stavbo',
    farm_auxiliary: 'Pomožna kmetijska stavba',
    farm: 'Kmetija',
    garage: 'Garaža',
    garages: 'Garaže',
    government: 'Vladna stavba',
    grandstand: 'Tribuna',
    greenhouse: 'Rastlinjak',
    hangar: 'Hangar',
    hayloft: 'Senik',
    hospital: 'Bolnišnična stavba',
    hotel: 'Hotelska stavba',
    house: 'Zasebna hiša',
    houseboat: 'Bivalni čoln',
    hut: 'Baraka',
    industrial: 'Industrijska stavba',
    kindergarten: 'Stavba vrtca',
    kiosk: 'Kiosk',
    manufacture: 'Proizvodna stavba',
    mosque: 'Mošeja',
    office: 'Poslovna pisarniška stavba',
    parking: 'Parkirna hiša',
    public: 'Javna stavba',
    residential: 'Stanovanjska hiša',
    retail: 'Trgovska stavba',
    roof: 'Streha',
    ruins: 'Ruševine stavbe',
    school: 'Šolska stavba',
    semidetached_house: 'Dvojček',
    service: 'Servisna stavba',
    shed: 'Lopa',
    shrine: 'Svetišče',
    stable: 'Konjski hlev',
    stadium: 'Stavba stadiona',
    static_caravan: 'Mobilna hiša, prikolica',
    storage_tank: 'Skladiščni rezervoar',
    sty: 'Svinjak',
    supermarket: 'Stavba supermarketa',
    synagogue: 'Sinagoga',
    temple: 'Tempelj',
    terrace: 'Vrstna hiša',
    train_station: 'Železniška postaja',
    transformer_tower: 'Transformatorski stolp',
    transportation: 'Prometna stavba',
    university: 'Univerzitetna stavba',
    warehouse: 'Skladišče',
    yes: 'Nedoločena stavba',
  },
  fixme: {
    '*': 'Napačno ali delno vrisan objekt',
  },
  ford: {
    yes: 'Brod',
  },
  bridge: {
    '*': {
      '*': 'Most',
      highway: {
        '*': 'Cestni most',
      },
      railway: {
        '*': 'Železniški most',
      },
    },
    no: '',
  },
  tunnel: {
    '*': {
      '*': 'Predor',
      highway: {
        '*': 'Cestni predor',
      },
      railway: {
        '*': 'Železniški predor',
      },
    },
    culvert: 'Prepust',
    no: '',
  },
  oneway: {
    yes: 'Enosmerna cesta',
  },
  foot: {
    no: 'Prehod za pešce prepovedan',
    yes: 'Prehod za pešce dovoljen',
    private: 'Prehod za pešce samo za lastnike',
    designated: 'Namenjeno pešcem',
  },
  bicycle: {
    no: 'Vožnja s kolesom prepovedana',
    yes: 'Vožnja s kolesom dovoljena',
    private: 'Vožnja s kolesom samo za lastnike',
    designated: 'Namenjeno kolesarjem',
  },
  vehicle: {
    no: 'Vožnja z vozilom prepovedana',
    yes: 'Vožnja z vozilom dovoljena',
    private: 'Vožnja z vozilom samo za lastnike',
    designated: 'Namenjeno vozilom',
  },
  motor_vehicle: {
    no: 'Vožnja z motornim vozilom prepovedana',
    yes: 'Vožnja z motornim vozilom dovoljena',
    private: 'Vožnja z motornim vozilom samo za lastnike',
    designated: 'Namenjeno motornim vozilom',
  },
  emergency: {
    defibrillator: 'Defibrilator',
    phone: 'Klic v sili',
  },
  entrance: {
    '*': 'Vhod',
    main: 'Glavni vhod',
    secondary: 'Stranski vhod',
    service: 'Servisni vhod',
    exit: 'Izhod',
    entrance: 'Vhod (samo)',
    emergency: 'Zasilni vhod',
    staircase: 'Vhod na stopnišče',
    home: 'Vhod v zasebno hišo/dom/vrt/stanovanje',
    garage: 'Vhod v garažo',
    shop: 'Vhod v trgovino',
    no: 'Ni vhoda',
  },
  highway: {
    '*': 'Cesta {}',
    bridleway: 'Jahalna pot',
    bus_stop: 'Avtobusna postaja',
    construction: 'Cesta v gradnji',
    crossing: 'Prehod za pešce',
    cycleway: 'Kolesarska steza',
    footway: 'Pločnik',
    living_street: 'Stanovanjska cesta (bivalna ulica)',
    motorway: 'Avtocesta',
    motorway_link: 'Priključek na avtocesto',
    path: {
      '*': 'Steza',
      foot: {
        designated: {
          bicycle: {
            designated: 'Skupna pot za pešce in kolesarje',
          },
        },
      },
    },
    pedestrian: 'Območje za pešce',
    piste: 'Smučarska proga',
    platform: 'Peron',
    primary: 'Cesta prvega reda',
    primary_link: 'Priključek na cesto prvega reda',
    raceway: 'Dirkališče',
    residential: 'Ulica',
    rest_area: 'Počivališče',
    road: 'Cesta neznane vrste',
    secondary: 'Cesta drugega reda',
    secondaty_link: 'Priključek na cesto drugega reda',
    service: {
      '*': 'Servisna, dovozna cesta',
      service: {
        '*': 'Servisna cesta {}',
        alley: 'Ozka ulica (prehod)',
        bus: 'Cesta za javni prevoz',
        'drive-through': 'Nakup iz avtomobila',
        driveway: 'Dovozna cesta',
        emergency_access: 'Intervencijska pot',
        parking_aisle: 'Vozna pot na parkirišču',
      },
    },
    steps: 'Stopnice',
    street_lamp: 'Ulična svetilka',
    tertiary: 'Cesta tretjega reda',
    tertiary_link: 'Priključek na cesto tretjega reda',
    track: {
      '*': 'Gozdna / poljska cesta neznane kakovosti',
      tracktype: {
        grade1: 'Utrjena gozdna / poljska cesta',
        grade2: 'Pretežno utrjena gozdna / poljska cesta',
        grade3: 'Manj trdna, neutrjena gozdna / poljska cesta',
        grade4: 'Gozdna / poljska cesta, prevozna s traktorjem',
        grade5: 'Komaj zaznavna gozdna / poljska cesta',
      },
    },
    trunk: 'Hitra cesta',
    trunk_link: 'Priključek na hitro cesto',
    unclassified: 'Nekategorizirana cesta',
    via_ferrata: 'Zavarovana plezalna pot (via ferrata)',
  },
  historic: {
    '*': 'Zgodovinski objekt {}',
    yes: 'Zgodovinski objekt',
    aircraft: 'Zgodovinsko letalo',
    archaeological_site: 'Arheološko najdišče',
    boundary_stone: 'Zgodovinski mejnik',
    building: 'Zgodovinska stavba',
    cannon: 'Zgodovinski top',
    castle: 'Grad',
    charcoal_pile: 'Mesto oglarske kope',
    church: 'Zgodovinska cerkev',
    city_gate: 'Mestna vrata',
    citywalls: 'Mestno obzidje',
    fort: 'Utrdba',
    heritage: 'Območje dediščine',
    hollow_way: 'Kolovoz',
    house: 'Zgodovinska hiša',
    manor: 'Graščina',
    memorial: 'Spominsko obeležje',
    milestone: 'Zgodovinski miljnik',
    mine_shaft: 'Zgodovinski rudniški jašek',
    mine: 'Zgodovinski rudnik',
    monastery: 'Zgodovinski samostan',
    monument: 'Spomenik',
    ruins: {
      '*': 'Ruševine',
      ruins: {
        castle: 'Ruševine gradu',
      },
    },
    shieling: 'Planinska koča (sezonska)',
    stone: 'Zgodovinski kamen',
    tomb: 'Grobnica',
    tree_shrine: 'Znamenje na drevesu',
    wayside_cross: 'Obcestni križ',
    wayside_shrine: 'Znamenje ob poti',
    wreck: 'Razbitina',
  },
  landuse: {
    '*': '{}',
    allotments: 'Vrtičkarsko območje',
    basin: 'Zadrževalnik',
    brownfield: 'Degradirano zemljišče',
    cemetery: 'Pokopališče',
    commercial: 'Poslovno območje',
    construction: 'Gradbišče',
    education: 'Izobraževalno območje',
    farmland: 'Njiva',
    farmyard: 'Kmečko dvorišče',
    forest: 'Gozd',
    garages: 'Garaže',
    grass: 'Trava',
    greenfield: 'Nepozidano zemljišče za gradnjo',
    industrial: 'Industrijsko območje',
    landfill: 'Odlagališče',
    logging: 'Sečnja',
    meadow: 'Travnik',
    military: 'Vojaško območje',
    orchard: 'Sadovnjak',
    pedestrian: 'Območje za pešce',
    plant_nursery: 'Drevesnica',
    quarry: 'Kamnolom',
    railway: 'Železniško območje',
    recreation_ground: 'Rekreacijsko območje',
    religions: 'Cerkveno zemljišče',
    reservoir: 'Vodni zbiralnik',
    residential: 'Stanovanjsko območje',
    retail: 'Trgovsko območje',
    vineyard: 'Vinograd',
    village_green: 'Vaška zelenica',
    winter_sports: 'Območje zimskih športov',
  },
  leisure: {
    '*': '{}',
    adult_gaming_centre: 'Igralnica za odrasle',
    amusement_arcade: 'Igralni salon',
    bandstand: 'Glasbeni paviljon',
    bathing_place: 'Kopališče',
    beach_resort: 'Obmorsko letovišče',
    bird_hide: 'Opazovalnica ptic',
    bleachers: 'Tribune',
    bowling_alley: 'Kegljišče (bowling)',
    dance: 'Plesni prostor',
    disc_golf_course: 'Igrišče za disk golf',
    dog_park: 'Pasji park',
    escape_game: 'Soba pobega',
    firepit: 'Kurišče',
    fishing: 'Ribolov',
    fitness_centre: 'Fitnes center',
    fitness_station: 'Fitnes postaja',
    garden: 'Vrt',
    golf_course: 'Igrišče za golf',
    hackerspace: 'Hackerspace',
    high_ropes_course: 'Pustolovski (vrvni) park',
    horse_riding: 'Konjeništvo',
    ice_rink: 'Drsališče',
    marina: 'Marina',
    miniature_golf: 'Minigolf',
    nature_reserve: 'Naravni rezervat',
    outdoor_seating: 'Zunanje sedenje',
    park: 'Park',
    picnic_table: {
      '*': 'Piknik miza',
      covered: {
        yes: 'Pokrita piknik miza',
        no: 'Nepokrita piknik miza',
      },
    },
    pitch: 'Športno igrišče',
    playground: 'Otroško igrišče',
    resort: 'Rekreacijsko letovišče',
    slipway: 'Spuščališče za čolne',
    sauna: {
      '*': 'Savna',
      sauna: {
        hot: 'Finska savna',
        steam: 'Parna savna (turška kopel)',
        smoke: 'Dimna savna (finska)',
        dry: 'Suha savna',
        hanjeungmak: 'Hanjeungmak (korejska savna)',
        aroma: 'Aroma savna',
        infrared: 'Infrardeča savna',
      },
    },
    sports_centre: 'Športni center',
    sports_hall: 'Športna dvorana',
    stadium: 'Stadion',
    summer_camp: 'Poletni tabor',
    sunbathing: 'Prostor za sončenje',
    swimming_area: 'Območje za plavanje',
    swimming_pool: 'Bazen',
    tanning_salon: 'Solarij',
    track: {
      '*': 'Dirkalna proga',
      sport: {
        cycling: 'Kolesarska proga',
        equestrian: 'Konjeniška proga',
        horse_racing: 'Konjska dirkalna proga',
      },
    },
    trampoline_park: 'Trampolinski park',
    water_park: 'Vodni park',
    wildlife_hide: 'Opazovalnica divjih živali',
  },
  man_made: {
    '*': '{}',
    adit: {
      '*': 'Rudniški rov',
      disused: {
        yes: 'Opuščen rudniški rov',
      },
    },
    antenna: 'Antena',
    apiary: 'Čebelnjak',
    beacon: 'Svetilnik',
    beehive: 'Čebelji panj',
    bridge: 'Most',
    bunker_silo: 'Silažna jama',
    cairn: 'Kamniti mož',
    cellar_entrance: 'Vhod v klet',
    chimney: 'Dimnik',
    clearcut: 'Goloseka',
    communications_tower: 'Velik telekomunikacijski stolp',
    cooling_tower: 'Hladilni stolp',
    crane: 'Žerjav',
    cross: 'Križ',
    cutline: 'Gozdni presek',
    dyke: 'Protipoplavni nasip',
    embankment: 'Nasip',
    flagpole: 'Zastavni drog',
    "forester's_lodge": 'Gozdarska koča',
    gasometer: 'Plinohram',
    goods_conveyor: 'Tekoči trak',
    groyne: 'Kratek obrežni nasip',
    lighthouse: 'Svetilnik',
    manhole: 'Kanalizacijski jašek',
    mast: {
      '*': 'Steber',
      'tower:type': {
        clock: 'Steber z uro',
        communication: 'Komunikacijski steber',
        lighting: 'Razsvetljevalni steber',
        monitoring: 'Nadzorni steber',
        radar: 'Radarski steber',
        siren: 'Steber s sireno',
      },
    },
    mineshaft: {
      '*': 'Rudniški jašek',
      disused: {
        yes: 'Opuščen rudniški jašek',
      },
    },
    monitoring_station: 'Nadzorna postaja',
    nesting_site: 'Gnezdišče',
    observatory: 'Observatorij',
    pier: 'Pomol',
    pipeline: {
      '*': 'Cevovod',
      location: {
        underground: 'Podzemni cevovod',
        underwater: 'Podvodni cevovod',
      },
    },
    pumping_station: 'Črpalna postaja',
    reservoir_covered: 'Pokriti rezervoar',
    silo: 'Silos',
    snow_cannon: 'Snežni top',
    spoil_heap: 'Odval',
    spring_box: 'Zajetje izvira',
    storage_tank: 'Skladiščni rezervoar',
    street_cabinet: 'Ulična omarica',
    surveillance: 'Nadzorna kamera',
    survey_point: 'Geodetska točka',
    telescope: 'Teleskop',
    tower: {
      '*': 'Stolp',
      'tower:type': {
        bell_tower: 'Zvonik',
        climbing: 'Plezalni stolp',
        clock: 'Urni stolp',
        communication: 'Telekomunikacijski stolp',
        cooling: 'Hladilni stolp',
        defensive: 'Obrambni stolp',
        diving: 'Skakalni stolp',
        hose: 'Stolp za sušenje cevi',
        lighting: 'Razsvetljevalni stolp',
        minaret: 'Minaret',
        monitoring: 'Nadzorni stolp',
        observation: 'Razgledni stolp',
        pagoda: 'Pagoda',
        radar: 'Radarski stolp',
        siren: 'Stolp s sireno',
        watchtower: 'Stražni stolp',
      },
    },
    utility_pole: 'Oskrbovalni drog',
    wastewater_plant: 'Čistilna naprava',
    water_tap: 'Vodovodna pipa',
    water_tower: 'Vodni stolp',
    water_well: 'Vodnjak',
    water_works: 'Vodarna',
    watermill: 'Mlin na vodo',
    windmill: 'Mlin na veter',
    works: 'Tovarna',
  },
  military: {
    '*': 'Vojaški objekt {}',
    academy: 'Vojaška akademija',
    airfield: 'Vojaško letališče',
    ammunition: 'Skladišče streliva',
    barracks: 'Vojašnica',
    base: 'Vojaška baza',
    bunker: 'Bunker',
    checkpoint: 'Vojaška kontrolna točka',
    danger_area: 'Vojaško nevarno območje',
    depot: 'Vojaško skladišče',
    launchpad: 'Izstrelišče',
    naval_base: 'Pomorska baza',
    nuclear_explosion_site: 'Mesto jedrskega poskusa',
    obstacle_course: 'Vojaška ovirna steza',
    office: 'Vojaški urad',
    range: 'Strelišče',
    school: 'Vojaška šola',
    training_area: 'Vojaško vadbišče',
    trench: 'Jarek',
  },
  mountain_pass: {
    yes: 'Gorski prelaz',
  },
  natural: {
    '*': '{}',
    arch: 'Skalno okno',
    bare_rock: 'Gola skala',
    basin: 'Kotlina',
    bay: 'Zaliv',
    beach: 'Plaža',
    birds_nest: 'Ptičje gnezdo',
    cave_entrance: 'Jama',
    cliff: 'Pečina',
    earth_bank: 'Brežina',
    fell: 'Gola gorska vzpetina',
    geyser: 'Gejzir',
    glacier: 'Ledenik',
    grassland: 'Travišče',
    gully: 'Grapa',
    heath: 'Resava',
    hot_spring: 'Termalni izvir',
    landslide: 'Zemeljski plaz',
    mountain_range: 'Gorovje',
    mud: 'Blato',
    peak: 'Vrh',
    plateau: 'Planota',
    ridge: 'Greben',
    rock: 'Skala',
    saddle: 'Sedlo',
    sand: 'Pesek',
    scree: 'Melišče',
    scrub: 'Grmovje',
    shingle: 'Prod',
    shrub: 'Grm',
    sinkhole: 'Vrtača',
    spring: {
      '*': 'Izvir',
      drinking_water: {
        yes: 'Pitni izvir',
        no: 'Nepitni izvir',
      },
      refitted: {
        yes: 'Urejeni izvir',
        no: 'Neurejeni izvir',
      },
      intermittent: {
        yes: 'Občasni izvir',
      },
      seasonal: {
        yes: 'Sezonski izvir',
      },
      water_characteristic: {
        '*': 'Mineralni izvir',
      },
    },
    stone: 'Balvan',
    tree: {
      '*': 'Drevo',
      protected: { yes: 'Zavarovano drevo' },
      denotation: {
        natural_monument: 'Drevesni naravni spomenik',
        landmark: 'Izstopajoče drevo',
        avenue: 'Drevo v drevoredu',
        urban: 'Mestno drevo',
        agricultural: 'Kmetijsko drevo',
      },
    },
    tree_row: 'Drevored',
    valley: 'Dolina',
    volcano: 'Ognjenik',
    water: 'Vodna površina',
    wetland: {
      '*': 'Mokrišče',
      wetland: {
        bog: 'Barje',
        reedbed: 'Trstičje',
        marsh: 'Močvirje',
        swamp: 'Močvara',
        wet_meadow: 'Mokrotni travnik',
        mangrove: 'Mangrova',
        fen: 'Nizko barje',
      },
    },
    wood: 'Gozd',
  },
  obstacle: {
    '*': 'Ovira {}',
    vegetation: 'Gosto rastlinje',
    fallen_tree: 'Podrto drevo / drevesa',
    unevenness: 'Neravnina',
    precipice: 'Prepad',
    heap: 'Kup',
    hole: 'Luknja',
    mud: 'Blato',
  },
  place: {
    '*': 'Kraj {}',
    city: 'Velemesto',
    country: 'Država',
    farm: 'Kmetija',
    hamlet: 'Zaselek',
    island: 'Otok',
    islet: 'Otoček',
    isolated_dwelling: 'Samota',
    locality: 'Lokaliteta',
    ocean: 'Ocean',
    sea: 'Morje',
    square: 'Trg',
    state: 'Zvezna država',
    suburb: 'Predmestje',
    town: 'Mesto',
    village: 'Vas',
  },
  power: {
    '*': '{}',
    generator: {
      '*': 'Generator električne energije',
      'generator:source': {
        nuclear: {
          '*': 'Generator električne energije iz jedrske energije',
          'generator:method': {
            fission: 'Generator električne energije iz jedrske cepitve',
            fusion: 'Generator električne energije iz jedrske fuzije',
          },
        },
        wind: {
          '*': 'Generator električne energije iz vetrne energije',
        },
        hydro: {
          '*': 'Generator električne energije iz vodne energije',
          'generator:method': {
            'water-storage':
              'Generator električne energije iz akumulirane vodne energije',
            'water-pumped-storage':
              'Generator električne energije iz črpalne vodne energije',
            'run-of-the-river':
              'Generator električne energije iz pretočne vodne energije',
          },
        },
        tidal: {
          '*': 'Generator električne energije iz energije plimovanja',
          'generator:method': {
            barrage: 'Generator električne energije iz plimske pregrade',
            stream: 'Generator električne energije iz plimskega toka',
          },
        },
        wave: {
          '*': 'Generator električne energije iz energije morskih valov',
        },
        geothermal: {
          '*': 'Generator električne energije iz geotermalne energije',
        },
        solar: {
          '*': 'Generator električne energije iz sončnega sevanja',
          'generator:method': {
            thermal:
              'Generator električne energije iz sončnega sevanja – termično',
            photovoltaic:
              'Generator električne energije iz sončnega sevanja – fotovoltaično',
          },
        },
        coal: {
          '*': 'Generator električne energije iz zgorevanja premoga',
        },
        gas: {
          '*': 'Generator električne energije iz zgorevanja plina',
        },
        biomass: {
          '*': 'Generator električne energije iz biomase',
          'generator:method': {
            combustion: 'Generator električne energije iz zgorevanja biomase',
            gasification: 'Generator električne energije iz uplinjanja biomase',
            anaerobic_digestion:
              'Generator električne energije iz anaerobne razgradnje biomase',
          },
        },
        biofuel: {
          '*': 'Generator električne energije iz biogoriva',
        },
        biogas: {
          '*': 'Generator električne energije iz bioplina',
        },
        oil: {
          '*': 'Generator električne energije iz zgorevanja nafte',
        },
        diesel: {
          '*': 'Generator električne energije iz zgorevanja dizelskega goriva',
        },
        gasoline: {
          '*': 'Generator električne energije iz zgorevanja bencina',
        },
        waste: {
          '*': 'Generator električne energije iz zgorevanja odpadkov',
          'generator:method': {
            combustion: 'Generator električne energije iz zgorevanja odpadkov',
            gasification:
              'Generator električne energije iz uplinjanja odpadkov',
          },
        },
      },
    },
    line: 'Električni daljnovod',
    minor_line: 'Manjši električni vod',
    plant: {
      '*': 'Elektrarna',
      'plant:source': {
        nuclear: {
          '*': 'Jedrska elektrarna',
          'plant:method': {
            fission: 'Elektrarna z jedrsko cepitvijo',
            fusion: 'Elektrarna z jedrsko fuzijo',
          },
        },
        wind: {
          '*': 'Vetrna elektrarna',
        },
        hydro: {
          '*': 'Hidroelektrarna',
          'plant:method': {
            'water-storage': 'Akumulacijska hidroelektrarna',
            'water-pumped-storage': 'Črpalna hidroelektrarna',
            'run-of-the-river': 'Pretočna hidroelektrarna',
          },
        },
        tidal: {
          '*': 'Plimska elektrarna',
          'plant:method': {
            barrage: 'Plimska elektrarna s pregrado',
            stream: 'Plimska elektrarna na tok',
          },
        },
        wave: {
          '*': 'Valovna elektrarna',
        },
        geothermal: {
          '*': 'Geotermalna elektrarna',
        },
        solar: {
          '*': 'Sončna elektrarna',
          'plant:method': {
            thermal: 'Sončna termična elektrarna',
            photovoltaic: 'Fotovoltaična elektrarna',
          },
        },
        coal: {
          '*': 'Termoelektrarna na premog',
        },
        gas: {
          '*': 'Plinska elektrarna',
        },
        biomass: {
          '*': 'Elektrarna na biomaso',
          'plant:method': {
            combustion: 'Elektrarna z zgorevanjem biomase',
            gasification: 'Elektrarna z uplinjanjem biomase',
            anaerobic_digestion: 'Elektrarna z anaerobno razgradnjo biomase',
          },
        },
        biofuel: {
          '*': 'Elektrarna na biogorivo',
        },
        biogas: {
          '*': 'Bioplinska elektrarna',
        },
        oil: {
          '*': 'Elektrarna na nafto',
        },
        diesel: {
          '*': 'Dizelska elektrarna',
        },
        gasoline: {
          '*': 'Bencinska elektrarna',
        },
        waste: {
          '*': 'Sežigalnica odpadkov s proizvodnjo elektrike',
          'plant:method': {
            combustion: 'Elektrarna z zgorevanjem odpadkov',
            gasification: 'Elektrarna z uplinjanjem odpadkov',
          },
        },
      },
    },
    pole: 'Električni drog',
    substation: 'Elektrorazdelilna postaja',
    tower: 'Daljnovodni steber',
    transformer: 'Transformator',
  },
  public_transport: {
    platform: 'Peron javnega prevoza',
    station: 'Postaja',
    stop_position: 'Postajališče',
  },
  railway: {
    '*': 'Železnica',
    abandoned: 'Opuščena železnica',
    construction: 'Železnica v gradnji',
    proposed: 'Predlagana železnica',
    disused: 'Neuporabljana železnica',
    funicular: 'Vzpenjača',
    light_rail: 'Lahka železnica',
    miniature: 'Miniaturna železnica',
    monorail: 'Enotirna železnica',
    narrow_gauge: 'Ozkotirna železnica',
    rail: 'Železniška proga',
    subway: 'Proga podzemne železnice',
    tram: 'Tramvajska proga',
    halt: 'Železniško postajališče',
    platform: 'Železniški peron',
    preserved: 'Muzejska železnica',
    station: 'Železniška postaja',
    stop: 'Železniško postajališče',
    subway_entrance: 'Vhod v podzemno železnico',
    tram_stop: 'Tramvajsko postajališče',
    buffer_stop: 'Železniški odbojnik',
    crossing: 'Križanje železniških prog',
    derail: 'Iztirnik',
    railway_crossing: 'Železniški prehod',
    roundhouse: 'Krožna lokomotivna remiza',
    signal: 'Železniški signal',
    switch: 'Železniška kretnica',
    level_crossing: 'Nivojski železniški prehod',
    traverser: 'Železniški prestavljalnik',
    turntable: 'Železniška vrtljiva plošča',
    ventilation_shaft: 'Prezračevalni jašek železnice',
    wash: 'Pralnica vlakov',
    water_crane: 'Železniški vodni žerjav',
    workshop: 'Železniška delavnica',
  },
  shop: {
    '*': 'Trgovina {}',
    household_linen: 'Gospodinjsko perilo',
    charity: 'Dobrodelna trgovina',
    chocolate: 'Trgovina s čokolado',
    fashion_accessories: 'Trgovina z modnimi dodatki',
    frozen_food: 'Trgovina z zamrznjeno hrano',
    hearing_aids: 'Trgovina s slušnimi aparati',
    weapons: 'Trgovina z orožjem',
    alcohol: 'Trgovina z alkoholom',
    antiques: 'Starine',
    art: 'Trgovina z umetninami',
    baby_goods: 'Otroški pripomočki',
    bag: 'Trgovina s torbami',
    bakery: 'Pekarna',
    bathroom_furnishing: 'Kopalniški studio',
    beauty: 'Lepotni salon',
    bed: 'Trgovina s posteljami',
    beverages: 'Trgovina s pijačo',
    bicycle: 'Trgovina s kolesi',
    bookmaker: 'Stavnica',
    books: 'Knjigarna',
    boutique: 'Butik',
    butcher: 'Mesnica',
    camera: 'Trgovina s fotoaparati',
    car: 'Prodaja avtomobilov',
    car_parts: 'Prodaja avtodelov',
    car_repair: 'Avtoservis',
    carpet: 'Trgovina s preprogami',
    cheese: 'Trgovina s siri',
    chemist: 'Drogerija',
    clothes: 'Trgovina z oblačili',
    coffee: 'Trgovina s kavo',
    collector: 'Trgovina za zbiralce',
    computer: 'Računalniška trgovina',
    confectionery: 'Slaščičarna',
    convenience: 'Živila',
    copyshop: 'Kopirnica',
    cosmetics: 'Trgovina s kozmetiko',
    craft: 'Trgovina z umetniškimi in obrtnimi potrebščinami',
    curtain: 'Trgovina z zavesami',
    dairy: 'Mlečni izdelki',
    deli: 'Delikatesa',
    department_store: 'Veleblagovnica',
    doityourself: 'Naredi si sam',
    doors: 'Trgovina z vrati',
    dry_cleaning: 'Kemična čistilnica',
    'e-cigarette': 'E-cigarete',
    electrical: 'Elektroinštalacijski material',
    electronics: 'Elektronika',
    erotic: 'Sexshop',
    fabric: 'Trgovina s tekstilom',
    farm: 'Kmečki izdelki',
    fireplace: 'Trgovina s kamini',
    fishing: 'Ribiške potrebščine',
    flooring: 'Trgovina s talnimi oblogami',
    florist: 'Cvetličarna',
    funeral_directors: 'Pogrebna služba',
    furniture: 'Pohištvo',
    games: 'Družabne igre',
    garden_center: 'Vrtni center',
    garden_centre: 'Vrtni center',
    general: 'Mešano blago',
    gift: 'Trgovina z darili',
    glaziery: 'Steklar',
    greengrocer: 'Sadje in zelenjava',
    hairdresser: 'Frizerstvo',
    hardware: 'Železnina',
    health_food: 'Trgovina z zdravo hrano',
    hifi: 'Trgovina s Hi-Fi',
    houseware: 'Gospodinjske potrebščine',
    hunting: 'Lovske potrebščine',
    ice_cream: 'Sladoled',
    interior_decoration: 'Notranja dekoracija',
    jewelry: 'Zlatarna',
    kiosk: 'Kiosk',
    kitchen: 'Kuhinjski studio',
    laundry: 'Pralnica',
    lighting: 'Svetila',
    locksmith: 'Ključavničar',
    lottery: 'Loterija',
    mall: 'Nakupovalno središče',
    massage: 'Masažni salon',
    medical_supply: 'Medicinski pripomočki',
    mobile_phone: 'Trgovina z mobilnimi telefoni',
    model: 'Modelarstvo',
    motorcycle: 'Prodaja motociklov',
    music: 'Trgovina z glasbo',
    musical_instrument: 'Trgovina z glasbili',
    newsagent: 'Časopisi in revije',
    nutrition_supplements: 'Prehranska dopolnila',
    optician: 'Optika',
    outdoor: 'Trgovina z opremo za na prosto',
    outpost: 'Prevzemno mesto',
    paint: 'Trgovina z barvami',
    pastry: 'Trgovina s sladkim pecivom',
    pawnbroker: 'Zastavljalnica',
    perfumery: 'Parfumerija',
    pet: 'Trgovina za male živali',
    pet_grooming: 'Nega hišnih ljubljenčkov',
    photo: 'Fotografska trgovina',
    radiotechnics: 'Prodaja elektronskih komponent',
    rental: 'Izposojevalnica',
    seafood: 'Morski sadeži',
    second_hand: 'Rabljeno blago',
    sewing: 'Šiviljske potrebščine',
    shoes: 'Obutev',
    sports: 'Športne potrebščine',
    stationery: 'Papirnica',
    supermarket: 'Supermarket',
    tailor: 'Krojač',
    tattoo: 'Tetovažni studio',
    tea: 'Čajnica',
    ticket: 'Prodaja vstopnic',
    tobacco: 'Trafika',
    toys: 'Trgovina z igračami',
    trade: 'Gradbeni material',
    travel_agency: 'Potovalna agencija',
    tyres: 'Vulkanizerstvo',
    vacant: 'Prazna trgovina',
    variety_store: 'Trgovina z raznovrstnim blagom',
    video: 'Videoteka',
    video_games: 'Videoigre',
    watches: 'Ure',
    wholesale: 'Veleprodaja',
    window_blind: 'Trgovina z žaluzijami',
    wine: 'Vinoteka',
  },
  sport: {
    '*': 'Šport {}',
    '10pin': 'Bowling (ten-pin)',
    '8pin': 'Kegljanje z osmimi keglji',
    '9pin': 'Kegljanje (devet kegljev)',
    'five-a-side': 'Mali nogomet (5 na 5)',
    'in-line_hockey': 'Inline hokej',
    'shot-put': 'Suvanje krogle',
    aerobics: 'Aerobika',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'Ameriški nogomet',
    american_handball: 'Ameriška rokometna igra',
    archery: 'Lokostrelstvo',
    association_football: 'Nogomet (asociacijski nogomet)',
    athletics: 'Atletika',
    australian_football: 'Avstralski nogomet',
    axe_throwing: 'Metanje sekire',
    badminton: 'Badminton',
    balle_pelote: 'Balle pelote',
    ballooning: 'Letenje s toplozračnim balonom',
    bandy: 'Bandy',
    barre: 'Barre vadba',
    base: 'BASE skoki',
    baseball: 'Baseball',
    basketball: 'Košarka',
    batting_cage: 'Vadbena kletka (baseball/softball)',
    beach_soccer: 'Nogomet na mivki',
    beach_tennis: 'Tenis na mivki',
    beachhandball: 'Rokomet na mivki',
    beachtennis: 'Tenis na mivki',
    beachvolleyball: 'Odbojka na mivki',
    biathlon: 'Biatlon',
    bicycle: 'Kolesarstvo',
    billards: 'Biljard',
    billiards: 'Biljard',
    bmx: 'BMX',
    bobsleigh: 'Bob',
    bodybuilding: 'Bodibilding',
    boules: 'Balinanje',
    bowling: 'Bowling',
    bowls: 'Bowls',
    boxing: 'Boks',
    bullfighting: 'Bikoborba',
    calisthenics: 'Kalistenika',
    canadian_football: 'Kanadski nogomet',
    candlepin: 'Candlepin bowling',
    canoe_polo: 'Kanu polo',
    canoe: 'Kanu',
    chess: 'Šah',
    chinlone: 'Chinlone',
    cliff_diving: 'Skoki v vodo s pečin',
    climbing_adventure: 'Pustolovsko plezanje',
    climbing: 'Plezanje',
    cockfighting: 'Petelinji boji',
    cricket_nets: 'Kriketne mreže',
    cricket: 'Kriket',
    croquet: 'Kroket',
    crossfit: 'CrossFit vadba',
    curling: 'Curling',
    cycle_ball: 'Kolesarski nogomet',
    cycle_polo: 'Kolesarski polo',
    cycling: 'Kolesarstvo',
    dance: 'Ples',
    dancing: 'Ples',
    darts: 'Pikado',
    disc_golf: 'Disk golf',
    diving: 'Skoki v vodo',
    dodgeball: 'Med dvema ognjema',
    dog_agility: 'Pasji agility',
    dog_racing: 'Pasje dirke',
    dragon_boat: 'Zmajev čoln (dirke)',
    equestrian: 'Konjeništvo',
    fencing: 'Sabljanje',
    field_hockey: 'Hokej na travi',
    fistball: 'Fistball',
    fitness: 'Fitnes',
    fives: 'Fives',
    floorball: 'Floorball',
    football: 'Nogomet',
    footballgolf: 'Nogometni golf',
    four_square: 'Igra four square',
    free_flying: 'Prosto letenje',
    freediving: 'Prosto potapljanje',
    funnel_ball: 'Igra funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Galski nogomet',
    gaelic_games: 'Galske igre',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Jadralno letenje',
    golf: 'Golf',
    gymnastics: 'Gimnastika',
    handball: 'Rokomet',
    hanggliding: 'Zmajarstvo',
    hapkido: 'Hapkido',
    high_rope_course: 'Visoki vrvni park',
    hiking: 'Pohodništvo',
    hockey: 'Hokej',
    hopscotch: 'Igra ristanc',
    horse_racing: 'Konjske dirke',
    horse_riding: 'Jahanje',
    horseshoes: 'Metanje podkev',
    ice_hockey: 'Hokej na ledu',
    ice_skating: 'Drsanje',
    ice_stock: 'Ledni šport (Eisstock)',
    jetsprint: 'Dirke hitrih čolnov (jet sprint)',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Karting',
    kick_scooter: 'Skiro (šport)',
    kickball: 'Kickball',
    kickboxing: 'Kickboxing',
    kitesurfing: 'Kitesurfanje',
    korfball: 'Korfball',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Lacrosse',
    laser_tag: 'Laserski boj',
    long_jump: 'Skok v daljino',
    martial_arts: 'Borilne veščine',
    mind_body_interventions: 'Vadba telo–um (npr. joga)',
    miniature_golf: 'Minigolf',
    model_aerodrome: 'Modelarsko letališče',
    motocross: 'Motokros',
    motor: 'Motošport',
    mtb: 'Gorsko kolesarstvo',
    multi: 'Različni športi',
    netball: 'Netball',
    nine_mens_morris: 'Igra mlin (Nine men’s morris)',
    obstacle_course: 'Tek z ovirami',
    orienteering: 'Orientacijski tek',
    paddle_tennis: 'Paddle tenis',
    paddleball: 'Paddleball',
    paddleboard: 'Supanje (stand-up paddleboarding)',
    padel: 'Padel',
    paintball: 'Paintball',
    parachuting: 'Padalstvo',
    paragliding: 'Jadralno padalstvo',
    parkour: 'Parkour',
    pedal_car_racing: 'Dirke s pedalnimi avtomobili',
    pelota: 'Pelota',
    pesäpallo: 'Pesäpallo (finski baseball)',
    petanque: 'Petanque',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Ples ob drogu',
    polo: 'Polo',
    powerlifting: 'Trojboj (powerlifting)',
    racquet: 'Loparski šport',
    rc_car: 'RC avtomobili',
    rodeo: 'Rodeo',
    roller_hockey: 'Hokej na kotalkah',
    roller_skating: 'Kotalkanje',
    rowing: 'Veslanje',
    rugby_league: 'Rugby liga',
    rugby_union: 'Rugby unija',
    rugby: 'Rugby',
    running: 'Tek',
    russian_skittles: 'Ruski keglji (gorodki)',
    safety_training: 'Varnostni trening',
    sailing: 'Jadranje',
    scuba_diving: 'Potapljanje',
    shooting_range: 'Strelišče',
    shooting: 'Streljanje',
    shuffleboard: 'Shuffleboard',
    skateboard: 'Rolkanje',
    skating: 'Drsanje',
    ski_jumping: 'Smučarski skoki',
    skiing: 'Smučanje',
    snooker: 'Snooker',
    snorkeling: 'Potapljanje z masko in dihalko',
    soccer: 'Nogomet',
    softball: 'Softball',
    speedway: 'Speedway (motociklizem na ravni progi)',
    squash: 'Squash',
    streetball: 'Ulična košarka',
    summer_toboggan: 'Poletno sankanje (proga)',
    sumo: 'Sumo',
    surfing: 'Deskanje na valovih',
    swimming: 'Plavanje',
    table_soccer: 'Namizni nogomet',
    table_tennis: 'Namizni tenis',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    team_handball: 'Rokomet',
    tennis: 'Tenis',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    toboggan: 'Sankanje',
    touch_football: 'Touch football',
    trampoline: 'Skakanje na trampolinu',
    trugo: 'Trugo',
    tug_of_war: 'Vlečenje vrvi',
    ultimate: 'Ultimate frizbi',
    ultralight_aviation: 'Ultralahko letalstvo',
    volleyball: 'Odbojka',
    wakeboarding: 'Wakeboarding',
    walking: 'Športna hoja',
    water_polo: 'Vaterpolo',
    water_ski: 'Smučanje na vodi',
    water_sports: 'Vodni športi',
    weightlifting: 'Dvigovanje uteži',
    windsurfing: 'Jadranje na deski',
    workout: 'Vadba',
    wrestling: 'Rokoborba',
    yoga: 'Joga',
    zurkhaneh_sport: 'Zurkhaneh (iranski tradicionalni šport)',
  },
  tourism: {
    '*': '{}',
    alpine_hut: 'Planinska koča',
    apartment: 'Apartma',
    aquarium: 'Akvarij',
    artwork: {
      '*': 'Umetnina',
      artwork_type: {
        architecture: 'Arhitektura',
        bust: 'Doprsni kip',
        graffiti: 'Grafit',
        installation: 'Umetniška instalacija',
        mosaic: 'Mozaik',
        mural: 'Stenska poslikava',
        painting: 'Slika',
        relief: 'Relief (umetnina)',
        sculpture: 'Skulptura',
        statue: 'Kip',
        stone: 'Balvan (umetnina)',
      },
    },
    attraction: 'Znamenitost',
    camp_site: 'Kamp',
    caravan_site: 'Avtokamp za prikolice',
    chalet: 'Počitniška koča',
    gallery: 'Galerija',
    guest_house: 'Gostišče',
    hostel: 'Hostel',
    hotel: 'Hotel',
    information: {
      '*': 'Informacije',
      information: {
        '*': 'Informacije {}',
        board: 'Informacijska tabla',
        guidepost: 'Smerokaz',
        map: 'Zemljevid',
        office: 'Turistično informacijski center',
        route_marker: 'Oznaka poti',
      },
    },
    motel: 'Motel',
    museum: 'Muzej',
    picnic_site: 'Prostor za piknik',
    theme_park: 'Tematski park',
    viewpoint: 'Razgledna točka',
    wilderness_hut: 'Koča v divjini',
    zoo: 'ZOO',
  },
  type: {
    route: {
      '*': 'Pot',
      route: {
        '*': 'Pot {}',
        bicycle: 'Kolesarska pot',
        bus: 'Avtobusna proga',
        foot: 'Pešpot',
        hiking: {
          '*': 'Pohodniška pot',
          network: {
            lwn: 'Lokalna pohodniška pot',
            rwn: 'Regionalna pohodniška pot',
            nwn: 'Državna pohodniška pot',
            iwn: 'Mednarodna pohodniška pot',
          },
        },
        horse: 'Jahalna pot',
        mtb: 'Gorskokolesarska pot',
        piste: 'Smučarska proga ali pot',
        railway: 'Železnica',
        ski: 'Smučarska pot',
        tram: 'Tramvajska proga',
      },
    },
  },
  seasonal: {
    yes: {
      '*': 'Sezonski',
      waterway: {
        stream: 'Sezonski potok',
        ditch: 'Sezonski jarek',
        drain: 'Sezonski odtok',
        waterfall: 'Sezonski slap',
      },
      natural: {
        water: 'Sezonska vodna površina',
      },
    },
  },
  intermittent: {
    yes: {
      '*': 'Občasni',
      waterway: {
        stream: 'Občasni potok',
        ditch: 'Občasni jarek',
        drain: 'Občasni odtok',
        waterfall: 'Občasni slap',
      },
      natural: {
        water: 'Občasna vodna površina',
      },
    },
  },
  waterway: {
    '*': 'Vodotok {}',
    canal: 'Kanal',
    canoe_pass: 'Prehod za kanuje',
    dam: 'Jez',
    ditch: 'Jarek',
    drain: 'Odtok',
    fairway: 'Plovna pot',
    fish_pass: 'Ribja steza',
    flowline: 'Tokovnica',
    link: 'Povezava vodotoka',
    pressurised: 'Tlačni vodovod',
    rapids: 'Brzice',
    river: 'Reka',
    stream: 'Potok',
    tidal_channel: 'Plimski kanal',
    waterfall: 'Slap',
    weir: 'Prelivni jez',
  },
  trail_visibility: {
    excellent: 'Odlična vidnost poti',
    good: 'Dobra vidnost poti',
    intermediate: 'Srednja vidnost poti',
    bad: 'Slaba vidnost poti',
    horrible: 'Zelo slaba vidnost poti',
    no: 'Brez vidnosti poti',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Rdeča',
  blue: 'Modra',
  green: 'Zelena',
  yellow: 'Rumena',
  orange: 'Oranžna',
  purple: 'Purpurna',
  violet: 'Vijolična',
  white: 'Bela',
  black: 'Črna',
  gray: 'Siva',
  brown: 'Rjava',
};
