import { DeepPartial } from '../deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  access: {
    customers: 'Len pre zákazníkov',
    private: 'Súkromný prístup',
    no: 'Zákaz vstupu',
  },
  aeroway: {
    aerodrome: 'Letisko',
    airstrip: 'Vzletová a pristávacia dráha (malé letisko)',
    apron: 'Odstavná plocha lietadiel',
    gate: 'Nástupná letisková brána',
    hangar: 'Hangár pre lietadlá',
    helipad: 'Heliport (vrtuľníková plocha)',
    holding_position: 'Vyčkávacie miesto lietadiel',
    jet_bridge: 'Nástupný most / mostík / tunel do lietadla',
    navigationaid: 'Letecké navigačné zariadenie',
    parking_position: 'Stojisko lietadla',
    runway: 'Vzletová a pristávacia dráha',
    stopway: 'Bezpečnostná plocha za leteckou dráhou',
    taxilane: 'Rolovacia letisková dráha na odbavovacej ploche',
    taxiway: 'Rolovacia letisková dráha',
    terminal: 'Letiskový terminál',
    threshold: 'Prahový bod letiskovej dráhy',
    tower: 'Riadiaca veža letovej prevádzky',
    windsock: 'Veterný rukáv',
  },
  aerialway: {
    '*': 'Lanová dráha',
    cable_car: 'Kabínková lanovka',
    chair_lift: 'Sedačková lanovka',
    goods: 'Nákladná lanovka',
    'j-bar': 'J-kotva',
    magic_carpet: 'Pohyblivý pás',
    mixed_lift: 'Kombinovaná lanovka',
    platter: 'Tanierový vlek',
    pylon: 'Podpera lanovky',
    rope_tow: 'Lanový vlek',
    station: 'Stanica lanovky',
    't-bar': 'T-kotva',
    zip_line: 'Zipline',
  },
  amenity: {
    '*': '{}',
    animal_breeding: 'Chov zvierat',
    animal_shelter: 'Prístrešok pre zvieratá',
    arts_centre: 'Centrum umenia',
    atm: 'Bankomat',
    bank: 'Banka',
    bar: 'Bar',
    bbq: 'Gril',
    bench: 'Lavička',
    bicycle_parking: 'Parkovanie pre bicykle',
    bicycle_rental: 'Požičovňa bicyklov',
    bicycle_repair_station: 'Stojan na opravu bicyklov',
    biergarten: 'Pivná záhradka',
    brothel: 'Nevestinec',
    bureau_de_change: 'Zmenáreň',
    bus_station: 'Autobusová stanica',
    cafe: 'Kaviareň',
    car_rental: 'Požičovňa áut',
    car_wash: 'Autoumývarka',
    casino: 'Kasíno',
    charging_station: 'Nabíjacia stanica',
    childcare: 'Starostlivosť o deti',
    cinema: 'Kino',
    clinic: 'Poliklinika',
    clock: 'Hodiny',
    college: 'Dodatočné vzdelávanie',
    community_centre: 'Komunitné centrum',
    compressed_air: 'Kompresor (na pneumatiky)',
    courthouse: 'Súd',
    dentist: 'Zubná ambulancia',
    device_charging_station: 'Nabíjacia stanica pre zariadenia',
    doctors: 'Všeobecný lekár',
    dressing_room: 'Šatňa',
    drinking_water: 'Pitná voda',
    driving_school: 'Autoškola',
    embassy: 'Ambasáda',
    events_venue: 'Miesto konania podujatí',
    fast_food: 'Rýchle občerstvenie',
    feeding_place: 'Krmelec',
    ferry_terminal: 'Terminál trajektu',
    fire_station: 'Hasičská stanica',
    food_court: 'Food court',
    fountain: 'Fontána',
    fuel: 'Čerpacia stanica',
    funeral_hall: 'Pohrebná sieň',
    gambling: 'Herňa',
    game_feeding: 'Krmelec',
    grave_yard: 'Pohrebisko',
    grit_bin: 'Nádoba s posypom',
    hospital: 'Nemocnica',
    hunting_stand: 'Poľovnícky posed',
    ice_cream: 'Zmrzlina',
    kindergarten: 'Materská škola',
    language_school: 'Jazyková škola',
    library: 'Knižnica',
    marketplace: 'Trhovisko',
    monastery: 'Kláštor',
    money_transfer: 'Prevod peňazí',
    motorcycle_parking: 'Parkovanie motocyklov',
    motorcycle_rental: 'Požičovňa motocyklov',
    nightclub: 'Nočný klub',
    parcel_locker: 'Box na výdaj zásielok',
    parking: 'Parkovanie',
    parking_entrance: 'Vjazd/výjazd parkoviska',
    parking_space: 'Parkovacie miesto',
    pharmacy: 'Lekáreň',
    place_of_mourning: 'Dom smútku',
    place_of_worship: 'Miesto náboženských obradov',
    planetarium: 'Planetárium',
    police: 'Polícia',
    post_box: 'Poštová schránka',
    post_office: 'Pošta',
    prison: 'Väznica',
    pub: 'Hostinec',
    public_bookcase: 'Knižná búdka',
    ranger_station: 'Strážcovská stanica',
    recycling: 'Recyklovanie',
    restaurant: 'Reštaurácia',
    school: 'Škola',
    shelter: {
      '*': 'Prístrešok',
      shelter_type: {
        '*': 'Prístrešok {}',
        basic_hut: 'Jednoduchá chata, bivak, útulňa',
        changing_rooms: 'Prezliekáreň',
        field_shelter: 'Poľný prístrešok',
        lean_to: 'Prístrešok s otvorenou stenou',
        picnic_shelter: {
          '*': 'Piknikový prístrešok',
          fireplace: {
            yes: 'Piknikový prístrešok s krbom',
          },
        },
        public_transport: 'Prístrešok verejnej dopravy',
        rock_shelter: 'Skalný úkryt',
        sun_shelter: 'Prístrešok proti slnku',
        weather_shelter: 'Prístrešok proti nepriaznivému počasiu',
      },
    },
    shower: 'Sprcha',
    ski_rental: 'Požičovňa lyží',
    smoking_area: 'Fajčiarska zóna',
    social_centre: 'Sociálne centrum',
    social_facility: {
      '*': 'Sociálne zariadenie',
      social_facility: {
        ambulatory_care: 'Zariadenie ambulantnej starostlivosti',
        assisted_living: 'Zariadenie pre život s asistenciou',
        clothing_bank: 'Odevná banka',
        day_care: 'Zariadenie dennej starostlivosti',
        food_bank: 'Potravinová banka',
        group_home: 'Skupinové bývanie',
        hospice: 'Hospic',
        nursing_home: 'Dom s opatrovateľskou službou',
        shelter: 'Nocľahárňa',
        soup_kitchen: 'Vývarovňa',
        workshop: 'Chránená dielňa',
      },
    },
    stripclub: 'Striptízový bar',
    studio: 'Štúdio',
    taxi: 'Taxi',
    telephone: 'Telefón',
    theatre: 'Divadlo',
    toilets: 'WC',
    townhall: 'Mestská radnica, obecný úrad',
    traffic_park: 'Dopravné ihrisko',
    trolley_bay: 'Priestor pre vozíky',
    university: 'Univerzita',
    vacuum_cleaner: 'Vysávač',
    vehicle_inspection: 'Kontrola vozidiel',
    vending_machine: {
      '*': 'Automat',
      vending: {
        bicycle_tube: 'Automat na bicyklové duše',
        bread: 'Automat na chlieb',
        bottle_return: 'Automat na vrátenie zálohovaných fliaš',
        candles: 'Automat na sviečky',
        chewing_gums: 'Automat na žuvačky',
        cigarettes: 'Automat na cigarety',
        coffee: 'Automat na kávu',
        condoms: 'Automat na kondómy',
        drinks: 'Automat na nápoje',
        elongated_coin: 'Automat na pamätné mince',
        eggs: 'Automat na vajcia',
        excrement_bags: 'Automat na vrecúška pre exkrementy',
        food: 'Automat na jedlo',
        fuel: 'Automat na palivo',
        gas: 'Automat na palivo',
        ice_cream: 'Automat na zmrzlinu',
        ice_cubes: 'Automat na kocky ľadu',
        milk: 'Automat na mlieko',
        movies: 'Automat na filmy',
        newspapers: 'Automat na noviny',
        parking_tickets: 'Parkovací automat',
        pizza: 'Automat na pizzu',
        public_transport_tickets: 'Automat na lístky verejnej dopravy',
        stamps: 'Automat na známky',
        sweets: 'Automat na sladkosti',
        water: 'Automat na vodu',
      },
    },
    veterinary: 'Veterinár',
    waste_basket: 'Odpadkový kôš',
    waste_disposal: 'Likvidácia odpadu',
    water_point: 'Odber pitnej vody',
    watering_place: 'Napájadlo',
  },
  attraction: {
    animal: 'Zvieracia atrakcia',
    amusement_ride: 'Zábavná jazda',
    big_wheel: 'Ruské koleso',
    carousel: 'Kolotoč',
    historic: 'Historická atrakcia',
    maze: 'Bludisko',
    roller_coaster: 'Horská dráha',
    summer_toboggan: 'Letná bobová dráha',
    train: 'Vyhliadkový vláčik',
    water_slide: 'Tobogan',
  },
  barrier: {
    '*': 'Bariéra {}',
    block: 'Blok',
    bollard: 'Stĺpik',
    border_control: 'Hraničná kontrola',
    cable_barrier: 'Káblové zvodidlo',
    chain: 'Reťaz',
    city_wall: 'Hradba',
    ditch: 'Priekopa',
    entrance: 'Vstup',
    fence: 'Plot',
    gate: 'Brána',
    guard_rail: 'Zvodidlá',
    handrail: 'Zábradlie',
    hedge: 'Živý plot',
    kerb: 'Obrubník',
    lift_gate: 'Závora',
    retaining_wall: 'Oporný múr',
    rope: 'Lano',
    sliding_gate: 'Posuvná brána',
    swing_gate: 'Otočná závora',
    turnstile: 'Turniket',
    wall: 'Múr',
  },
  boundary: {
    '*': 'Oblasť',
    marker: 'Hraničný kameň',
    administrative: {
      '*': 'Administratívna oblasť',
      admin_level: {
        '2': 'Štát',
        '3': 'Región',
        '4': 'Kraj',
        '5': 'Provincia',
        '6': 'Mesto',
        '7': 'Oblasť',
        '8': 'Okres',
        '9': 'Obec',
        '10': 'Katastrálne územie',
      },
    },
    national_park: 'Národný park',
    protected_area: 'Chránená oblasť',
  },
  'abandoned:building': { '*': 'Trvalo opustená budova' },
  'disused:building': { '*': 'Nepoužívaná budova' },
  'ruins:building': { '*': 'Ruina budovy' },
  building: {
    '*': {
      '*': 'Budova',
      abandoned: {
        yes: 'Trvalo opustená budova',
      },
      disused: {
        yes: 'Nepoužívaná budova',
      },
      ruins: {
        yes: 'Ruina budovy',
      },
    },
    abandoned: 'Trvalo opustená budova',
    disused: 'Nepoužívaná budova',
    apartments: 'Apartmány (blok)',
    barn: 'Stodola',
    bungalow: 'Bungalov',
    bunker: 'Budova bunkra',
    cabin: 'Búda, chatka',
    cathedral: 'Katedrála',
    chapel: 'Kaplnka',
    church: 'Kostol',
    civic: 'Verejná budova',
    collapsed: 'Zrútena budova',
    commercial: 'Budova určená na komerčné účely',
    construction: 'Výstavba budovy',
    cowshed: 'Kravín',
    detached: 'Samostatne stojaci rodinný dom',
    dormitory: 'Internát',
    entrance: 'Vstup do budovy',
    farm_auxiliary: 'Pomocná budova farmy',
    farm: 'Statok',
    garage: 'Garáž',
    garages: 'Garáže',
    government: 'Vládna budova',
    grandstand: 'Tribúna',
    greenhouse: 'Sklenník',
    hangar: 'Hangár',
    hayloft: 'Senník',
    hospital: 'Budova nemocnice',
    hotel: 'Budova hotela',
    house: 'Rodinný dom',
    houseboat: 'Hausbót',
    hut: 'Chatrč',
    industrial: 'Budova určená na priemyselné účely',
    kindergarten: 'Budova materskej školy',
    kiosk: 'Kiosk',
    manufacture: 'Manufacture budova',
    mosque: 'Mešita',
    office: 'Budova s kanceláriami',
    parking: 'Budova parkovania',
    public: 'Verejná budova',
    residential: 'Obytný dom',
    retail: 'Budova predajne',
    roof: 'Strecha',
    ruins: 'Ruina budovy',
    school: 'Budova školy',
    semidetached_house: 'Dvojdom',
    service: 'Servisná budova',
    shed: 'Kôlňa',
    shrine: 'Svätyňa',
    stable: 'Stajňa',
    stadium: 'Budova štadiónu',
    static_caravan: 'Obytný príves, karavan',
    storage_tank: 'Cisterna',
    sty: 'Chlievik',
    supermarket: 'Supermarket budova',
    synagogue: 'Synagóga',
    temple: 'Chrám',
    terrace: 'Radový dom',
    train_station: 'Vlaková stanica',
    transformer_tower: 'Transformer tower',
    transportation: 'Budova prepravy',
    university: 'Budova univerzity',
    warehouse: 'Sklad',
    yes: 'Neurčitá budova',
  },
  fixme: {
    '*': 'Nesprávne alebo neúplne zmapovaný prvok',
  },
  ford: {
    yes: 'Brod',
  },
  bridge: {
    '*': {
      '*': 'Most',
      highway: {
        '*': 'Most pozemnej komunikácie',
      },
      railway: {
        '*': 'Železničný most',
      },
    },
    no: '',
  },
  tunnel: {
    '*': {
      '*': 'Tunel',
      highway: {
        '*': 'Tunel pozemnej komunikácie',
      },
      railway: {
        '*': 'Železničný tunel',
      },
    },
    culvert: 'Priepust',
    no: '',
  },
  oneway: {
    yes: 'Jednosmerka',
  },
  foot: {
    no: 'Vstup zakázaný',
    yes: 'Vstup povolený',
    private: 'Vstup len pre vlastníkov',
    designated: 'Vstup vyhradený',
  },
  bicycle: {
    no: 'Vjazd na bicykli zakázaný',
    yes: 'Vjazd na bicykli povolený',
    private: 'Vjazd na bicykli len pre vlastníkov',
    designated: 'Vjazd na bicykli vyhradený',
  },
  vehicle: {
    no: 'Vjazd vozidlom zakázaný',
    yes: 'Vjazd vozidlom povolený',
    private: 'Vjazd vozidlom len pre vlastníkov',
    designated: 'Vjazd vozidlom vyhradený',
  },
  motor_vehicle: {
    no: 'Vjazd motorovým vozidlom zakázaný',
    yes: 'Vjazd motorovým vozidlom povolený',
    private: 'Vjazd motorovým vozidlom len pre vlastníkov',
    designated: 'Vjazd motorovým vozidlom vyhradený',
  },
  highway: {
    '*': 'Cesta {}',
    bridleway: 'Jazdecká cesta',
    bus_stop: 'Autobusová zastávka',
    construction: 'Cesta vo výstavbe',
    crossing: 'Priechod',
    cycleway: 'Cyklochodník',
    footway: 'Chodník',
    living_street: 'Obytná zóna',
    motorway: 'Diaľnica',
    motorway_link: 'Napojenie na diaľnicu',
    path: {
      '*': 'Cestička',
      foot: {
        designated: {
          bicycle: {
            designated: 'Spoločná cesta pre chodcov aj cyklistov',
          },
        },
      },
    },
    pedestrian: 'Pešia zóna',
    piste: 'Lyžiarská trasa',
    platform: 'Nástupište',
    primary: 'Cesta prvej triedy',
    primary_link: 'Napojenie na cestu prvej triedy',
    raceway: 'Pretekárska dráha',
    residential: 'Ulica',
    road: 'Cesta neznámeho druhu',
    secondary: 'Cesta druhej triedy',
    secondaty_link: 'Napojenie na cestu druhej triedy',
    service: {
      '*': 'Servisná, príjazdová cesta',
      service: {
        '*': 'Servisná cesta {}',
        alley: 'Prejazdová cesta',
        bus: 'Cesta vyhradená pre autobus',
        'drive-through': 'Cesta pre nákup z auta',
        driveway: 'Príjazdová cesta',
        emergency_access: 'Požiarna cesta',
        parking_aisle: 'Cesta na parkovisku',
      },
    },
    steps: 'Schody',
    street_lamp: 'Pouličná lampa',
    tertiary: 'Cesta tretej triedy',
    tertiary_link: 'Napojenie na cestu tretej triedy',
    track: {
      '*': 'Lesná / poľná cesta neznámej kvality',
      tracktype: {
        grade1: 'Spevnená lesná / poľná cesta',
        grade2: 'Prevažne spevnená lesná / poľná cesta',
        grade3: 'Menej pevná lesná / poľná cesta',
        grade4: 'Prevažne mäkká lesná / poľná cesta',
        grade5: 'Mäkká lesná / poľná cesta',
      },
    },
    trunk: 'Cesta pre motorové vozidlá',
    trunk_link: 'Napojenie na cestu pre motorové vozidlá',
    unclassified: 'Neklasifikovaná cesta',
    via_ferrata: 'Zaistená cesta (Via ferrata)',
  },
  historic: {
    '*': 'Historický objekt {}',
    yes: 'Historický objekt',
    aircraft: 'Historické lietadlo',
    archaeological_site: 'Archeologické nálezisko',
    boundary_stone: 'Historický hraničný kameň',
    building: 'Historická budova',
    cannon: 'Historické delo',
    castle: 'Hrad',
    charcoal_pile: 'Miesto po uhliarskej milieri',
    church: 'Historický kostol',
    city_gate: 'Mestská brána',
    citywalls: 'Mestské hradby',
    fort: 'Pevnosť',
    heritage: 'Pamiatkové miesto',
    hollow_way: 'Úvozová cesta',
    house: 'Historický dom',
    manor: 'Panstvo',
    memorial: 'Pamätník',
    milestone: 'Historický míľnik',
    mine_shaft: 'Historická banská šachta',
    mine: 'Historická baňa',
    monastery: 'Historický kláštor',
    monument: 'Pomník, monument',
    ruins: {
      '*': 'Ruiny',
      ruins: {
        castle: 'Zrúcanina hradu',
      },
    },
    shieling: 'Salaš (historický)',
    stone: 'Historický kameň',
    tomb: 'Hrobka',
    tree_shrine: 'Svätý obrázok na strome',
    wayside_cross: 'Prícestný kríž',
    wayside_shrine: 'Božia muka',
    wreck: 'Vrak',
  },
  landuse: {
    '*': '{}',
    allotments: 'Záhradkárska oblasť',
    basin: 'Záchytná nádrž',
    brownfield: 'Miesto na novú výstavbu',
    cemetery: 'Cintorín',
    commercial: 'Komerčná zóna',
    construction: 'Stavenisko',
    education: 'Školská zóna',
    farmland: 'Pole',
    farmyard: 'Družstvo',
    forest: 'Hospodársky les',
    garages: 'Garáže',
    grass: 'Tráva',
    greenfield: 'Nové miesto na výstavbu',
    industrial: 'Priemyselná zóna',
    landfill: 'Skládka',
    meadow: 'Lúka',
    military: 'Vojenská oblasť',
    orchard: 'Sad',
    pedestrian: 'Plocha pre peších',
    plant_nursery: 'Lesná škôlka',
    quarry: 'Lom',
    railway: 'Plocha železnice',
    recreation_ground: 'Oddychová zóna',
    religions: 'Cirkevný pozemok',
    reservoir: 'Priehrada / nádrž',
    residential: 'Rezidenčná zóna',
    retail: 'Nákupná zóna',
    vineyard: 'Vinica',
    village_green: '"Náves"',
    winter_sports: 'Miesto zimných športov',
  },
  leisure: {
    '*': '{}',
    adult_gaming_centre: 'Herňa pre dospelých',
    amusement_arcade: 'Zábavná herňa',
    bandstand: 'Hudobný pavilón',
    bathing_place: 'Miesto na kúpanie',
    beach_resort: 'Plážový rezort',
    bird_hide: 'Pozorovateľňa vtáctva',
    bleachers: 'Tribúny',
    bowling_alley: 'Bowlingová dráha',
    dance: 'Tanečný priestor',
    disc_golf_course: 'Ihrisko na discgolf',
    dog_park: 'Park pre psy',
    escape_game: 'Úniková hra',
    firepit: 'Ohnisko',
    fishing: 'Miesto na rybárčenie',
    fitness_centre: 'Fitness centrum',
    fitness_station: 'Fitness stanica',
    garden: 'Záhrada',
    golf_course: 'Golfové ihrisko',
    hackerspace: 'Hackerspace',
    high_ropes_course: 'Lanový park',
    horse_riding: 'Jazdenie na koni',
    ice_rink: 'Klzisko',
    marina: 'Marína',
    miniature_golf: 'Minigolf',
    nature_reserve: 'Prírodná rezervácia',
    outdoor_seating: 'Vonkajšie sedenie',
    park: 'Park',
    picnic_table: {
      '*': 'Piknikový stôl',
      covered: {
        yes: 'Krytý piknikový stôl',
        no: 'Nekrytý piknikový stôl',
      },
    },
    pitch: 'Športové ihrisko',
    playground: 'Detské ihrisko',
    resort: 'Rekreačný rezort',
    sauna: {
      '*': 'Sauna',
      sauna: {
        hot: 'Fínska sauna',
        steam: 'Parná sauna (turecký kúpeľ)',
        smoke: 'Dymová sauna (fínska)',
        dry: 'Suchá sauna',
        hanjeungmak: 'Hanjeungmak (kórejská sauna)',
        aroma: 'Aromatická sauna',
        infrared: 'Infračervená sauna',
      },
    },
    slipway: 'Spúšťacia rampa pre lode',
    sports_centre: 'Športové centrum',
    sports_hall: 'Športová hala',
    stadium: 'Štadión',
    summer_camp: 'Letný tábor',
    sunbathing: 'Priestor na opaľovanie',
    swimming_area: 'Plavecká oblasť',
    swimming_pool: 'Bazén',
    tanning_salon: 'Solárium',
    track: 'Dráha',
    trampoline_park: 'Trampolínový park',
    water_park: 'Akvapark',
    wildlife_hide: 'Pozorovateľňa zveri',
  },
  man_made: {
    '*': '{}',
    adit: {
      '*': 'Banská štôlňa',
      disused: {
        yes: 'Nepoužívaná banská štôlňa',
      },
    },
    antenna: 'Anténa',
    apiary: 'Včelnica',
    beacon: 'Maják',
    beehive: 'Úľ',
    bridge: 'Most',
    bunker_silo: 'Silážna jama',
    cairn: 'Kamenný mužík',
    cellar_entrance: 'Pivničný vchod',
    chimney: 'Komín',
    clearcut: 'Rúbanisko',
    communications_tower: 'Veľká telekomunikačná veža',
    cooling_tower: 'Chladiacia veža',
    crane: 'Žeriav',
    cross: 'Kríž',
    cutline: 'Priesek',
    dyke: 'Hrádza',
    embankment: 'Násyp',
    flagpole: 'Vlajkový stožiar',
    "forester's_lodge": 'Horáreň',
    gasometer: 'Plynomer',
    goods_conveyor: 'Dopravný pás',
    groyne: 'Krátka pobrežná hrádza',
    lighthouse: 'Maják',
    manhole: 'Šachta',
    mast: {
      '*': 'Stožiar',
      'tower:type': {
        clock: 'Stožiar s hodinami',
        communication: 'Telekomunikačný stožiar',
        lighting: 'Osvetľovací stožiar',
        monitoring: 'Monitorovací stožiar',
        radar: 'Radarový stožiar',
        siren: 'Stožiar so sirénou',
      },
    },
    mineshaft: {
      '*': 'Banská šachta',
      disused: {
        yes: 'Nepoužívaná banská šachta',
      },
    },
    monitoring_station: 'Monitorovacia stanica',
    nesting_site: 'Hniezdo',
    observatory: 'Observatórium',
    pier: 'Mólo',
    pipeline: {
      '*': 'Potrubie',
      location: {
        underground: 'Podzemné potrubie',
        underwater: 'Podvodné potrubie',
      },
    },
    pumping_station: 'Prečerpávacia stanica',
    reservoir_covered: 'Krytý rezervoár',
    silo: 'Silo',
    snow_cannon: 'Snežné delo',
    spoil_heap: 'Halda',
    spring_box: 'Kryt prameňa',
    storage_tank: 'Skladovacia cisterna',
    street_cabinet: 'Pouličná skriňa',
    surveillance: 'Bezpečnostná kamera',
    survey_point: 'Geodetický bod',
    telescope: 'Teleskop',
    tower: {
      '*': 'Veža',
      'tower:type': {
        bell_tower: 'Zvonica',
        climbing: 'Lezecká veža',
        clock: 'Hodinová veža',
        communication: 'Telekomunikačná veža',
        cooling: 'Chladiarenska veža',
        defensive: 'Obranná veža',
        diving: 'Skokanská veža',
        hose: 'Sušiaca veža na hadice',
        lighting: 'Osvetľovacia veža',
        minaret: 'Minaret',
        monitoring: 'Monitorovacia veža',
        observation: 'Vyhliadková veža',
        pagoda: 'Pagoda',
        radar: 'Radarová veža',
        siren: 'Veža so sirénou',
        watchtower: 'Strážna veža',
      },
    },
    utility_pole: 'Úžitkový stožiar',
    wastewater_plant: 'Čistička odpadových vôd',
    water_tap: 'Vodovodný kohútik',
    water_tower: 'Vodárenská veža',
    water_well: 'Studňa',
    water_works: 'Vodohospodársky objekt',
    watermill: 'Vodný mlyn',
    windmill: 'Veterný mlyn',
    works: 'Fabrika',
  },
  military: {
    '*': 'Vojenský objekt {}',
    academy: 'Vojenská akadémia',
    airfield: 'Vojenské letisko',
    ammunition: 'Sklad munície',
    barracks: 'Kasárne',
    base: 'Vojenská základňa',
    bunker: 'Bunker',
    checkpoint: 'Vojenský kontrolný bod',
    danger_area: 'Vojenský nebezpečný priestor',
    depot: 'Vojenský sklad',
    launchpad: 'Odpaľovacia plocha',
    naval_base: 'Námorná základňa',
    nuclear_explosion_site: 'Miesto jadrového testu',
    obstacle_course: 'Vojenská prekážková dráha',
    office: 'Vojenský úrad',
    range: 'Vojenská strelnica',
    school: 'Vojenská škola',
    training_area: 'Vojenský výcvikový priestor',
    trench: 'Zákop',
  },
  mountain_pass: {
    yes: 'Horský prechod',
  },
  natural: {
    '*': '{}',
    arch: 'Skalné okno',
    bare_rock: 'Holá skala',
    basin: 'Kotlina',
    bay: 'Zátoka',
    beach: 'Pláž',
    birds_nest: 'Vtáčie hniezdo',
    cave_entrance: 'Jaskyňa',
    cliff: 'Bralo',
    earth_bank: 'Svah',
    fell: 'Bezlesý vrch / holina / pastvina',
    geyser: 'Gejzír',
    glacier: 'Ľadovec',
    grassland: 'Trávnatá vegetácia',
    gully: 'Roklina',
    heath: 'Step',
    hot_spring: 'Termálny prameň',
    landslide: 'Zosuv pôdy',
    mountain_range: 'Pohorie',
    mud: 'Blato',
    peak: 'Vrchol',
    plateau: 'Planina',
    ridge: 'Hrebeň',
    rock: 'Skala',
    saddle: 'Sedlo',
    sand: 'Piesok',
    scree: 'Suťovisko',
    scrub: 'Kríky',
    shingle: 'Štrk (vodný)',
    shrub: 'Krík',
    sinkhole: 'Závrt',
    spring: {
      '*': 'Prameň',
      drinking_water: {
        yes: 'Pitný prameň',
        no: 'Nepitný prameň',
      },
      refitted: {
        yes: 'Upravený prameň',
        no: 'Neupravený prameň',
      },
      intermittent: {
        yes: 'Občasný prameň',
      },
      seasonal: {
        yes: 'Sezónny prameň',
      },
      water_characteristic: {
        '*': 'Minerálny prameň',
      },
    },
    stone: 'Balvan',
    tree: {
      '*': 'Strom',
      protected: { yes: 'Chránený strom' },
      denotation: {
        natural_monument: 'Monumentálny strom',
        landmark: 'Prominentný strom',
        avenue: 'Strom v aleji',
        urban: 'Mestský strom',
        agricultural: 'Hospodársky strom',
      },
    },
    tree_row: 'Stromoradie / vetrolam',
    valley: 'Dolina',
    water: 'Vodná plocha',
    wetland: {
      '*': 'Mokraď',
      wetland: {
        bog: 'Rašelinisko',
        reedbed: 'Rákosina',
        marsh: 'Močiar',
        swamp: 'Bažina',
        wet_meadow: 'Vlhká lúka',
        mangrove: 'Mangrovy',
        fen: 'Slatinisko',
      },
    },
    wood: 'Les',
  },
  place: {
    '*': 'Miesto {}',
    city: 'Veľkomesto',
    country: 'Krajina',
    farm: 'Farma',
    hamlet: 'Osada',
    island: 'Ostrov',
    islet: 'Ostrovček',
    isolated_dwelling: 'Samota',
    locality: 'Lokalita',
    ocean: 'Oceán',
    sea: 'More',
    square: 'Námestie',
    state: 'Štát',
    suburb: 'Predmestie',
    town: 'Mesto',
    village: 'Dedina',
  },
  power: {
    '*': '{}',
    generator: {
      '*': 'Generátor elektrickej energie',
      'generator:source': {
        nuclear: {
          '*': 'Generátor elektrickej energie z jadrovej energie',
          'generator:method': {
            fission: 'Generátor elektrickej energie zo štiepenia jadra',
            fusion: 'Generátor elektrickej energie z jadrovej fúzie',
          },
        },
        wind: {
          '*': 'Generátor elektrickej energie z veternej energie',
        },
        hydro: {
          '*': 'Generátor elektrickej energie z vodnej energie',
          'generator:method': {
            'water-storage':
              'Generátor elektrickej energie z akumulovanej vodnej energie',
            'water-pumped-storage':
              'Generátor elektrickej energie z prečerpávanej vodnej energie',
            'run-of-the-river':
              'Generátor elektrickej energie z prietokovej vodnej energie',
          },
        },
        tidal: {
          '*': 'Generátor elektrickej energie z prílivovej energie',
          'generator:method': {
            barrage: 'Generátor elektrickej energie z prílivovej hrádze',
            stream: 'Generátor elektrickej energie z prílivového prúdu',
          },
        },
        wave: {
          '*': 'Generátor elektrickej energie z energie morských vĺn',
        },
        geothermal: {
          '*': 'Generátor elektrickej energie z geotermálnej',
        },
        solar: {
          '*': 'Generátor elektrickej energie zo slnečného žiarenia',
          'generator:method': {
            thermal:
              'Generátor elektrickej energie zo slnečného žiarenia - termálne',
            photovoltaic:
              'Generátor elektrickej energie zo slnečného žiarenia - fotovolticky',
          },
        },
        coal: {
          '*': 'Generátor elektrickej energie zo spaľovania uhlia',
        },
        gas: {
          '*': 'Generátor elektrickej energie zo spaľovania plynu',
        },
        biomass: {
          '*': 'Generátor elektrickej energie z biomasy',
          'generator:method': {
            combustion: 'Generátor elektrickej energie zo spaľovania biomasy',
            gasification:
              'Generátor elektrickej energie zo splyňovania biomasy',
            anaerobic_digestion:
              'Generátor elektrickej energie z anaeróbneho rozkladu biomasy',
          },
        },
        biofuel: {
          '*': 'Generátor elektrickej energie z biopaliva',
        },
        biogas: {
          '*': 'Generátor elektrickej energie z bioplynu',
        },
        oil: {
          '*': 'Generátor elektrickej energie zo spaľovania ropy',
        },
        diesel: {
          '*': 'Generátor elektrickej energie zo spaľovania nafty',
        },
        gasoline: {
          '*': 'Generátor elektrickej energie zo spaľovania benzínu',
        },
        waste: {
          '*': 'Generátor elektrickej energie zo spaľovania odpadu',
          'generator:method': {
            combustion: 'Generátor elektrickej energie zo spaľovania odpadu',
            gasification: 'Generátor elektrickej energie zo splyňovania odpadu',
          },
        },
      },
    },
    line: 'Elektrické vedenie',
    minor_line: 'Malé elektrické vedenie',
    plant: {
      '*': 'Elektráreň',
      'plant:source': {
        nuclear: {
          '*': 'Jadrová elektráreň',
          'plant:method': {
            fission: 'Elektráreň so štiepením jadra',
            fusion: 'Elektráreň s jadrovou fúziou',
          },
        },
        wind: {
          '*': 'Veterná elektráreň',
        },
        hydro: {
          '*': 'Vodná elektráreň',
          'plant:method': {
            'water-storage': 'Priehradná vodná elektráreň',
            'water-pumped-storage': 'Prečerpávacia vodná elektráreň',
            'run-of-the-river': 'Prietoková vodná elektráreň',
          },
        },
        tidal: {
          '*': 'Prílivová elektráreň',
          'plant:method': {
            barrage: 'Prílivová elektráreň s hrádzou',
            stream: 'Prílivová elektráreň z prúdu',
          },
        },
        wave: {
          '*': 'Vlnová elektráreň',
        },
        geothermal: {
          '*': 'Geotermálna elektráreň',
        },
        solar: {
          '*': 'Solárna elektráreň',
          'plant:method': {
            thermal: 'Solárna termálna elektráreň',
            photovoltaic: 'Fotovoltická elektráreň',
          },
        },
        coal: {
          '*': 'Uhoľná elektráreň',
        },
        gas: {
          '*': 'Plynová elektráreň',
        },
        biomass: {
          '*': 'Elektráreň na biomasu',
          'plant:method': {
            combustion: 'Elektráreň so spaľovaním biomasy',
            gasification: 'Elektráreň so splyňovaním biomasy',
            anaerobic_digestion: 'Elektráreň s anaeróbnym rozkladom biomasy',
          },
        },
        biofuel: {
          '*': 'Elektráreň na biopalivo',
        },
        biogas: {
          '*': 'Bioplynová elektráreň',
        },
        oil: {
          '*': 'Elektráreň na ropu',
        },
        diesel: {
          '*': 'Naftová elektráreň',
        },
        gasoline: {
          '*': 'Benzínová elektráreň',
        },
        waste: {
          '*': 'Spaľovňa odpadu s výrobou elektriny',
          'plant:method': {
            combustion: 'Elektráreň so spaľovaním odpadu',
            gasification: 'Elektráreň so splyňovaním odpadu',
          },
        },
      },
    },
    pole: 'Elektrický stĺp',
    substation: 'Elektrická distribučná stanica',
    tower: 'Veža vysokého napätia',
    transformer: 'Transformátor',
  },
  public_transport: {
    platform: 'Nástupište verejnej dopravy',
    station: 'Stanica',
    stop_position: 'Zastávka',
  },
  railway: {
    '*': 'Železnica',
    abandoned: 'Zrušená železnica',
    buffer_stop: 'Železničné zarážadlo',
    construction: 'Železnica vo výstavbe',
    crossing: 'Križovanie železničných tratí',
    derail: 'Výkoľajka',
    disused: 'Nepoužívaná železnica',
    funicular: 'Lanová železnica',
    halt: 'Železničná zastávka',
    level_crossing: 'Úrovňové železničné priecestie',
    light_rail: 'Ľahká železnica',
    miniature: 'Miniatúrna železnica',
    monorail: 'Jednokoľajová dráha',
    narrow_gauge: 'Úzkorozchodná železnica',
    platform: 'Železničné nástupište',
    preserved: 'Historická železnica',
    proposed: 'Navrhovaná železnica',
    rail: 'Železničná trať',
    railway_crossing: 'Železničné priecestie',
    roundhouse: 'Kruhové rušňové depo',
    signal: 'Železničné návestidlo',
    station: 'Železničná stanica',
    stop: 'Železničná zastávka',
    subway: 'Trať metra',
    subway_entrance: 'Vstup do metra',
    switch: 'Železničná výhybka',
    tram: 'Električková trať',
    tram_stop: 'Električková zastávka',
    traverser: 'Železničná presuvňa',
    turntable: 'Železničná točňa',
    ventilation_shaft: 'Vetracia šachta železnice',
    wash: 'Umývacia koľaj',
    water_crane: 'Železničný vodný žeriav',
    workshop: 'Železničná dielňa',
  },

  shop: {
    '*': 'Obchod {}',
    household_linen: 'Domáca bielizeň',
    charity: 'Obchod s Dobročinnosťou',
    chocolate: 'Čokoládovňa',
    fashion_accessories: 'Obchod s módnymi doplnkami',
    frozen_food: 'Obchod s mrazenými potravinami',
    hearing_aids: 'Obchod so slúchadlami',
    weapons: 'Obchod so zbraňami',
    alcohol: 'Obchod s alkoholom',
    antiques: 'Starožitnosti',
    art: 'Obchod s umením',
    baby_goods: 'Detské potreby',
    bag: 'Predaj kabeliek',
    bakery: 'Pekáreň',
    bathroom_furnishing: 'Kúpeľňové štúdio',
    beauty: 'Kozmetický salón',
    bed: 'Predaj postelí a matracov',
    beverages: 'Obchod s nápojmi',
    bicycle: 'Predaj bicyklov',
    bookmaker: 'Stávková kancelária',
    books: 'Kníhkupectvo',
    boutique: 'Butik',
    butcher: 'Mäsiarstvo',
    camera: 'Predaj fotoaparátov',
    car: 'Predaj áut',
    car_parts: 'Predaj autosúčiastok',
    car_repair: 'Autoservis',
    carpet: 'Predaj kobercov',
    cheese: 'Predaj syrov',
    chemist: 'Drogéria',
    clothes: 'Odevy',
    coffee: 'Predajňa kávy',
    collector: 'Obchod pre zberateľov',
    computer: 'Počítačový obchod',
    confectionery: 'Cukráreň',
    convenience: 'Potraviny',
    copyshop: 'Copy centrum',
    cosmetics: 'Obchod s kozmetikou',
    craft: 'Obchod s potrebami pre umelcov a remeselníkov',
    curtain: 'Predajňa záclon a závesov',
    dairy: 'Mliečne výrobky',
    deli: 'Lahôdky',
    department_store: 'Obchodný dom',
    doityourself: 'Urob si sám',
    doors: 'Predaj dverí',
    dry_cleaning: 'Čistiareň',
    'e-cigarette': 'E-cigarety',
    electrical: 'Elektroinštalačný materiál',
    electronics: 'Elektro',
    erotic: 'Sexshop',
    fabric: 'Metrový textil',
    farm: 'Farmárske výrobky',
    fireplace: 'Predaj krbov',
    fishing: 'Rybárske potreby',
    flooring: 'Predaj podláh',
    florist: 'Kvetinárstvo',
    funeral_directors: 'Pohrebná služba',
    furniture: 'Nábytok',
    games: 'Stolové hry',
    garden_center: 'Záhradné centrum',
    garden_centre: 'Záhradné centrum',
    general: 'Zmiešaný tovar',
    gift: 'Suveníry a darčeky',
    glaziery: 'Sklenár',
    greengrocer: 'Ovocie a zelenina',
    hairdresser: 'Kaderníctvo, holičstvo',
    hardware: 'Železiarstvo',
    health_food: 'Predaj zdravého jedla',
    hifi: 'Obchod s Hi-fi',
    houseware: 'Domáce potreby',
    hunting: 'Lovecké potreby',
    ice_cream: 'Zmrzlina',
    interior_decoration: 'Interiérové dekorácie',
    jewelry: 'Klenotníctvo',
    kiosk: 'Stánok',
    kitchen: 'Kuchynské štúdio',
    laundry: 'Práčovňa',
    lighting: 'Svietidlá',
    locksmith: 'Zámočník',
    lottery: 'Lotéria',
    mall: 'Nákupné stredisko',
    massage: 'Masážny salón',
    medical_supply: 'Zdravotnícke potreby',
    mobile_phone: 'Predaj mobilných telefónov',
    model: 'Modelárstvo',
    motorcycle: 'Predaj motocyklov',
    music: 'Predaj hudobných nosičov',
    musical_instrument: 'Hudobniny',
    newsagent: 'Noviny a časopisy',
    nutrition_supplements: 'Výživové doplnky',
    optician: 'Optika',
    outdoor: 'Predaj outdoor vybavenia',
    outpost: 'Zásielkovňa',
    paint: 'Farby-laky',
    pastry: 'Obchod so sladkým pečivom',
    pawnbroker: 'Záložňa',
    perfumery: 'Parfuméria',
    pet: 'Potreby pre zvieratá',
    pet_grooming: 'Salón pre zvieracích miláčikov',
    photo: 'Fotografické služby',
    radiotechnics: 'Predaj elektronických súčiastok',
    rental: 'Požičovňa',
    seafood: 'Predaj morských plodov',
    second_hand: 'Second hand',
    sewing: 'Krajčírske potreby',
    shoes: 'Obuv',
    sports: 'Športové potreby',
    stationery: 'Papiernictvo',
    supermarket: 'Supermarket',
    tailor: 'Krajčír',
    tattoo: 'Tetovacie štúdio',
    tea: 'Čajovňa',
    ticket: 'Predaj lístkov',
    tobacco: 'Predaj tabakových výrobkov',
    toys: 'Hračkárstvo',
    trade: 'Stavebniny',
    travel_agency: 'Cestovná kancelária',
    tyres: 'Pneuservis',
    vacant: 'Prázdny obchod',
    variety_store: 'Rozličný tovar',
    video: 'Predaj DVD',
    video_games: 'Videohry',
    watches: 'Hodinár',
    wholesale: 'Veľkoobchod',
    window_blind: 'Predaj žalúzií',
    wine: 'Vinotéka',
  },
  sport: {
    '*': 'Šport {}',
    '8pin': 'Osemkolkový bowling',
    '10pin': 'Bowling',
    '9pin': 'Kužeľky',
    'five-a-side': 'Malý futbal (5 na 5)',
    'in-line_hockey': 'Inline hokej',
    'shot-put': 'Vrh guľou',
    aerobics: 'Aerobik',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'Americký futbal',
    american_handball: 'Americká hádzaná',
    archery: 'Lukostreľba',
    association_football: 'Futbal (asociačný futbal)',
    athletics: 'Atletika',
    australian_football: 'Austrálsky futbal',
    axe_throwing: 'Šport v hode sekerou',
    badminton: 'Bedminton',
    balle_pelote: 'Šport balle pelote',
    ballooning: 'Teplovzdušné balónovanie',
    bandy: 'Bandy',
    barre: 'Barre cvičenie',
    base: 'BASE jumping',
    baseball: 'Baseball',
    basketball: 'Basketbal',
    batting_cage: 'Tréningová klietka na baseball/softbal',
    beach_soccer: 'Plážový futbal',
    beach_tennis: 'Plážový tenis',
    beachhandball: 'Plážová hádzaná',
    beachtennis: 'Plážový tenis',
    beachvolleyball: 'Plážový volejbal',
    biathlon: 'Biatlon',
    bicycle: 'Cyklistika',
    billards: 'Biliard',
    billiards: 'Biliard',
    bmx: 'BMX',
    bobsleigh: 'Boby',
    bodybuilding: 'Kulturistika',
    boules: 'Petang',
    bowling: 'Bowling',
    bowls: 'Bowls',
    boxing: 'Box',
    bullfighting: 'Býčie zápasy',
    calisthenics: 'Kalistenika',
    canadian_football: 'Kanadský futbal',
    candlepin: 'Candlepin bowling',
    canoe_polo: 'Kanoe pólo',
    canoe: 'Kanoe',
    chess: 'Šach',
    chinlone: 'Šport chinlone',
    cliff_diving: 'Skoky do vody z útesov',
    climbing_adventure: 'Climbing adventure',
    climbing: 'Lezenie',
    cockfighting: 'Kohútie zápasy',
    cricket_nets: 'Kriketové siete',
    cricket: 'Kriket',
    croquet: 'Kroket',
    crossfit: 'CrossFit tréning',
    curling: 'Curling',
    cycle_ball: 'Cyklobal',
    cycle_polo: 'Cyklopólo',
    cycling: 'Cyklistika',
    dance: 'Tanečný šport',
    dancing: 'Tanečný šport',
    darts: 'Šípky (šport)',
    disc_golf: 'Disc golf',
    diving: 'Skoky do vody',
    dodgeball: 'Vybíjaná',
    dog_agility: 'Psí agility',
    dog_racing: 'Psie preteky',
    dragon_boat: 'Dračí čln (preteky)',
    equestrian: 'Jazdectvo',
    fencing: 'Šerm',
    field_hockey: 'Pozemný hokej',
    fistball: 'Fistbal',
    fitness: 'Posilňovňa',
    fives: 'Šport fives',
    floorball: 'Floorball',
    football: 'Futbal',
    footballgolf: 'Futbalgolf',
    four_square: 'Hra four square',
    free_flying: 'Závesné lietanie',
    freediving: 'Voľné potápanie',
    funnel_ball: 'Hra funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Galský futbal',
    gaelic_games: 'Gaelské hry',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Bezmotorové lietanie',
    golf: 'Golf',
    gymnastics: 'Gymnastika',
    handball: 'Hádzaná',
    hanggliding: 'Rogalo (závesné lietanie)',
    hapkido: 'Hapkido',
    high_rope_course: 'Lanový park',
    hiking: 'Turistika',
    hockey: 'Hokej',
    hopscotch: 'Skákanie škôlky',
    horse_racing: 'Dostihy',
    horse_riding: 'Jazda na koni',
    horseshoes: 'Podkovy',
    ice_hockey: 'Ľadový hokej',
    ice_skating: 'Korčuľovanie na ľade',
    ice_stock: 'Ľadový metlobal (Eisstock)',
    jetsprint: 'Preteky rýchlostných člnov (jet sprint)',
    judo: 'Džudo',
    karate: 'Karate',
    karting: 'Motokáry',
    kick_scooter: 'Jazda na kolobežke (šport)',
    kickball: 'Kickball',
    kickboxing: 'Kickbox',
    kitesurfing: 'Kitesurfing',
    korfball: 'Korfball',
    krachtbal: 'Šport krachtbal',
    krolf: 'Šport krolf',
    lacrosse: 'Lakros',
    laser_tag: 'Laser aréna',
    long_jump: 'Skok do diaľky',
    martial_arts: 'Bojové umenia',
    mind_body_interventions: 'Cvičenia telo–myseľ (napr. joga)',
    miniature_golf: 'Minigolf',
    model_aerodrome: 'Modelárske letisko',
    motocross: 'Motokros',
    motor: 'Preteky motorových vozidiel',
    mtb: 'Horská cyklistika',
    multi: 'Rôzne športy',
    netball: 'Nohejbal',
    nine_mens_morris: 'Hra mlyn (Nine men’s morris)',
    obstacle_course: 'Prekážkový beh',
    orienteering: 'Orientačný beh',
    paddle_tennis: 'Paddle tenis',
    paddleball: 'Paddleball',
    paddleboard: 'Stand-up paddleboarding',
    padel: 'Padel tenis',
    paintball: 'Paintball',
    parachuting: 'Parašutizmus',
    paragliding: 'Paragliding',
    parkour: 'Parkour',
    pedal_car_racing: 'Preteky šliapacích áut',
    pelota: 'Pelota',
    pesäpallo: 'Pesäpallo (fínsky baseball)',
    petanque: 'Petang (zlé tagovanie)',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole dance (šport)',
    polo: 'Pólo',
    powerlifting: 'Silový trojboj',
    racquet: 'Raketa',
    rc_car: 'RC autá',
    rodeo: 'Rodeo',
    roller_hockey: 'Kolieskový hokej',
    roller_skating: 'Kolieskové korčuľovanie',
    rowing: 'Veslovanie',
    rugby_league: 'Ragby liga',
    rugby_union: 'Ragby únia',
    rugby: 'Ragby',
    running: 'Beh',
    russian_skittles: 'Ruské kolky',
    safety_training: 'Športové bezpečnostné tréningy',
    sailing: 'Plachtenie',
    scuba_diving: 'Potápanie',
    shooting_range: 'Strelnica',
    shooting: 'Streľba',
    shuffleboard: 'Shuffleboard',
    skateboard: 'Skateboard',
    skating: 'Korčuľovanie',
    ski_jumping: 'Skoky na lyžiach',
    skiing: 'Lyžovanie',
    snooker: 'Snooker',
    snorkeling: 'Šnorchlovanie',
    soccer: 'Futbal',
    softball: 'Softbal',
    speedway: 'Plochá dráha (motocyklový šport)',
    squash: 'Squash',
    streetball: 'Streetball',
    summer_toboggan: 'Letná bobová dráha',
    sumo: 'Sumo',
    surfing: 'Surfovanie',
    swimming: 'Plávanie',
    table_soccer: 'Stolný futbal',
    table_tennis: 'Stolný tenis',
    taekwondo: 'Taekwondo',
    tamburello: 'Šport tamburello',
    team_handball: 'Hádzaná',
    tennis: 'Tenis',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    toboggan: 'Tobogan',
    touch_football: 'Bezkontaktný futbal (touch football)',
    trampoline: 'Skákanie na trampolíne',
    trugo: 'Šport trugo',
    tug_of_war: 'Preťahovanie lanom',
    ultimate: 'Ultimate frisbee',
    ultralight_aviation: 'Športové ultralight lietanie',
    volleyball: 'Volejbal',
    wakeboarding: 'Wakeboarding',
    walking: 'Športová chôdza',
    water_polo: 'Vodné pólo',
    water_ski: 'Vodné lyžovanie',
    water_sports: 'Vodné športy',
    weightlifting: 'Vzpieranie',
    windsurfing: 'Windsurfing',
    workout: 'Cvičenie',
    wrestling: 'Zápasenie',
    yoga: 'Joga',
    zurkhaneh_sport: 'Zurkhaneh (iránsky tradičný šport)',
  },
  tourism: {
    '*': '{}',
    alpine_hut: 'Horská chata',
    apartment: 'Apartmán',
    aquarium: 'Akvárium',
    artwork: {
      '*': 'Umenie',
      artwork_type: {
        architecture: 'Významná budova, stavba',
        bust: 'Busta',
        graffiti: 'Graffiti',
        installation: 'Umelecká inštalácia',
        mosaic: 'Mozaika (umenie)',
        mural: 'Nástenná maľba',
        painting: 'Maľba',
        relief: 'Reliéf (umenie)',
        sculpture: 'Plastika',
        statue: 'Socha',
        stone: 'Balvan (umenie)',
      },
    },
    attraction: 'Atrakcia',
    camp_site: 'Kemp',
    caravan_site: 'Autokemp pre obytné prívesy',
    chalet: 'Chata',
    gallery: 'Galéria',
    guest_house: 'Penzión',
    hostel: 'Hostel',
    hotel: 'Hotel',
    information: {
      '*': 'Informácie',
      information: {
        '*': 'Informácie {}',
        board: 'Informačná tabuľa',
        guidepost: 'Rázcestník, smerovník',
        map: 'Mapa',
        office: 'Turistická informačná kancelária',
        route_marker: 'Označenie trasy',
      },
    },
    motel: 'Motel',
    museum: 'Múzeum',
    picnic_site: 'Miesto na piknik',
    theme_park: 'Tématický park',
    viewpoint: 'Výhľad',
    wilderness_hut: 'Chata v divočine',
    zoo: 'ZOO',
  },
  type: {
    route: {
      '*': 'Trasa',
      route: {
        '*': 'Trasa {}',
        bicycle: 'Cyklotrasa',
        bus: 'Trasa autobusu',
        foot: 'Pešia trasa',
        hiking: {
          '*': 'Turistická trasa',
          network: {
            lwn: 'Miestna turistická trasa',
            rwn: 'Regionálna turistická trasa',
            nwn: 'Národná turistická trasa',
            iwn: 'Medzinárodná turistická trasa',
          },
        },
        horse: 'Jazdecká trasa',
        mtb: 'Trasa pre horské bicykle',
        piste: 'Bežkárska trasa',
        railway: 'Železničná trasa',
        ski: 'Lyžiarska trasa',
        tram: 'Električková trasa',
      },
    },
  },
  seasonal: {
    yes: {
      waterway: 'Sezónny vodný tok',
      natural: {
        water: 'Sezónny vodná plocha',
      },
    },
  },
  intermittent: {
    yes: {
      waterway: 'Občasný vodný tok',
      natural: {
        water: 'Občasná vodná plocha',
      },
    },
  },
  waterway: {
    '*': 'Vodný tok {}',
    canal: 'Kanál',
    canoe_pass: 'Priechod pre kanoe',
    dam: 'Priehrada',
    ditch: 'Priekopa',
    drain: 'Odtok',
    fairway: 'Plavebná dráha (fairway)',
    fish_pass: 'Rybí prechod',
    flowline: 'Prúdová línia',
    pressurised: 'Tlakové vodné potrubie',
    link: 'Vodný spoj',
    rapids: 'Pereje',
    river: 'Rieka',
    stream: 'Potok',
    tidal_channel: 'Prílivový kanál',
    waterfall: 'Vodopád',
    weir: 'Hrádza',
  },
  trail_visibility: {
    excellent: 'Excelentná viditeľnosť trasy',
    good: 'Dobrá viditeľnosť trasy',
    intermediate: 'Stredná viditeľnosť trasy',
    bad: 'Zlá viditeľnosť trasy',
    horrible: 'Hrozná viditeľnosť trasy',
    no: 'Žiadna viditeľnosť trasy',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Červená',
  blue: 'Modrá',
  green: 'Zelená',
  yellow: 'Žltá',
  orange: 'Oranžová',
  purple: 'Purpurová',
  violet: 'Fialová',
  white: 'Biela',
  black: 'Čierna',
  gray: 'Sivá',
  brown: 'Hnedá',
};
