import { DeepPartial } from '../deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  aeroway: {
    aerodrome: 'Letiště',
    airstrip: 'Vzletová a přistávací dráha',
    apron: 'Odstavná plocha letadel',
    gate: 'Nástupní letištní brána',
    hangar: 'Hangár pro letadla',
    helipad: 'Heliport (plocha pro vrtulníky)',
    holding_position: 'Vyčkávací místo letadel',
    jet_bridge: 'Nástupní most / tunel do letadla',
    navigationaid: 'Letecké navigační zařízení',
    parking_position: 'Stání letadla',
    runway: 'Vzletová a přistávací dráha',
    stopway: 'Bezpečnostní plocha za dráhou',
    taxilane: 'Pojížděcí dráha na odbavovací ploše',
    taxiway: 'Pojížděcí dráha',
    terminal: 'Letištní terminál',
    threshold: 'Prahový bod dráhy',
    tower: 'Řídicí věž letového provozu',
    windsock: 'Větrný rukáv',
  },

  aerialway: {
    '*': 'Lanovka, vlek',
    cable_car: 'Kabinková lanovka',
    chair_lift: 'Sedačková lanovka',
    goods: 'Nákladní lanovka',
    'j-bar': 'J-kotva',
    magic_carpet: 'Pohyblivý pás',
    mixed_lift: 'Kombinovaná lanovka',
    platter: 'Talířový vlek',
    pylon: 'Podpěra lanovky',
    rope_tow: 'Lanový vlek',
    station: 'Stanice lanovky',
    't-bar': 'T-kotva',
    zip_line: 'Zipline',
  },

  amenity: {
    '*': '{}',
    animal_breeding: 'Chov zvířat',
    animal_shelter: 'Přístřešek pro zvířata',
    arts_centre: 'Centrum umění',
    bank: 'Banka',
    bar: 'Bar',
    bbq: 'Gril',
    bench: 'Lavička',
    bicycle_parking: 'Parkoviště pro kola',
    bicycle_rental: 'Půjčovna kol',
    bicycle_repair_station: 'Stojan na opravu kol',
    biergarten: 'Pivní zahrádka',
    brothel: 'Bordel',
    bureau_de_change: 'Směnárna',
    bus_station: 'Autobusové nádraží',
    cafe: 'Kavárna',
    car_rental: 'Půjčovna aut',
    car_wash: 'Automyčka',
    casino: 'Kasino',
    charging_station: 'Nabíjecí stanice',
    childcare: 'Péče o děti',
    cinema: 'Kino',
    clinic: 'Poliklinika',
    clock: 'Hodiny',
    college: 'Dodatečné vzdělávání',
    community_centre: 'Komunitní centrum',
    compressed_air: 'Kompresor (na pneumatiky)',
    courthouse: 'Soud',
    dentist: 'Zubní ordinace',
    device_charging_station: 'Nabíjecí stanice elektrovozidel',
    doctors: 'Lékařská ordinace',
    dressing_room: 'Šatna',
    drinking_water: 'Pitná voda',
    driving_school: 'Autoškola',
    embassy: 'Ambasáda',
    events_venue: 'Místo konání akcí',
    fast_food: 'Rychlé občerstvení',
    feeding_place: 'Krmelec',
    ferry_terminal: 'Terminál trajektu',
    fire_station: 'Hasičská stanice',
    food_court: 'Food court',
    fountain: 'Fontána',
    fuel: 'Čerpací stanice',
    funeral_hall: 'Pohřební síň',
    gambling: 'Herna',
    game_feeding: 'Krmelec',
    grave_yard: 'Pohřebiště',
    grit_bin: 'Nádoba s posypem',
    hospital: 'Nemocnice',
    hunting_stand: 'Myslivecký posed',
    ice_cream: 'Zmrzlina',
    kindergarten: 'Školka',
    language_school: 'Jazyková škola',
    library: 'Knihovna',
    marketplace: 'Trhovisko',
    monastery: 'Klášter',
    money_transfer: 'Převod peněz',
    motorcycle_parking: 'Parkování motocyklů',
    motorcycle_rental: 'Půjčovna motocyklů',
    nightclub: 'Noční klub',
    parcel_locker: 'Box na výdej zásilek',
    parking_entrance: 'Vjezd/výjezd parkoviště',
    parking_space: 'Parkovací místo',
    parking: 'Parkování',
    pharmacy: 'Lékárna',
    place_of_mourning: 'Dům smutku',
    place_of_worship: 'Miesto náboženských obradov',
    planetarium: 'Planetárium',
    police: 'Policie',
    post_box: 'Poštovní schránka',
    post_office: 'Pošta',
    prison: 'Věznice',
    pub: 'Hospoda',
    public_bookcase: 'Knižní budka',
    ranger_station: 'Strážcovská stanice',
    atm: 'Bankomat',
    recycling: 'Recyklování',
    restaurant: 'Restaurace',
    school: 'Škola',
    shelter: {
      '*': 'Přístřešek',
      shelter_type: {
        '*': 'Přístřešek {}',
        basic_hut: 'Jednoduchá chata, bivak, útulna',
        changing_rooms: 'Převlékárna',
        field_shelter: 'Polní přístřešek',
        lean_to: 'Přístřešek s otevřenou stěnou',
        picnic_shelter: {
          '*': 'Piknikový přístřešek',
          fireplace: { yes: 'Piknikový přístřešek s krbem' },
        },
        public_transport: 'Přístřešek veřejné dopravy',
        rock_shelter: 'Skalní úkryt',
        sun_shelter: 'Přístřešek proti slunci',
        weather_shelter: 'Přístřešek proti nepříznivému počasí',
      },
    },
    shower: 'Sprcha',
    ski_rental: 'Půjčovna lyží',
    smoking_area: 'Kuřácká zóna',
    social_centre: 'Sociální centrum',
    social_facility: {
      '*': 'Sociální zařízení',
      social_facility: {
        ambulatory_care: 'Zařízení ambulantní péče',
        assisted_living: 'Zařízení pro život s asistencí',
        clothing_bank: 'Odevná banka',
        day_care: 'Zariadenie dennej starostlivosti',
        food_bank: 'Potravinová banka',
        group_home: 'Skupinové bývanie',
        hospice: 'Hospic',
        nursing_home: 'Dom s opatrovateľskou službou',
        shelter: 'Nocľaháreň',
        soup_kitchen: 'Vývarovňa',
        workshop: 'Chránená dielňa',
      },
    },
    stripclub: 'Striptýzový bar',
    studio: 'Studio / ateliér',
    taxi: 'Taxi',
    telephone: 'Telefon',
    theatre: 'Divadlo',
    toilets: 'WC',
    townhall: 'Radnice, obecní úřad',
    traffic_park: 'Dopravní hřiště',
    trolley_bay: 'Prostor pro vozíky',
    university: 'Univerzita',
    vacuum_cleaner: 'Vysavač',
    vehicle_inspection: 'Kontrola vozidel',
    vending_machine: {
      '*': 'Automat',
      vending: {
        bicycle_tube: 'Automat na cyklistické duše',
        bread: 'Automat na chléb',
        bottle_return: 'Automat na vracení lahví',
        candles: 'Automat na svíčky',
        chewing_gums: 'Automat na žvýkačky',
        cigarettes: 'Automat na cigarety',
        coffee: 'Automat na kávu',
        condoms: 'Automat na kondomy',
        drinks: 'Automat na nápoje',
        elongated_coin: 'Automat na pamětní mince',
        eggs: 'Automat na vejce',
        excrement_bags: 'Automat na sáčky na exkrementy',
        food: 'Automat na jídlo',
        fuel: 'Automat na palivo',
        gas: 'Automat na palivo',
        ice_cream: 'Automat na zmrzlinu',
        ice_cubes: 'Automat na kostky ledu',
        milk: 'Automat na mléko',
        movies: 'Automat na filmy',
        newspapers: 'Automat na noviny',
        parking_tickets: 'Parkovací automat',
        pizza: 'Automat na pizzu',
        public_transport_tickets: 'Automat na jízdenky veřejné dopravy',
        stamps: 'Automat na známky',
        sweets: 'Automat na sladkosti',
        water: 'Automat na vodu',
      },
    },
    veterinary: 'Veterinář',
    waste_basket: 'Odpadkový koš',
    waste_disposal: 'Odpadkový koš',
    water_point: 'Odběr pitné vody',
    watering_place: 'Napajedlo',
  },

  barrier: {
    '*': 'Bariéra {}',
    block: 'Blok',
    bollard: 'Sloupek',
    border_control: 'Hraniční kontrola',
    chain: 'Řetěz',
    ditch: 'Příkop',
    entrance: 'Vstup',
    fence: 'Plot',
    gate: 'Brána',
    hedge: 'Živý plot',
    kerb: 'Obrubník',
    lift_gate: 'Závora',
    rope: 'Lano',
    sliding_gate: 'Posuvná brána',
    swing_gate: 'Otoční závora',
    turnstile: 'Turniket',
    wall: 'Zeď',
    cable_barrier: 'Kabelové svodidlo',
    city_wall: 'Hradba',
    guard_rail: 'Svodidla',
    handrail: 'Zábradlí',
    retaining_wall: 'Opěrná zeď',
  },

  boundary: {
    '*': 'Oblast',
    administrative: {
      '*': 'Administrativní oblast',
      admin_level: {
        '2': 'Stát',
        '3': 'Region',
        '4': 'Kraj',
        '5': 'Provincie',
        '6': 'Město',
        '7': 'Oblast',
        '8': 'Okres',
        '9': 'Obec',
        '10': 'Katastrální území',
      },
    },
    marker: 'Hraniční kámen',
    national_park: 'Národní park',
    protected_area: 'Chráněná oblast',
  },

  building: {
    '*': {
      '*': 'Budova {}',

      abandoned: {
        yes: 'Trvale opuštěná budova',
      },

      disused: {
        yes: 'Nepoužívaná budova',
      },

      ruins: {
        yes: 'Ruina budovy',
      },
    },

    apartments: 'Apartmány (blok)',
    barn: 'Stodola',
    bungalow: 'Bungalov',
    bunker: 'Bunkr',
    cabin: 'Bouda, chatka',
    cathedral: 'Katedrála',
    chapel: 'Kaplička',
    church: 'Kostel',
    civic: 'Veřejná budova',
    collapsed: 'Zřícená budova',
    commercial: 'Budova určená pro komerční účely',
    construction: 'Výstavba budovy',
    cowshed: 'Kravín',
    detached: 'Samostatně stojící rodinný dům',
    dormitory: 'Internát',
    entrance: 'Vstup do budovy',
    farm_auxiliary: 'Pomocná budova farmy',
    farm: 'Statek',
    garage: 'Garáž',
    garages: 'Garáže',
    government: 'Vládní budova',
    grandstand: 'Tribuna',
    greenhouse: 'Skleník',
    hangar: 'Hangár',
    hayloft: 'Seník',
    hospital: 'Budova nemocnice',
    hotel: 'Hotel',
    house: 'Rodinný dům',
    houseboat: 'Hausbót',
    hut: 'Chatrč',
    industrial: 'Budova určená pro průmyslové účely',
    kindergarten: 'Budova mateřské školy',
    kiosk: 'Kiosek',
    manufacture: 'Manufacture budova',
    mosque: 'Mešita',
    office: 'Kancelářská budova',
    parking: 'Budova parkování',
    public: 'Veřejná budova',
    residential: 'Obytný dům',
    retail: 'Budova prodejny',
    roof: 'Střecha',
    ruins: 'Ruiny budovy',
    school: 'Budova školy',
    semidetached_house: 'Dvojdům',
    service: 'Servisní budova',
    shed: 'Kůlna',
    shrine: 'Svatyně',
    stable: 'Stáj',
    static_caravan: 'Obytný přívěs, karavan',
    storage_tank: 'Cisterna',
    sty: 'Chlívek',
    supermarket: 'Supermarket budova',
    synagogue: 'Synagoga',
    temple: 'Chrám',
    terrace: 'Radový dům',
    train_station: 'Vlaková stanice',
    transformer_tower: 'Transformer tower',
    transportation: 'Budova přepravy',
    university: 'Budova univerzity',
    warehouse: 'Sklad',
    yes: 'Budova',
    abandoned: 'Trvale opuštěná budova',
    disused: 'Nepoužívaná budova',
    stadium: 'Budova stadionu',
  },

  highway: {
    '*': 'Cesta {}',
    bus_stop: 'Autobusová zastávka',
    construction: 'Cesta ve výstavbě',
    crossing: 'Přechod',
    cycleway: 'Cyklostezka',
    footway: 'Chodník',
    living_street: 'Rezidenční zóna',
    motorway: 'Dálnice',
    motorway_link: 'Napojení na dálnici',

    path: {
      '*': 'Pěšina',

      foot: {
        designated: {
          bicycle: {
            designated: 'Společná stezka pro pěší a cyklisty',
          },
        },
      },
    },

    primary: 'Cesta první třídy',
    primary_link: 'Napojení na cestu první třídy',
    residential: 'Ulice',
    secondary: 'Cesta druhé třídy',
    secondaty_link: 'Napojení na cestu druhé třídy',

    service: {
      '*': 'Servisní, příjezdová cesta',
      service: {
        '*': 'Servisní cesta {}',
        alley: 'Příjezdová cesta',
        bus: 'Cesta vyhražená pro autobusy',
        'drive-through': 'Cesta pro nákup z auta',
        driveway: 'Příjezdová cesta',
        emergency_access: 'Požární cesta',
        parking_aisle: 'Cesta parkoviště',
      },
    },

    steps: 'Schody',
    tertiary: 'Cesta třetí třídy',
    tertiary_link: 'Napojení na cestu třetí třídy',

    track: {
      '*': 'Lesní / polní cesta',
      tracktype: {
        grade1: 'Zpevněná lesní / polní cesta',
        grade2: 'Převážně zpevněná lesní / polní cesta',
        grade3: 'Méňe pevná lesní / polní cesta',
        grade4: 'Převážně měkká lesní / polní cesta',
        grade5: 'Měkká lesní / polní cesta',
      },
    },

    trunk: 'Silnice pro motorová vozidla',
    trunk_link: 'Napojení na cestu pro motorová vozidla',
    unclassified: 'Neklasifikovaná cesta',
    pedestrian: 'Pěší zóna',
    street_lamp: 'Pouliční lampa',
    bridleway: 'Jezdecká stezka',
    piste: 'Lyžařská trať',
    platform: 'Nástupiště',
    raceway: 'Závodní dráha',
    road: 'Cesta neznámého typu',
    via_ferrata: 'Via ferrata',
  },

  historic: {
    '*': 'Historický objekt',
    archaeological_site: 'Archeologické naleziště',
    castle: 'Hrad',
    church: 'Historický kostel',
    city_gate: 'Městská brána',
    manor: 'Panství',
    memorial: 'Pmátník',
    monastery: 'Klášter',
    monument: 'Pomník, monument',

    ruins: {
      '*': 'Ruiny',
      ruins: {
        castle: 'Zřícenina hradu',
      },
    },

    tomb: 'Hrobka',
    wayside_cross: 'Křížek u cesty',
    wayside_shrine: 'Boží muka',
    aircraft: 'Historické letadlo',
    boundary_stone: 'Historický hraniční kámen',
    building: 'Historická budova',
    cannon: 'Historické dělo',
    charcoal_pile: 'Místo po milíři',
    citywalls: 'Městské hradby',
    fort: 'Pevnost',
    heritage: 'Památkové místo',
    hollow_way: 'Úvozová cesta',
    house: 'Historický dům',
    milestone: 'Historický milník',
    mine: 'Historický důl',
    mine_shaft: 'Historická důlní šachta',
    shieling: 'Salaš (sezónní horská chata)',
    stone: 'Historický kámen',
    tree_shrine: 'Svatý obrázek na stromě',
    wreck: 'Vrak',
    yes: 'Historický objekt',
  },

  landuse: {
    '*': '{}',
    allotments: 'Zahrádkářská oblast',
    basin: 'Záchytná nádrž',
    brownfield: 'Brownfield (zanedbané území)',
    cemetery: 'Hřbitov',
    commercial: 'Komerční zóna',
    construction: 'Staveniště',
    education: 'Školní zóna',
    farmland: 'Pole',
    farmyard: 'Družstvo',
    forest: 'Les',
    garages: 'Garáže',
    grass: 'Tráva',
    greenfield: 'Greenfield (nezastavěné území)',
    industrial: 'Industriální zóna',
    landfill: 'Skládka',
    meadow: 'Louka',
    military: 'Vojenský újezd',
    orchard: 'Sad',
    plant_nursery: 'Lesní školka',
    quarry: 'Lom',
    recreation_ground: 'Rekreační zóna',
    religions: 'Cirkevní pozemek',
    reservoir: 'Přehrada / vodní nádrž',
    residential: 'Rezidenční zóna',
    retail: 'Nákupní zóna',
    vineyard: 'Vinice',
    winter_sports: 'Zimní sporty',
    pedestrian: 'Plocha pro pěší',
    railway: 'Plocha železnice',
    village_green: 'Náves',
  },

  leisure: {
    '*': '{}',
    bleachers: 'Tribuny',
    escape_game: 'Úniková hra',
    hackerspace: 'Hackerspace',
    ice_rink: 'Klzisko',
    marina: 'súkromný prístav',
    miniature_golf: 'Minigolf',
    dog_park: 'Park pro psy',
    firepit: 'Ohniště',
    fishing: 'Místo pro rybolov',
    fitness_centre: 'Posilovna',
    fitness_station: 'Posilovací zařízení',
    garden: 'Zahrada',
    golf_course: 'Golfové hřiště',
    horse_riding: 'Jízda na koni',
    nature_reserve: 'Přírodní rezervace',
    park: 'Park',

    picnic_table: {
      '*': 'Piknikový stůl',
      covered: {
        yes: 'Krytý piknikový stůl',
        no: 'Nekrytý piknikový stůl',
      },
    },

    pitch: 'Sportovní hřiště',
    playground: 'Dětské hřiště',
    sports_centre: 'Sportovní centrum',
    sports_hall: 'Sportovní hala',
    stadium: 'Stadion',
    swimming_pool: 'Bazén',
    track: 'Cesta',
    water_park: 'Vodní park',
    adult_gaming_centre: 'Herna pro dospělé',
    amusement_arcade: 'Zábavní herna',
    bandstand: 'Hudební pavilon',
    bathing_place: 'Místo ke koupání',
    beach_resort: 'Plážový resort',
    bird_hide: 'Pozorovatelna ptáků',
    bowling_alley: 'Bowlingová dráha',
    dance: 'Taneční prostor',
    disc_golf_course: 'Hřiště na discgolf',
    high_ropes_course: 'Lanový park',
    outdoor_seating: 'Venkovní sezení',
    resort: 'Rekreační resort',

    sauna: {
      '*': 'Sauna',

      sauna: {
        aroma: 'Aromatická sauna',
        dry: 'Suchá sauna',
        hanjeungmak: 'Hanjeungmak (korejská sauna)',
        hot: 'Finská sauna',
        infrared: 'Infračervená sauna',
        smoke: 'Kouřová sauna (finská)',
        steam: 'Parní sauna (turecká lázeň)',
      },
    },

    slipway: 'Spouštěcí rampa pro lodě',
    summer_camp: 'Letní tábor',
    sunbathing: 'Prostor pro opalování',
    swimming_area: 'Plavecká oblast',
    tanning_salon: 'Solárium',
    trampoline_park: 'Trampolínový park',
    wildlife_hide: 'Pozorovatelna zvěře',
  },

  man_made: {
    '*': '{}',
    "forester's_lodge": 'Horárna',

    adit: {
      '*': 'Důlní štola',

      disused: {
        yes: 'Nepoužívaná důlní štola',
      },
    },

    antenna: 'Anténa',
    beacon: 'Maják',
    beehive: 'Včelí úl',
    bridge: 'Most',
    bunker_silo: 'Silo',
    cairn: 'Kamenný mužík',
    cellar_entrance: 'Sklepní vchod',
    chimney: 'Komín',
    clearcut: 'Roubaniště',
    communications_tower: 'Telekomunikační věž',
    cooling_tower: 'Chladicí věž',
    crane: 'Jeřáb',
    cross: 'Kříž',
    cutline: 'Průsek',
    dyke: 'Hráz',
    embankment: 'Násyp',
    flagpole: 'Vlajkový stožár',
    gasometer: 'Plynoměr',
    goods_conveyor: 'Dopravní pás',
    groyne: 'Krátká pobřežní hráz',
    lighthouse: 'Maják',
    manhole: 'Šachta',

    mast: {
      '*': 'Stožár',

      'tower:type': {
        clock: 'Stožár s hodinami',
        communication: 'Telekomunikační stožár',
        lighting: 'Osvětlovací stožár',
        monitoring: 'Monitorovací stožár',
        radar: 'Radarový stožár',
        siren: 'Stožár se sirénou',
      },
    },

    mineshaft: {
      '*': 'Důlní šachta',

      disused: {
        yes: 'Nepoužívaná důlní šachta',
      },
    },

    monitoring_station: 'Monitorovací stanice',
    nesting_site: 'Hnízdo',
    observatory: 'Observatorium',
    pier: 'Molo',

    pipeline: {
      '*': 'Potrubí',

      location: {
        underground: 'Podzemní potrubí',
        underwater: 'Podvodní potrubí',
      },
    },

    reservoir_covered: 'Krytý rezervoár',
    silo: 'Silo',
    snow_cannon: 'Sněžné dělo',
    spoil_heap: 'Halda',
    spring_box: 'Kryt pramene',
    storage_tank: 'Skladovací cisterna',
    street_cabinet: 'Pouliční skříň',
    surveillance: 'Bezpečnostní kamera',
    survey_point: 'Geodetický bod',
    telescope: 'Teleskop',

    tower: {
      '*': 'Věž',
      'tower:type': {
        bell_tower: 'Zvonice',
        communication: 'Telekomunikační věž',
        cooling: 'Chladírenská věž',
        observation: 'Rozhledna',
        climbing: 'Lezecká věž',
        clock: 'Hodinová věž',
        defensive: 'Obranná věž',
        diving: 'Skokanská věž',
        hose: 'Sušicí věž na hadice',
        lighting: 'Osvětlovací věž',
        minaret: 'Minaret',
        monitoring: 'Monitorovací věž',
        pagoda: 'Pagoda',
        radar: 'Radarová věž',
        siren: 'Věž se sirénou',
        watchtower: 'Strážní věž',
      },
    },

    utility_pole: 'Užitkový stožár',
    wastewater_plant: 'Čistička odpadních vod',
    water_tap: 'Vodovodní kohoutek',
    water_tower: 'Vodárenská věž',
    water_well: 'Studna',
    water_works: 'Vodohospodářský objekt',
    watermill: 'Vodní mlýn',
    windmill: 'Větrný mlýn',
    works: 'Fabrika',
    apiary: 'Včelnice',
    pumping_station: 'Přečerpávací stanice',
  },

  natural: {
    '*': '{}',
    arch: 'Skalní okno',
    bare_rock: 'Holá skála',
    basin: 'Kotlina',
    bay: 'Zátoka',
    beach: 'Pláž',
    birds_nest: 'Vtáčie hniezdo',
    cave_entrance: 'Jeskyně',
    cliff: 'Skála',
    earth_bank: 'Svah',
    fell: 'Bažina',
    geyser: 'Gejzir',
    glacier: 'Ľadovec',
    grassland: 'Travnatá vegetace',
    gully: 'Roklina',
    heath: 'Step',
    hot_spring: 'Termální pramen',
    landslide: 'Zosuv pôdy',
    mountain_range: 'Pohoří',
    mud: 'Bláto',
    peak: 'Vrchol',
    plateau: 'Planina',
    ridge: 'Hřeben',
    rock: 'Kámen',
    saddle: 'Sedlo',
    sand: 'Písek',
    scree: 'Suťoviště',
    scrub: 'Keře',
    shingle: 'Štrk (vodný)',
    shrub: 'Krík',
    sinkhole: 'Závrt',
    spring: {
      '*': 'Pramen',

      drinking_water: {
        yes: 'Pitný pramen',
        no: 'Nepitný pramen',
      },

      refitted: {
        yes: 'Upravený pramen',
        no: 'Neupravený pramen',
      },

      intermittent: {
        yes: 'Občasný pramen',
      },

      seasonal: {
        yes: 'Sezónní pramen',
      },

      water_characteristic: {
        '*': 'Minerální pramen',
      },
    },
    stone: 'Balvan',
    tree: {
      protected: {
        yes: 'Chráněný strom',
      },

      denotation: {
        natural_monument: 'Přírodní památka strom',
        landmark: 'Významný strom',
        avenue: 'Strom v aleji',
        urban: 'Městský strom',
        agricultural: 'Hospodářský strom',
      },

      '*': 'Strom',
    },

    tree_row: 'Stromořadí / větrolam',
    valley: 'Údolí',
    water: 'Vodní plocha',
    wetland: {
      '*': 'Mokřad',
      wetland: {
        bog: 'Rašeliniště',
        fen: 'Slatiniště',
        mangrove: 'Mangrovy',
        marsh: 'Mokřad',
        reedbed: 'Rákosina',
        swamp: 'Bažina',
        wet_meadow: 'Vlhká louka',
      },
    },
    wood: 'Les',
  },

  place: {
    '*': 'Místo {}',
    city: 'Velkoměsto',
    country: 'Krajina',
    farm: 'Farma',
    hamlet: 'Osada',
    island: 'Ostrov',
    islet: 'Ostrůvek',
    isolated_dwelling: 'Samota',
    locality: 'Lokalita',
    ocean: 'Oceán',
    sea: 'Moře',
    square: 'Náměstí',
    state: 'Stát',
    suburb: 'Předměstí',
    town: 'Město',
    village: 'Vesnice',
  },

  power: {
    '*': '{}',
    generator: {
      '*': 'Generátor',

      'generator:source': {
        biofuel: {
          '*': 'Generátor elektrické energie z biopaliva',
        },

        biogas: {
          '*': 'Generátor elektrické energie z bioplynu',
        },

        biomass: {
          '*': 'Generátor elektrické energie z biomasy',

          'generator:method': {
            anaerobic_digestion:
              'Generátor elektrické energie z anaerobního rozkladu biomasy',
            combustion: 'Generátor elektrické energie ze spalování biomasy',
            gasification: 'Generátor elektrické energie ze zplyňování biomasy',
          },
        },

        coal: {
          '*': 'Generátor elektrické energie ze spalování uhlí',
        },

        diesel: {
          '*': 'Generátor elektrické energie ze spalování nafty',
        },

        gas: {
          '*': 'Generátor elektrické energie ze spalování plynu',
        },

        gasoline: {
          '*': 'Generátor elektrické energie ze spalování benzínu',
        },

        geothermal: {
          '*': 'Generátor elektrické energie z geotermální energie',
        },

        hydro: {
          '*': 'Generátor elektrické energie z vodní energie',

          'generator:method': {
            'run-of-the-river':
              'Generátor elektrické energie z průtokové vodní energie',
            'water-pumped-storage':
              'Generátor elektrické energie z přečerpávané vodní energie',
            'water-storage':
              'Generátor elektrické energie z akumulované vodní energie',
          },
        },

        nuclear: {
          '*': 'Generátor elektrické energie z jaderné energie',

          'generator:method': {
            fission: 'Generátor elektrické energie ze štěpení jádra',
            fusion: 'Generátor elektrické energie z jaderné fúze',
          },
        },

        oil: {
          '*': 'Generátor elektrické energie ze spalování ropy',
        },

        solar: {
          '*': 'Generátor elektrické energie ze slunečního záření',

          'generator:method': {
            photovoltaic:
              'Generátor elektrické energie ze slunečního záření - fotovoltaický',
            thermal:
              'Generátor elektrické energie ze slunečního záření - termální',
          },
        },

        tidal: {
          '*': 'Generátor elektrické energie z přílivové energie',

          'generator:method': {
            barrage: 'Generátor elektrické energie z přílivové hráze',
            stream: 'Generátor elektrické energie z přílivového proudu',
          },
        },

        waste: {
          '*': 'Generátor elektrické energie ze spalování odpadu',

          'generator:method': {
            combustion: 'Generátor elektrické energie ze spalování odpadu',
            gasification: 'Generátor elektrické energie ze zplyňování odpadu',
          },
        },

        wave: {
          '*': 'Generátor elektrické energie z energie mořských vln',
        },

        wind: {
          '*': 'Generátor elektrické energie z větrné energie',
        },
      },
    },
    line: 'Elektrické vedení',
    minor_line: 'Vedlejší elektrické vedení',
    plant: {
      '*': 'Elektrárna',

      'plant:source': {
        biofuel: {
          '*': 'Elektrárna na biopalivo',
        },

        biogas: {
          '*': 'Bioplynová elektrárna',
        },

        biomass: {
          '*': 'Elektrárna na biomasu',

          'plant:method': {
            anaerobic_digestion: 'Elektrárna s anaerobním rozkladem biomasy',
            combustion: 'Elektrárna se spalováním biomasy',
            gasification: 'Elektrárna se zplyňováním biomasy',
          },
        },

        coal: {
          '*': 'Uhelná elektrárna',
        },

        diesel: {
          '*': 'Naftová elektrárna',
        },

        gas: {
          '*': 'Plynová elektrárna',
        },

        gasoline: {
          '*': 'Benzínová elektrárna',
        },

        geothermal: {
          '*': 'Geotermální elektrárna',
        },

        hydro: {
          '*': 'Vodní elektrárna',

          'plant:method': {
            'run-of-the-river': 'Průtoková vodní elektrárna',
            'water-pumped-storage': 'Přečerpávací vodní elektrárna',
            'water-storage': 'Přehradní vodní elektrárna',
          },
        },

        nuclear: {
          '*': 'Jaderná elektrárna',

          'plant:method': {
            fission: 'Elektrárna se štěpením jádra',
            fusion: 'Elektrárna s jadernou fúzí',
          },
        },

        oil: {
          '*': 'Elektrárna na ropu',
        },

        solar: {
          '*': 'Solární elektrárna',

          'plant:method': {
            photovoltaic: 'Fotovoltaická elektrárna',
            thermal: 'Solární termální elektrárna',
          },
        },

        tidal: {
          '*': 'Přílivová elektrárna',

          'plant:method': {
            barrage: 'Přílivová elektrárna s hrází',
            stream: 'Přílivová elektrárna z proudu',
          },
        },

        waste: {
          '*': 'Spalovna odpadu s výrobou elektřiny',

          'plant:method': {
            combustion: 'Elektrárna se spalováním odpadu',
            gasification: 'Elektrárna se zplyňováním odpadu',
          },
        },

        wave: {
          '*': 'Vlnová elektrárna',
        },

        wind: {
          '*': 'Větrná elektrárna',
        },
      },
    },
    pole: 'Elektrický sloup',
    substation: 'Elektrická distribuční stanice',
    tower: 'Stožár vysokého napětí',
    transformer: 'Transformátor',
  },

  public_transport: {
    platform: 'Nástupiště',
    station: 'Stanice',
    stop_position: 'Zastávka',
  },

  railway: {
    '*': 'Železnice',
    abandoned: 'Zrušená železnice',
    buffer_stop: 'Železniční zarážedlo',
    construction: 'Železnice ve výstavbě',
    crossing: 'Křížení železničních tratí',
    derail: 'Výkolejka',
    disused: 'Nepoužívaná železnice',
    funicular: 'Lanová dráha',
    halt: 'Železniční zastávka',
    level_crossing: 'Železniční přejezd',
    light_rail: 'Lehká železnice',
    miniature: 'Miniaturní železnice',
    monorail: 'Jednokolejná dráha',
    narrow_gauge: 'Úzkorozchodná železnice',
    platform: 'Železniční nástupiště',
    preserved: 'Historická železnice',
    proposed: 'Navrhovaná železnice',
    rail: 'Železniční trať',
    railway_crossing: 'Železniční přejezd',
    roundhouse: 'Kruhové depo',
    signal: 'Železniční návěstidlo',
    station: 'Železniční stanice',
    stop: 'Železniční zastávka',
    subway: 'Trať metra',
    subway_entrance: 'Vstup do metra',
    switch: 'Železniční výhybka',
    tram: 'Tramvajová trať',
    tram_stop: 'Tramvajová zastávka',
    traverser: 'Přesuvna',
    turntable: 'Točna',
    ventilation_shaft: 'Ventilační šachta železnice',
    wash: 'Myčka vlaků',
    water_crane: 'Železniční vodní jeřáb',
    workshop: 'Železniční dílna',
  },

  shop: {
    '*': 'Obchod {}',
    household_linen: 'Povlečení do domácnosti',
    charity: 'Charitativní obchod',
    chocolate: 'Obchod s čokoládou',
    fashion_accessories: 'Obchod s módními doplňky',
    frozen_food: 'Obchod s mraženými potravinami',
    hearing_aids: 'Obchod se sluchadly',
    weapons: 'Obchod se zbraněmi',
    'e-cigarette': 'E-cigareta',
    alcohol: 'Obchod s alkoholem',
    antiques: 'Starožitnosti',
    art: 'Obchod s uměním',
    baby_goods: 'Dětské potřeby',
    bag: 'Prodej kabelek',
    bakery: 'Pekařství',
    bathroom_furnishing: 'Koupelnové studio',
    beauty: 'Kosmetický salon',
    bed: 'Prodej postelí a matrací',
    beverages: 'Obchod s pitím',
    bicycle: 'Prodej kol',
    bookmaker: 'Sázková kancelář',
    books: 'Knihkupectví',
    boutique: 'Butik',
    butcher: 'Masna',
    camera: 'Prodej fotoaparátů',
    car_parts: 'Prodej autodílů',
    car_repair: 'Autoservis',
    car: 'Prodej aut',
    carpet: 'Prodej koberců',
    cheese: 'Prodej sýrů',
    chemist: 'Drogerie',
    clothes: 'Obchod s oblečením',
    coffee: 'Prodejna kávy',
    collector: 'Obchod pro sběratele',
    computer: 'Počítačový obchod',
    confectionery: 'Cukrárna',
    convenience: 'Potraviny',
    copyshop: 'Copy centrum',
    cosmetics: 'Obchod s kosmetikou',
    craft: 'Obchod s potřebami pro umělce a řemeslníky',
    curtain: 'Prodejna záclon a závěsů',
    dairy: 'Mléčné výrobky',
    deli: 'Lahůdky',
    department_store: 'Obchodní dům',
    doityourself: 'Udělej si sám',
    doors: 'Prodej dveří',
    dry_cleaning: 'Čistárna',
    electrical: 'Elektroinstalační materiál',
    electronics: 'Obchod s elektronikou',
    erotic: 'Sexshop',
    fabric: 'Metrový textil',
    farm: 'Farmařské výrobky',
    fireplace: 'Prodej krbů',
    fishing: 'Rybářské potřeby',
    flooring: 'Prodej podlah',
    florist: 'Květinářství',
    funeral_directors: 'Pohřební služby',
    furniture: 'Prodej nábytku',
    games: 'Stolní hry',
    garden_center: 'Záhradní centrum',
    garden_centre: 'Zahradní centrum',
    general: 'Smíšené zboží',
    gift: 'Suvenýry a dárky',
    glaziery: 'Sklenář',
    greengrocer: 'Ovoce a zelenina',
    hairdresser: 'Kadernictví, holičství',
    hardware: 'Železářství',
    health_food: 'Prodej zdravého jídla',
    hifi: 'Obchod s Hi-fi',
    houseware: 'Domácí potřeby',
    hunting: 'Lovecké potřeby',
    ice_cream: 'Zmrzlina',
    interior_decoration: 'Interiérové ​​dekorace',
    jewelry: 'Klenotnictví',
    kiosk: 'Stánek',
    kitchen: 'Kuchyňské studio',
    laundry: 'Prádelna',
    lighting: 'Svítidla',
    locksmith: 'Zámečník',
    lottery: 'Loterie',
    mall: 'Nákupní středisko',
    massage: 'Masážní salon',
    medical_supply: 'Zdravotnické potřeby',
    mobile_phone: 'Prodej mobilních telefonů',
    model: 'Modelářství',
    motorcycle: 'Prodej motocyklů',
    music: 'Prodej hudebních nosičů',
    musical_instrument: 'Hudobeniny',
    newsagent: 'Noviny a časopisy',
    nutrition_supplements: 'Výživové doplňky',
    optician: 'Optika',
    outdoor: 'Prodej outdoorového vybavení',
    outpost: 'Zásilkovna',
    paint: 'Farby, laky',
    pastry: 'Obchod se sladkým pečivem',
    pawnbroker: 'Záložna',
    perfumery: 'Parfumerie',
    pet_grooming: 'Salon pro zvířecí mazlíčky',
    pet: 'Potřeby pro zvířata',
    photo: 'Fotografické služby',
    radiotechnics: 'Prodej elektronických součástek',
    rental: 'Půjčovna',
    seafood: 'Prodej mořských plodů',
    second_hand: 'Second hand',
    sewing: 'Krajčířské potřeby',
    shoes: 'Obuv',
    sports: 'Sportovní potřeby',
    stationery: 'Papírnictví',
    supermarket: 'Supermarket',
    tailor: 'Krajčíř',
    tattoo: 'Tetovací studio',
    tea: 'Čajovna',
    ticket: 'Prodej lístků',
    tobacco: 'Prodej tabákových výrobků',
    toys: 'Hračkařství',
    trade: 'Stavebniny',
    travel_agency: 'Cestovní kancelář',
    tyres: 'Pneuservis',
    vacant: 'Prázdný obchod',
    variety_store: 'Rozličné zboží',
    video_games: 'Videohry',
    video: 'Prodej DVD',
    watches: 'Hodinář',
    wholesale: 'Velkoobchod',
    window_blind: 'Prodej žaluzií',
    wine: 'Vinotéka',
  },

  sport: {
    '*': 'Sportovní aktivita {}',
    australian_football: 'Australský fotbal',
    billiards: 'Biliárd',
    boxing: 'Box',
    cliff_diving: 'Skoky do vody ze skály',
    cricket: 'Kriket',
    cricket_nets: 'Kriketové sítě',
    croquet: 'Kroket',
    curling: 'Curling',
    gaelic_games: 'Gaelské hry',
    horseshoes: 'Podkovy',
    korfball: 'Korfball',
    long_jump: 'Dálkový skok',
    orienteering: 'Orientační běh',
    paddle_tennis: 'Paddle tenis',
    pelota: 'Pelota',
    racquet: 'Raketka',
    rc_car: 'RC auta',
    rugby: 'Ragby',
    rugby_league: 'Ragby liga',
    rugby_union: 'Ragby unie',
    sailing: 'Plachtění',
    surfing: 'Surfování',
    table_soccer: 'Stolní fotbal',
    team_handball: 'Házená',
    toboggan: 'Tobogán',
    '9pin': 'Kuželky',
    '10pin': 'Bowling',
    'shot-put': 'Vrh koulí',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'Americký fotbal',
    archery: 'Lukostřelba',
    athletics: 'Atletika',
    badminton: 'Badminton',
    baseball: 'Baseball',
    basketball: 'Basketbal',
    beachvolleyball: 'Plážový volejbal',
    bicycle: 'Cyklistika',
    bmx: 'BMX',
    boules: 'Petang',
    bowling: 'Bowling',
    bowls: 'Bowls',
    canoe: 'Kanoe',
    chess: 'Šachy',
    climbing_adventure: 'Climbing adventure',
    climbing: 'Lezení',
    cycling: 'Cyklistika',
    darts: 'Šipky (sport)',
    disc_golf: 'Disc golf',
    dog_racing: 'Psí závod',
    equestrian: 'Jezdectví',
    field_hockey: 'Pozemní hokej',
    fitness: 'Posilovna',
    floorball: 'Floorball',
    free_flying: 'Závěsné létání',
    golf: 'Golf',
    gymnastics: 'Gymnastika',
    handball: 'Házená',
    hockey: 'Hokej',
    horse_racing: 'Dostihy',
    ice_hockey: 'Lední hokej',
    ice_skating: 'Bruslení na ledě',
    judo: 'Džudo',
    karate: 'Karate',
    karting: 'Motokáry',
    laser_tag: 'Laser aréna',
    model_aerodrome: 'Modelářské letiště',
    motocross: 'Motokros',
    motor: 'Závody motorových vozidel',
    multi: 'Různé sporty',
    netball: 'Nohejbal',
    paintball: 'Paintball',
    petanque: 'Petang (špatné tagování)',
    roller_skating: 'Kolečkové bruslení',
    rowing: 'Veslování',
    running: 'Běh',
    scuba_diving: 'Potápění',
    shooting_range: 'Střelnice',
    shooting: 'Střelba',
    skateboard: 'Skateboard',
    skating: 'Bruslení',
    ski_jumping: 'Skoky na lyžích',
    skiing: 'Lyžování',
    soccer: 'Fotbal',
    squash: 'Squash',
    streetball: 'Streetball',
    swimming: 'Plavání',
    table_tennis: 'Stolní tenis',
    tennis: 'Tenis',
    volleyball: 'Volejbal',
    water_ski: 'Vodní lyžování',
    workout: 'Cvičení',
    yoga: 'Jóga',
    '8pin': 'Osmikolkový bowling',
    aerobics: 'Aerobik',
    american_handball: 'Americká házená',
    association_football: 'Fotbal (asociační fotbal)',
    axe_throwing: 'Hod sekerou',
    balle_pelote: 'Balle pelote',
    ballooning: 'Létání horkovzdušným balónem',
    bandy: 'Bandy',
    barre: 'Barre cvičení',
    base: 'BASE jumping',
    batting_cage: 'Tréninková klec pro baseball/softball',
    beach_soccer: 'Plážový fotbal',
    beach_tennis: 'Plážový tenis',
    beachhandball: 'Plážová házená',
    beachtennis: 'Plážový tenis',
    biathlon: 'Biatlon',
    billards: 'Biliard',
    bobsleigh: 'Boby',
    bodybuilding: 'Kulturistika',
    bullfighting: 'Býčí zápasy',
    calisthenics: 'Kalistenika',
    canadian_football: 'Kanadský fotbal',
    candlepin: 'Candlepin bowling',
    canoe_polo: 'Kanoe pólo',
    chinlone: 'Chinlone',
    cockfighting: 'Kohoutí zápasy',
    crossfit: 'CrossFit trénink',
    cycle_ball: 'Cyklobal',
    cycle_polo: 'Cyklopólo',
    dance: 'Taneční sport',
    dancing: 'Taneční sport',
    diving: 'Skoky do vody',
    dodgeball: 'Vybíjená',
    dog_agility: 'Psí agility',
    dragon_boat: 'Závody dračích lodí',
    fencing: 'Šerm',
    fistball: 'Fistbal',
    'five-a-side': 'Malý fotbal (5 na 5)',
    fives: 'Fives',
    football: 'Fotbal',
    footballgolf: 'Fotbalgolf',
    four_square: 'Four square',
    freediving: 'Volné potápění',
    funnel_ball: 'Funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Gaelský fotbal',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Bezmotorové létání',
    hanggliding: 'Rogalo',
    hapkido: 'Hapkido',
    high_rope_course: 'Lanový park',
    hiking: 'Turistika',
    hopscotch: 'Skákání panáka',
    horse_riding: 'Jízda na koni',
    ice_stock: 'Lední metaná (Eisstock)',
    'in-line_hockey': 'Inline hokej',
    jetsprint: 'Závody rychlostních člunů (jet sprint)',
    kick_scooter: 'Jízda na koloběžce (sport)',
    kickball: 'Kickball',
    kickboxing: 'Kickbox',
    kitesurfing: 'Kitesurfing',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Lakros',
    martial_arts: 'Bojová umění',
    mind_body_interventions: 'Cvičení tělo–mysl (např. jóga)',
    miniature_golf: 'Minigolf',
    mtb: 'Horská cyklistika',
    nine_mens_morris: 'Hra mlýn',
    obstacle_course: 'Překážkový běh',
    paddleball: 'Paddleball',
    paddleboard: 'Stand-up paddleboarding',
    padel: 'Padel tenis',
    parachuting: 'Parašutismus',
    paragliding: 'Paragliding',
    parkour: 'Parkour',
    pedal_car_racing: 'Závody šlapacích aut',
    pesäpallo: 'Pesäpallo (finský baseball)',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole dance (sport)',
    polo: 'Pólo',
    powerlifting: 'Silový trojboj',
    rodeo: 'Rodeo',
    roller_hockey: 'Kolečkový hokej',
    russian_skittles: 'Ruské kuželky',
    safety_training: 'Bezpečnostní sportovní trénink',
    shuffleboard: 'Shuffleboard',
    snooker: 'Snooker',
    snorkeling: 'Šnorchlování',
    softball: 'Softbal',
    speedway: 'Plochá dráha (motocyklový sport)',
    summer_toboggan: 'Letní bobová dráha',
    sumo: 'Sumo',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    touch_football: 'Bezkontaktní fotbal (touch football)',
    trampoline: 'Skákání na trampolíně',
    trugo: 'Trugo',
    tug_of_war: 'Přetahování lanem',
    ultimate: 'Ultimate frisbee',
    ultralight_aviation: 'Sportovní ultralehké létání',
    wakeboarding: 'Wakeboarding',
    walking: 'Sportovní chůze',
    water_polo: 'Vodní pólo',
    water_sports: 'Vodní sporty',
    weightlifting: 'Vzpírání',
    windsurfing: 'Windsurfing',
    wrestling: 'Zápasení',
    zurkhaneh_sport: 'Zurkhaneh (íránský tradiční sport)',
  },

  tourism: {
    '*': '{}',
    alpine_hut: 'Horská chata',
    apartment: 'Apartmán',
    aquarium: 'Akvárium',

    artwork: {
      '*': 'Umění',
      artwork_type: {
        architecture: 'Významná budova, stavba',
        bust: 'Busta',
        graffiti: 'Graffiti',
        installation: 'Umělecká instalace',
        mosaic: 'Mozaika (umění)',
        mural: 'Nástěnná malba',
        painting: 'Obraz',
        relief: 'Reliéf (umění)',
        sculpture: 'Plastika',
        statue: 'Socha',
        stone: 'Balvan (umění)',
      },
    },

    attraction: 'Atrakce',
    camp_site: 'Kemp',
    caravan_site: 'Autokemp pro obytné přívěsy',
    chalet: 'Chata',
    gallery: 'Galerie',
    guest_house: 'Penzion',
    hostel: 'Hostel',
    hotel: 'Hotel',

    information: {
      '*': 'Informace',
      information: {
        '*': 'Informace {}',
        board: 'Informační tabule',
        guidepost: 'Rozcestník, směrovník',
        map: 'Mapa',
        office: 'Informační kancelář',
        route_marker: 'Označení trasy',
      },
    },

    motel: 'Motel',
    museum: 'Muzeum',
    picnic_site: 'Místo na piknik',
    viewpoint: 'Výhled',
    wilderness_hut: 'Chata v divočině',
    zoo: 'ZOO',
    theme_park: 'Tematický park',
  },

  type: {
    route: {
      '*': 'Trasa',
      route: {
        '*': 'Trasa {}',
        bicycle: 'Cyklostezka',
        bus: 'Trasa autobusu',
        foot: 'Stezka pro pěší',
        hiking: {
          '*': 'Turistická stezka',

          network: {
            iwn: 'Mezinárodní turistická trasa',
            lwn: 'Místní turistická trasa',
            nwn: 'Národní turistická trasa',
            rwn: 'Regionální turistická trasa',
          },
        },
        horse: 'Jezdecká trasa',
        mtb: 'Stezka pro horská kola',
        piste: 'Sjezdovka',
        railway: 'Železnice',
        ski: 'Lyžařská stezka',
        tram: 'Tramvajová dráha',
      },
    },
  },

  waterway: {
    '*': 'Vodní tok {}',
    canal: 'Kanál',
    dam: 'Přehrada',
    ditch: 'Příkop',
    drain: 'Dranáž',
    river: 'Řeka',
    stream: 'Potok',
    waterfall: 'Vodopád',
    weir: 'Hráz',
    canoe_pass: 'Průchod pro kánoe',
    fairway: 'Plavební dráha',
    fish_pass: 'Rybí přechod',
    flowline: 'Proudnice',
    link: 'Vodní spojka',
    pressurised: 'Tlakové vodní potrubí',
    rapids: 'Peřeje',
    tidal_channel: 'Přílivový kanál',
  },

  bicycle: {
    designated: 'Vyhrazeno pro jízdní kola',
    no: 'Vjezd na kole zakázán',
    private: 'Vjezd na kole jen pro vlastníky',
    yes: 'Vjezd na kole povolen',
  },

  bridge: {
    '*': {
      '*': 'Most',

      highway: {
        '*': 'Silniční most',
      },

      railway: {
        '*': 'Železniční most',
      },
    },

    no: '',
  },

  foot: {
    designated: 'Vyhrazeno pro pěší',
    no: 'Vstup pěším zakázán',
    private: 'Vstup pěším jen pro vlastníky',
    yes: 'Vstup pěším povolen',
  },

  ford: {
    yes: 'Brod',
  },

  motor_vehicle: {
    designated: 'Vyhrazeno pro motorová vozidla',
    no: 'Vjezd motorovým vozidlům zakázán',
    private: 'Vjezd motorovým vozidlům jen pro vlastníky',
    yes: 'Vjezd motorovým vozidlům povolen',
  },

  mountain_pass: {
    yes: 'Horský průsmyk',
  },

  oneway: {
    yes: 'Jednosměrka',
  },

  trail_visibility: {
    bad: 'Špatná viditelnost stezky',
    excellent: 'Výborná viditelnost stezky',
    good: 'Dobrá viditelnost stezky',
    horrible: 'Velmi špatná viditelnost stezky',
    intermediate: 'Střední viditelnost stezky',
    no: 'Žádná viditelnost stezky',
  },

  tunnel: {
    '*': {
      '*': 'Tunel',

      highway: {
        '*': 'Silniční tunel',
      },

      railway: {
        '*': 'Železniční tunel',
      },
    },

    culvert: 'Propustek',
    no: '',
  },

  vehicle: {
    designated: 'Vyhrazeno pro vozidla',
    no: 'Vjezd vozidlům zakázán',
    private: 'Vjezd vozidlům jen pro vlastníky',
    yes: 'Vjezd vozidlům povolen',
  },

  military: {
    '*': 'Vojenský objekt {}',
    academy: 'Vojenská akademie',
    airfield: 'Vojenské letiště',
    ammunition: 'Sklad munice',
    barracks: 'Kasárna',
    base: 'Vojenská základna',
    bunker: 'Bunkr',
    checkpoint: 'Vojenský kontrolní bod',
    danger_area: 'Vojenský nebezpečný prostor',
    depot: 'Vojenský sklad',
    launchpad: 'Odpalovací plocha',
    naval_base: 'Námořní základna',
    nuclear_explosion_site: 'Místo jaderného testu',
    obstacle_course: 'Vojenská překážková dráha',
    office: 'Vojenský úřad',
    range: 'Vojenská střelnice',
    school: 'Vojenská škola',
    training_area: 'Vojenský výcvikový prostor',
    trench: 'Zákop',
  },

  'abandoned:building': {
    '*': 'Trvale opuštěná budova',
  },

  'disused:building': {
    '*': 'Nepoužívaná budova',
  },

  'ruins:building': {
    '*': 'Ruiny budovy',
  },

  fixme: {
    '*': 'Nesprávně nebo částečně zmapovaný prvek',
  },

  intermittent: {
    yes: {
      natural: {
        water: 'Občasná vodní plocha',
      },

      waterway: 'Občasný vodní tok',
    },
  },

  seasonal: {
    yes: {
      natural: {
        water: 'Sezónní vodní plocha',
      },

      waterway: 'Sezónní vodní tok',
    },
  },

  attraction: {
    amusement_ride: 'Zábavní atrakce',
    animal: 'Zvířecí atrakce',
    big_wheel: 'Ruské kolo',
    carousel: 'Kolotoč',
    historic: 'Historická atrakce',
    maze: 'Bludiště',
    roller_coaster: 'Horská dráha',
    summer_toboggan: 'Letní bobová dráha',
    train: 'Vyhlídkový vláček',
    water_slide: 'Tobogan',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Červená',
  blue: 'Modrá',
  green: 'Zelená',
  yellow: 'Žlutá',
  orange: 'Oranžová',
  purple: 'Purpurová',
  violet: 'Fialová',
  white: 'Bílá',
  black: 'Černá',
  gray: 'Šedá',
  brown: 'Hnědá',
};
