import { DeepPartialWithRequiredObjects } from '../deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartialWithRequiredObjects<OsmTagToNameMapping> =
  {
    aeroway: {
      aerodrome: 'Lotnisko',
    },

    amenity: {
      shelter: {
        shelter_type: {
          picnic_shelter: {
            fireplace: {
              yes: 'Altana piknikowa z kominkiem',
            },
            '*': 'Altana piknikowa',
          },
          '*': 'Schronienie {}',
          basic_hut: 'Prosta chata',
          changing_rooms: 'Przebieralnia',
          field_shelter: 'Polowe schronienie',
          lean_to: 'Schronienie z otwartą ścianą',
          public_transport: 'Wiata przystankowa',
          rock_shelter: 'Schronisko skalne',
          sun_shelter: 'Zadaszenie przeciwsłoneczne',
          weather_shelter: 'Schronienie przed pogodą',
        },
        '*': 'Schronienie',
      },

      social_facility: {
        social_facility: {
          ambulatory_care: 'Opieka ambulatoryjna',
          assisted_living: 'Mieszkanie wspomagane',
          clothing_bank: 'Bank odzieży',
          day_care: 'Opieka dzienna',
          food_bank: 'Bank żywności',
          group_home: 'Dom grupowy',
          hospice: 'Hospicjum',
          nursing_home: 'Dom opieki',
          shelter: 'Schronisko',
          soup_kitchen: 'Jadłodajnia',
          workshop: 'Warsztat',
        },
        '*': 'Placówka socjalna',
      },

      vending_machine: {
        vending: {
          bicycle_tube: 'Automat z dętkami rowerowymi',
          bread: 'Automat z chlebem',
          bottle_return: 'Automat do zwrotu butelek',
          candles: 'Automat ze świecami',
          chewing_gums: 'Automat z gumami do żucia',
          cigarettes: 'Automat z papierosami',
          coffee: 'Automat z kawą',
          condoms: 'Automat z prezerwatywami',
          drinks: 'Automat z napojami',
          elongated_coin: 'Automat z monetami pamiątkowymi',
          eggs: 'Automat z jajkami',
          excrement_bags: 'Automat z woreczkami na odchody',
          food: 'Automat z jedzeniem',
          fuel: 'Automat z paliwem',
          gas: 'Automat z gazem',
          ice_cream: 'Automat z lodami',
          ice_cubes: 'Automat z kostkami lodu',
          milk: 'Automat z mlekiem',
          movies: 'Automat z filmami',
          newspapers: 'Automat z gazetami',
          parking_tickets: 'Automat biletów parkingowych',
          pizza: 'Automat z pizzą',
          public_transport_tickets: 'Automat biletów komunikacji miejskiej',
          stamps: 'Automat ze znaczkami',
          sweets: 'Automat ze słodyczami',
          water: 'Automat z wodą',
        },
        '*': 'Automat',
      },

      '*': '{}',

      animal_breeding: 'Hodowla zwierząt',
      animal_shelter: 'Schronisko dla zwierząt',
      arts_centre: 'Centrum sztuki',
      atm: 'Bankomat',
      bank: 'Bank',
      bar: 'Bar',
      bbq: 'Grill',
      bench: 'Ławka',
      bicycle_parking: 'Parking rowerowy',
      bicycle_rental: 'Wypożyczalnia rowerów',
      bicycle_repair_station: 'Stacja naprawy rowerów',
      biergarten: 'Ogródek piwny',
      brothel: 'Dom publiczny',
      bureau_de_change: 'Kantor',
      bus_station: 'Dworzec autobusowy',
      cafe: 'Kawiarnia',
      car_rental: 'Wypożyczalnia samochodów',
      car_wash: 'Myjnia samochodowa',
      casino: 'Kasyno',
      charging_station: 'Stacja ładowania',
      childcare: 'Opieka nad dziećmi',
      cinema: 'Kino',
      clinic: 'Przychodnia',
      clock: 'Zegar',
      college: 'Kolegium',
      community_centre: 'Centrum społecznościowe',
      compressed_air: 'Sprężone powietrze',
      courthouse: 'Sąd',
      dentist: 'Dentysta',
      device_charging_station: 'Stacja ładowania urządzeń',
      doctors: 'Gabinet lekarski',
      dressing_room: 'Przebieralnia',
      drinking_water: 'Woda pitna',
      driving_school: 'Szkoła jazdy',
      embassy: 'Ambasada',
      events_venue: 'Miejsce wydarzeń',
      fast_food: 'Fast food',
      feeding_place: 'Miejsce karmienia',
      ferry_terminal: 'Terminal promowy',
      fire_station: 'Straż pożarna',
      food_court: 'Strefa gastronomiczna',
      fountain: 'Fontanna',
      fuel: 'Stacja paliw',
      funeral_hall: 'Dom pogrzebowy',
      gambling: 'Hazard',
      game_feeding: 'Karmisko',
      grave_yard: 'Cmentarz',
      grit_bin: 'Pojemnik na piasek',
      hospital: 'Szpital',
      hunting_stand: 'Ambona myśliwska',
      ice_cream: 'Lody',
      kindergarten: 'Przedszkole',
      language_school: 'Szkoła językowa',
      library: 'Biblioteka',
      marketplace: 'Targowisko',
      monastery: 'Klasztor',
      money_transfer: 'Przelew pieniędzy',
      motorcycle_parking: 'Parking dla motocykli',
      motorcycle_rental: 'Wypożyczalnia motocykli',
      nightclub: 'Klub nocny',
      parcel_locker: 'Paczkomat',
      parking: 'Parking',
      parking_entrance: 'Wjazd na parking',
      parking_space: 'Miejsce parkingowe',
      pharmacy: 'Apteka',
      place_of_mourning: 'Miejsce żałoby',
      place_of_worship: 'Miejsce kultu',
      planetarium: 'Planetarium',
      police: 'Policja',
      post_box: 'Skrzynka pocztowa',
      post_office: 'Poczta',
      prison: 'Więzienie',
      pub: 'Pub',
      public_bookcase: 'Publiczna biblioteczka',
      ranger_station: 'Posterunek strażników',
      recycling: 'Recykling',
      restaurant: 'Restauracja',
      school: 'Szkoła',
      shower: 'Prysznic',
      ski_rental: 'Wypożyczalnia nart',
      smoking_area: 'Strefa dla palących',
      social_centre: 'Centrum socjalne',
      stripclub: 'Klub ze striptizem',
      studio: 'Studio',
      taxi: 'Taksówka',
      telephone: 'Telefon',
      theatre: 'Teatr',
      toilets: 'Toaleta',
      townhall: 'Ratusz',
      traffic_park: 'Miasteczko ruchu drogowego',
      trolley_bay: 'Stanowisko na wózki',
      university: 'Uniwersytet',
      vacuum_cleaner: 'Odkurzacz',
      vehicle_inspection: 'Kontrola pojazdów',
      veterinary: 'Weterynarz',
      waste_basket: 'Kosz na śmieci',
      waste_disposal: 'Utylizacja odpadów',
      water_point: 'Punkt poboru wody',
      watering_place: 'Wodopój',
    },

    barrier: {
      '*': 'Bariera {}',
      block: 'Blok',
      bollard: 'Słupek',
      border_control: 'Kontrola graniczna',
      cable_barrier: 'Bariera kablowa',
      chain: 'Łańcuch',
      city_wall: 'Mur miejski',
      ditch: 'Rów (bariera)',
      entrance: 'Wejście',
      fence: 'Ogrodzenie',
      gate: 'Brama',
      guard_rail: 'Bariera ochronna',
      handrail: 'Poręcz',
      hedge: 'Żywopłot',
      kerb: 'Krawężnik',
      lift_gate: 'Szlaban',
      rope: 'Lina',
      sliding_gate: 'Brama przesuwna',
      swing_gate: 'Brama uchylna',
      turnstile: 'Kołowrót',
      wall: 'Mur',
    },

    boundary: {
      administrative: {
        admin_level: {
          '2': 'Państwo',
          '3': 'Region',
          '4': 'Okręg',
          '5': 'Prowincja',
          '6': 'Miasto',
          '7': 'Region',
          '8': 'Powiat',
          '9': 'Wieś',
          '10': 'Obszar katastralny',
        },
        '*': 'Region administracyjny',
      },
      '*': 'Region',
      national_park: 'Park narodowy',
      protected_area: 'Obszar chroniony',
    },

    building: {
      '*': 'Budynek {}',
      apartments: 'Apartamenty (blok)',
      barn: 'Stodoła',
      bungalow: 'Bungalow',
      bunker: 'Bunkier',
      cabin: 'Domek',
      cathedral: 'Katedra',
      chapel: 'Kaplica',
      church: 'Kościół',
      civic: 'Budynek publiczny',
      collapsed: 'Zawalony budynek',
      commercial: 'Budynek komercyjny',
      construction: 'Budowa budynku',
      cowshed: 'Obora',
      detached: 'Dom wolnostojący',
      dormitory: 'Akademik',
      entrance: 'Wejście do budynku',
      farm_auxiliary: 'Pomocniczy budynek gospodarstwa',
      farm: 'Gospodarstwo',
      garage: 'Garaż',
      garages: 'Garaże',
      government: 'Budynek rządowy',
      grandstand: 'Trybuna',
      greenhouse: 'Szklarnia',
      hangar: 'Hangar',
      hayloft: 'Stodoła na siano',
      hospital: 'Budynek szpitalny',
      hotel: 'Budynek hotelowy',
      house: 'Dom prywatny',
      houseboat: 'Dom na wodzie',
      hut: 'Chatka',
      industrial: 'Budynek przemysłowy',
      kindergarten: 'Budynek przedszkola',
      kiosk: 'Kiosk',
      manufacture: 'Budynek fabryczny',
      mosque: 'Meczet',
      office: 'Budynek biurowy',
      parking: 'Budynek parkingowy',
      public: 'Budynek publiczny',
      residential: 'Budynek mieszkalny',
      retail: 'Budynek handlowy',
      roof: 'Dach',
      ruins: 'Ruiny budynku',
      school: 'Budynek szkoły',
      semidetached_house: 'Bliźniak',
      service: 'Budynek usługowy',
      shed: 'Szopa',
      shrine: 'Kapliczka',
      stable: 'Stajnia',
      static_caravan: 'Dom mobilny, przyczepa kempingowa',
      storage_tank: 'Zbiornik magazynowy',
      sty: 'Chlew',
      supermarket: 'Budynek supermarketu',
      synagogue: 'Synagoga',
      temple: 'Świątynia',
      terrace: 'Szeregowiec',
      train_station: 'Stacja kolejowa',
      transformer_tower: 'Wieża transformatorowa',
      transportation: 'Budynek transportu',
      university: 'Budynek uniwersytetu',
      warehouse: 'Magazyn',
      yes: 'Niezidentyfikowany budynek',
    },

    highway: {
      service: {
        service: {
          '*': 'Droga serwisowa {}',
          alley: 'Zaułek',
          bus: 'Droga dla komunikacji publicznej',
          'drive-through': 'Przejazd dla samochodów',
          driveway: 'Podjazd',
          emergency_access: 'Droga pożarowa',
          parking_aisle: 'Droga na parkingu',
        },
        '*': 'Droga serwisowa / dojazdowa',
      },

      track: {
        tracktype: {
          grade1: 'Utwardzona droga leśna',
          grade2: 'Przeważnie utwardzona droga leśna',
          grade3: 'Słabiej utwardzona droga leśna',
          grade4: 'Droga leśna dla traktorów lub podobnych pojazdów',
          grade5: 'Słabo widoczna droga leśna',
        },
        '*': 'Droga leśna / polna',
      },

      '*': 'Droga {}',
      bus_stop: 'Przystanek autobusowy',
      construction: 'Droga w budowie',
      crossing: 'Przejście dla pieszych',
      cycleway: 'Droga rowerowa',
      footway: 'Chodnik',
      living_street: 'Strefa zamieszkania',
      motorway: 'Autostrada',
      motorway_link: 'Zjazd na autostradę',
      path: 'Ścieżka',
      pedestrian: 'Strefa piesza',
      primary: 'Droga główna',
      primary_link: 'Zjazd z drogi głównej',
      residential: 'Ulica mieszkalna',
      secondary: 'Droga drugorzędna',
      secondaty_link: 'Zjazd z drogi drugorzędnej',
      steps: 'Schody',
      street_lamp: 'Latarnia uliczna',
      tertiary: 'Droga trzeciorzędna',
      tertiary_link: 'Zjazd z drogi trzeciorzędnej',
      trunk: 'Droga ekspresowa',
      trunk_link: 'Zjazd z drogi ekspresowej',
      unclassified: 'Droga nieklasyfikowana',
    },

    historic: {
      ruins: {
        ruins: {
          castle: 'Ruiny zamku',
        },
        '*': 'Ruiny',
      },

      '*': 'Obiekt historyczny',
      archaeological_site: 'Stanowisko archeologiczne',
      castle: 'Zamek',
      church: 'Zabytkowy kościół',
      city_gate: 'Brama miejska',
      manor: 'Dwór',
      memorial: 'Pomnik',
      monastery: 'Klasztor',
      monument: 'Monument',
      tomb: 'Grobowiec',
      wayside_cross: 'Przydrożny krzyż',
      wayside_shrine: 'Przydrożna kapliczka',
    },

    landuse: {
      '*': '{}',
      allotments: 'Ogródki działkowe',
      basin: 'Zbiornik',
      brownfield: 'Teren poprzemysłowy',
      cemetery: 'Cmentarz',
      commercial: 'Strefa handlowa',
      construction: 'Plac budowy',
      education: 'Strefa edukacyjna',
      farmland: 'Ziemia uprawna',
      farmyard: 'Podwórze',
      forest: 'Las',
      garages: 'Garaże',
      grass: 'Trawa',
      greenfield: 'Teren pod zabudowę',
      industrial: 'Strefa przemysłowa',
      landfill: 'Wysypisko',
      meadow: 'Łąka',
      military: 'Obszar wojskowy',
      orchard: 'Sad',
      plant_nursery: 'Szkółka roślin',
      quarry: 'Kamieniołom',
      recreation_ground: 'Teren rekreacyjny',
      religions: 'Grunt religijny',
      reservoir: 'Zbiornik wodny',
      residential: 'Teren mieszkalny',
      retail: 'Strefa handlowa',
      vineyard: 'Winnica',
      winter_sports: 'Sporty zimowe',
    },

    leisure: {
      picnic_table: {
        covered: {
          yes: 'Zadaszony stół piknikowy',
        },
        '*': 'Stół piknikowy',
      },
      pitch: {
        sport: {
          badminton: 'Boisko do badmintona',
          basketball: 'Boisko do koszykówki',
          beachvolleyball: 'Boisko do siatkówki plażowej',
          hockey: 'Boisko do hokeja',
          ice_hockey: 'Boisko do hokeja na lodzie',
          multi: 'Boisko wielofunkcyjne',
          soccer: 'Boisko do piłki nożnej',
          tennis: 'Kort tenisowy',
          volleyball: 'Boisko do siatkówki',
        },
        '*': 'Boisko',
      },
      '*': '{}',
      bleachers: 'Trybuny',
      escape_game: 'Escape game',
      hackerspace: 'Hackerspace',
      ice_rink: 'Lodowisko',
      marina: 'Marina',
      miniature_golf: 'Minigolf',
      dog_park: 'Park dla psów',
      firepit: 'Miejsce na ognisko',
      fishing: 'Miejsce do wędkowania',
      fitness_centre: 'Centrum fitness',
      fitness_station: 'Stacja fitness',
      garden: 'Ogród',
      golf_course: 'Pole golfowe',
      horse_riding: 'Jazda konna',
      nature_reserve: 'Rezerwat przyrody',
      park: 'Park',
      playground: 'Plac zabaw',
      sports_centre: 'Centrum sportowe',
      sports_hall: 'Hala sportowa',
      stadium: 'Stadion',
      swimming_pool: 'Basen',
      track: 'Tor',
      water_park: 'Park wodny',
    },

    man_made: {
      tower: {
        'tower:type': {
          bell_tower: 'Dzwonnica',
          communication: 'Wieża telekomunikacyjna',
          cooling: 'Wieża chłodnicza',
          observation: 'Wieża widokowa',
        },
        '*': 'Wieża',
      },
      '*': '{}',
      adit: 'Sztolnia',
      antenna: 'Antena',
      beacon: 'Latarnia',
      beehive: 'Ul',
      bridge: 'Most',
      bunker_silo: 'Silos bunkrowy',
      cairn: 'Stos kamieni',
      cellar_entrance: 'Wejście do piwnicy',
      chimney: 'Komin',
      clearcut: 'Wycinka',
      communications_tower: 'Wieża telekomunikacyjna',
      cooling_tower: 'Wieża chłodnicza',
      crane: 'Dźwig',
      cross: 'Krzyż',
      cutline: 'Linia wycinki',
      dyke: 'Wał przeciwpowodziowy',
      embankment: 'Nasyp',
      flagpole: 'Maszt flagowy',
      "forester's_lodge": 'Leśniczówka',
      gasometer: 'Gazomierz',
      goods_conveyor: 'Przenośnik towarów',
      groyne: 'Falochron',
      lighthouse: 'Latarnia morska',
      manhole: 'Wpust kanalizacyjny',
      mast: 'Maszt',
      mineshaft: 'Szyb kopalniany',
      monitoring_station: 'Stacja monitoringu',
      nesting_site: 'Miejsce gniazdowania',
      observatory: 'Obserwatorium',
      pier: 'Pirs',
      pipeline: 'Rurociąg',
      reservoir_covered: 'Zbiornik kryty',
      silo: 'Silos',
      snow_cannon: 'Armatka śnieżna',
      spoil_heap: 'Hałda odpadów',
      spring_box: 'Skrzynka źródlana',
      storage_tank: 'Zbiornik magazynowy',
      street_cabinet: 'Szafka uliczna',
      surveillance: 'Monitoring',
      survey_point: 'Punkt pomiarowy',
      telescope: 'Teleskop',
      utility_pole: 'Słup użyteczności publicznej',
      wastewater_plant: 'Oczyszczalnia ścieków',
      water_tap: 'Kran wodny',
      water_tower: 'Wieża ciśnień',
      water_well: 'Studnia',
      water_works: 'Ujęcie wody',
      watermill: 'Młyn wodny',
      windmill: 'Młyn wiatrowy',
      works: 'Zakład',
    },

    natural: {
      spring: {
        drinking_water: {
          yes: 'Źródło pitnej wody',
          no: 'Źródło nie do picia',
        },
        refitted: {
          yes: 'Przerobione źródło',
          no: 'Nieprzerobione źródło',
        },
        '*': 'Źródło',
      },
      tree: {
        protected: {
          yes: 'Drzewo chronione',
        },
        denotation: {
          natural_monument: 'Drzewo pomnikowe',
          landmark: 'Drzewo charakterystyczne',
          avenue: 'Drzewo alei',
          urban: 'Drzewo miejskie',
          agricultural: 'Drzewo gospodarcze',
        },
        '*': 'Drzewo',
      },
      '*': '{}',
      arch: 'Łuk skalny',
      bare_rock: 'Goła skała',
      basin: 'Kotlina',
      bay: 'Zatoka',
      beach: 'Plaża',
      birds_nest: 'Gniazdo ptaków',
      cave_entrance: 'Jaskinia',
      cliff: 'Skała',
      earth_bank: 'Nasyp ziemny',
      fell: 'Błotnisty teren',
      geyser: 'Gejzer',
      glacier: 'Lodowiec',
      grassland: 'Teren trawiasty',
      gully: 'Wąwóz',
      heath: 'Wrzosowisko',
      hot_spring: 'Gorące źródło',
      landslide: 'Osuwisko',
      mountain_range: 'Pasmo górskie',
      mud: 'Błoto',
      peak: 'Szczyt',
      plateau: 'Płaskowyż',
      ridge: 'Grzbiet',
      rock: 'Skała',
      saddle: 'Przełęcz',
      sand: 'Piasek',
      scree: 'Osuwisko skalne',
      scrub: 'Zarośla',
      shingle: 'Żwir',
      shrub: 'Krzew',
      sinkhole: 'Lej krasowy',
      stone: 'Kamień',
      tree_row: 'Szpaler drzew',
      valley: 'Dolina',
      water: 'Zbiornik wodny',
      wetland: 'Torfowisko',
      wood: 'Las',
    },

    place: {
      '*': 'Miejsce {}',
      city: 'Miasto',
      country: 'Kraj',
      farm: 'Gospodarstwo',
      hamlet: 'Przysiółek',
      island: 'Wyspa',
      islet: 'Wysepka',
      isolated_dwelling: 'Samotne gospodarstwo',
      locality: 'Miejscowość',
      ocean: 'Ocean',
      sea: 'Morze',
      square: 'Plac',
      state: 'Stan',
      suburb: 'Przedmieście',
      town: 'Miasteczko',
      village: 'Wieś',
    },

    power: {
      '*': '{}',
      generator: 'Generator',
      line: 'Linia energetyczna',
      minor_line: 'Mała linia energetyczna',
      plant: 'Elektrownia',
      pole: 'Słup energetyczny',
      substation: 'Stacja transformatorowa',
      tower: 'Wieża energetyczna',
      transformer: 'Transformator',
    },

    public_transport: {
      platform: 'Peron',
      station: 'Stacja',
      stop_position: 'Miejsce zatrzymania',
    },

    shop: {
      '*': 'Sklep {}',
      household_linen: 'Pościel domowa',
      charity: 'Sklep charytatywny',
      chocolate: 'Sklep z czekoladą',
      fashion_accessories: 'Sklep z akcesoriami modowymi',
      frozen_food: 'Sklep z mrożonkami',
      hearing_aids: 'Sklep z aparatami słuchowymi',
      weapons: 'Sklep z bronią',
      alcohol: 'Sklep z alkoholem',
      antiques: 'Antyki',
      art: 'Sklep z dziełami sztuki',
      baby_goods: 'Sklep dla niemowląt',
      bag: 'Sklep z torebkami',
      bakery: 'Piekarnia',
      bathroom_furnishing: 'Sklep z wyposażeniem łazienkowym',
      beauty: 'Sklep kosmetyczny',
      bed: 'Sklep z łóżkami',
      beverages: 'Sklep z napojami',
      bicycle: 'Sklep rowerowy',
      bookmaker: 'Zakłady bukmacherskie',
      books: 'Księgarnia',
      boutique: 'Butik',
      butcher: 'Rzeźnik',
      camera: 'Sklep fotograficzny',
      car: 'Salon samochodowy',
      car_parts: 'Części samochodowe',
      car_repair: 'Warsztat samochodowy',
      carpet: 'Sklep z dywanami',
      cheese: 'Sklep z serami',
      chemist: 'Drogeria',
      clothes: 'Sklep odzieżowy',
      coffee: 'Kawiarnia',
      collector: 'Sklep dla kolekcjonerów',
      computer: 'Sklep komputerowy',
      confectionery: 'Cukiernia',
      convenience: 'Sklep spożywczy',
      copyshop: 'Ksero',
      cosmetics: 'Drogeria kosmetyczna',
      craft: 'Sklep z artykułami rękodzielniczymi',
      curtain: 'Sklep z zasłonami',
      dairy: 'Sklep z nabiałem',
      deli: 'Delikatesy',
      department_store: 'Dom handlowy',
      doityourself: 'Sklep z narzędziami',
      doors: 'Sklep z drzwiami',
      dry_cleaning: 'Pralnia chemiczna',
      'e-cigarette': 'Sklep z e-papierosami',
      electrical: 'Sklep elektryczny',
      electronics: 'Sklep elektroniczny',
      erotic: 'Sklep erotyczny',
      fabric: 'Sklep z tkaninami',
      farm: 'Sklep na farmie',
      fireplace: 'Sklep z kominkami',
      fishing: 'Sklep wędkarski',
      flooring: 'Sklep z podłogami',
      florist: 'Kwiaciarnia',
      funeral_directors: 'Zakład pogrzebowy',
      furniture: 'Sklep meblowy',
      games: 'Sklep z grami',
      garden_center: 'Centrum ogrodnicze',
      garden_centre: 'Centrum ogrodnicze',
      general: 'Sklep ogólnospożywczy',
      gift: 'Sklep z upominkami',
      glaziery: 'Witrynarstwo',
      greengrocer: 'Sklep z owocami i warzywami',
      hairdresser: 'Fryzjer',
      hardware: 'Sklep z narzędziami',
      health_food: 'Sklep ze zdrową żywnością',
      hifi: 'Sklep Hi-Fi',
      houseware: 'Sklep z artykułami gospodarstwa domowego',
      hunting: 'Sklep myśliwski',
      ice_cream: 'Lodziarnia',
      interior_decoration: 'Sklep z dekoracjami wnętrz',
      jewelry: 'Jubiler',
      kiosk: 'Kiosk',
      kitchen: 'Sklep kuchenny',
      laundry: 'Pralnia',
      lighting: 'Sklep oświetleniowy',
      locksmith: 'Ślusarz',
      lottery: 'Salon gier losowych',
      mall: 'Centrum handlowe',
      massage: 'Salon masażu',
      medical_supply: 'Sklep medyczny',
      mobile_phone: 'Sklep z telefonami komórkowymi',
      model: 'Sklep modelarski',
      motorcycle: 'Sklep motocyklowy',
      music: 'Sklep muzyczny',
      musical_instrument: 'Sklep z instrumentami muzycznymi',
      newsagent: 'Kiosk z prasą',
      nutrition_supplements: 'Sklep z suplementami diety',
      optician: 'Optyk',
      outdoor: 'Sklep outdoorowy',
      outpost: 'Placówka',
      paint: 'Sklep z farbami',
      pastry: 'Cukiernia',
      pawnbroker: 'Lombard',
      perfumery: 'Perfumy',
      pet: 'Sklep zoologiczny',
      pet_grooming: 'Salon pielęgnacji zwierząt',
      photo: 'Sklep fotograficzny',
      radiotechnics: 'Sklep radiotechniczny',
      rental: 'Wypożyczalnia',
      seafood: 'Sklep z owocami morza',
      second_hand: 'Secondhand',
      sewing: 'Sklep krawiecki',
      shoes: 'Sklep obuwniczy',
      sports: 'Sklep sportowy',
      stationery: 'Papierniczy',
      supermarket: 'Supermarket',
      tailor: 'Krawiec',
      tattoo: 'Salon tatuażu',
      tea: 'Herbaciarnia',
      ticket: 'Sprzedaż biletów',
      tobacco: 'Sklep tytoniowy',
      toys: 'Sklep z zabawkami',
      trade: 'Sklep budowlany',
      travel_agency: 'Biuro podróży',
      tyres: 'Sklep z oponami',
      vacant: 'Wolny lokal',
      variety_store: 'Sklep wielobranżowy',
      video: 'Sklep wideo',
      video_games: 'Sklep z grami wideo',
      watches: 'Sklep z zegarkami',
      wholesale: 'Hurtownia',
      window_blind: 'Sklep z roletami',
      wine: 'Sklep z winem',
    },

    sport: {
      '*': 'Sport {}',
      australian_football: 'Football australijski',
      billiards: 'Bilard',
      boxing: 'Boks',
      cliff_diving: 'Skoki do wody z klifu',
      cricket: 'Krykiet',
      cricket_nets: 'Siatki do krykieta',
      croquet: 'Kroket',
      curling: 'Curling',
      gaelic_games: 'Gry gaelickie',
      horseshoes: 'Rzut podkową',
      korfball: 'Korfball',
      long_jump: 'Skok w dal',
      orienteering: 'Orientacja sportowa',
      paddle_tennis: 'Tenis paddle',
      pelota: 'Pelota',
      racquet: 'Rakieta',
      rc_car: 'Samochody RC',
      rugby: 'Rugby',
      rugby_league: 'Liga rugby',
      rugby_union: 'Unia rugby',
      sailing: 'Żeglarstwo',
      surfing: 'Surfing',
      table_soccer: 'Piłkarzyki',
      team_handball: 'Piłka ręczna',
      toboggan: 'Tobogan',
      '9pin': 'Kręgle 9-kołowe',
      '10pin': 'Kręgle 10-kołowe',
      aikido: 'Aikido',
      airsoft: 'Airsoft',
      american_football: 'Football amerykański',
      archery: 'Łucznictwo',
      athletics: 'Lekkoatletyka',
      badminton: 'Badminton',
      baseball: 'Baseball',
      basketball: 'Koszykówka',
      beachvolleyball: 'Siatkówka plażowa',
      bicycle: 'Kolarstwo',
      bmx: 'BMX',
      boules: 'Bulet',
      bowling: 'Kręgle',
      bowls: 'Bowls',
      canoe: 'Kajakarstwo',
      chess: 'Szachy',
      climbing: 'Wspinaczka',
      climbing_adventure: 'Przygoda wspinaczkowa',
      cycling: 'Kolarstwo',
      darts: 'Rzutki',
      disc_golf: 'Disc golf',
      dog_racing: 'Wyścigi psów',
      equestrian: 'Jeździectwo',
      field_hockey: 'Hokej na trawie',
      fitness: 'Fitness',
      floorball: 'Unihokej',
      free_flying: 'Lot swobodny',
      golf: 'Golf',
      gymnastics: 'Gimnastyka',
      handball: 'Piłka ręczna',
      hockey: 'Hokej',
      horse_racing: 'Wyścigi konne',
      ice_hockey: 'Hokej na lodzie',
      ice_skating: 'Łyżwiarstwo',
      judo: 'Judo',
      karate: 'Karate',
      karting: 'Karting',
      laser_tag: 'Laser tag',
      model_aerodrome: 'Modelarski aerodrom',
      motocross: 'Motocross',
      motor: 'Motorsport',
      multi: 'Wiele sportów',
      netball: 'Netball',
      paintball: 'Paintball',
      petanque: 'Petanque',
      roller_skating: 'Jazda na rolkach',
      rowing: 'Wioślarstwo',
      running: 'Bieganie',
      scuba_diving: 'Nurkowanie',
      shooting: 'Strzelectwo',
      shooting_range: 'Strzelnica',
      'shot-put': 'Pchnięcie kulą',
      skateboard: 'Skateboard',
      skating: 'Łyżwiarstwo',
      ski_jumping: 'Skoki narciarskie',
      skiing: 'Narciarstwo',
      soccer: 'Piłka nożna',
      squash: 'Squash',
      streetball: 'Streetball',
      swimming: 'Pływanie',
      table_tennis: 'Tenis stołowy',
      tennis: 'Tenis',
      volleyball: 'Siatkówka',
      water_ski: 'Narty wodne',
      workout: 'Trening',
      yoga: 'Joga',
    },

    tourism: {
      artwork: {
        artwork_type: {
          architecture: 'Architektura',
          bust: 'Popiersie',
          graffiti: 'Graffiti',
          installation: 'Instalacja artystyczna',
          mosaic: 'Mozaika',
          mural: 'Mural',
          painting: 'Obraz',
          relief: 'Płaskorzeźba',
          sculpture: 'Rzeźba',
          statue: 'Figura',
          stone: 'Głaz (dzieło sztuki)',
        },
        '*': 'Sztuka',
      },

      information: {
        information: {
          '*': 'Informacja {}',
          board: 'Tablica informacyjna',
          guidepost: 'Drogowskaz',
          map: 'Mapa',
          office: 'Biuro informacji',
        },
        '*': 'Informacja',
      },

      '*': '{}',

      alpine_hut: 'Schronisko górskie',
      apartment: 'Apartament',
      aquarium: 'Akwarium',
      attraction: 'Atrakcja',
      camp_site: 'Pole namiotowe',
      caravan_site: 'Miejsce dla przyczep kempingowych',
      chalet: 'Szałas',
      gallery: 'Galeria',
      guest_house: 'Pensjonat',
      hostel: 'Hostel',
      hotel: 'Hotel',
      motel: 'Motel',
      museum: 'Muzeum',
      picnic_site: 'Miejsce na piknik',
      viewpoint: 'Punkt widokowy',
      wilderness_hut: 'Szałas na odludziu',
      zoo: 'Zoo',
    },

    type: {
      route: {
        route: {
          '*': 'Szlak {}',
          bicycle: 'Szlak rowerowy',
          bus: 'Trasa autobusu',
          foot: 'Szlak pieszy',
          hiking: 'Szlak turystyczny',
          horse: 'Szlak jeździecki',
          mtb: 'Szlak rowerów górskich',
          piste: 'Stok narciarski lub ścieżka',
          railway: 'Linia kolejowa',
          ski: 'Trasa narciarska',
          tram: 'Trasa tramwajowa',
        },
        '*': 'Szlak',
      },
    },

    waterway: {
      '*': 'Droga wodna {}',
      canal: 'Kanał',
      dam: 'Zapora',
      ditch: 'Rów (droga wodna)',
      drain: 'Odpływ',
      river: 'Rzeka',
      stream: 'Strumień, potok',
      waterfall: 'Wodospad',
      weir: 'Próg wodny',
    },

    /* TODO translate; non-english translations:
     * cs: 'Lanovka, vlek'
     * hu: 'Felvonó, drótkötélpálya'
     * it: 'Via aerea, ascensore'
     * sk: 'Lanovka, vlek'
     * de: 'Seilbahn, Aufzug'
     */
    aerialway: 'Wyciąg linowy, kolejka',

    /* TODO translate; non-english translations:
     * cs: 'Železnice'
     * hu: 'Vasút'
     * it: 'Ferrovia'
     * sk: 'Železnica'
     * de: 'Eisenbahn'
     */
    railway: 'Kolej',
  };

export const colorNames: Record<string, string> = {
  red: 'Czerwona',
  blue: 'Niebieska',
  green: 'Zielona',
  yellow: 'Żółta',
  orange: 'Pomarańczowa',
  purple: 'Purpurowa',
  violet: 'Fioletowa',
  white: 'Biała',
  black: 'Czarna',
  gray: 'Szara',
  brown: 'Brązowa',
};
