import { DeepPartial } from '@shared/types/deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  aeroway: {
    aerodrome: 'Aereoporto',
    airstrip: 'Pista di atterraggio',
    apron: 'Piazzale aeromobili',
    gate: 'Gate aeroportuale',
    hangar: 'Hangar aeromobili',
    helipad: 'Eliporto',
    holding_position: 'Punto attesa aeromobili',
    jet_bridge: 'Pontile d’imbarco passeggeri',
    navigationaid: 'Aiuto alla navigazione aerea',
    parking_position: 'Posizione parcheggio aeromobili',
    runway: 'Pista',
    stopway: 'Stopway pista',
    taxilane: 'Corsia di rullaggio',
    taxiway: 'Via di rullaggio',
    terminal: 'Terminal aeroportuale',
    threshold: 'Soglia pista',
    tower: 'Torre di controllo',
    windsock: 'Manica a vento',
  },

  aerialway: {
    '*': 'Via aerea, ascensore',
    cable_car: 'Funivia',
    chair_lift: 'Seggiovia',
    goods: 'Funivia merci',
    'j-bar': 'Skilift a J',
    magic_carpet: 'Tappeto mobile',
    mixed_lift: 'Impianto misto',
    platter: 'Skilift a piattello',
    pylon: 'Pilone',
    rope_tow: 'Sciovia a fune',
    station: 'Stazione impianto',
    't-bar': 'Skilift a T',
    zip_line: 'Zipline',
  },

  amenity: {
    '*': '{}',
    animal_breeding: 'Allevamento',
    animal_shelter: 'Rifugio per animali',
    arts_centre: 'Centro artistico',
    atm: 'Bancomat',
    bank: 'Banca',
    bar: 'Bar',
    bbq: 'Griglia',
    bench: 'Panchina',
    bicycle_parking: 'Parcheggio bici',
    bicycle_rental: 'Noleggio bici',
    bicycle_repair_station: 'Meccanico bici',
    biergarten: 'Birreria',
    brothel: 'Bordello',
    bureau_de_change: 'Cambio valuta',
    bus_station: 'Stazione autobus',
    cafe: 'Caffè',
    car_rental: 'Noleggio auto',
    car_wash: 'Lavaggio auto',
    casino: 'Casinò',
    charging_station: 'Stazione di ricarica',
    childcare: 'Assistenza infantile',
    cinema: 'Cinema',
    clinic: 'Clinica',
    clock: 'Orologio',
    college: 'College',
    community_centre: 'Centro comunitario',
    compressed_air: 'Aria compressa',
    courthouse: 'Tribunale',
    dentist: 'Dentista',
    device_charging_station: 'Stazione ricarica dispositivi',
    doctors: 'Ambulatorio medico',
    dressing_room: 'Spogliatoio',
    drinking_water: 'Acqua potabile',
    driving_school: 'Scuola guida',
    embassy: 'Ambasciata',
    events_venue: 'Luogo per eventi',
    fast_food: 'Fast food',
    feeding_place: 'Mangiatoia',
    ferry_terminal: 'Terminal traghetti',
    fire_station: 'Caserma Pompieri',
    food_court: 'Ristoro',
    fountain: 'Fontana',
    fuel: 'Stazione Gas',
    funeral_hall: 'Casa del commiato',
    gambling: 'Gioco azzardo',
    game_feeding: 'Gioco alimentazione',
    grave_yard: 'Cimitero',
    grit_bin: 'Pattumiera',
    hospital: 'Ospedale',
    hunting_stand: 'Supporto da caccia',
    ice_cream: 'Gelati',
    kindergarten: 'Scuola materna',
    language_school: 'Scuola di lingue',
    library: 'Biblioteca',
    marketplace: 'Mercato',
    monastery: 'Monastero',
    money_transfer: 'Transazioni denaro',
    motorcycle_parking: 'Parcheggio motocicli',
    motorcycle_rental: 'Noleggio motocicli',
    nightclub: 'Nightclub',
    parcel_locker: 'Parcel locker',
    parking: 'Parcheggio',
    parking_entrance: 'Entrata parcheggio',
    parking_space: 'Area di parcheggio',
    pharmacy: 'Farmacia',
    place_of_mourning: 'Luogo di lutto',
    place_of_worship: 'Luogo di culto',
    planetarium: 'Planetario',
    police: 'Polizia',
    post_box: 'Casella postale',
    post_office: 'Ufficio postale',
    prison: 'Prigione',
    pub: 'Pub',
    public_bookcase: 'Libreria pubblica',
    ranger_station: 'Stazione Ranger',
    recycling: 'Raccolta differenziata',
    restaurant: 'Ristorante',
    school: 'Scuola',
    shelter: {
      '*': 'Riparo',
      shelter_type: {
        '*': 'Shelter {}',
        basic_hut: 'Tettoia',
        changing_rooms: 'Spogliatoi',
        field_shelter: 'Rifugio da campo',
        lean_to: 'Appoggiato a',
        picnic_shelter: {
          '*': 'Tettoia per picnic',
          fireplace: {
            yes: 'Riparo da picnic con camino',
          },
        },
        public_transport: 'Ricovero mezzi pubblici',
        rock_shelter: 'Riparo roccioso',
        sun_shelter: 'Riparo dal sole',
        weather_shelter: 'Rifugio meteorologico',
      },
    },
    shower: 'Doccia',
    ski_rental: 'Noleggio sci',
    smoking_area: 'Area fumatori',
    social_centre: 'Centro sociale',
    social_facility: {
      '*': 'Struttura sociale',
      social_facility: {
        // dairy_kitchen: 'Cucina casearia',
        // outreach: 'Sensibilizzazione',
        ambulatory_care: 'Ambulatorio di cura',
        assisted_living: 'Assistenza vita',
        clothing_bank: 'Banca abbigliamento',
        day_care: 'Asilo nido',
        food_bank: 'Banca del cibo',
        group_home: 'Casa di accoglienza',
        hospice: 'Ospizio',
        nursing_home: 'Casa di riposo',
        shelter: 'Riparo',
        soup_kitchen: 'Mensa per i poveri',
        workshop: 'Officina',
      },
    },
    stripclub: 'Spogliarello',
    studio: 'Studio',
    taxi: 'Taxi',
    telephone: 'Telefono',
    theatre: 'Teatro',
    toilets: 'WC',
    townhall: 'Municipio',
    traffic_park: 'Parco del traffico',
    trolley_bay: 'Trolley',
    university: 'Università',
    vacuum_cleaner: 'Aspirapolvere',
    vehicle_inspection: 'Controllo veicolo',
    vending_machine: {
      '*': 'Distributore Automatico',
      vending: {
        bicycle_tube: "Distributore di camere d'aria per biciclette",
        bread: 'Distributore di pane',
        bottle_return: 'Macchina per il reso delle bottiglie',
        candles: 'Distributore di candele',
        chewing_gums: 'Distributore di gomme da masticare',
        cigarettes: 'Distributore di sigarette',
        coffee: 'Distributore di caffè',
        condoms: 'Distributore di preservativi',
        drinks: 'Distributore di bevande',
        elongated_coin: 'Macchina per monete souvenir',
        eggs: 'Distributore di uova',
        excrement_bags: 'Dispenser di sacchetti per escrementi',
        food: 'Distributore di cibo',
        fuel: 'Distributore di carburante',
        gas: 'Distributore di carburante',
        ice_cream: 'Distributore di gelati',
        ice_cubes: 'Distributore di cubetti di ghiaccio',
        milk: 'Distributore di latte',
        movies: 'Distributore di film',
        newspapers: 'Distributore di giornali',
        parking_tickets: 'Parcometro',
        pizza: 'Distributore di pizza',
        public_transport_tickets:
          'Distributore di biglietti per i trasporti pubblici',
        stamps: 'Distributore di francobolli',
        sweets: 'Distributore di dolci',
        water: 'Distributore di acqua',
      },
    },
    veterinary: 'Veterinario',
    waste_basket: 'Cassonetto',
    waste_disposal: 'Smaltimento rifiuti',
    water_point: 'Punto Acqua',
    watering_place: 'Abbeveratoio',
  },

  barrier: {
    '*': 'Barrier {}',
    block: 'Blocco',
    bollard: 'Dissuasore',
    border_control: 'Controllo di frontiera',
    cable_barrier: 'Barriera cavi',
    chain: 'Catena',
    city_wall: 'Mura cittadine',
    ditch: 'Fossato',
    entrance: 'Entrata',
    fence: 'Recinzione',
    gate: 'Cancello',
    guard_rail: 'Guardrail',
    handrail: 'Corrimano',
    hedge: 'Siepe',
    kerb: 'Cordolo',
    lift_gate: 'Ascensore',
    rope: 'Corda',
    sliding_gate: 'Cancello scorrevole',
    swing_gate: 'Cancello a battente',
    turnstile: 'Tornello',
    wall: 'Muro',
    retaining_wall: 'Muro di contenimento',
  },

  boundary: {
    '*': 'Regione',
    administrative: {
      '*': 'Regione Amministrativa',
      admin_level: {
        '2': 'Stato',
        '3': 'Regione',
        '4': 'Distretto',
        '5': 'Provincia',
        '6': 'Città',
        '7': 'Regione',
        '8': 'Distretto',
        '9': 'Villaggio',
        '10': 'Regione catastale',
      },
    },
    marker: 'Cippo di confine',
    national_park: 'Parco Nazionale',
    protected_area: 'Area Protetta',
  },

  building: {
    '*': {
      '*': 'Edificio {}',

      abandoned: {
        yes: 'Edificio abbandonato',
      },

      disused: {
        yes: 'Edificio dismesso',
      },

      ruins: {
        yes: 'Rovine di edificio',
      },
    },

    apartments: 'Condominio',
    barn: 'Fienile',
    bungalow: 'Bungalow',
    bunker: 'Bunker',
    cabin: 'Cabina',
    cathedral: 'Cattedrale',
    chapel: 'Cappella',
    church: 'Chiesa',
    civic: 'Palazzo civico',
    collapsed: 'Edificio crollato',
    commercial: 'Edificio commerciale',
    construction: 'Edificio in costruzione',
    cowshed: 'Stalla',
    detached: 'Casa indipendente',
    dormitory: 'Dormitorio',
    entrance: 'Ingresso edificio',
    farm_auxiliary: 'Fabbricato agricolo ausiliario',
    farm: 'Azienda agricola',
    garage: 'Garage',
    garages: 'Garage',
    government: 'Edificio governativo',
    grandstand: 'Tribuna',
    greenhouse: 'Serra',
    hangar: 'Hangar',
    hayloft: 'Fienile',
    hospital: 'Edificio ospedaliero',
    hotel: 'Edificio alberghiero',
    house: 'Casa privata',
    houseboat: 'Casa galleggiante',
    hut: 'Capanna',
    industrial: 'Edificio industriale',
    kindergarten: "Edificio dell'asilo",
    kiosk: 'Chiosco',
    manufacture: 'Manifattura',
    mosque: 'Moschea',
    office: 'Ufficio',
    parking: 'Parcheggio',
    public: 'Edificio pubblico',
    residential: 'Casa residenziale',
    retail: 'Rivendita',
    roof: 'Tetto',
    ruins: 'Rovine di edifici',
    school: 'Scuola',
    semidetached_house: 'Casa bifamiliare',
    service: 'Edificio di servizio',
    shed: 'Capannone',
    shrine: 'Altare',
    stable: 'Stalla',
    static_caravan: 'Casa mobile',
    storage_tank: 'Serbatoio di stoccaggio',
    sty: 'Porcile',
    supermarket: 'Supermercato',
    synagogue: 'Sinagoga',
    temple: 'Tempio',
    terrace: 'Terrazza',
    train_station: 'Stazione dei treni',
    transformer_tower: 'Torre di trasformazione',
    transportation: 'Trasporti',
    university: 'Università',
    warehouse: 'Magazzino',
    yes: 'Indeterminato',
    abandoned: 'Edificio abbandonato',
    disused: 'Edificio dismesso',
    stadium: 'Edificio stadio',
  },

  highway: {
    '*': 'Strada {}',
    bus_stop: 'Fermata autobus',
    construction: 'Strada in costruzione',
    crossing: 'Attraversamento pedonale',
    cycleway: 'Pista ciclabile',
    footway: 'Marciapiedi',
    living_street: 'Strada residenziale',
    motorway: 'Autostrada',
    motorway_link: 'Collegamento autostradale',

    path: {
      '*': 'Sentiero',

      foot: {
        designated: {
          bicycle: {
            designated: 'Percorso condiviso pedoni e biciclette',
          },
        },
      },
    },

    pedestrian: 'Zona pedonale',
    primary: 'Strada primaria',
    primary_link: 'Collegamento strada primaria',
    residential: 'Strada',
    secondary: 'Strada secondaria',
    secondaty_link: 'Collegamento strada secondaria',

    service: {
      '*': 'Servizio stradale',
      service: {
        '*': 'Strada di servizio {}',
        alley: 'Vicolo',
        bus: 'Strada autobus',
        'drive-through': 'percorribile in auto',
        driveway: 'Viale',
        emergency_access: 'Accesso di emergenza',
        parking_aisle: 'Corridoio di parcheggio',
      },
    },

    steps: 'Scale',
    street_lamp: 'Lampione',
    tertiary: 'Strada terziaria',
    tertiary_link: 'Collegamento strada terziaria',

    track: {
      '*': 'Strada forestale',
      tracktype: {
        grade1: 'Strada forestale compattata',
        grade2: 'Strada forestale prevalentemente compattata',
        grade3: 'Strada forestale sterrata',
        grade4: 'Strada forestale percorribile con trattore o similari',
        grade5: 'Strada forestale poco distinguibile',
      },
    },

    trunk: 'Strada principale',
    trunk_link: 'Collegamento strada principale',
    unclassified: 'Strada minore/non classificata',
    bridleway: 'Percorso equestre',
    piste: 'Pista',
    platform: 'Banchina',
    raceway: 'Circuito',
    road: 'Strada di tipo sconosciuto',
    via_ferrata: 'Via ferrata',
  },

  historic: {
    '*': 'Struttura storica',
    archaeological_site: 'Sito archeologico',
    castle: 'Castello',
    church: 'Chiesa storica',
    city_gate: 'Porta della città',
    manor: 'Maniero',
    memorial: 'Memoriale',
    monastery: 'Monastero',
    monument: 'Monumento',

    ruins: {
      '*': 'Rovine',
      ruins: {
        castle: 'Rovine Castello',
      },
    },

    tomb: 'Tomba',
    wayside_cross: 'Croce lungo la strada',
    wayside_shrine: 'Altare lungo la strada',
    aircraft: 'Aeromobile storico',
    boundary_stone: 'Cippo di confine storico',
    building: 'Edificio storico',
    cannon: 'Cannone storico',
    charcoal_pile: 'Sito carbonaia',
    citywalls: 'Mura cittadine',
    fort: 'Forte',
    heritage: 'Sito del patrimonio',
    hollow_way: 'Strada incavata',
    house: 'Casa storica',
    milestone: 'Miliario storico',
    mine: 'Miniera storica',
    mine_shaft: 'Pozzo minerario storico',
    shieling: 'Capanna stagionale di montagna',
    stone: 'Pietra storica',
    tree_shrine: 'Santuario arboreo',
    wreck: 'Relitto',
    yes: 'Struttura storica',
  },

  landuse: {
    '*': '{}',
    allotments: 'Lottizzazioni',
    basin: 'Serbatoio di raccolta',
    brownfield: 'Terreno dismesso',
    cemetery: 'Cimitero',
    commercial: 'Commerciale',
    construction: 'Costruzione',
    education: 'Zona scolastica',
    farmland: 'Terreno agricolo',
    farmyard: 'Aia',
    forest: 'Foresta',
    garages: 'Garage',
    grass: 'Erba',
    greenfield: 'Terreno edificabile',
    industrial: 'Industriale',
    landfill: 'Discarica',
    meadow: 'Prateria',
    military: 'Area militare',
    orchard: 'Frutteto',
    plant_nursery: 'Vivaio',
    quarry: 'Cava',
    recreation_ground: 'Terreno ricreativo',
    religions: 'Area religiosa',
    reservoir: 'Serbatoio',
    residential: 'Residenziale',
    retail: 'Rivendita',
    vineyard: 'Vigneto',
    winter_sports: 'Sport invernali',
    pedestrian: 'Area pedonale',
    railway: 'Area ferroviaria',
    village_green: 'Prato del villaggio',
  },

  leisure: {
    '*': '{}',
    bleachers: 'Gradinate',
    escape_game: 'Gioco di fuga',
    hackerspace: 'Hackerspace',
    ice_rink: 'Pista di ghiaccio',
    marina: 'Marina',
    miniature_golf: 'Minigolf',
    dog_park: 'Area per cani',
    firepit: 'Focolare',
    fishing: 'Pesca',
    fitness_centre: 'Centro sportivo',
    fitness_station: 'Stazione sportiva',
    garden: 'Giardino',
    golf_course: 'Campo di Golf',
    horse_riding: 'Maneggio',
    nature_reserve: 'Riserva Naturale',
    park: 'Parco',

    picnic_table: {
      '*': 'Tavolo da Picnic',
      covered: {
        yes: 'covered Tavolo da Picnic',
        no: 'Tavolo da picnic scoperto',
      },
    },

    pitch: 'Campo sportivo',
    playground: 'Terreno di gioco',
    sports_centre: 'Centro sportivo',
    sports_hall: 'Palazzetto dello Sport',
    stadium: 'Stadio',
    swimming_pool: 'Piscina',
    track: 'Pista',
    water_park: 'Parco acquatico',
    adult_gaming_centre: 'Sala giochi per adulti',
    amusement_arcade: 'Sala giochi',
    bandstand: 'Chiosco per banda',
    bathing_place: 'Luogo balneabile',
    beach_resort: 'Stabilimento balneare',
    bird_hide: 'Osservatorio ornitologico',
    bowling_alley: 'Pista da bowling',
    dance: 'Spazio danza',
    disc_golf_course: 'Campo da disc golf',
    high_ropes_course: 'Percorso avventura',
    outdoor_seating: 'Posti a sedere all’aperto',
    resort: 'Resort ricreativo',

    sauna: {
      '*': 'Sauna',

      sauna: {
        aroma: 'Sauna aromatica',
        dry: 'Sauna secca',
        hanjeungmak: 'Hanjeungmak (sauna coreana)',
        hot: 'Sauna finlandese',
        infrared: 'Sauna a infrarossi',
        smoke: 'Sauna a fumo (finlandese)',
        steam: 'Bagno turco (sauna a vapore)',
      },
    },

    slipway: 'Scivolo per barche',
    summer_camp: 'Campo estivo',
    sunbathing: 'Area prendisole',
    swimming_area: 'Area balneazione',
    tanning_salon: 'Centro abbronzatura',
    trampoline_park: 'Parco trampolini',
    wildlife_hide: 'Osservatorio fauna selvatica',
  },

  man_made: {
    '*': '{}',

    adit: {
      '*': 'Ingresso',

      disused: {
        yes: 'Galleria mineraria dismessa',
      },
    },

    antenna: 'Antenna',
    beacon: 'Faro',
    beehive: 'Alveare',
    bridge: 'Ponte',
    bunker_silo: 'Silos',
    cairn: 'Ometto',
    cellar_entrance: 'Ingresso cantina',
    chimney: 'Ciminiera',
    clearcut: 'Area disboscata',
    communications_tower: 'Torre telecomunicazioni',
    cooling_tower: 'Torre di raffreddamento',
    crane: 'Gru',
    cross: 'Croce',
    cutline: 'Linea disboscata',
    dyke: 'Diga',
    embankment: 'Terrapieno',
    flagpole: 'Bandiera',
    "forester's_lodge": 'Caserma forestale',
    gasometer: 'Gasometro',
    goods_conveyor: 'Nastro trasportatore',
    groyne: 'Pali marini',
    lighthouse: 'Faro',
    manhole: 'Tombino',

    mast: {
      '*': 'Antenna',

      'tower:type': {
        clock: 'Traliccio con orologio',
        communication: 'Traliccio telecomunicazioni',
        lighting: 'Traliccio illuminazione',
        monitoring: 'Traliccio monitoraggio',
        radar: 'Traliccio radar',
        siren: 'Traliccio con sirena',
      },
    },

    mineshaft: {
      '*': 'Miniera',

      disused: {
        yes: 'Pozzo minerario dismesso',
      },
    },

    monitoring_station: 'Stazione di monitoraggio',
    nesting_site: 'Sito di nidificazione',
    observatory: 'Osservatorio',
    pier: 'Molo',

    pipeline: {
      '*': 'Tubatura',

      location: {
        underground: 'Condotta sotterranea',
        underwater: 'Condotta sottomarina',
      },
    },

    reservoir_covered: 'Serbatoio coperto',
    silo: 'Silo',
    snow_cannon: 'Cannone sparaneve',
    spoil_heap: 'Ammasso di detriti',
    spring_box: 'Scatola sorgente',
    storage_tank: 'Serbatoio di stoccaggio',
    street_cabinet: 'Armadio di derivazione',
    surveillance: 'Sorveglianza',
    survey_point: 'Punto trigonometrico',
    telescope: 'Telescopio',

    tower: {
      '*': 'Torre',
      'tower:type': {
        bell_tower: 'Torre campanaria',
        communication: 'Torre telecomunicazioni',
        cooling: 'Torre di raffreddamento',
        observation: 'Torre di osservazione',
        climbing: 'Torre di arrampicata',
        clock: 'Torre dell’orologio',
        defensive: 'Torre difensiva',
        diving: 'Torre per tuffi',
        hose: 'Torre asciugatura manichette',
        lighting: 'Torre illuminazione',
        minaret: 'Minareto',
        monitoring: 'Torre monitoraggio',
        pagoda: 'Torre pagoda',
        radar: 'Torre radar',
        siren: 'Torre con sirena',
        watchtower: 'Torre di guardia',
      },
    },

    utility_pole: 'Polo di utilità',
    wastewater_plant: 'Impianto acque reflue',
    water_tap: 'Rubinetto',
    water_tower: 'Torre acquedotto',
    water_well: 'Pozzo',
    water_works: 'Lavori idrici',
    watermill: 'Mulino ad acqua',
    windmill: 'Mulino a vento',
    works: 'Fabbrica',
    apiary: 'Apiario',
    pumping_station: 'Stazione di pompaggio',
  },

  natural: {
    '*': '{}',
    arch: 'Arco di pietra',
    bare_rock: 'Roccia nuda',
    basin: 'Bacino',
    bay: 'Baia',
    beach: 'Spiaggia',
    birds_nest: 'Nido',
    cave_entrance: 'Grotta',
    cliff: 'Scogliera',
    earth_bank: 'Calanchi',
    fell: 'Prateria montana',
    geyser: 'Geyser',
    glacier: 'Ghiacciaio',
    grassland: 'Prateria',
    gully: 'Canalone',
    heath: 'Brughiera',
    hot_spring: 'Sorgente calda',
    landslide: 'Frana',
    mountain_range: 'Catena montuosa',
    mud: 'Fango',
    peak: 'Vetta',
    plateau: 'Altopiano',
    ridge: 'Cresta',
    rock: 'Roccia',
    saddle: 'Sella',
    sand: 'Sabbia',
    scree: 'Ghiaione',
    scrub: 'Boscaglia',
    shingle: 'Sassi',
    shrub: 'Arbusto',
    sinkhole: 'Dolina',
    spring: {
      '*': 'Sorgente',

      drinking_water: {
        yes: 'Acqua potabile',
        no: 'Acqua non potabile',
      },

      refitted: {
        yes: 'Rettificata',
        no: 'Non rettificata',
      },

      intermittent: {
        yes: 'Sorgente intermittente',
      },

      seasonal: {
        yes: 'Sorgente stagionale',
      },

      water_characteristic: {
        '*': 'Sorgente minerale',
      },
    },
    stone: 'Pietra',
    tree: {
      '*': 'Albero',
      protected: {
        yes: 'Albero protetto',
      },
      denotation: {
        natural_monument: 'Albero monumentale naturale',
        landmark: 'Albero di riferimento',
        avenue: 'Albero di viale',
        urban: 'Albero urbano',
        agricultural: 'Albero agricolo',
      },
    },

    tree_row: 'Filare alberi',
    valley: 'Valle',
    water: 'Acqua',
    wetland: {
      '*': 'Zona umida',
      wetland: {
        bog: 'Torbiera alta',
        fen: 'Torbiera bassa',
        mangrove: 'Mangrovia',
        marsh: 'Palude',
        reedbed: 'Canneto',
        swamp: 'Pantano',
        wet_meadow: 'Prato umido',
      },
    },
    wood: 'Foresta',
  },

  place: {
    '*': 'Luogo {}',
    city: 'Città',
    country: 'Nazione',
    farm: 'Fattoria',
    hamlet: 'Borgo',
    island: 'Isola',
    islet: 'Isolotto',
    isolated_dwelling: 'Abitazione isolata',
    locality: 'Località',
    ocean: 'Oceano',
    sea: 'Mare',
    square: 'Piazza',
    state: 'Stato',
    suburb: 'Sobborgo',
    town: 'Paese',
    village: 'Villaggio',
  },

  power: {
    '*': '{}',
    generator: {
      '*': 'Generatore',

      'generator:source': {
        biofuel: {
          '*': 'Generatore elettrico a biocarburante',
        },

        biogas: {
          '*': 'Generatore elettrico a biogas',
        },

        biomass: {
          '*': 'Generatore elettrico a biomassa',

          'generator:method': {
            anaerobic_digestion:
              'Generatore elettrico da digestione anaerobica della biomassa',
            combustion: 'Generatore elettrico a combustione di biomassa',
            gasification: 'Generatore elettrico a gassificazione di biomassa',
          },
        },

        coal: {
          '*': 'Generatore elettrico a carbone',
        },

        diesel: {
          '*': 'Generatore elettrico diesel',
        },

        gas: {
          '*': 'Generatore elettrico a gas',
        },

        gasoline: {
          '*': 'Generatore elettrico a benzina',
        },

        geothermal: {
          '*': 'Generatore elettrico geotermico',
        },

        hydro: {
          '*': 'Generatore idroelettrico',

          'generator:method': {
            'run-of-the-river': 'Generatore idroelettrico ad acqua fluente',
            'water-pumped-storage': 'Generatore idroelettrico a pompaggio',
            'water-storage': 'Generatore idroelettrico a bacino',
          },
        },

        nuclear: {
          '*': 'Generatore elettrico nucleare',

          'generator:method': {
            fission: 'Generatore elettrico nucleare a fissione',
            fusion: 'Generatore elettrico nucleare a fusione',
          },
        },

        oil: {
          '*': 'Generatore elettrico a olio combustibile',
        },

        solar: {
          '*': 'Generatore elettrico solare',

          'generator:method': {
            photovoltaic: 'Generatore elettrico solare fotovoltaico',
            thermal: 'Generatore elettrico solare termico',
          },
        },

        tidal: {
          '*': 'Generatore elettrico da marea',

          'generator:method': {
            barrage: 'Generatore elettrico da sbarramento di marea',
            stream: 'Generatore elettrico da correnti di marea',
          },
        },

        waste: {
          '*': 'Generatore elettrico da rifiuti',

          'generator:method': {
            combustion: 'Generatore elettrico da combustione rifiuti',
            gasification: 'Generatore elettrico da gassificazione rifiuti',
          },
        },

        wave: {
          '*': 'Generatore elettrico da onde',
        },

        wind: {
          '*': 'Generatore elettrico eolico',
        },
      },
    },
    line: 'Linea elettrica',
    minor_line: 'Linea elettrica minore',
    plant: {
      '*': 'Centrale',

      'plant:source': {
        biofuel: {
          '*': 'Centrale a biocarburante',
        },

        biogas: {
          '*': 'Centrale a biogas',
        },

        biomass: {
          '*': 'Centrale a biomassa',

          'plant:method': {
            anaerobic_digestion:
              'Centrale a biomassa con digestione anaerobica',
            combustion: 'Centrale a biomassa con combustione',
            gasification: 'Centrale a biomassa con gassificazione',
          },
        },

        coal: {
          '*': 'Centrale a carbone',
        },

        diesel: {
          '*': 'Centrale diesel',
        },

        gas: {
          '*': 'Centrale a gas',
        },

        gasoline: {
          '*': 'Centrale a benzina',
        },

        geothermal: {
          '*': 'Centrale geotermica',
        },

        hydro: {
          '*': 'Centrale idroelettrica',

          'plant:method': {
            'run-of-the-river': 'Centrale idroelettrica ad acqua fluente',
            'water-pumped-storage': 'Centrale idroelettrica a pompaggio',
            'water-storage': 'Centrale idroelettrica a bacino',
          },
        },

        nuclear: {
          '*': 'Centrale nucleare',

          'plant:method': {
            fission: 'Centrale nucleare a fissione',
            fusion: 'Centrale nucleare a fusione',
          },
        },

        oil: {
          '*': 'Centrale a olio combustibile',
        },

        solar: {
          '*': 'Centrale solare',

          'plant:method': {
            photovoltaic: 'Centrale solare fotovoltaica',
            thermal: 'Centrale solare termica',
          },
        },

        tidal: {
          '*': 'Centrale mareomotrice',

          'plant:method': {
            barrage: 'Centrale mareomotrice a sbarramento',
            stream: 'Centrale mareomotrice a correnti',
          },
        },

        waste: {
          '*': 'Centrale da rifiuti',

          'plant:method': {
            combustion: 'Centrale da combustione rifiuti',
            gasification: 'Centrale da gassificazione rifiuti',
          },
        },

        wave: {
          '*': 'Centrale da energia ondosa',
        },

        wind: {
          '*': 'Centrale eolica',
        },
      },
    },
    pole: 'Polo di alimentazione',
    substation: 'Sottostazione',
    tower: 'Torre di potenza',
    transformer: 'Transformatore',
  },

  public_transport: {
    platform: 'Piattaforma',
    station: 'Stazione',
    stop_position: 'Punto di stop',
  },

  railway: {
    '*': 'Ferrovia',
    abandoned: 'Ferrovia abbandonata',
    buffer_stop: 'Paraurti ferroviario',
    construction: 'Ferrovia in costruzione',
    crossing: 'Attraversamento binari',
    derail: 'Dispositivo deragliatore',
    disused: 'Ferrovia dismessa',
    funicular: 'Funicolare',
    halt: 'Fermata ferroviaria',
    level_crossing: 'Passaggio a livello',
    light_rail: 'Metropolitana leggera',
    miniature: 'Ferrovia in miniatura',
    monorail: 'Monorotaia',
    narrow_gauge: 'Ferrovia a scartamento ridotto',
    platform: 'Banchina ferroviaria',
    preserved: 'Ferrovia storica',
    proposed: 'Ferrovia proposta',
    rail: 'Linea ferroviaria',
    railway_crossing: 'Attraversamento ferroviario',
    roundhouse: 'Rimessa circolare ferroviaria',
    signal: 'Segnale ferroviario',
    station: 'Stazione ferroviaria',
    stop: 'Fermata ferroviaria',
    subway: 'Linea metropolitana',
    subway_entrance: 'Ingresso metropolitana',
    switch: 'Scambio ferroviario',
    tram: 'Linea tranviaria',
    tram_stop: 'Fermata tram',
    traverser: 'Traslatore ferroviario',
    turntable: 'Piattaforma girevole ferroviaria',
    ventilation_shaft: 'Pozzo ventilazione ferroviario',
    wash: 'Lavaggio treni',
    water_crane: 'Colonna idrica ferroviaria',
    workshop: 'Officina ferroviaria',
  },

  shop: {
    '*': 'Negozio {}',
    household_linen: 'Casa biancheria',
    charity: 'Negozio di Beneficenza',
    chocolate: 'Negozio di Cioccolato',
    fashion_accessories: 'Negozio di Accessori Moda',
    frozen_food: 'Negozio di Alimenti Surgelati',
    hearing_aids: 'Negozio di Apparecchi Acustici',
    weapons: 'Negozio di Armi',
    alcohol: 'Alcolici',
    antiques: 'Antiquariato',
    art: 'Arti',
    baby_goods: 'Oggetti per bambini',
    bag: 'Borse',
    bakery: 'Forno',
    bathroom_furnishing: 'Arredo bagno',
    beauty: 'Cosmetici',
    bed: 'Letti',
    beverages: 'Bevande',
    bicycle: 'Biciclette',
    bookmaker: 'Bookmaker',
    books: 'Libri',
    boutique: 'Boutique',
    butcher: 'Macelleria',
    camera: 'Fotografia',
    car: 'Automobili',
    car_parts: 'Ricambi auto',
    car_repair: 'Riparazione auto',
    carpet: 'Tappeti',
    cheese: 'Formaggi',
    chemist: 'Farmacia',
    clothes: 'Abbigliamento',
    coffee: 'Caffè',
    collector: 'Collezionista',
    computer: 'Computer',
    confectionery: 'Confetteria',
    convenience: 'Minimarket',
    copyshop: 'Copisteria',
    cosmetics: 'Cosmetici',
    craft: 'Artigianato',
    curtain: 'Tende',
    dairy: 'Latticini',
    deli: 'Gastronomia',
    department_store: 'Grande magazzino',
    doityourself: 'Fai-da-te',
    doors: 'Porte',
    dry_cleaning: 'Lavaggio a secco',
    'e-cigarette': 'Sigarette elettroniche',
    electrical: 'Materiale elettrico',
    electronics: 'Elettronica',
    erotic: 'Sex shop',
    fabric: 'Tessili',
    farm: 'Negozio fattoria',
    fireplace: 'Caminetti',
    fishing: 'Pesca',
    flooring: 'Pavimenti',
    florist: 'Fioraio',
    funeral_directors: 'Servizi funebri',
    furniture: 'Arredamento',
    games: 'Giochi',
    garden_center: 'Giardinaggio',
    garden_centre: 'Giardinaggio',
    general: 'Negozio generico',
    gift: 'Articoli da regalo',
    glaziery: 'Vetreria',
    greengrocer: 'Frutta e verdura',
    hairdresser: 'Parrucchiere',
    hardware: 'Ferramenta',
    health_food: 'Cibi sani',
    hifi: 'Hi-Fi',
    houseware: 'Casalinghi',
    hunting: 'Caccia',
    ice_cream: 'Gelati',
    interior_decoration: 'Decorazione di interni',
    jewelry: 'Gioielleria',
    kiosk: 'Chiosco',
    kitchen: 'Cucine',
    laundry: 'Lavanderia',
    lighting: 'Illuminazione',
    locksmith: 'Fabbro',
    lottery: 'Lotteria',
    mall: 'Centro commerciale',
    massage: 'Massaggi',
    medical_supply: 'Forniture mediche',
    mobile_phone: 'Cellulari',
    model: 'Modellismo',
    motorcycle: 'Motocicli',
    music: 'Musica',
    musical_instrument: 'Strumenti musicali',
    newsagent: 'Giornalaio',
    nutrition_supplements: 'Integratori alimentari',
    optician: 'Ottica',
    outdoor: 'Outdoor',
    outpost: 'Avamposto',
    paint: 'Pittura',
    pastry: 'Pasticceria',
    pawnbroker: 'Pegni',
    perfumery: 'Profumeria',
    pet: 'Animali domestici',
    pet_grooming: 'Tolettatura',
    photo: 'Fotografo',
    radiotechnics: 'Radiotecnica',
    rental: 'Noleggio',
    seafood: 'Frutti di mare',
    second_hand: 'Usato',
    sewing: 'Cucito',
    shoes: 'Scarpe',
    sports: 'Sport',
    stationery: 'Cartoleria',
    supermarket: 'Supermercato',
    tailor: 'Sartoria',
    tattoo: 'Tatuaggi',
    tea: 'Tea shop',
    ticket: 'Biglietteria',
    tobacco: 'Tabacchi',
    toys: 'Giocattoli',
    trade: 'Materiali edili',
    travel_agency: 'Agenzia di viaggio',
    tyres: 'Pneumatici',
    vacant: 'Negozio libero',
    variety_store: 'Varietà',
    video: 'Video',
    video_games: 'Videogames',
    watches: 'Orologi',
    wholesale: 'Ingrosso',
    window_blind: 'Tende da finestra',
    wine: 'Vini',
  },

  sport: {
    '*': 'Sport {}',
    australian_football: 'Football australiano',
    billiards: 'Biliardo',
    boxing: 'Boxe',
    cliff_diving: 'Tuffi da scogliera',
    cricket: 'Cricket',
    cricket_nets: 'Reti per cricket',
    croquet: 'Croquet',
    curling: 'Curling',
    gaelic_games: 'Giochi gaelici',
    horseshoes: 'Ferri di cavallo',
    korfball: 'Korfball',
    long_jump: 'Salto in lungo',
    orienteering: 'Orientamento',
    paddle_tennis: 'Paddle tennis',
    pelota: 'Pelota',
    racquet: 'Racchetta',
    rc_car: 'Auto RC',
    rugby: 'Rugby',
    rugby_league: 'Rugby a 13',
    rugby_union: 'Rugby a 15',
    sailing: 'Vela',
    surfing: 'Surf',
    table_soccer: 'Calcio balilla',
    team_handball: 'Pallamano',
    toboggan: 'Slitta',
    '9pin': 'Bowling 9 birilli',
    '10pin': 'Bowling 10 birilli',
    aikido: 'Aikido',
    airsoft: 'Aria compressa',
    american_football: 'Football Americano',
    archery: "Tiro con l'arco",
    athletics: 'Atletica',
    badminton: 'Badminton',
    baseball: 'Baseball',
    basketball: 'Basket',
    beachvolleyball: 'Beach volley',
    bicycle: 'Bicicletta',
    bmx: 'BMX',
    boules: 'Bocce',
    bowling: 'Bowling',
    bowls: 'Bocce',
    canoe: 'Canoa',
    chess: 'Scacchi',
    climbing: 'Arrampicata',
    climbing_adventure: 'Arrampicata',
    cycling: 'Ciclismo',
    darts: 'Freccette',
    disc_golf: 'Golf',
    dog_racing: 'Corse di cani',
    equestrian: 'Equitazione',
    field_hockey: 'Hockey',
    fitness: 'Fitness',
    floorball: 'Mini hockey',
    free_flying: 'Volo libero',
    golf: 'Golf',
    gymnastics: 'Ginnastica',
    handball: 'Pallamano',
    hockey: 'Hockey',
    horse_racing: 'Corse di cavalli',
    ice_hockey: 'Hockey su ghiaccio',
    ice_skating: 'Pattinaggio su ghiaccio',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Go Kart',
    laser_tag: 'Laser',
    model_aerodrome: 'Aereomodellismo',
    motocross: 'Motocross',
    motor: 'Motori',
    multi: 'Multi',
    netball: 'Pallacanestro',
    paintball: 'Paintball',
    petanque: 'Bocce',
    roller_skating: 'Pattinaggio',
    rowing: 'Canottaggio',
    running: 'Corsa',
    scuba_diving: 'Immersioni subacque',
    shooting: 'Tiro a segno',
    shooting_range: 'Poligono di tiro',
    'shot-put': 'Lancio del peso',
    skateboard: 'Skateboard',
    skating: 'Pattinaggio',
    ski_jumping: 'Salto con gli sci',
    skiing: 'Sci',
    soccer: 'Calcio',
    squash: 'Squash',
    streetball: 'Streetball',
    swimming: 'Nuoto',
    table_tennis: 'Ping pong',
    tennis: 'Tennis',
    volleyball: 'Pallavolo',
    water_ski: "Sci d'acqua",
    workout: 'Palestra',
    yoga: 'Yoga',
    '8pin': 'Bowling a otto birilli',
    aerobics: 'Aerobica',
    american_handball: 'Pallamano americana',
    association_football: 'Calcio (soccer)',
    axe_throwing: 'Lancio dell’ascia',
    balle_pelote: 'Balle pelote',
    ballooning: 'Volo in mongolfiera',
    bandy: 'Bandy',
    barre: 'Fitness barre',
    base: 'BASE jumping',
    batting_cage: 'Gabbia di battuta (baseball/softball)',
    beach_soccer: 'Calcio da spiaggia',
    beach_tennis: 'Beach tennis',
    beachhandball: 'Pallamano da spiaggia',
    beachtennis: 'Beach tennis',
    biathlon: 'Biathlon',
    billards: 'Biliardo',
    bobsleigh: 'Bob',
    bodybuilding: 'Bodybuilding',
    bullfighting: 'Corrida',
    calisthenics: 'Calisthenics',
    canadian_football: 'Football canadese',
    candlepin: 'Bowling candlepin',
    canoe_polo: 'Canoa polo',
    chinlone: 'Chinlone',
    cockfighting: 'Combattimento di galli',
    crossfit: 'CrossFit',
    cycle_ball: 'Ciclopalla',
    cycle_polo: 'Ciclopolo',
    dance: 'Danza sportiva',
    dancing: 'Danza sportiva',
    diving: 'Tuffi',
    dodgeball: 'Dodgeball',
    dog_agility: 'Agility cinofila',
    dragon_boat: 'Gara di dragon boat',
    fencing: 'Scherma',
    fistball: 'Pallapugno',
    'five-a-side': 'Calcio a 5',
    fives: 'Fives',
    football: 'Football',
    footballgolf: 'Football golf',
    four_square: 'Four square',
    freediving: 'Apnea',
    funnel_ball: 'Funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Football gaelico',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Volo a vela',
    hanggliding: 'Deltaplano',
    hapkido: 'Hapkido',
    high_rope_course: 'Percorso corde alte',
    hiking: 'Escursionismo',
    hopscotch: 'Campana',
    horse_riding: 'Equitazione',
    ice_stock: 'Eisstock',
    'in-line_hockey': 'Hockey inline',
    jetsprint: 'Jet sprint',
    kick_scooter: 'Monopattino sportivo',
    kickball: 'Kickball',
    kickboxing: 'Kickboxing',
    kitesurfing: 'Kitesurf',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Lacrosse',
    martial_arts: 'Arti marziali',
    mind_body_interventions: 'Esercizi mente-corpo (es. yoga)',
    miniature_golf: 'Minigolf',
    mtb: 'Mountain bike',
    nine_mens_morris: 'Gioco del mulino',
    obstacle_course: 'Percorso a ostacoli',
    paddleball: 'Paddleball',
    paddleboard: 'Stand-up paddle',
    padel: 'Padel',
    parachuting: 'Paracadutismo',
    paragliding: 'Parapendio',
    parkour: 'Parkour',
    pedal_car_racing: 'Gara auto a pedali',
    pesäpallo: 'Pesäpallo (baseball finlandese)',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole dance',
    polo: 'Polo',
    powerlifting: 'Powerlifting',
    rodeo: 'Rodeo',
    roller_hockey: 'Hockey su pista',
    russian_skittles: 'Birilli russi',
    safety_training: 'Allenamento sicurezza',
    shuffleboard: 'Shuffleboard',
    snooker: 'Snooker',
    snorkeling: 'Snorkeling',
    softball: 'Softball',
    speedway: 'Speedway',
    summer_toboggan: 'Pista bob estiva',
    sumo: 'Sumo',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    touch_football: 'Touch football',
    trampoline: 'Trampolino elastico',
    trugo: 'Trugo',
    tug_of_war: 'Tiro alla fune',
    ultimate: 'Ultimate frisbee',
    ultralight_aviation: 'Aviazione ultraleggera',
    wakeboarding: 'Wakeboard',
    walking: 'Marcia sportiva',
    water_polo: 'Pallanuoto',
    water_sports: 'Sport acquatici',
    weightlifting: 'Sollevamento pesi',
    windsurfing: 'Windsurf',
    wrestling: 'Lotta',
    zurkhaneh_sport: 'Zurkhaneh',
  },

  tourism: {
    '*': '{}',
    alpine_hut: 'Rifugio Alpino',
    apartment: 'Appartamento',
    aquarium: 'Acquario',

    artwork: {
      '*': 'Arte',
      artwork_type: {
        architecture: 'Architettura',
        bust: 'Busto',
        graffiti: 'Graffiti',
        installation: 'Installazione artistica',
        mosaic: 'Piastrelle',
        mural: 'Murale',
        painting: 'Pittura',
        relief: 'Rilievo (opera arte)',
        sculpture: 'Scultura',
        statue: 'Statua',
        stone: 'Boulder (opera arte)',
      },
    },

    attraction: 'Attrazione',
    camp_site: 'Campeggio',
    caravan_site: 'Area camper',
    chalet: 'Chalet',
    gallery: 'Galleria',
    guest_house: 'Pensione',
    hostel: 'Ostello',
    hotel: 'Albergo',

    information: {
      '*': 'Informazioni',
      information: {
        '*': 'Informatzioni {}',
        board: 'Pannello informativo',
        guidepost: 'Posto Guida',
        map: 'Mappa',
        office: 'Ufficio informazioni',
        route_marker: 'Segnavia',
      },
    },

    motel: 'Motel',
    museum: 'Museo',
    picnic_site: 'Area Picnic',
    viewpoint: 'Punto panoramico',
    wilderness_hut: 'Rifugio',
    zoo: 'Zoo',
    theme_park: 'Parco tematico',
  },

  type: {
    route: {
      '*': 'Percorso',
      route: {
        '*': 'Percorso {}',
        bicycle: 'Percorso ciclistico',
        bus: 'Linea AutoBUS',
        foot: 'Percorso pedonale',
        hiking: {
          '*': 'Percorso escursionistico',

          network: {
            iwn: 'Sentiero escursionistico internazionale',
            lwn: 'Sentiero escursionistico locale',
            nwn: 'Sentiero escursionistico nazionale',
            rwn: 'Sentiero escursionistico regionale',
          },
        },
        horse: 'Percorso equitazione',
        mtb: 'Percorso mountain bike',
        piste: 'Percorso Sci',
        railway: 'Ferrovia',
        ski: 'Pista da sci',
        tram: 'Linea Tram',
      },
    },
  },

  waterway: {
    '*': 'Via navigabile {}',
    canal: 'Canale',
    dam: 'Diga',
    ditch: 'Fossato (navigabile)',
    drain: 'Fosso',
    river: 'Fiume',
    stream: 'Ruscello, Torrente',
    waterfall: 'Cascata',
    weir: 'Chiusa',
    canoe_pass: 'Passaggio canoe',
    fairway: 'Canale navigabile',
    fish_pass: 'Scala di risalita pesci',
    flowline: 'Linea di flusso',
    link: 'Collegamento corso d’acqua',
    pressurised: 'Condotta idrica in pressione',
    rapids: 'Rapide',
    tidal_channel: 'Canale di marea',
  },

  'abandoned:building': {
    '*': 'Edificio abbandonato',
  },

  'disused:building': {
    '*': 'Edificio dismesso',
  },

  'ruins:building': {
    '*': 'Rovine di edificio',
  },

  attraction: {
    amusement_ride: 'Attrazione meccanica',
    animal: 'Attrazione animale',
    big_wheel: 'Ruota panoramica',
    carousel: 'Giostra',
    historic: 'Attrazione storica',
    maze: 'Labirinto',
    roller_coaster: 'Montagne russe',
    summer_toboggan: 'Pista bob estiva',
    train: 'Trenino attrazione',
    water_slide: 'Scivolo acquatico',
  },

  bicycle: {
    designated: 'Designato per biciclette',
    no: 'Accesso biciclette vietato',
    private: 'Accesso biciclette solo proprietari',
    yes: 'Accesso biciclette consentito',
  },

  bridge: {
    '*': {
      '*': 'Ponte',

      highway: {
        '*': 'Ponte stradale',
      },

      railway: {
        '*': 'Ponte ferroviario',
      },
    },

    no: '',
  },

  fixme: {
    '*': 'Elemento mappato in modo errato o incompleto',
  },

  foot: {
    designated: 'Designato per pedoni',
    no: 'Accesso pedonale vietato',
    private: 'Accesso pedonale solo proprietari',
    yes: 'Accesso pedonale consentito',
  },

  ford: {
    yes: 'Guado',
  },

  intermittent: {
    yes: {
      natural: {
        water: 'Area d’acqua intermittente',
      },

      waterway: 'Corso d’acqua intermittente',
    },
  },

  military: {
    '*': 'Struttura militare {}',
    academy: 'Accademia militare',
    airfield: 'Aeroporto militare',
    ammunition: 'Deposito munizioni',
    barracks: 'Caserma',
    base: 'Base militare',
    bunker: 'Bunker',
    checkpoint: 'Posto di controllo militare',
    danger_area: 'Area militare pericolosa',
    depot: 'Deposito militare',
    launchpad: 'Piattaforma di lancio',
    naval_base: 'Base navale',
    nuclear_explosion_site: 'Sito test nucleari',
    obstacle_course: 'Percorso ostacoli militare',
    office: 'Ufficio militare',
    range: 'Poligono di tiro',
    school: 'Scuola militare',
    training_area: 'Area addestramento militare',
    trench: 'Trincea',
  },

  motor_vehicle: {
    designated: 'Designato per veicoli a motore',
    no: 'Accesso veicoli a motore vietato',
    private: 'Accesso veicoli a motore solo proprietari',
    yes: 'Accesso veicoli a motore consentito',
  },

  mountain_pass: {
    yes: 'Passo di montagna',
  },

  oneway: {
    yes: 'Senso unico',
  },

  seasonal: {
    yes: {
      natural: {
        water: 'Area d’acqua stagionale',
      },

      waterway: 'Corso d’acqua stagionale',
    },
  },

  trail_visibility: {
    bad: 'Visibilità sentiero scarsa',
    excellent: 'Visibilità sentiero eccellente',
    good: 'Visibilità sentiero buona',
    horrible: 'Visibilità sentiero pessima',
    intermediate: 'Visibilità sentiero media',
    no: 'Nessuna visibilità sentiero',
  },

  tunnel: {
    '*': {
      '*': 'Galleria',

      highway: {
        '*': 'Galleria stradale',
      },

      railway: {
        '*': 'Galleria ferroviaria',
      },
    },

    culvert: 'Tombino',
    no: '',
  },

  vehicle: {
    designated: 'Designato per veicoli',
    no: 'Accesso veicoli vietato',
    private: 'Accesso veicoli solo proprietari',
    yes: 'Accesso veicoli consentito',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Rosso',
  blue: 'Blu',
  green: 'Verde',
  yellow: 'Giallo',
  orange: 'Arancio',
  purple: 'Porpora',
  violet: 'Viola',
  white: 'Bianco',
  black: 'Nero',
  gray: 'Grigio',
  brown: 'Marrone',
};
