import { DeepPartial } from '../deepPartial.js';
import { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  aeroway: {
    aerodrome: 'Flughafen',
  },

  amenity: {
    shelter: {
      shelter_type: {
        picnic_shelter: {
          fireplace: {
            yes: 'Picknickunterstand mit Kamin',
          },
          '*': 'Picknickunterstand',
        },
        '*': 'Unterstand {}',
        basic_hut: 'Einfache Hütte',
        changing_rooms: 'Umkleideraum',
        field_shelter: 'Feldunterstand',
        lean_to: 'Anlehnunterstand',
        public_transport: 'Haltestellenunterstand',
        rock_shelter: 'Felsunterstand',
        sun_shelter: 'Sonnenschutz',
        weather_shelter: 'Wetterschutz',
      },
      '*': 'Unterstand',
    },
    social_facility: {
      social_facility: {
        ambulatory_care: 'Ambulante Pflege',
        assisted_living: 'Betreutes Wohnen',
        clothing_bank: 'Kleiderkammer',
        day_care: 'Tagesstätte',
        food_bank: 'Tafel',
        group_home: 'Gemeinschaftswohnheim',
        hospice: 'Hospiz',
        nursing_home: 'Pflegeheim',
        shelter: 'Obdach',
        soup_kitchen: 'Suppenküche',
        workshop: 'Werkstatt',
      },
      '*': 'Soziale Einrichtung',
    },
    vending_machine: {
      vending: {
        bicycle_tube: 'Fahrradschlauch-Automat',
        bread: 'Brotautomat',
        bottle_return: 'Pfandflaschenrückgabeautomat',
        candles: 'Kerzenautomat',
        chewing_gums: 'Kaugummi-Automat',
        cigarettes: 'Zigarettenautomat',
        coffee: 'Kaffeeautomat',
        condoms: 'Kondomautomat',
        drinks: 'Getränkeautomat',
        elongated_coin: 'Souvenir-Münzautomat',
        eggs: 'Eierautomat',
        excrement_bags: 'Hundekotbeutelautomat',
        food: 'Lebensmittelautomat',
        fuel: 'Kraftstoffautomat',
        gas: 'Gasautomat',
        ice_cream: 'Eisautomat',
        ice_cubes: 'Eiswürfelautomat',
        milk: 'Milchautomat',
        movies: 'Filmautomat',
        newspapers: 'Zeitungsautomat',
        parking_tickets: 'Parkscheinautomat',
        pizza: 'Pizzaautomat',
        public_transport_tickets: 'Fahrkartenautomat',
        stamps: 'Briefmarkenautomat',
        sweets: 'Süßigkeitenautomat',
        water: 'Wasserspender',
      },
      '*': 'Automat',
    },
    '*': '{}',
    animal_breeding: 'Tierhaltung',
    animal_shelter: 'Tierheim',
    arts_centre: 'Kunstzentrum',
    atm: 'Geldautomat',
    bank: 'Bank',
    bar: 'Bar',
    bbq: 'Grill',
    bench: 'Bank',
    bicycle_parking: 'Fahrradparkplatz',
    bicycle_rental: 'Fahrradverleih',
    bicycle_repair_station: 'Fahrradreparaturstation',
    biergarten: 'Biergarten',
    brothel: 'Bordell',
    bureau_de_change: 'Wechselstube',
    bus_station: 'Busbahnhof',
    cafe: 'Café',
    car_rental: 'Autovermietung',
    car_wash: 'Autowäsche',
    casino: 'Casino',
    charging_station: 'Ladestation',
    childcare: 'Kinderbetreuung',
    cinema: 'Kino',
    clinic: 'Klinik',
    clock: 'Uhr',
    college: 'Hochschule',
    community_centre: 'Gemeinschaftszentrum',
    compressed_air: 'Druckluft',
    courthouse: 'Gericht',
    dentist: 'Zahnarzt',
    device_charging_station: 'Ladestation für Geräte',
    doctors: 'Arztpraxis',
    dressing_room: 'Umkleide',
    drinking_water: 'Trinkwasser',
    driving_school: 'Fahrschule',
    embassy: 'Botschaft',
    events_venue: 'Veranstaltungsort',
    fast_food: 'Fast Food',
    feeding_place: 'Futterstelle',
    ferry_terminal: 'Fährterminal',
    fire_station: 'Feuerwache',
    food_court: 'Foodcourt',
    fountain: 'Brunnen',
    fuel: 'Tankstelle',
    funeral_hall: 'Trauerhalle',
    gambling: 'Glücksspiel',
    game_feeding: 'Wildfütterung',
    grave_yard: 'Friedhof',
    grit_bin: 'Streugutbehälter',
    hospital: 'Krankenhaus',
    hunting_stand: 'Jagdstand',
    ice_cream: 'Eis',
    kindergarten: 'Kindergarten',
    language_school: 'Sprachschule',
    library: 'Bibliothek',
    marketplace: 'Marktplatz',
    monastery: 'Kloster',
    money_transfer: 'Geldtransfer',
    motorcycle_parking: 'Motorradparkplatz',
    motorcycle_rental: 'Motorradverleih',
    nightclub: 'Nachtclub',
    parcel_locker: 'Paketfach',
    parking: 'Parkplatz',
    parking_entrance: 'Parkplatzeingang',
    parking_space: 'Parkplatz',
    pharmacy: 'Apotheke',
    place_of_mourning: 'Trauerstätte',
    place_of_worship: 'Andachtsstätte',
    planetarium: 'Planetarium',
    police: 'Polizei',
    post_box: 'Briefkasten',
    post_office: 'Postamt',
    prison: 'Gefängnis',
    pub: 'Kneipe',
    public_bookcase: 'Öffentlicher Bücherschrank',
    ranger_station: 'Rangerstation',
    recycling: 'Recycling',
    restaurant: 'Restaurant',
    school: 'Schule',
    shower: 'Dusche',
    ski_rental: 'Skiverleih',
    smoking_area: 'Raucherbereich',
    social_centre: 'Soziales Zentrum',
    stripclub: 'Stripclub',
    studio: 'Studio',
    taxi: 'Taxi',
    telephone: 'Telefon',
    theatre: 'Theater',
    toilets: 'WC',
    townhall: 'Rathaus',
    traffic_park: 'Verkehrsübungsplatz',
    trolley_bay: 'Einkaufswagenstellplatz',
    university: 'Universität',
    vacuum_cleaner: 'Staubsauger',
    vehicle_inspection: 'Fahrzeugprüfung',
    veterinary: 'Tierarzt',
    waste_basket: 'Mülleimer',
    waste_disposal: 'Abfallentsorgung',
    water_point: 'Wasserstelle',
    watering_place: 'Tränkestelle',
  },

  barrier: {
    '*': 'Barriere {}',
    block: 'Block',
    bollard: 'Poller',
    border_control: 'Grenzkontrolle',
    cable_barrier: 'Kabelschutzplanke',
    chain: 'Kette',
    city_wall: 'Stadtmauer',
    ditch: 'Graben (Barriere)',
    entrance: 'Eingang',
    fence: 'Zaun',
    gate: 'Tor',
    guard_rail: 'Leitplanke',
    handrail: 'Handlauf',
    hedge: 'Hecke',
    kerb: 'Bordstein',
    lift_gate: 'Schranke',
    rope: 'Seil',
    sliding_gate: 'Schiebetor',
    swing_gate: 'Drehtor',
    turnstile: 'Drehkreuz',
    wall: 'Mauer',
  },

  boundary: {
    administrative: {
      admin_level: {
        '2': 'Land',
        '3': 'Region',
        '4': 'Bezirk',
        '5': 'Provinz',
        '6': 'Stadt',
        '7': 'Region',
        '8': 'Bezirk',
        '9': 'Dorf',
        '10': 'Katastergebiet',
      },
      '*': 'Verwaltungsregion',
    },
    '*': 'Region',
    marker: 'Grenzstein',
    national_park: 'Nationalpark',
    protected_area: 'Schutzgebiet',
  },

  building: {
    '*': 'Gebäude {}',
    apartments: 'Wohnungen (Block)',
    barn: 'Scheune',
    bungalow: 'Bungalow',
    bunker: 'Bunker',
    cabin: 'Hütte',
    cathedral: 'Kathedrale',
    chapel: 'Kapelle',
    church: 'Kirche',
    civic: 'Öffentliches Gebäude',
    collapsed: 'Eingestürztes Gebäude',
    commercial: 'Gewerbegebäude',
    construction: 'Gebäude im Bau',
    cowshed: 'Kuhstall',
    detached: 'Freistehendes Haus',
    dormitory: 'Schlafsaal',
    entrance: 'Gebäudeeingang',
    farm_auxiliary: 'Nebengebäude eines Bauernhofs',
    farm: 'Bauernhof',
    garage: 'Garage',
    garages: 'Garagen',
    government: 'Regierungsgebäude',
    grandstand: 'Tribüne',
    greenhouse: 'Gewächshaus',
    hangar: 'Hangar',
    hayloft: 'Heuboden',
    hospital: 'Krankenhausgebäude',
    hotel: 'Hotelgebäude',
    house: 'Privathaus',
    houseboat: 'Hausboot',
    hut: 'Hütte',
    industrial: 'Industriegebäude',
    kindergarten: 'Kindergartengebäude',
    kiosk: 'Kiosk',
    manufacture: 'Fabrikgebäude',
    mosque: 'Moschee',
    office: 'Bürogebäude',
    parking: 'Parkhaus',
    public: 'Öffentliches Gebäude',
    residential: 'Wohnhaus',
    retail: 'Geschäftsgebäude',
    roof: 'Dach',
    ruins: 'Gebäuderuine',
    school: 'Schulgebäude',
    semidetached_house: 'Doppelhaushälfte',
    service: 'Servicegebäude',
    shed: 'Schuppen',
    shrine: 'Schrein',
    stable: 'Stall',
    static_caravan: 'Mobilheim, Wohnwagen',
    storage_tank: 'Lagerbehälter',
    sty: 'Schweinestall',
    supermarket: 'Supermarktgebäude',
    synagogue: 'Synagoge',
    temple: 'Tempel',
    terrace: 'Reihenhaus',
    train_station: 'Bahnhof',
    transformer_tower: 'Umspannwerk',
    transportation: 'Verkehrsgebäude',
    university: 'Universitätsgebäude',
    warehouse: 'Lagerhaus',
    yes: 'Unbestimmtes Gebäude',
  },

  highway: {
    service: {
      service: {
        '*': 'Servicestraße {}',
        alley: 'Gasse',
        bus: 'Busstraße',
        'drive-through': 'Drive-through',
        driveway: 'Zufahrt',
        emergency_access: 'Feuerwehrzufahrt',
        parking_aisle: 'Parkgasse',
      },
      '*': 'Servicezufahrt',
    },
    track: {
      tracktype: {
        grade1: 'Verdichteter Waldweg',
        grade2: 'Überwiegend verdichteter Waldweg',
        grade3: 'Weniger fester, unbefestigter Waldweg',
        grade4: 'Waldweg befahrbar mit Traktor oder ähnlichen Fahrzeugen',
        grade5: 'Kaum erkennbarer Waldweg',
      },
      '*': 'Waldweg',
    },
    '*': 'Straße {}',
    bus_stop: 'Bushaltestelle',
    construction: 'Straße im Bau',
    crossing: 'Fußgängerüberweg',
    cycleway: 'Radweg',
    footway: 'Gehweg',
    living_street: 'Wohnstraße',
    motorway: 'Autobahn',
    motorway_link: 'Autobahnanschluss',
    path: 'Pfad',
    pedestrian: 'Fußgängerzone',
    primary: 'Hauptstraße',
    primary_link: 'Anschluss Hauptstraße',
    residential: 'Straße',
    secondary: 'Nebenstraße',
    secondaty_link: 'Anschluss Nebenstraße',
    steps: 'Treppen',
    street_lamp: 'Straßenlaterne',
    tertiary: 'Tertiärstraße',
    tertiary_link: 'Anschluss Tertiärstraße',
    trunk: 'Fernstraße',
    trunk_link: 'Fernstraßenanschluss',
    unclassified: 'unklassifizierte Straße',
  },

  historic: {
    ruins: {
      ruins: {
        castle: 'Burgruine',
      },
      '*': 'Ruinen',
    },
    '*': 'Historische Struktur',
    archaeological_site: 'Archäologische Fundstätte',
    castle: 'Burg',
    church: 'Historische Kirche',
    city_gate: 'Stadttor',
    manor: 'Herrenhaus',
    memorial: 'Gedenkstätte',
    monastery: 'Kloster',
    monument: 'Denkmal',
    tomb: 'Grab',
    wayside_cross: 'Bildstock',
    wayside_shrine: 'Feldkapelle',
  },

  landuse: {
    '*': '{}',
    allotments: 'Kleingärten',
    basin: 'Becken',
    brownfield: 'Brachfläche',
    cemetery: 'Friedhof',
    commercial: 'Gewerbegebiet',
    construction: 'Baustelle',
    education: 'Bildungszone',
    farmland: 'Ackerland',
    farmyard: 'Hof',
    forest: 'Wald',
    garages: 'Garagen',
    grass: 'Gras',
    greenfield: 'Grünfläche',
    industrial: 'Industriegebiet',
    landfill: 'Mülldeponie',
    meadow: 'Wiese',
    military: 'Militärgebiet',
    orchard: 'Obstgarten',
    plant_nursery: 'Pflanzschule',
    quarry: 'Steinbruch',
    recreation_ground: 'Erholungsgebiet',
    religions: 'Kirchliches Grundstück',
    reservoir: 'Stausee',
    residential: 'Wohngebiet',
    retail: 'Einzelhandel',
    vineyard: 'Weinberg',
    winter_sports: 'Wintersportgebiet',
  },

  leisure: {
    '*': '{}',
    picnic_table: {
      covered: {
        yes: 'Überdachter Picknicktisch',
      },
      '*': 'Picknicktisch',
    },
    pitch: 'Spielfeld',
    bleachers: 'Tribüne',
    escape_game: 'Escape Room',
    hackerspace: 'Hackerspace',
    ice_rink: 'Eisbahn',
    marina: 'Marina',
    miniature_golf: 'Minigolf',
    dog_park: 'Hundespielplatz',
    firepit: 'Feuerstelle',
    fishing: 'Angelplatz',
    fitness_centre: 'Fitnesscenter',
    fitness_station: 'Fitnessstation',
    garden: 'Garten',
    golf_course: 'Golfplatz',
    horse_riding: 'Reiten',
    nature_reserve: 'Naturschutzgebiet',
    park: 'Park',
    playground: 'Spielplatz',
    sports_centre: 'Sportzentrum',
    sports_hall: 'Sporthalle',
    stadium: 'Stadion',
    swimming_pool: 'Schwimmbad',
    track: 'Bahn',
    water_park: 'Wasserpark',
  },

  man_made: {
    tower: {
      'tower:type': {
        bell_tower: 'Glockenturm',
        communication: 'Kommunikationsturm',
        cooling: 'Kühlturm',
        observation: 'Aussichtsturm',
      },
      '*': 'Turm',
    },
    '*': '{}',
    adit: 'Stollen',
    antenna: 'Antenne',
    beacon: 'Leuchtturm',
    beehive: 'Bienenstock',
    bridge: 'Brücke',
    bunker_silo: 'Bunkersilo',
    cairn: 'Steinmarkierung',
    cellar_entrance: 'Kellerzugang',
    chimney: 'Schornstein',
    clearcut: 'Rodung',
    communications_tower: 'Kommunikationsturm',
    cooling_tower: 'Kühlturm',
    crane: 'Kran',
    cross: 'Kreuz',
    cutline: 'Schneise',
    dyke: 'Deich',
    embankment: 'Damm',
    flagpole: 'Fahnenmast',
    "forester's_lodge": 'Forsthaus',
    gasometer: 'Gasometer',
    goods_conveyor: 'Förderband',
    groyne: 'Wellenbrecher',
    lighthouse: 'Leuchtturm',
    manhole: 'Schacht',
    mast: 'Mast',
    mineshaft: 'Bergwerkschacht',
    monitoring_station: 'Überwachungsstation',
    nesting_site: 'Nistplatz',
    observatory: 'Observatorium',
    pier: 'Pier',
    pipeline: 'Pipeline',
    reservoir_covered: 'Überdachtes Reservoir',
    silo: 'Silo',
    snow_cannon: 'Schneekanone',
    spoil_heap: 'Abraumhalde',
    spring_box: 'Quellschutz',
    storage_tank: 'Lagertank',
    street_cabinet: 'Straßenschrank',
    surveillance: 'Überwachungskamera',
    survey_point: 'Vermessungspunkt',
    telescope: 'Teleskop',
    utility_pole: 'Strommast',
    wastewater_plant: 'Kläranlage',
    water_tap: 'Wasserhahn',
    water_tower: 'Wasserturm',
    water_well: 'Brunnen',
    water_works: 'Wasserwerk',
    watermill: 'Wassermühle',
    windmill: 'Windmühle',
    works: 'Fabrik',
  },

  natural: {
    spring: {
      drinking_water: {
        yes: 'Trinkquelle',
        no: 'Nicht trinkbare Quelle',
      },
      refitted: {
        yes: 'Ausgebaute Quelle',
        no: 'Unausgebaute Quelle',
      },
      '*': 'Quelle',
    },
    tree: {
      protected: {
        yes: 'Geschützter Baum',
      },
      denotation: {
        natural_monument: 'Naturdenkmalbaum',
        landmark: 'Markanter Baum',
        avenue: 'Allee-Baum',
        urban: 'Stadtbaum',
        agricultural: 'Nutzbaum',
      },
      '*': 'Baum',
    },
    '*': '{}',
    arch: 'Felsbogen',
    bare_rock: 'Fels',
    basin: 'Becken',
    bay: 'Bucht',
    beach: 'Strand',
    birds_nest: 'Vogelnest',
    cave_entrance: 'Höhle',
    cliff: 'Klippe',
    earth_bank: 'Erdwall',
    fell: 'Hochmoor',
    geyser: 'Geysir',
    glacier: 'Gletscher',
    grassland: 'Grasland',
    gully: 'Rinne',
    heath: 'Heide',
    hot_spring: 'Heißquelle',
    landslide: 'Erdrutsch',
    mountain_range: 'Gebirgskette',
    mud: 'Schlamm',
    peak: 'Gipfel',
    plateau: 'Hochebene',
    ridge: 'Grat',
    rock: 'Fels',
    saddle: 'Sattel',
    sand: 'Sand',
    scree: 'Schutt',
    scrub: 'Buschwerk',
    shingle: 'Kiesstrand',
    shrub: 'Strauch',
    sinkhole: 'Dolinen',
    stone: 'Felsblock',
    tree_row: 'Baumreihe',
    valley: 'Tal',
    water: 'Gewässer',
    wetland: {
      '*': 'Feuchtgebiet',
      wetland: {},
    },
    wood: 'Wald',
  },

  place: {
    '*': 'Ort {}',
    city: 'Stadt',
    country: 'Land',
    farm: 'Bauernhof',
    hamlet: 'Weiler',
    island: 'Insel',
    islet: 'Inselchen',
    isolated_dwelling: 'Einzelhof',
    locality: 'Ortslage',
    ocean: 'Ozean',
    sea: 'Meer',
    square: 'Platz',
    state: 'Bundesland',
    suburb: 'Vorort',
    town: 'Städtchen',
    village: 'Dorf',
  },

  power: {
    '*': '{}',
    generator: {
      '*': 'Generator',
    },
    line: 'Stromleitung',
    minor_line: 'Nebenstromleitung',
    plant: {
      '*': 'Kraftwerk',
    },
    pole: 'Strommast',
    substation: 'Umspannwerk',
    tower: 'Stromturm',
    transformer: 'Transformator',
  },

  public_transport: {
    platform: 'Bahnsteig',
    station: 'Station',
    stop_position: 'Haltestelle',
  },

  shop: {
    '*': 'Geschäft {}',
    household_linen: 'Haushaltswäsche',
    charity: 'Wohltätigkeitsladen',
    chocolate: 'Schokoladengeschäft',
    fashion_accessories: 'Modezubehörgeschäft',
    frozen_food: 'Tiefkühlkostladen',
    hearing_aids: 'Hörgerätegeschäft',
    weapons: 'Waffenladen',
    alcohol: 'Alkoholgeschäft',
    antiques: 'Antiquitäten',
    art: 'Kunstladen',
    baby_goods: 'Babybedarf',
    bag: 'Taschengeschäft',
    bakery: 'Bäckerei',
    bathroom_furnishing: 'Badausstattung',
    beauty: 'Kosmetikgeschäft',
    bed: 'Bettengeschäft',
    beverages: 'Getränkeladen',
    bicycle: 'Fahrradladen',
    bookmaker: 'Wettbüro',
    books: 'Buchhandlung',
    boutique: 'Boutique',
    butcher: 'Metzgerei',
    camera: 'Kamera Geschäft',
    car: 'Autohändler',
    car_parts: 'Autoteile',
    car_repair: 'Autowerkstatt',
    carpet: 'Teppichgeschäft',
    cheese: 'Käseladen',
    chemist: 'Drogerie',
    clothes: 'Bekleidungsgeschäft',
    coffee: 'Coffeeshop',
    collector: 'Sammlergeschäft',
    computer: 'Computerladen',
    confectionery: 'Süßwarenladen',
    convenience: 'Spätkauf',
    copyshop: 'Copyshop',
    cosmetics: 'Kosmetikladen',
    craft: 'Handwerksladen',
    curtain: 'Gardinenladen',
    dairy: 'Milchprodukte',
    deli: 'Feinkostladen',
    department_store: 'Kaufhaus',
    doityourself: 'Baumarkt',
    doors: 'Türenladen',
    dry_cleaning: 'Reinigung',
    'e-cigarette': 'E-Zigarettenladen',
    electrical: 'Elektrogeschäft',
    electronics: 'Elektronikladen',
    erotic: 'Sexshop',
    fabric: 'Stoffladen',
    farm: 'Hofladen',
    fireplace: 'Kaminladen',
    fishing: 'Angelgeschäft',
    flooring: 'Bodenbelagsladen',
    florist: 'Blumenladen',
    funeral_directors: 'Bestattungsinstitut',
    furniture: 'Möbelgeschäft',
    games: 'Spieleladen',
    garden_center: 'Gartencenter',
    garden_centre: 'Gartencenter',
    general: 'Gemischtwarenladen',
    gift: 'Geschenkeladen',
    glaziery: 'Glaser',
    greengrocer: 'Obst- und Gemüseladen',
    hairdresser: 'Friseursalon',
    hardware: 'Eisenwarenladen',
    health_food: 'Naturkostladen',
    hifi: 'HiFi-Laden',
    houseware: 'Haushaltswarenladen',
    hunting: 'Jagdausrüstung',
    ice_cream: 'Eisdiele',
    interior_decoration: 'Einrichtungsdekoration',
    jewelry: 'Juwelier',
    kiosk: 'Kiosk',
    kitchen: 'Küchenstudio',
    laundry: 'Waschsalon',
    lighting: 'Beleuchtungsgeschäft',
    locksmith: 'Schlüsseldienst',
    lottery: 'Lottoannahmestelle',
    mall: 'Einkaufszentrum',
    massage: 'Massagesalon',
    medical_supply: 'Sanitätsfachgeschäft',
    mobile_phone: 'Handyladen',
    model: 'Modellbau',
    motorcycle: 'Motorradgeschäft',
    music: 'Musikladen',
    musical_instrument: 'Musikinstrumentengeschäft',
    newsagent: 'Zeitschriftenladen',
    nutrition_supplements: 'Nahrungsergänzungsmittel',
    optician: 'Optiker',
    outdoor: 'Outdoorladen',
    outpost: 'Außenstelle',
    paint: 'Farbengeschäft',
    pastry: 'Konditorei',
    pawnbroker: 'Pfandleihhaus',
    perfumery: 'Parfümerie',
    pet: 'Tierbedarf',
    pet_grooming: 'Tierpflegesalon',
    photo: 'Fotogeschäft',
    radiotechnics: 'Radiotechnikladen',
    rental: 'Verleih',
    seafood: 'Meeresfrüchtegeschäft',
    second_hand: 'Secondhandladen',
    sewing: 'Nähbedarf',
    shoes: 'Schuhladen',
    sports: 'Sportgeschäft',
    stationery: 'Papierwarenladen',
    supermarket: 'Supermarkt',
    tailor: 'Schneider',
    tattoo: 'Tattoo-Studio',
    tea: 'Teeladen',
    ticket: 'Ticketverkauf',
    tobacco: 'Tabakladen',
    toys: 'Spielwarengeschäft',
    trade: 'Baumaterialgeschäft',
    travel_agency: 'Reisebüro',
    tyres: 'Reifenhandel',
    vacant: 'Leerstehendes Geschäft',
    variety_store: 'Vielzweckladen',
    video: 'Videoverleih',
    video_games: 'Videospieleladen',
    watches: 'Uhrengeschäft',
    wholesale: 'Großhandel',
    window_blind: 'Jalousienladen',
    wine: 'Weinladen',
  },

  sport: {
    '*': 'Sport {}',
    australian_football: 'Australischer Fußball',
    billiards: 'Billard',
    boxing: 'Boxen',
    cliff_diving: 'Klipptauchen',
    cricket: 'Cricket',
    cricket_nets: 'Cricket-Netze',
    croquet: 'Krocket',
    curling: 'Curling',
    gaelic_games: 'Gaelic Games',
    horseshoes: 'Hufeisenwerfen',
    korfball: 'Korfball',
    long_jump: 'Weitsprung',
    orienteering: 'Orientierungslauf',
    paddle_tennis: 'Paddle Tennis',
    pelota: 'Pelota',
    racquet: 'Schläger',
    rc_car: 'RC-Autos',
    rugby: 'Rugby',
    rugby_league: 'Rugby League',
    rugby_union: 'Rugby Union',
    sailing: 'Segeln',
    surfing: 'Surfen',
    table_soccer: 'Tischfußball',
    team_handball: 'Handball',
    toboggan: 'Rodeln',
    '9pin': '9-Pin Bowling',
    '10pin': '10-Pin Bowling',
    aikido: 'Aikido',
    airsoft: 'Airsoft',
    american_football: 'American Football',
    archery: 'Bogenschießen',
    athletics: 'Leichtathletik',
    badminton: 'Badminton',
    baseball: 'Baseball',
    basketball: 'Basketball',
    beachvolleyball: 'Beachvolleyball',
    bicycle: 'Fahrrad',
    bmx: 'BMX',
    boules: 'Boule',
    bowling: 'Bowling',
    bowls: 'Bowls',
    canoe: 'Kanu',
    chess: 'Schach',
    climbing: 'Klettern',
    climbing_adventure: 'Kletterabenteuer',
    cycling: 'Radfahren',
    darts: 'Darts',
    disc_golf: 'Disc Golf',
    dog_racing: 'Hunderennen',
    equestrian: 'Reiten',
    field_hockey: 'Feldhockey',
    fitness: 'Fitness',
    floorball: 'Floorball',
    free_flying: 'Freiflug',
    golf: 'Golf',
    gymnastics: 'Gymnastik',
    handball: 'Handball',
    hockey: 'Hockey',
    horse_racing: 'Pferderennen',
    ice_hockey: 'Eishockey',
    ice_skating: 'Eislaufen',
    judo: 'Judo',
    karate: 'Karate',
    karting: 'Kartfahren',
    laser_tag: 'Lasertag',
    model_aerodrome: 'Modellflugplatz',
    motocross: 'Motocross',
    motor: 'Motorsport',
    multi: 'Mehrere Sportarten',
    netball: 'Netball',
    paintball: 'Paintball',
    petanque: 'Pétanque',
    roller_skating: 'Rollschuhlaufen',
    rowing: 'Rudern',
    running: 'Laufen',
    scuba_diving: 'Tauchen',
    shooting: 'Schießen',
    shooting_range: 'Schießstand',
    'shot-put': 'Kugelstoßen',
    skateboard: 'Skateboard',
    skating: 'Schlittschuhlaufen',
    ski_jumping: 'Skispringen',
    skiing: 'Skifahren',
    soccer: 'Fußball',
    squash: 'Squash',
    streetball: 'Streetball',
    swimming: 'Schwimmen',
    table_tennis: 'Tischtennis',
    tennis: 'Tennis',
    volleyball: 'Volleyball',
    water_ski: 'Wasserski',
    workout: 'Workout',
    yoga: 'Yoga',
  },

  tourism: {
    artwork: {
      artwork_type: {
        architecture: 'Architektur',
        bust: 'Büste',
        graffiti: 'Graffiti',
        installation: 'Kunstinstallation',
        mosaic: 'Mosaik',
        mural: 'Wandmalerei',
        painting: 'Gemälde',
        relief: 'Relief (Kunstwerk)',
        sculpture: 'Skulptur',
        statue: 'Statue',
        stone: 'Felskunst',
      },
      '*': 'Kunst',
    },

    information: {
      information: {
        '*': 'Information {}',
        board: 'Informationsschild',
        guidepost: 'Wegweiser',
        map: 'Karte',
        office: 'Informationsbüro',
      },
      '*': 'Information',
    },

    '*': '{}',

    alpine_hut: 'Alpenhütte',
    apartment: 'Apartment',
    aquarium: 'Aquarium',
    attraction: 'Attraktion',
    camp_site: 'Campingplatz',
    caravan_site: 'Wohnwagenstellplatz',
    chalet: 'Chalet',
    gallery: 'Galerie',
    guest_house: 'Gästehaus',
    hostel: 'Hostel',
    hotel: 'Hotel',
    motel: 'Motel',
    museum: 'Museum',
    picnic_site: 'Picknickplatz',
    viewpoint: 'Aussichtspunkt',
    wilderness_hut: 'Schutzhütte',
    zoo: 'Zoo',
  },

  type: {
    route: {
      route: {
        '*': 'Weg {}',
        bicycle: 'Fahrradweg',
        bus: 'Buslinie',
        foot: 'Fußweg',
        hiking: 'Wanderweg',
        horse: 'Reitweg',
        mtb: 'Mountainbike-Strecke',
        piste: 'Skipiste',
        railway: 'Bahnstrecke',
        ski: 'Langlaufloipe',
        tram: 'Straßenbahnlinie',
      },

      '*': 'Weg',
    },
  },

  waterway: {
    '*': 'Wasserstraße {}',
    canal: 'Kanal',
    dam: 'Staudamm',
    ditch: 'Graben (Wasserstraße)',
    drain: 'Entwässerung',
    river: 'Fluss',
    stream: 'Bach, Fließ',
    waterfall: 'Wasserfall',
    weir: 'Wehr',
  },

  aerialway: 'Seilbahn, Aufzug',
  railway: 'Eisenbahn',
};

export const colorNames: Record<string, string> = {
  red: 'Rot',
  blue: 'Blau',
  green: 'Grün',
  yellow: 'Gelb',
  orange: 'Orange',
  purple: 'Lila',
  violet: 'Violett',
  white: 'Weiß',
  black: 'Schwarz',
  gray: 'Grau',
  brown: 'Braun',
};
