import type { DeepPartial } from '@shared/types/deepPartial.js';
import type { OsmTagToNameMapping } from './osmTagToNameMappingType.js';

export const osmTagToNameMapping: DeepPartial<OsmTagToNameMapping> = {
  access: {
    customers: 'Réservé aux clients',
    private: 'Élément privé',
    no: 'Élément à accès interdit',
  },
  aeroway: {
    aerodrome: 'Aérodrome',
    airstrip: 'Piste d’atterrissage',
    apron: 'Aire de trafic',
    gate: 'Porte d’embarquement',
    hangar: 'Hangar à avions',
    helipad: 'Hélipad',
    holding_position: 'Point d’attente',
    jet_bridge: 'Passerelle d’embarquement',
    navigationaid: 'Aide à la navigation aérienne',
    parking_position: 'Position de stationnement avion',
    runway: 'Piste',
    stopway: 'Prolongement d’arrêt',
    taxilane: 'Voie de circulation d’aire',
    taxiway: 'Voie de circulation',
    terminal: 'Terminal d’aéroport',
    threshold: 'Seuil de piste',
    tower: 'Tour de contrôle',
    windsock: 'Manche à air',
  },
  aerialway: {
    '*': 'Remontée mécanique',
    cable_car: 'Téléphérique',
    chair_lift: 'Télésiège',
    goods: 'Téléphérique de marchandises',
    'j-bar': 'Téléski à perche J',
    magic_carpet: 'Tapis roulant',
    mixed_lift: 'Télémix',
    platter: 'Téléski à assiettes',
    pylon: 'Pylône',
    rope_tow: 'Téléski à câble bas',
    station: 'Gare',
    't-bar': 'Téléski à perche T',
    zip_line: 'Tyrolienne',
  },
  amenity: {
    '*': '{}',
    animal_breeding: 'Élevage d’animaux',
    animal_shelter: 'Refuge pour animaux',
    arts_centre: 'Centre culturel',
    atm: 'Distributeur de billets',
    bank: 'Banque',
    bar: 'Bar',
    bbq: 'Barbecue',
    bench: 'Banc',
    bicycle_parking: 'Stationnement pour vélos',
    bicycle_rental: 'Location de vélos',
    bicycle_repair_station: 'Station de réparation de vélos',
    biergarten: 'Biergarten',
    brothel: 'Maison close',
    bureau_de_change: 'Bureau de change',
    bus_station: 'Gare routière',
    cafe: 'Café',
    car_rental: 'Location de voitures',
    car_wash: 'Station de lavage',
    casino: 'Casino',
    charging_station: 'Borne de recharge',
    childcare: 'Garde d’enfants',
    cinema: 'Cinéma',
    clinic: 'Clinique',
    clock: 'Horloge',
    college: 'Établissement d’enseignement supérieur',
    community_centre: 'Centre communautaire',
    compressed_air: 'Air comprimé',
    courthouse: 'Palais de justice',
    dentist: 'Dentiste',
    device_charging_station: 'Station de recharge d’appareils',
    doctors: 'Cabinet médical',
    dressing_room: 'Vestiaire',
    drinking_water: 'Eau potable',
    driving_school: 'Auto-école',
    embassy: 'Ambassade',
    events_venue: 'Salle d’événements',
    exhibition_centre: "Centre d'exposition",
    fast_food: 'Restauration rapide',
    feeding_place: 'Point de nourrissage',
    ferry_terminal: 'Terminal de ferry',
    fire_station: 'Caserne de pompiers',
    food_court: 'Aire de restauration',
    fountain: 'Fontaine',
    fuel: 'Station-service',
    funeral_hall: 'Salle funéraire',
    gambling: 'Jeux d’argent',
    game_feeding: 'Nourrissage du gibier',
    grave_yard: 'Cimetière',
    grit_bin: 'Bac à sel',
    hospital: 'Hôpital',
    hunting_stand: 'Mirador de chasse',
    ice_cream: 'Glacier',
    kindergarten: 'Jardin d’enfants',
    language_school: 'École de langues',
    letter_box: 'Boîte aux lettres privée',
    library: 'Bibliothèque',
    loading_dock: 'Quai de chargement',
    lounger: 'Transat',
    marketplace: 'Marché',
    monastery: 'Monastère',
    money_transfer: 'Transfert d’argent',
    motorcycle_parking: 'Stationnement pour motos',
    motorcycle_rental: 'Location de motos',
    nightclub: 'Boîte de nuit',
    parcel_locker: 'Consigne à colis',
    parking: 'Parking',
    parking_entrance: 'Entrée de parking',
    parking_space: 'Place de stationnement',
    pharmacy: 'Pharmacie',
    place_of_mourning: 'Funérarium',
    place_of_worship: 'Lieu de culte',
    planetarium: 'Planétarium',
    police: 'Police',
    post_box: 'Boîte aux lettres',
    post_office: 'Bureau de poste',
    prison: 'Prison',
    pub: 'Pub',
    public_bath: 'Bain public',
    public_bookcase: 'Boîte à livres',
    public_building: 'Bâtiment public',
    ranger_station: 'Poste de gardes forestiers',
    recycling: 'Recyclage',
    restaurant: 'Restaurant',
    school: 'École',
    shelter: {
      '*': 'Abri',
      shelter_type: {
        '*': 'Abri {}',
        basic_hut: 'Cabane sommaire',
        changing_rooms: 'Vestiaires',
        field_shelter: 'Abri de champ',
        lean_to: 'Appentis',
        picnic_shelter: {
          '*': 'Abri de pique-nique',
          fireplace: { yes: 'Abri de pique-nique avec foyer' },
        },
        public_transport: 'Abri de transport public',
        rock_shelter: 'Abri sous roche',
        sun_shelter: 'Abri solaire',
        weather_shelter: 'Abri météo',
      },
    },
    shower: 'Douche',
    ski_rental: 'Location de skis',
    smoking_area: 'Zone fumeurs',
    social_centre: 'Centre social',
    social_facility: {
      '*': 'Établissement social',
      social_facility: {
        ambulatory_care: 'Soins ambulatoires',
        assisted_living: 'Résidence services',
        clothing_bank: 'Banque de vêtements',
        day_care: 'Accueil de jour',
        food_bank: 'Banque alimentaire',
        group_home: 'Foyer d’hébergement',
        hospice: 'Centre de soins palliatifs',
        nursing_home: 'Maison de retraite médicalisée',
        shelter: 'Hébergement d’urgence',
        soup_kitchen: 'Soupe populaire',
        workshop: 'Atelier protégé',
      },
    },
    stripclub: 'Club de striptease',
    studio: 'Studio',
    taxi: 'Taxi',
    telephone: 'Téléphone',
    theatre: 'Théâtre',
    toilets: 'WC, toilettes',
    townhall: 'Mairie',
    traffic_park: 'Piste d’éducation routière',
    trolley_bay: 'Abri à chariots',
    university: 'Université',
    vacuum_cleaner: 'Aspirateur',
    vehicle_inspection: 'Contrôle technique',
    vending_machine: {
      '*': 'Distributeur automatique',
      vending: {
        bicycle_tube: 'Distributeur de chambres à air',
        bread: 'Distributeur de pain',
        bottle_return: 'Machine de consigne de bouteilles',
        candles: 'Distributeur de bougies',
        chewing_gums: 'Distributeur de chewing-gums',
        cigarettes: 'Distributeur de cigarettes',
        coffee: 'Distributeur de café',
        condoms: 'Distributeur de préservatifs',
        drinks: 'Distributeur de boissons',
        elongated_coin: 'Machine à médailles souvenirs',
        eggs: 'Distributeur d’œufs',
        excrement_bags: 'Distributeur de sacs à déjections',
        food: 'Distributeur de nourriture',
        fuel: 'Distributeur de carburant',
        gas: 'Distributeur de gaz',
        ice_cream: 'Distributeur de glaces',
        ice_cubes: 'Distributeur de glaçons',
        milk: 'Distributeur de lait',
        movies: 'Distributeur de films',
        newspapers: 'Distributeur de journaux',
        parking_tickets: 'Horodateur',
        pizza: 'Distributeur de pizzas',
        public_transport_tickets: 'Distributeur de titres de transport',
        stamps: 'Distributeur de timbres',
        sweets: 'Distributeur de confiseries',
        water: 'Distributeur d’eau',
      },
    },
    veterinary: 'Vétérinaire',
    waste_basket: 'Poubelle',
    waste_disposal: 'Point de collecte des déchets',
    water_point: 'Point d’eau potable',
    watering_place: 'Abreuvoir',
  },
  attraction: {
    animal: 'Attraction animalière',
    amusement_ride: 'Manège',
    big_wheel: 'Grande roue',
    carousel: 'Carrousel',
    historic: 'Attraction historique',
    maze: 'Labyrinthe',
    roller_coaster: 'Montagnes russes',
    summer_toboggan: 'Piste de luge d’été',
    train: 'Petit train touristique',
    water_slide: 'Toboggan aquatique',
  },
  barrier: {
    '*': 'Barrière {}',
    block: 'Bloc',
    bollard: 'Borne',
    border_control: 'Poste frontière',
    cable_barrier: 'Barrière à câbles',
    chain: 'Chaîne',
    city_wall: 'Muraille',
    ditch: 'Fossé (barrière)',
    entrance: 'Entrée',
    fence: 'Clôture',
    gate: 'Portail',
    guard_rail: 'Glissière de sécurité',
    handrail: 'Main courante',
    hedge: 'Haie',
    kerb: 'Bordure',
    lift_gate: 'Barrière levante',
    retaining_wall: 'Mur de soutènement',
    rope: 'Corde',
    sliding_gate: 'Portail coulissant',
    swing_gate: 'Barrière pivotante',
    turnstile: 'Tourniquet',
    wall: 'Mur',
  },
  boundary: {
    '*': 'Région',
    aboriginal_lands: 'Territoire autochtone',
    administrative: {
      '*': 'Région administrative',
      admin_level: {
        '2': 'Pays',
        '3': 'Région',
        '4': 'District',
        '5': 'Province',
        '6': 'Ville',
        '7': 'Région',
        '8': 'District',
        '9': 'Village',
        '10': 'Territoire cadastral',
      },
    },
    cadastral: 'Limite cadastrale',
    census: 'Zone de recensement',
    forest_compartment: 'Parcelle forestière',
    forest_planning: "Unité d'aménagement forestier",
    'geomorphological-unit': 'Unité géomorphologique',
    health: 'Zone de santé',
    local_authority: "Territoire d'une collectivité locale",
    maritime: 'Frontière maritime',
    marker: 'Borne frontière',
    national_park: 'Parc national',
    political: 'Circonscription électorale',
    postal_code: 'Zone de code postal',
    protected_area: 'Zone protégée',
    religious_administration: 'Circonscription religieuse',
    statistical: 'Zone statistique',
    water_protection_area: 'Périmètre de protection des eaux',
  },
  'abandoned:building': { '*': 'Bâtiment abandonné' },
  club: {
    '*': 'Club',
    automobile: 'Club automobile',
    charity: 'Club caritatif',
    culture: 'Club culturel',
    fishing: 'Club de pêche',
    hunting: 'Club de chasse',
    music: 'Club de musique',
    nature: 'Club de protection de la nature',
    scout: 'Groupe scout',
    social: 'Club social',
    sport: 'Club sportif',
    veterans: "Club d'anciens combattants",
  },
  'disused:building': { '*': 'Bâtiment désaffecté' },
  healthcare: {
    '*': 'Établissement de santé',
    alternative: 'Médecine alternative',
    audiologist: 'Audiologiste',
    blood_donation: 'Centre de don du sang',
    centre: 'Centre de santé',
    clinic: 'Clinique',
    counselling: 'Centre de conseil',
    dentist: 'Dentiste',
    dialysis: 'Centre de dialyse',
    doctor: 'Cabinet médical',
    hospital: 'Hôpital',
    laboratory: "Laboratoire d'analyses",
    midwife: 'Sage-femme',
    nurse: 'Service infirmier',
    optometrist: 'Optométriste',
    pharmacy: 'Pharmacie',
    physiotherapist: 'Physiothérapeute',
    podiatrist: 'Podologue',
    psychotherapist: 'Psychothérapeute',
    rehabilitation: 'Centre de rééducation',
    speech_therapist: 'Orthophoniste',
  },
  junction: {
    '*': 'Carrefour',
    circular: 'Carrefour giratoire',
    intersection: 'Intersection',
    jughandle: 'Jughandle',
    roundabout: 'Rond-point',
  },
  lock: {
    '*': 'Écluse',
  },
  office: {
    '*': 'Bureau',
    accountant: 'Comptable',
    advertising_agency: 'Agence de publicité',
    architect: 'Architecte',
    association: 'Association',
    company: "Bureau d'entreprise",
    consulting: 'Cabinet de conseil',
    coworking: 'Espace de coworking',
    diplomatic: 'Représentation diplomatique',
    educational_institution: "Établissement d'enseignement",
    employment_agency: "Agence pour l'emploi",
    energy_supplier: "Fournisseur d'énergie",
    estate_agent: 'Agence immobilière',
    financial: 'Services financiers',
    financial_advisor: 'Conseiller financier',
    forestry: 'Office forestier',
    government: 'Administration publique',
    insurance: "Bureau d'assurance",
    it: 'Entreprise informatique',
    lawyer: 'Avocat',
    logistics: 'Entreprise de logistique',
    newspaper: 'Rédaction de journal',
    ngo: 'Organisation non gouvernementale',
    notary: 'Notaire',
    political_party: 'Parti politique',
    property_management: 'Gestion immobilière',
    religion: 'Bureau religieux',
    research: 'Bureau de recherche',
    security: 'Société de sécurité',
    tax_advisor: 'Conseiller fiscal',
    telecommunication: 'Bureau de télécommunications',
    travel_agent: 'Agence de voyage',
    union: 'Bureau syndical',
    water_utility: 'Régie des eaux',
  },
  'ruins:building': { '*': 'Ruines d’un bâtiment' },
  building: {
    '*': {
      '*': 'Bâtiment',
      abandoned: {
        yes: 'Bâtiment abandonné',
      },
      disused: {
        yes: 'Bâtiment désaffecté',
      },
      ruins: {
        yes: 'Ruines d’un bâtiment',
      },
    },
    abandoned: 'Bâtiment abandonné',
    agricultural: 'Bâtiment agricole',
    allotment_house: 'Cabanon de jardin',
    boathouse: 'Hangar à bateaux',
    carport: 'Abri de voiture',
    college: "Bâtiment d'établissement supérieur",
    container: 'Bâtiment en conteneur',
    disused: 'Bâtiment désaffecté',
    apartments: 'Immeuble d’habitation',
    barn: 'Grange',
    bungalow: 'Bungalow',
    bunker: 'Bunker',
    cabin: 'Cabane',
    cathedral: 'Cathédrale',
    chapel: 'Chapelle',
    church: 'Église',
    civic: 'Bâtiment public',
    collapsed: 'Bâtiment effondré',
    commercial: 'Bâtiment commercial',
    construction: 'Bâtiment en construction',
    cowshed: 'Étable',
    detached: 'Maison isolée',
    dormitory: 'Résidence collective',
    entrance: 'Entrée de bâtiment',
    farm_auxiliary: 'Bâtiment agricole annexe',
    farm: 'Ferme',
    fire_station: 'Bâtiment de caserne de pompiers',
    garage: 'Garage',
    garages: 'Garages',
    government: 'Bâtiment gouvernemental',
    grandstand: 'Tribune',
    greenhouse: 'Serre',
    hangar: 'Hangar',
    hayloft: 'Fenil',
    historic: 'Bâtiment historique',
    hospital: 'Bâtiment hospitalier',
    hotel: 'Bâtiment d’hôtel',
    house: 'Maison individuelle',
    houseboat: 'Maison flottante',
    hut: 'Cabane',
    industrial: 'Bâtiment industriel',
    kindergarten: 'Bâtiment de maternelle',
    kiosk: 'Kiosque',
    manufacture: 'Bâtiment de fabrication',
    mosque: 'Mosquée',
    office: 'Immeuble de bureaux',
    outbuilding: 'Dépendance',
    parking: 'Bâtiment de stationnement',
    pavilion: 'Pavillon',
    public: 'Bâtiment public',
    residential: 'Bâtiment résidentiel',
    retail: 'Commerce de détail',
    roof: 'Toit',
    ruins: 'Ruines de bâtiment',
    school: 'Bâtiment scolaire',
    semidetached_house: 'Maison jumelée',
    service: 'Bâtiment technique',
    shed: 'Remise',
    shrine: 'Sanctuaire',
    silo: 'Silo',
    sports_centre: 'Bâtiment de centre sportif',
    sports_hall: 'Salle de sport',
    stable: 'Écurie',
    stadium: 'Bâtiment de stade',
    static_caravan: 'Mobil-home',
    storage_tank: 'Réservoir de stockage',
    sty: 'Porcherie',
    supermarket: 'Bâtiment de supermarché',
    synagogue: 'Synagogue',
    temple: 'Temple',
    tent: 'Tente permanente',
    terrace: 'Maison en rangée',
    toilets: 'Bâtiment de toilettes',
    train_station: 'Gare',
    transformer_tower: 'Tour de transformation',
    transportation: 'Bâtiment de transport',
    university: 'Bâtiment universitaire',
    warehouse: 'Entrepôt',
    yes: 'Bâtiment indéterminé',
  },
  fixme: {
    '*': 'Élément mal ou partiellement cartographié',
  },
  ford: {
    yes: 'Gué',
  },
  bridge: {
    '*': {
      '*': 'Pont',
      highway: {
        '*': 'Pont routier',
      },
      railway: {
        '*': 'Pont ferroviaire',
      },
    },
    no: '',
  },
  tunnel: {
    '*': {
      '*': 'Tunnel',
      highway: {
        '*': 'Tunnel routier',
      },
      railway: {
        '*': 'Tunnel ferroviaire',
      },
    },
    culvert: 'Ponceau',
    no: '',
  },
  oneway: {
    yes: 'Sens unique',
  },
  foot: {
    no: 'Accès piéton interdit',
    yes: 'Accès piéton autorisé',
    private: 'Accès piéton réservé aux propriétaires',
    designated: 'Réservé aux piétons',
  },
  bicycle: {
    no: 'Accès vélo interdit',
    yes: 'Accès vélo autorisé',
    private: 'Accès vélo réservé aux propriétaires',
    designated: 'Réservé aux vélos',
  },
  vehicle: {
    no: 'Accès véhicule interdit',
    yes: 'Accès véhicule autorisé',
    private: 'Accès véhicule réservé aux propriétaires',
    designated: 'Réservé aux véhicules',
  },
  motor_vehicle: {
    no: 'Accès véhicule motorisé interdit',
    yes: 'Accès véhicule motorisé autorisé',
    private: 'Accès véhicule motorisé réservé aux propriétaires',
    designated: 'Réservé aux véhicules motorisés',
  },
  craft: {
    '*': 'Artisan {}',
    yes: 'Artisan',
    bakery: 'Boulangerie',
    beekeeper: 'Apiculteur',
    blacksmith: 'Forgeron',
    brewery: 'Brasserie',
    builder: 'Entreprise de construction',
    carpenter: 'Charpentier',
    caterer: 'Traiteur',
    cleaning: 'Entreprise de nettoyage',
    confectionery: 'Confiseur',
    distillery: 'Distillerie',
    dressmaker: 'Couturière',
    electrician: 'Électricien',
    electronics_repair: 'Réparation électronique',
    gardener: 'Jardinier',
    glaziery: 'Vitrier',
    grinding_mill: 'Moulin',
    handicraft: 'Artisanat',
    hvac: 'Chauffage et climatisation',
    jeweller: 'Bijoutier',
    joiner: 'Menuisier',
    key_cutter: 'Reproduction de clés',
    locksmith: 'Serrurier',
    metal_construction: 'Construction métallique',
    painter: 'Peintre',
    photographer: 'Photographe',
    plumber: 'Plombier',
    pottery: 'Poterie',
    roofer: 'Couvreur',
    sawmill: 'Scierie',
    shoemaker: 'Cordonnier',
    signmaker: 'Enseigniste',
    stonemason: 'Tailleur de pierre',
    tailor: 'Tailleur',
    tiler: 'Carreleur',
    upholsterer: 'Tapissier',
    watchmaker: 'Horloger',
    window_construction: 'Fabricant de fenêtres',
    winery: 'Cave viticole',
  },
  emergency: {
    access_point: 'Point de secours',
    ambulance_station: "Station d'ambulances",
    assembly_point: 'Point de rassemblement',
    defibrillator: 'Défibrillateur',
    fire_extinguisher: 'Extincteur',
    fire_hose: "Tuyau d'incendie",
    fire_hydrant: "Bouche d'incendie",
    fire_water_pond: "Réserve d'eau incendie",
    landing_site: "Zone d'atterrissage d'urgence",
    life_ring: 'Bouée de sauvetage',
    lifeguard: 'Poste de secours',
    phone: 'Téléphone d’urgence',
    siren: 'Sirène',
    suction_point: "Point d'aspiration",
    water_tank: "Citerne d'incendie",
  },
  entrance: {
    '*': 'Entrée',
    main: 'Entrée principale',
    secondary: 'Entrée secondaire',
    service: 'Entrée de service',
    exit: 'Sortie',
    entrance: 'Entrée (seulement)',
    emergency: 'Sortie de secours',
    staircase: 'Entrée d’escalier',
    home: 'Entrée d’une maison/habitation/jardin/appartement privé',
    garage: 'Entrée de garage',
    shop: 'Entrée de magasin',
    no: 'Pas d’entrée',
  },
  highway: {
    '*': 'Route {}',
    bridleway: 'Piste cavalière',
    bus_stop: 'Arrêt de bus',
    busway: 'Voie de bus',
    construction: 'Route en construction',
    corridor: 'Couloir intérieur',
    crossing: 'Passage piéton',
    cycleway: 'Piste cyclable',
    elevator: 'Ascenseur',
    emergency_access_point: 'Point de secours',
    emergency_bay: "Aire d'arrêt d'urgence",
    escape: 'Voie de détresse',
    footway: 'Trottoir',
    give_way: 'Cédez le passage',
    hitchhiking: "Point d'auto-stop",
    ladder: 'Échelle',
    living_street: 'Zone de rencontre',
    milestone: 'Borne kilométrique',
    mini_roundabout: 'Mini-giratoire',
    motorway: 'Autoroute',
    motorway_junction: 'Échangeur autoroutier',
    motorway_link: 'Bretelle d’autoroute',
    passing_place: 'Aire de croisement',
    path: {
      '*': 'Chemin',
      foot: {
        designated: {
          bicycle: {
            designated: 'Chemin piéton et cyclable partagé',
          },
        },
      },
    },
    pedestrian: 'Zone piétonne',
    piste: 'Piste (ski)',
    platform: 'Quai',
    primary: 'Route primaire',
    primary_link: 'Bretelle de route primaire',
    priority: 'Panneau de priorité',
    proposed: 'Route en projet',
    raceway: 'Circuit de course',
    residential: 'Rue',
    rest_area: 'Aire de repos',
    road: 'Route de type inconnu',
    secondary: 'Route secondaire',
    secondary_link: 'Bretelle de route secondaire',
    service: {
      '*': 'Voie de desserte',
      service: {
        '*': 'Voie de desserte {}',
        alley: 'Ruelle',
        bus: 'Voie réservée aux transports en commun',
        'drive-through': 'Service au volant',
        driveway: 'Allée privée',
        emergency_access: 'Voie d’accès de secours',
        parking_aisle: 'Allée de parking',
      },
    },
    services: 'Aire de service',
    speed_camera: 'Radar de vitesse',
    speed_display: 'Radar pédagogique',
    steps: 'Escaliers, marches',
    stop: 'Panneau stop',
    street_lamp: 'Lampadaire',
    tertiary: 'Route tertiaire',
    tertiary_link: 'Bretelle de route tertiaire',
    toll_gantry: 'Portique de péage',
    track: {
      '*': 'Chemin d’exploitation de qualité inconnue',
      tracktype: {
        grade1: 'Chemin compacté',
        grade2: 'Chemin majoritairement compacté',
        grade3: 'Chemin non revêtu peu stabilisé',
        grade4: 'Chemin carrossable par tracteur',
        grade5: 'Chemin à peine perceptible',
      },
    },
    traffic_calming: 'Dispositif de ralentissement',
    traffic_island: 'Îlot directionnel',
    traffic_mirror: 'Miroir routier',
    traffic_sign: 'Panneau de signalisation',
    traffic_signals: 'Feux de circulation',
    trailhead: 'Départ de sentier',
    trunk: 'Voie rapide',
    trunk_link: 'Bretelle de voie rapide',
    turning_circle: 'Aire de retournement',
    turning_loop: 'Boucle de retournement',
    unclassified: 'Route non classée',
    via_ferrata: 'Via ferrata',
  },
  historic: {
    '*': 'Structure historique {}',
    battlefield: 'Champ de bataille',
    bomb_crater: 'Cratère de bombe',
    bunker: 'Bunker historique',
    dome: 'Dôme historique',
    quarry: 'Carrière historique',
    railway: 'Chemin de fer historique',
    railway_station: 'Gare historique',
    roman_road: 'Voie romaine',
    tower: 'Tour historique',
    yes: 'Structure historique',
    aircraft: 'Avion historique',
    archaeological_site: 'Site archéologique',
    boundary_stone: 'Borne frontière historique',
    building: 'Bâtiment historique',
    cannon: 'Canon historique',
    castle: 'Château',
    charcoal_pile: 'Site de charbonnière',
    church: 'Église historique',
    city_gate: 'Porte de ville',
    citywalls: 'Remparts',
    fort: 'Fort',
    heritage: 'Site patrimonial',
    hollow_way: 'Chemin creux',
    house: 'Maison historique',
    manor: 'Manoir',
    memorial: 'Mémorial',
    milestone: 'Borne historique',
    mine_shaft: 'Puits de mine historique',
    mine: 'Mine historique',
    monastery: 'Monastère historique',
    monument: 'Monument',
    ruins: {
      '*': 'Ruines',
      ruins: {
        castle: 'Ruines de château',
      },
    },
    shieling: 'Chalet d’alpage (saisonnier)',
    stone: 'Pierre historique',
    tomb: 'Tombeau',
    tree_shrine: 'Arbre sanctuaire',
    wayside_cross: 'Croix de chemin',
    wayside_shrine: 'Oratoire',
    wreck: 'Épave',
  },
  landuse: {
    '*': '{}',
    allotments: 'Jardins familiaux',
    animal_keeping: "Élevage d'animaux",
    apiary: 'Zone de rucher',
    aquaculture: 'Aquaculture',
    basin: 'Bassin',
    brownfield: 'Friche industrielle',
    cemetery: 'Cimetière',
    churchyard: "Terrain d'église",
    civic: 'Terrain civique',
    civic_admin: 'Terrain administratif',
    commercial: 'Zone commerciale',
    conservation: 'Zone de conservation',
    construction: 'Chantier',
    culture: 'Terrain culturel',
    depot: 'Dépôt',
    education: 'Zone d’enseignement',
    emergency: 'Terrain des services de secours',
    fairground: 'Champ de foire',
    farm: 'Terre agricole',
    farmland: 'Terres agricoles',
    farmyard: 'Cour de ferme',
    flowerbed: 'Parterre de fleurs',
    forest: 'Forêt',
    forestry: 'Terrain forestier',
    garages: 'Garages',
    garden: 'Espace de jardin',
    grass: 'Pelouse',
    greenery: 'Espace vert',
    greenfield: 'Terrain à bâtir',
    greenhouse_horticulture: 'Horticulture sous serre',
    harbour: 'Zone portuaire',
    healthcare: 'Terrain de santé',
    highway: 'Emprise routière',
    houseboat: 'Mouillage de péniches',
    industrial: 'Zone industrielle',
    institutional: 'Terrain institutionnel',
    landfill: 'Décharge',
    logging: 'Coupe forestière',
    meadow: 'Prairie',
    military: 'Zone militaire',
    mine_spoils: 'Zone de terril',
    orchard: 'Verger',
    paddock: 'Enclos',
    peat_cutting: 'Tourbière exploitée',
    pedestrian: 'Zone piétonne',
    piste: 'Zone de piste de ski',
    plant_nursery: 'Pépinière',
    plantation: 'Plantation',
    quarry: 'Carrière',
    railway: 'Emprise ferroviaire',
    recreation_ground: 'Terrain de loisirs',
    religious: 'Terrain religieux',
    reservoir: 'Réservoir',
    residential: 'Zone résidentielle',
    retail: 'Zone commerciale (détail)',
    salt_pond: 'Marais salant',
    school: "Terrain d'école",
    shrubs: 'Arbustes',
    static_caravan: 'Terrain de mobil-homes',
    storage: 'Zone de stockage',
    tourism: 'Zone touristique',
    traffic_island: "Zone d'îlot directionnel",
    tree_pit: "Fosse d'arbre",
    village_green: 'Pelouse communale',
    vineyard: 'Vignoble',
    wasteland: 'Terrain vague',
    winter_sports: 'Sports d’hiver',
  },
  leisure: {
    '*': '{}',
    adult_gaming_centre: 'Salle de jeux pour adultes',
    amusement_arcade: 'Salle d’arcade',
    bandstand: 'Kiosque à musique',
    bathing_place: 'Lieu de baignade',
    beach_resort: 'Station balnéaire',
    bird_hide: 'Observatoire ornithologique',
    bleachers: 'Gradins',
    bowling_alley: 'Bowling',
    common: 'Terrain communal',
    dance: 'Salle de danse',
    disc_golf_course: 'Parcours de disc-golf',
    dog_park: 'Parc canin',
    escape_game: 'Escape game',
    firepit: 'Foyer',
    fishing: 'Pêche',
    fitness_centre: 'Salle de fitness',
    fitness_station: 'Station de fitness',
    garden: 'Jardin',
    golf_course: 'Parcours de golf',
    hackerspace: 'Hackerspace',
    high_ropes_course: 'Parcours acrobatique en hauteur',
    horse_riding: 'Équitation',
    hot_tub: 'Bain à remous',
    ice_rink: 'Patinoire',
    indoor_play: 'Aire de jeux couverte',
    marina: 'Marina',
    miniature_golf: 'Mini-golf',
    nature_reserve: 'Réserve naturelle',
    outdoor_seating: 'Terrasse',
    park: 'Parc',
    picnic_table: {
      '*': 'Table de pique-nique',
      covered: {
        yes: 'Table de pique-nique couverte',
        no: 'Table de pique-nique découverte',
      },
    },
    pitch: 'Terrain de sport',
    playground: 'Aire de jeux',
    recreation_ground: 'Terrain de loisirs',
    resort: 'Complexe de loisirs',
    schoolyard: "Cour d'école",
    slipway: 'Cale de mise à l’eau',
    sauna: {
      '*': 'Sauna',
      sauna: {
        hot: 'Sauna finlandais',
        steam: 'Hammam',
        smoke: 'Sauna à fumée (finlandais)',
        dry: 'Sauna sec',
        hanjeungmak: 'Hanjeungmak (sauna coréen)',
        aroma: 'Sauna aux arômes',
        infrared: 'Sauna infrarouge',
      },
    },
    sports_centre: 'Centre sportif',
    sports_hall: 'Salle de sport',
    stadium: 'Stade',
    summer_camp: 'Colonie de vacances',
    sunbathing: 'Espace de bronzage',
    swimming_area: 'Zone de baignade',
    swimming_pool: 'Piscine',
    tanning_salon: 'Salon de bronzage',
    track: {
      '*': 'Piste',
      sport: {
        cycling: 'Piste de cyclisme',
        equestrian: 'Piste équestre',
        horse_racing: 'Hippodrome',
      },
    },
    trampoline_park: 'Parc de trampolines',
    water_park: 'Parc aquatique',
    wildlife_hide: 'Observatoire animalier',
  },
  man_made: {
    '*': '{}',
    adit: {
      '*': 'Galerie de mine',
      disused: {
        yes: 'Galerie de mine désaffectée',
      },
    },
    antenna: 'Antenne',
    apiary: 'Rucher',
    beacon: 'Balise',
    beehive: 'Ruche',
    breakwater: 'Brise-lames',
    bridge: 'Pont',
    bunker_silo: 'Silo-couloir',
    cairn: 'Cairn',
    cellar_entrance: 'Entrée de cave',
    chimney: 'Cheminée',
    clearcut: 'Coupe rase',
    communications_tower: 'Grande tour de télécommunication',
    cooling_tower: 'Tour de refroidissement',
    crane: 'Grue',
    cross: 'Croix',
    cutline: 'Layon',
    dyke: 'Digue',
    embankment: 'Remblai',
    flagpole: 'Mât de drapeau',
    "forester's_lodge": 'Maison forestière',
    gasometer: 'Gazomètre',
    goods_conveyor: 'Convoyeur à marchandises',
    groyne: 'Épi (brise-lames)',
    lighthouse: 'Phare',
    manhole: 'Regard',
    mast: {
      '*': 'Mât',
      'tower:type': {
        clock: 'Mât d’horloge',
        communication: 'Mât de communication',
        lighting: 'Mât d’éclairage',
        monitoring: 'Mât de surveillance',
        radar: 'Mât radar',
        siren: 'Mât de sirène',
      },
    },
    mineshaft: {
      '*': 'Puits de mine',
      disused: {
        yes: 'Puits de mine désaffecté',
      },
    },
    monitoring_station: 'Station de surveillance',
    nesting_site: 'Site de nidification',
    observatory: 'Observatoire',
    pier: 'Jetée',
    pipeline: {
      '*': 'Conduite',
      location: {
        underground: 'Conduite souterraine',
        underwater: 'Conduite sous-marine',
      },
    },
    pumping_station: 'Station de pompage',
    quay: 'Quai',
    reservoir_covered: 'Réservoir couvert',
    silo: 'Silo',
    snow_cannon: 'Canon à neige',
    spoil_heap: 'Terril',
    spring_box: 'Captage de source',
    storage_tank: 'Réservoir de stockage',
    street_cabinet: 'Armoire de rue',
    surveillance: 'Vidéosurveillance',
    survey_point: 'Point géodésique',
    telescope: 'Télescope',
    tower: {
      '*': 'Tour',
      'tower:type': {
        bell_tower: 'Clocher',
        climbing: 'Tour d’escalade',
        clock: 'Tour d’horloge',
        communication: 'Tour de communication',
        cooling: 'Tour de refroidissement',
        defensive: 'Tour défensive',
        diving: 'Plongeoir',
        hose: 'Tour de séchage des tuyaux',
        lighting: 'Tour d’éclairage',
        minaret: 'Minaret',
        monitoring: 'Tour de surveillance',
        observation: 'Tour d’observation',
        pagoda: 'Pagode',
        radar: 'Tour radar',
        siren: 'Tour de sirène',
        watchtower: 'Tour de guet',
      },
    },
    tunnel: 'Galerie technique',
    utility_pole: 'Poteau',
    wastewater_plant: 'Station d’épuration',
    water_tap: 'Robinet d’eau',
    water_tower: 'Château d’eau',
    water_well: 'Puits',
    water_works: 'Usine des eaux',
    watermill: 'Moulin à eau',
    windmill: 'Moulin à vent',
    works: 'Usine',
  },
  military: {
    '*': 'Installation militaire {}',
    academy: 'Académie militaire',
    airfield: 'Aérodrome militaire',
    ammunition: 'Dépôt de munitions',
    barracks: 'Caserne',
    base: 'Base militaire',
    bunker: 'Bunker',
    checkpoint: 'Poste de contrôle militaire',
    danger_area: 'Zone militaire dangereuse',
    depot: 'Dépôt militaire',
    launchpad: 'Aire de lancement',
    naval_base: 'Base navale',
    nuclear_explosion_site: 'Site d’essais nucléaires',
    obstacle_course: 'Parcours du combattant',
    office: 'Bureau militaire',
    range: 'Champ de tir',
    school: 'École militaire',
    training_area: 'Terrain d’entraînement militaire',
    trench: 'Tranchée',
  },
  mountain_pass: {
    yes: 'Col de montagne',
  },
  natural: {
    '*': '{}',
    arch: 'Arche rocheuse',
    arete: 'Arête',
    bare_rock: 'Roche nue',
    basin: 'Bassin',
    bay: 'Baie',
    beach: 'Plage',
    birds_nest: 'Nid d’oiseau',
    cape: 'Cap',
    cave_entrance: 'Grotte',
    cliff: 'Falaise',
    crevasse: 'Crevasse',
    dune: 'Dune',
    earth_bank: 'Talus',
    fell: 'Lande d’altitude',
    geyser: 'Geyser',
    glacier: 'Glacier',
    grass: 'Pelouse',
    grassland: 'Prairie naturelle',
    gully: 'Ravine',
    heath: 'Lande',
    hill: 'Colline',
    hot_spring: 'Source chaude',
    isthmus: 'Isthme',
    land: 'Terre',
    landform: 'Relief',
    landslide: 'Glissement de terrain',
    mountain_range: 'Chaîne de montagnes',
    mud: 'Boue',
    peak: 'Sommet',
    peninsula: 'Péninsule',
    plain: 'Plaine',
    plateau: 'Plateau',
    reef: 'Récif',
    ridge: 'Crête',
    rock: 'Rocher',
    saddle: 'Col (selle)',
    sand: 'Sable',
    scree: 'Éboulis',
    scrub: 'Broussailles',
    shingle: 'Galets',
    shoal: 'Haut-fond',
    shrub: 'Arbuste',
    shrubbery: "Massif d'arbustes",
    sinkhole: 'Doline',
    spring: {
      '*': 'Source',
      drinking_water: {
        yes: 'Source potable',
        no: 'Source non potable',
      },
      refitted: {
        yes: 'Source aménagée',
        no: 'Source non aménagée',
      },
      intermittent: {
        yes: 'Source intermittente',
      },
      seasonal: {
        yes: 'Source saisonnière',
      },
      water_characteristic: {
        '*': 'Source minérale',
      },
    },
    stone: 'Pierre',
    strait: 'Détroit',
    tree: {
      '*': 'Arbre',
      protected: { yes: 'Arbre protégé' },
      denotation: {
        natural_monument: 'Arbre monument naturel',
        landmark: 'Arbre remarquable',
        avenue: 'Arbre d’alignement',
        urban: 'Arbre urbain',
        agricultural: 'Arbre agricole',
      },
    },
    tree_group: 'Bosquet',
    tree_row: 'Rangée d’arbres',
    tree_stump: 'Souche',
    valley: 'Vallée',
    volcano: 'Volcan',
    water: {
      '*': 'Plan d’eau',

      water: {
        basin: 'Bassin',
        canal: 'Canal',
        ditch: 'Fossé',
        drain: 'Fossé de drainage',
        fish_pass: 'Passe à poissons',
        lagoon: 'Lagune',
        lake: 'Lac',
        moat: 'Douve',
        oxbow: 'Bras mort',
        pond: 'Étang',
        reflecting_pool: 'Bassin miroir',
        reservoir: 'Réservoir',
        river: 'Rivière',
        salt_pond: 'Marais salant',
        stream: 'Ruisseau',
        stream_pool: 'Vasque',
        wastewater: "Bassin d'eaux usées",
      },
    },
    wetland: {
      '*': 'Zone humide',
      wetland: {
        bog: 'Tourbière',
        reedbed: 'Roselière',
        marsh: 'Marais',
        swamp: 'Marécage',
        wet_meadow: 'Prairie humide',
        mangrove: 'Mangrove',
        fen: 'Bas-marais',
      },
    },
    wood: 'Forêt',
  },
  obstacle: {
    '*': 'Obstacle {}',
    vegetation: 'Végétation dense',
    fallen_tree: 'Arbre(s) tombé(s)',
    unevenness: 'Irrégularité du terrain',
    precipice: 'Précipice',
    heap: 'Tas',
    hole: 'Trou',
    mud: 'Boue',
  },
  place: {
    '*': 'Lieu {}',
    allotments: 'Cité de jardins familiaux',
    archipelago: 'Archipel',
    borough: 'Arrondissement',
    cadastral_community: 'Commune cadastrale',
    city: 'Grande ville',
    city_block: 'Îlot urbain',
    civil_parish: 'Paroisse civile',
    country: 'Pays',
    county: 'Comté',
    croft: 'Petite ferme',
    district: 'District',
    farm: 'Ferme',
    hamlet: 'Hameau',
    island: 'Île',
    islet: 'Îlot',
    isolated_dwelling: 'Habitat isolé',
    locality: 'Lieu-dit',
    municipality: 'Commune',
    neighbourhood: 'Quartier',
    ocean: 'Océan',
    plot: 'Parcelle',
    province: 'Province',
    quarter: 'Quartier',
    region: 'Région',
    sea: 'Mer',
    square: 'Place',
    state: 'État',
    subdivision: 'Sous-quartier',
    suburb: 'Quartier',
    town: 'Ville',
    township: 'Township',
    village: 'Village',
    // Not real OSM tags: Nominatim classifies address objects, address
    // interpolations and computed postcode areas this way, and Photon falls back
    // to `yes` for a class it cannot use. See doc/photon-geocoder.md.
    house: 'Adresse',
    house_number: 'Adresse',
    postcode: 'Code postal',
    yes: 'Lieu',
  },
  playground: {
    '*': 'Équipement de jeu {}',
    activitypanel: "Panneau d'activités",
    aerialrotator: 'Manège suspendu',
    agility_trail: "Parcours d'agilité",
    baby_swing: 'Balançoire bébé',
    balancebeam: "Poutre d'équilibre",
    basketrotator: 'Panier tournant',
    basketswing: 'Balançoire nid',
    bridge: 'Pont de jeu',
    climbing: "Agrès d'escalade",
    climbing_pole: "Mât d'escalade",
    climbing_slope: "Pente d'escalade",
    climbingframe: 'Cage à grimper',
    climbingwall: "Mur d'escalade",
    cushion: 'Coussin gonflable',
    exercise: 'Agrès de fitness',
    hammock: 'Hamac',
    hopscotch: 'Marelle (aire de jeux)',
    horizontal_bar: 'Barre fixe',
    ladder: 'Échelle de jeu',
    platform: 'Plateforme de jeu',
    playhouse: 'Maisonnette de jeu',
    pump: 'Pompe de jeu',
    rope_traverse: 'Traversée de cordes',
    roundabout: 'Tourniquet de jeu',
    sandpit: 'Bac à sable',
    seesaw: 'Balançoire à bascule',
    sledding: 'Piste de luge',
    slide: 'Toboggan',
    spinner: 'Toupie',
    splash_pad: "Aire de jeux d'eau",
    spring_board: 'Planche à ressort',
    springy: 'Jeu à ressort',
    stepping_stone: 'Pas japonais',
    steps: 'Marches de jeu',
    structure: 'Structure de jeu',
    swing: 'Balançoire',
    teenshelter: 'Abri pour adolescents',
    trampoline: 'Trampoline de jeu',
    tunnel_tube: 'Tunnel de jeu',
    water: "Jeu d'eau",
    water_channel: "Canal d'eau de jeu",
    wobble_bridge: 'Pont oscillant',
    youth_bench: 'Banc pour adolescents',
    zipwire: 'Tyrolienne de jeu',
  },
  power: {
    '*': '{}',
    cable: 'Câble électrique',
    cable_distribution: 'Distribution par câble',
    cable_distribution_cabinet: 'Armoire de distribution',
    catenary_mast: 'Poteau caténaire',
    catenary_portal: 'Portique caténaire',
    circuit: 'Circuit électrique',
    compensator: 'Compensateur de puissance réactive',
    connection: 'Connexion de ligne électrique',
    converter: 'Convertisseur électrique',
    generator: {
      '*': 'Générateur électrique',
      'generator:source': {
        nuclear: {
          '*': 'Générateur nucléaire',
          'generator:method': {
            fission: 'Générateur à fission nucléaire',
            fusion: 'Générateur à fusion nucléaire',
          },
        },
        wind: {
          '*': 'Éolienne',
        },
        hydro: {
          '*': 'Générateur hydroélectrique',
          'generator:method': {
            'water-storage': 'Générateur hydroélectrique à réservoir',
            'water-pumped-storage':
              'Générateur hydroélectrique par pompage-turbinage',
            'run-of-the-river': 'Générateur hydroélectrique au fil de l’eau',
          },
        },
        tidal: {
          '*': 'Générateur marémoteur',
          'generator:method': {
            barrage: 'Générateur marémoteur à barrage',
            stream: 'Générateur hydrolien',
          },
        },
        wave: {
          '*': 'Générateur houlomoteur',
        },
        geothermal: {
          '*': 'Générateur géothermique',
        },
        solar: {
          '*': 'Générateur solaire',
          'generator:method': {
            thermal: 'Générateur solaire thermique',
            photovoltaic: 'Générateur solaire photovoltaïque',
          },
        },
        coal: {
          '*': 'Générateur au charbon',
        },
        gas: {
          '*': 'Générateur au gaz',
        },
        biomass: {
          '*': 'Générateur à biomasse',
          'generator:method': {
            combustion: 'Générateur à combustion de biomasse',
            gasification: 'Générateur à gazéification de biomasse',
            anaerobic_digestion:
              'Générateur à biomasse par digestion anaérobie',
          },
        },
        biofuel: {
          '*': 'Générateur à biocarburant',
        },
        biogas: {
          '*': 'Générateur au biogaz',
        },
        oil: {
          '*': 'Générateur au fioul',
        },
        diesel: {
          '*': 'Générateur diesel',
        },
        gasoline: {
          '*': 'Générateur à essence',
        },
        waste: {
          '*': 'Générateur de valorisation énergétique des déchets',
          'generator:method': {
            combustion: 'Générateur à incinération de déchets',
            gasification: 'Générateur à gazéification de déchets',
          },
        },
      },
    },
    heliostat: 'Héliostat',
    insulator: 'Isolateur',
    inverter: 'Onduleur',
    line: 'Ligne électrique',
    line_section: 'Tronçon de ligne électrique',
    minor_cable: 'Câble électrique secondaire',
    minor_line: 'Ligne électrique secondaire',
    minor_underground_cable: 'Câble souterrain secondaire',
    plant: {
      '*': 'Centrale électrique',
      'plant:source': {
        nuclear: {
          '*': 'Centrale nucléaire',
          'plant:method': {
            fission: 'Centrale à fission nucléaire',
            fusion: 'Centrale à fusion nucléaire',
          },
        },
        wind: {
          '*': 'Centrale éolienne',
        },
        hydro: {
          '*': 'Centrale hydroélectrique',
          'plant:method': {
            'water-storage': 'Centrale hydroélectrique à réservoir',
            'water-pumped-storage':
              'Centrale hydroélectrique par pompage-turbinage',
            'run-of-the-river': 'Centrale hydroélectrique au fil de l’eau',
          },
        },
        tidal: {
          '*': 'Centrale marémotrice',
          'plant:method': {
            barrage: 'Centrale marémotrice à barrage',
            stream: 'Centrale hydrolienne',
          },
        },
        wave: {
          '*': 'Centrale houlomotrice',
        },
        geothermal: {
          '*': 'Centrale géothermique',
        },
        solar: {
          '*': 'Centrale solaire',
          'plant:method': {
            thermal: 'Centrale solaire thermique',
            photovoltaic: 'Centrale solaire photovoltaïque',
          },
        },
        coal: {
          '*': 'Centrale au charbon',
        },
        gas: {
          '*': 'Centrale au gaz',
        },
        biomass: {
          '*': 'Centrale à biomasse',
          'plant:method': {
            combustion: 'Centrale à combustion de biomasse',
            gasification: 'Centrale à gazéification de biomasse',
            anaerobic_digestion: 'Centrale à biomasse par digestion anaérobie',
          },
        },
        biofuel: {
          '*': 'Centrale à biocarburant',
        },
        biogas: {
          '*': 'Centrale au biogaz',
        },
        oil: {
          '*': 'Centrale au fioul',
        },
        diesel: {
          '*': 'Centrale diesel',
        },
        gasoline: {
          '*': 'Centrale à essence',
        },
        waste: {
          '*': 'Centrale de valorisation énergétique des déchets',
          'plant:method': {
            combustion: 'Centrale à incinération de déchets',
            gasification: 'Centrale à gazéification de déchets',
          },
        },
      },
    },
    pole: 'Poteau électrique',
    portal: 'Portique de ligne électrique',
    roof_pole: 'Poteau de toit',
    substation: 'Poste électrique',
    switch: 'Sectionneur',
    switchgear: 'Appareillage de commutation',
    terminal: 'Terminaison de ligne électrique',
    tower: 'Pylône électrique',
    transformer: 'Transformateur',
    transition: 'Transition ligne-câble',
  },
  public_transport: {
    platform: 'Quai de transport en commun',
    station: 'Station',
    stop_position: 'Point d’arrêt',
  },
  railway: {
    '*': 'Voie ferrée',
    abandoned: 'Voie ferrée abandonnée',
    construction: 'Voie ferrée en construction',
    facility: 'Installation ferroviaire',
    junction: 'Bifurcation ferroviaire',
    milestone: 'Borne kilométrique ferroviaire',
    proposed: 'Voie ferrée en projet',
    disused: 'Voie ferrée désaffectée',
    funicular: 'Funiculaire',
    light_rail: 'Métro léger',
    miniature: 'Chemin de fer miniature',
    monorail: 'Monorail',
    narrow_gauge: 'Voie ferrée à voie étroite',
    rail: 'Ligne de chemin de fer',
    razed: 'Voie ferrée démantelée',
    signal_box: "Poste d'aiguillage",
    site: 'Site ferroviaire',
    subway: 'Ligne de métro',
    train_station_entrance: 'Entrée de gare',
    tram: 'Ligne de tramway',
    halt: 'Halte ferroviaire',
    platform: 'Quai ferroviaire',
    preserved: 'Chemin de fer touristique',
    station: 'Gare ferroviaire',
    stop: 'Arrêt ferroviaire',
    subway_entrance: 'Entrée de métro',
    tram_crossing: 'Traversée de tramway',
    tram_level_crossing: 'Passage à niveau de tramway',
    tram_stop: 'Arrêt de tramway',
    buffer_stop: 'Butoir',
    crossing: 'Traversée de voie ferrée (piétonne)',
    derail: 'Dérailleur de sécurité',
    railway_crossing: 'Croisement ferroviaire',
    roundhouse: 'Rotonde ferroviaire',
    signal: 'Signal ferroviaire',
    switch: 'Aiguillage',
    level_crossing: 'Passage à niveau',
    traverser: 'Chariot transbordeur',
    turntable: 'Plaque tournante',
    ventilation_shaft: 'Puits de ventilation ferroviaire',
    wash: 'Lavage de trains',
    water_crane: 'Grue hydraulique (ferroviaire)',
    workshop: 'Atelier ferroviaire',
    yard: 'Gare de triage',
  },
  shop: {
    '*': 'Magasin {}',
    agrarian: 'Magasin agricole',
    household_linen: 'Linge de maison',
    charity: 'Magasin caritatif',
    chocolate: 'Chocolaterie',
    fashion_accessories: 'Accessoires de mode',
    frozen_food: 'Surgelés',
    hearing_aids: 'Audioprothésiste',
    storage_rental: 'Location de box de stockage',
    telecommunication: 'Boutique de télécommunications',
    weapons: 'Armurerie',
    alcohol: 'Magasin d’alcools',
    antiques: 'Antiquités',
    art: 'Magasin d’art',
    baby_goods: 'Articles pour bébés',
    bag: 'Maroquinerie',
    bakery: 'Boulangerie',
    bathroom_furnishing: 'Équipement de salle de bain',
    beauty: 'Institut de beauté',
    bed: 'Magasin de literie',
    beverages: 'Magasin de boissons',
    bicycle: 'Magasin de vélos',
    bookmaker: 'Bureau de paris',
    books: 'Librairie',
    boutique: 'Boutique',
    butcher: 'Boucherie',
    camera: 'Magasin d’appareils photo',
    car: 'Concessionnaire automobile',
    car_parts: 'Pièces auto',
    car_repair: 'Garage automobile',
    carpet: 'Magasin de tapis',
    cheese: 'Fromagerie',
    chemist: 'Droguerie',
    clothes: 'Magasin de vêtements',
    coffee: 'Magasin de café',
    collector: 'Magasin de collection',
    computer: 'Magasin d’informatique',
    confectionery: 'Confiserie',
    convenience: 'Supérette',
    copyshop: 'Magasin de reprographie',
    cosmetics: 'Magasin de cosmétiques',
    craft: 'Magasin de loisirs créatifs',
    curtain: 'Magasin de rideaux',
    dairy: 'Crèmerie',
    deli: 'Épicerie fine',
    department_store: 'Grand magasin',
    doityourself: 'Magasin de bricolage',
    doors: 'Magasin de portes',
    dry_cleaning: 'Pressing',
    'e-cigarette': 'Cigarette électronique',
    electrical: 'Matériel électrique',
    electronics: 'Électronique',
    erotic: 'Sex-shop',
    fabric: 'Magasin de tissus',
    farm: 'Vente à la ferme',
    fireplace: 'Magasin de cheminées',
    fishing: 'Magasin de pêche',
    flooring: 'Magasin de revêtements de sol',
    florist: 'Fleuriste',
    funeral_directors: 'Pompes funèbres',
    furniture: 'Magasin de meubles',
    games: 'Magasin de jeux',
    garden_center: 'Jardinerie',
    garden_centre: 'Jardinerie',
    general: 'Magasin général',
    gift: 'Magasin de cadeaux',
    glaziery: 'Vitrerie',
    greengrocer: 'Primeur',
    hairdresser: 'Coiffeur',
    hardware: 'Quincaillerie',
    health_food: 'Magasin diététique',
    hifi: 'Magasin hi-fi',
    houseware: 'Articles ménagers',
    hunting: 'Magasin de chasse',
    ice_cream: 'Glacier',
    interior_decoration: 'Décoration intérieure',
    jewelry: 'Bijouterie',
    kiosk: 'Kiosque',
    kitchen: 'Magasin de cuisines',
    laundry: 'Laverie',
    lighting: 'Magasin de luminaires',
    locksmith: 'Serrurerie',
    lottery: 'Loterie',
    mall: 'Centre commercial',
    massage: 'Massages',
    medical_supply: 'Matériel médical',
    mobile_phone: 'Magasin de téléphonie mobile',
    model: 'Magasin de modélisme',
    motorcycle: 'Magasin de motos',
    music: 'Magasin de musique',
    musical_instrument: 'Magasin d’instruments de musique',
    newsagent: 'Marchand de journaux',
    nutrition_supplements: 'Compléments alimentaires',
    optician: 'Opticien',
    outdoor: 'Magasin de plein air',
    outpost: 'Point de retrait',
    paint: 'Magasin de peinture',
    pastry: 'Pâtisserie',
    pawnbroker: 'Prêteur sur gages',
    perfumery: 'Parfumerie',
    pet: 'Animalerie',
    pet_grooming: 'Toilettage pour animaux',
    photo: 'Magasin de photographie',
    radiotechnics: 'Composants électroniques',
    rental: 'Location',
    seafood: 'Poissonnerie',
    second_hand: 'Occasion',
    sewing: 'Mercerie',
    shoes: 'Magasin de chaussures',
    sports: 'Magasin de sport',
    stationery: 'Papeterie',
    supermarket: 'Supermarché',
    tailor: 'Tailleur',
    tattoo: 'Salon de tatouage',
    tea: 'Magasin de thé',
    ticket: 'Billetterie',
    tobacco: 'Bureau de tabac',
    toys: 'Magasin de jouets',
    trade: 'Matériaux de construction',
    travel_agency: 'Agence de voyage',
    tyres: 'Magasin de pneus',
    vacant: 'Local vacant',
    variety_store: 'Bazar',
    video: 'Vidéoclub',
    video_games: 'Magasin de jeux vidéo',
    watches: 'Horlogerie',
    wholesale: 'Vente en gros',
    window_blind: 'Magasin de stores',
    wine: 'Cave à vin',
  },
  sport: {
    '*': 'Sport {}',
    '10pin': 'Bowling (10 quilles)',
    '8pin': 'Bowling (8 quilles)',
    '9pin': 'Quilles (9 quilles)',
    'five-a-side': 'Football à cinq',
    'in-line_hockey': 'Roller in line hockey',
    'shot-put': 'Lancer du poids',
    aerobics: 'Aérobic',
    aikido: 'Aïkido',
    airsoft: 'Airsoft',
    american_football: 'Football américain',
    american_handball: 'Handball américain',
    archery: 'Tir à l’arc',
    association_football: 'Football (soccer)',
    athletics: 'Athlétisme',
    australian_football: 'Football australien',
    axe_throwing: 'Lancer de hache',
    badminton: 'Badminton',
    balle_pelote: 'Balle pelote',
    ballooning: 'Montgolfière',
    bandy: 'Bandy',
    barre: 'Barre au sol (fitness)',
    base: 'Saut BASE',
    baseball: 'Baseball',
    basketball: 'Basketball',
    batting_cage: 'Cage de frappe (baseball/softball)',
    beach_soccer: 'Beach soccer',
    beach_tennis: 'Beach tennis',
    beachhandball: 'Beach handball',
    beachtennis: 'Beach tennis',
    beachvolleyball: 'Beach-volley',
    biathlon: 'Biathlon',
    bicycle: 'Cyclisme (sport)',
    billards: 'Billard',
    billiards: 'Billard',
    bmx: 'BMX',
    bobsleigh: 'Bobsleigh',
    bodybuilding: 'Culturisme',
    boules: 'Boules',
    bowling: 'Bowling',
    bowls: 'Boulingrin',
    boxing: 'Boxe',
    bullfighting: 'Tauromachie',
    calisthenics: 'Callisthénie',
    canadian_football: 'Football canadien',
    candlepin: 'Bowling candlepin',
    canoe_polo: 'Kayak-polo',
    canoe: 'Canoë',
    chess: 'Échecs',
    chinlone: 'Chinlone',
    cliff_diving: 'Plongeon de haut vol',
    climbing_adventure: 'Parcours d’escalade aventure',
    climbing: 'Escalade',
    cockfighting: 'Combat de coqs',
    cricket_nets: 'Filets de cricket',
    cricket: 'Cricket',
    croquet: 'Croquet',
    crossfit: 'CrossFit',
    curling: 'Curling',
    cycle_ball: 'Cycle-balle',
    cycle_polo: 'Bike-polo',
    cycling: 'Cyclisme',
    dance: 'Danse',
    dancing: 'Danse',
    darts: 'Fléchettes',
    disc_golf: 'Disc golf',
    diving: 'Plongée',
    dodgeball: 'Balle au prisonnier',
    dog_agility: 'Agility canine',
    dog_racing: 'Course de lévriers',
    dragon_boat: 'Course de bateaux-dragons',
    equestrian: 'Équitation',
    fencing: 'Escrime',
    field_hockey: 'Hockey sur gazon',
    fistball: 'Balle au poing',
    fitness: 'Fitness',
    fives: 'Fives',
    floorball: 'Floorball',
    football: 'Football',
    footballgolf: 'Footgolf',
    four_square: 'Four square',
    free_flying: 'Vol libre',
    freediving: 'Apnée',
    funnel_ball: 'Funnel ball',
    futsal: 'Futsal',
    gaelic_football: 'Football gaélique',
    gaelic_games: 'Jeux gaéliques',
    gaga: 'Gaga ball',
    gateball: 'Gateball',
    gliding: 'Vol à voile',
    golf: 'Golf',
    gymnastics: 'Gymnastique',
    handball: 'Handball',
    hanggliding: 'Deltaplane',
    hapkido: 'Hapkido',
    high_rope_course: 'Parcours acrobatique en hauteur',
    hiking: 'Randonnée',
    hockey: 'Hockey',
    hopscotch: 'Marelle',
    horse_racing: 'Course hippique',
    horse_riding: 'Équitation',
    horseshoes: 'Fers à cheval (jeu)',
    ice_hockey: 'Hockey sur glace',
    ice_skating: 'Patinage sur glace',
    ice_stock: 'Ice stock (curling bavarois)',
    jetsprint: 'Jet sprint',
    judo: 'Judo',
    karate: 'Karaté',
    karting: 'Karting',
    kick_scooter: 'Trottinette (sport)',
    kickball: 'Kickball',
    kickboxing: 'Kick-boxing',
    kitesurfing: 'Kitesurf',
    korfball: 'Korfball',
    krachtbal: 'Krachtbal',
    krolf: 'Krolf',
    lacrosse: 'Crosse (lacrosse)',
    laser_tag: 'Laser game',
    long_jump: 'Saut en longueur',
    martial_arts: 'Arts martiaux',
    mind_body_interventions: 'Exercice corps-esprit (p. ex. yoga)',
    miniature_golf: 'Mini-golf',
    model_aerodrome: 'Aérodrome de modélisme',
    motocross: 'Motocross',
    motor: 'Sport mécanique',
    mtb: 'VTT',
    multi: 'Multisport',
    netball: 'Netball',
    nine_mens_morris: 'Jeu du moulin',
    obstacle_course: 'Course d’obstacles',
    orienteering: 'Course d’orientation',
    paddle_tennis: 'Paddle tennis',
    paddleball: 'Paddleball',
    paddleboard: 'Stand up paddle',
    padel: 'Padel',
    paintball: 'Paintball',
    parachuting: 'Parachutisme',
    paragliding: 'Parapente',
    parkour: 'Parkour',
    pedal_car_racing: 'Course de voitures à pédales',
    pelota: 'Pelote',
    pesäpallo: 'Pesäpallo (baseball finlandais)',
    petanque: 'Pétanque',
    pickleball: 'Pickleball',
    pilates: 'Pilates',
    pole_dance: 'Pole dance',
    polo: 'Polo',
    powerlifting: 'Force athlétique',
    racquet: 'Sports de raquette',
    rc_car: 'Voitures radiocommandées',
    rodeo: 'Rodéo',
    roller_hockey: 'Rink hockey',
    roller_skating: 'Patin à roulettes',
    rowing: 'Aviron',
    rugby_league: 'Rugby à XIII',
    rugby_union: 'Rugby à XV',
    rugby: 'Rugby',
    running: 'Course à pied',
    russian_skittles: 'Gorodki',
    safety_training: 'Formation à la sécurité',
    sailing: 'Voile',
    scuba_diving: 'Plongée sous-marine',
    shooting_range: 'Stand de tir',
    shooting: 'Tir',
    shuffleboard: 'Shuffleboard',
    skateboard: 'Skateboard',
    skating: 'Patinage',
    ski_jumping: 'Saut à ski',
    skiing: 'Ski',
    snooker: 'Snooker',
    snorkeling: 'Snorkeling',
    soccer: 'Football',
    softball: 'Softball',
    speedway: 'Speedway',
    squash: 'Squash',
    streetball: 'Streetball',
    summer_toboggan: 'Piste de luge d’été',
    sumo: 'Sumo',
    surfing: 'Surf',
    swimming: 'Natation',
    table_soccer: 'Baby-foot',
    table_tennis: 'Tennis de table',
    taekwondo: 'Taekwondo',
    tamburello: 'Tamburello',
    team_handball: 'Handball',
    tennis: 'Tennis',
    teqball: 'Teqball',
    tetherball: 'Tetherball',
    toboggan: 'Luge',
    touch_football: 'Touch rugby',
    trampoline: 'Trampoline',
    trugo: 'Trugo',
    tug_of_war: 'Tir à la corde',
    ultimate: 'Ultimate (frisbee)',
    ultralight_aviation: 'ULM',
    volleyball: 'Volleyball',
    wakeboarding: 'Wakeboard',
    walking: 'Marche (sport)',
    water_polo: 'Water-polo',
    water_ski: 'Ski nautique',
    water_sports: 'Sports nautiques',
    weightlifting: 'Haltérophilie',
    windsurfing: 'Planche à voile',
    workout: 'Musculation',
    wrestling: 'Lutte',
    yoga: 'Yoga',
    zurkhaneh_sport: 'Zurkhaneh',
  },
  tourism: {
    '*': '{}',
    alpine_hut: 'Refuge de montagne',
    apartment: 'Appartement de vacances',
    aquarium: 'Aquarium',
    artwork: {
      '*': 'Œuvre d’art',
      artwork_type: {
        architecture: 'Architecture',
        bust: 'Buste',
        graffiti: 'Graffiti',
        installation: 'Installation artistique',
        mosaic: 'Mosaïque',
        mural: 'Peinture murale',
        painting: 'Peinture',
        relief: 'Relief (œuvre)',
        sculpture: 'Sculpture',
        statue: 'Statue',
        stone: 'Rocher (œuvre)',
      },
    },
    attraction: 'Attraction',
    cabin: 'Cabane touristique',
    camp_pitch: 'Emplacement de camping',
    camp_site: 'Camping',
    caravan_site: 'Aire pour caravanes',
    chalet: 'Chalet',
    gallery: 'Galerie',
    guest_house: 'Maison d’hôtes',
    hostel: 'Auberge de jeunesse',
    hotel: 'Hôtel',
    hunting_lodge: 'Pavillon de chasse',
    information: {
      '*': 'Information',
      information: {
        '*': 'Information {}',
        board: 'Panneau d’information',
        guidepost: 'Poteau indicateur',
        map: 'Carte',
        office: 'Office de tourisme',
        route_marker: 'Balise d’itinéraire',
      },
    },
    motel: 'Motel',
    museum: 'Musée',
    picnic_site: 'Aire de pique-nique',
    theme_park: 'Parc à thème',
    viewpoint: 'Point de vue',
    wilderness_hut: 'Refuge non gardé',
    zoo: 'Zoo',
  },
  type: {
    route: {
      '*': 'Itinéraire',
      route: {
        '*': 'Itinéraire {}',
        aerialway: 'Ligne de remontée mécanique',
        bicycle: {
          '*': 'Itinéraire cyclable',
          network: {
            lcn: 'Itinéraire cyclable local',
            rcn: 'Itinéraire cyclable régional',
            ncn: 'Itinéraire cyclable national',
            icn: 'Itinéraire cyclable international',
          },
        },
        bus: 'Ligne de bus',
        canoe: 'Itinéraire de canoë',
        canyoning: 'Itinéraire de canyoning',
        detour: 'Itinéraire de déviation',
        emergency_access: "Itinéraire d'accès de secours",
        ferry: 'Ligne de ferry',
        fitness_trail: 'Parcours de santé',
        foot: {
          '*': 'Itinéraire pédestre',
          network: {
            lwn: 'Itinéraire pédestre local',
            rwn: 'Itinéraire pédestre régional',
            nwn: 'Itinéraire pédestre national',
            iwn: 'Itinéraire pédestre international',
          },
          pilgrimage: {
            '*': 'Chemin de pèlerinage',
            no: '',
          },
        },
        funicular: 'Ligne de funiculaire',
        hiking: {
          '*': 'Itinéraire de randonnée',
          network: {
            lwn: 'Itinéraire de randonnée local',
            rwn: 'Itinéraire de randonnée régional',
            nwn: 'Itinéraire de randonnée national',
            iwn: 'Itinéraire de randonnée international',
          },
          pilgrimage: {
            '*': 'Chemin de pèlerinage',
            no: '',
          },
        },
        historic: 'Itinéraire historique',
        historic_railway: 'Ligne ferroviaire historique',
        horse: {
          '*': 'Itinéraire équestre',
          network: {
            lhn: 'Itinéraire équestre local',
            rhn: 'Itinéraire équestre régional',
          },
        },
        inline_skates: 'Itinéraire de roller',
        junction: 'Échangeur',
        light_rail: 'Ligne de tram-train',
        motorboat: 'Itinéraire de bateau à moteur',
        mtb: 'Itinéraire VTT',
        nordic_walking: 'Itinéraire de marche nordique',
        pipeline: 'Tracé de pipeline',
        piste: 'Piste ou itinéraire de ski',
        portage: 'Itinéraire de portage',
        power: 'Tracé de ligne électrique',
        railway: 'Ligne ferroviaire',
        road: 'Itinéraire routier',
        running: 'Parcours de course à pied',
        share_taxi: 'Ligne de taxi collectif',
        ski: 'Itinéraire de ski',
        subway: 'Ligne de métro',
        tracks: 'Tracé des voies ferrées',
        train: 'Ligne de train',
        tram: 'Ligne de tramway',
        trolleybus: 'Ligne de trolleybus',
        via_ferrata: 'Via ferrata',
        waterway: 'Itinéraire navigable',
        worship: {
          '*': 'Chemin de pèlerinage',
          worship: {
            stations_of_the_cross: 'Chemin de croix',
          },
        },
      },
    },
  },
  seasonal: {
    yes: {
      '*': 'Saisonnier',
      waterway: {
        stream: 'Ruisseau saisonnier',
        ditch: 'Fossé saisonnier',
        drain: 'Canal de drainage saisonnier',
        waterfall: 'Cascade saisonnière',
      },
      natural: {
        water: 'Plan d’eau saisonnier',
      },
    },
  },
  intermittent: {
    yes: {
      '*': 'Intermittent',
      waterway: {
        stream: 'Ruisseau intermittent',
        ditch: 'Fossé intermittent',
        drain: 'Canal de drainage intermittent',
        waterfall: 'Cascade intermittente',
      },
      natural: {
        water: 'Plan d’eau intermittent',
      },
    },
  },
  waterway: {
    '*': 'Cours d’eau {}',
    boatyard: 'Chantier naval',
    canal: 'Canal',
    canoe_pass: 'Passe à canoë',
    dam: 'Barrage',
    ditch: 'Fossé (cours d’eau)',
    dock: 'Dock',
    drain: 'Canal de drainage',
    drystream: "Cours d'eau à sec",
    fairway: 'Chenal navigable',
    fish_pass: 'Passe à poissons',
    flowline: 'Ligne d’écoulement',
    link: 'Liaison de cours d’eau',
    lock_gate: "Porte d'écluse",
    milestone: 'Borne fluviale',
    pressurised: 'Conduite d’eau sous pression',
    rapids: 'Rapides',
    river: 'Rivière',
    sluice_gate: 'Vanne',
    stream: 'Ruisseau',
    tidal_channel: 'Chenal de marée',
    wadi: 'Oued',
    waterfall: 'Cascade',
    weir: 'Déversoir',
  },
  trail_visibility: {
    excellent: 'Excellente visibilité du sentier',
    good: 'Bonne visibilité du sentier',
    intermediate: 'Visibilité moyenne du sentier',
    bad: 'Mauvaise visibilité du sentier',
    horrible: 'Très mauvaise visibilité du sentier',
    no: 'Aucune visibilité du sentier',
  },
};

export const colorNames: Record<string, string> = {
  red: 'Rouge',
  blue: 'Bleu',
  green: 'Vert',
  yellow: 'Jaune',
  orange: 'Orange',
  purple: 'Pourpre',
  violet: 'Violet',
  white: 'Blanc',
  black: 'Noir',
  gray: 'Gris',
  brown: 'Brun',
};
